### ISSUE TITLE
XMLHttpRequest is not defined when Realm is used in the electron main process

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-js#2406] opened 2019-06-06 18:40 UTC
Studio is using Realm mostly in the renderer process, but there are a few cases where we call some of the API in the main process - notably when handling links with custom protocol - these fire in the main process. To be able to hand off a user to the renderer process, we call `Realm.Sync.User.login`, but that fails with the following error:

```
[ELECTRON] ReferenceError: XMLHttpRequest is not defined
[ELECTRON]     at fetchWithTimeout (/Users/nikolairinchev/work/realm-studio/node_modules/realm/lib/user-methods.js:82:17)
[ELECTRON]     at next (/Users/nikolairinchev/work/realm-studio/node_modules/realm/lib/user-methods.js:146:9)
[ELECTRON]     at Promise (/Users/nikolairinchev/work/realm-studio/node_modules/realm/lib/user-methods.js:161:13)
[ELECTRON]     at new Promise (<anonymous>)
[ELECTRON]     at performFetch (/Users/nikolairinchev/work/realm-studio/node_modules/realm/lib/user-methods.js:159:16)
[ELECTRON]     at _authenticate (/Users/nikolairinchev/work/realm-studio/node_modules/realm/lib/user-methods.js:351:12)
[ELECTRON]     at performFetch.then (/Users/nikolairinchev/work/realm-studio/node_modules/realm/lib/user-methods.js:374:20)
[ELECTRON]     at process._tickCallback (internal/process/next_tick.js:68:7)
```

While I know the Realm API would not work in the main process, it's a bit surprising that purely js API fail. It would be great if we could support those without having to resort to workarounds.

**Comment by kraenhansen** [comment] 2019-06-08 11:19
I believe this could be considered a duplicate of https://github.com/realm/realm-js/issues/2274#issuecomment-472598810

**Comment by kneth** [comment] 2019-08-12 12:49
I am closing it as it is a subset/duplicate of #2274.

**Closed by kneth** 2019-08-12 12:49 UTC
Labels: T:Duplicate
