### ISSUE TITLE
No logging on Ubuntu 16.04

### ISSUE THREAD

**Issue by kspangsege** [realm/realm-js#1107] opened 2017-06-28 16:41 UTC
The following program logs nothing on Ubuntu 16.04 with Realm JS 1.8.2:

~~~
const Realm = require('realm');

// Realm.Sync.setSyncLogger(() => { console.log("CLICK"); });

const Foo = {
  name: 'Foo',
  properties: { alpha: 'int' }
};

Realm.Sync.User.login('http://localhost:9080', 'ks@realm.io', 'foo', (error, user) => {
  if (error) {
    console.log(error);
  }
  else {
    let realm = new Realm({
      schema: [Foo],
      sync: { user: user, url: 'realm://localhost:9080/~/foo' },
    });
  }
});
~~~

Also, `CLICK` is not printed if I enable the custom logger.

This was the case when I installed Realm JS on clean Ubuntu 16.04 using `npm install --save realm`.

If I instead build the binding from the GitHub repo, then default and custom logging works as expected.

cc @fealebenpae

**Comment by fealebenpae** [comment] 2017-06-29 12:44
The Node.js SDK has always built its Linux binaries on CentOS 6 and so far things have worked on the two distro families we targeted: CentOS 6+ and Ubuntu 14.04+. Every version of Realm Object Server released so far has used realm-js with CentOS 6 binaries. I think that this is an ABI issue because building the exact same source code on the target machine works, but when building it on CentOS 6 and running on the target machine logging disappears.

The Node.js SDK doesn’t do any logging itself, at best it only exposes functionality in realm-sync and realm-object-store (`Realm.Sync.setSyncLogger`/`Realm.Sync.setLogLevel`). It seems to me that recently something has changed in our stack that the way we build for Linux suddenly impacts logging. I don’t know what this could be, and I have no idea how to go about finding out as I have very little Linux knowledge and understand next to nothing about why one binary built on CentOS 6 might exhibit different behavior when ran on Ubuntu 16.04.

**Comment by kspangsege** [comment] 2017-06-29 12:48
What makes me suspect that it might not be an ABI issue, is that a custom logger is also not working. It seems strange to me that an ABI issue would impact the callout to the custom logger, but nothing else.

**Comment by fealebenpae** [comment] 2017-06-29 13:02
If the same source code performs as expected when compiled on Ubuntu 16.04 and ran on Ubuntu 16.04, but does not when compiled on CentOS 6 and ran on Ubuntu 16.04, then my hunch is that something about running on a different distro causes the wrong behavior.

**Comment by kspangsege** [comment] 2017-06-29 13:46
Something like an uninitialized variable can also cause this kind of behavior, i.e., it may happen to have a value on some platforms that makes it work, and a value on platforms that make it fail. OF course, the problem could also be in object store, or even deeper down.

Here is what I suggest you do,

 1. Check whether logging works on CentOS.
 2. Have CI make a new build, just to verify that it is not just an issue with a specific package file.
 3. Have CI make a custom build (same way as usual) which writes to STDERR from various strategic places, then run it on Ubuntu to see where the log execution is obstructed.

I can provide you with virtual boxes of Ubuntu and other Linux distros if you want, but it is really easy to make them yourself.

**Comment by fealebenpae** [comment] 2017-06-29 14:37
Can you try with the latest realm package on npm (1.8.3 at this time) and see if it works? I'm unable to reproduce this on an Ubuntu 16.04 machine.

**Comment by kspangsege** [comment] 2017-06-29 14:45
I can try it out on my Ubuntu 16.04 virtual box, but could you say something about what you changed?

> I'm unable to reproduce this on an Ubuntu 16.04 machine.

Please clarify, can you not reproduce with 1.8.1 on Ubuntu 16.04? If so, that could be a crucial clue.

**Comment by fealebenpae** [comment] 2017-06-29 14:45
It's likely that you were impacted by a bug in 1.8.2 that caused refreshing the access token for a sync session to stall indefinitely if the user is an admin on the server. It was already fixed in `master` (and the fix released in 1.8.3) when you built realm-js from source. The real issue here is that the sync engine was never started, not that there were no logs, and we could have easily observed this by checking the server for any connections.

**Comment by kspangsege** [comment] 2017-06-29 14:47
We are talking about ROS 1.8.3, right?

**Comment by kspangsege** [comment] 2017-06-29 14:48
Or JS binding 1.8.3?

**Comment by fealebenpae** [comment] 2017-06-29 14:48
> Please clarify

1.8.1 works, 1.8.2 doesn't work, 1.8.3 works. All on Ubuntu 16.04. It's the admin user bug.

> We are talking about ROS 1.8.3, right?

No, realm-js

**Comment by kspangsege** [comment] 2017-06-29 14:49
Ok, got it.

**Comment by fealebenpae** [comment] 2017-06-29 14:52
ROS shouldn't be impacted by this unless it tries to `Realm.Sync.User.login` as an admin user internally. To the best of my knowledge ROS uses `Realm.Sync.User.adminUser` which was not impacted by the access token refresh stalling. If ROS doesn't display any logs for its sync client the cause might be unrelated, but I recommend replacing the object server's realm-js package with 1.8.3.

**Comment by kspangsege** [comment] 2017-06-29 15:13
Ok, I am getting client-side log output now with 1.8.3, so that part is fixed.

> ROS shouldn't be impacted by this unless it tries to Realm.Sync.User.login as an admin user internally.

The fact that ThreadLearning is getting no server-side log output at all on Ubuntu 16.04 with ROS 1.8.1 leads me to suspect that this issue is also affecting ROS and the server side.

**Comment by fealebenpae** [comment] 2017-06-29 15:25
Please elaborate - does the server dashboard's log tab contain no logs whatsoever?

**Comment by kspangsege** [comment] 2017-06-29 16:00
> Please elaborate - does the server dashboard's log tab contain no logs whatsoever?

Not sure about the dashboard, but nothing at all was emitted to the log file (`/var/log/realm-object-server`), so I suppose that means that the dashboard log would be empty too.

See https://realmio.slack.com/messages/C51HLBYG2/convo/C4V9D1DLK-1498648690.192233/ for details.

**Comment by fealebenpae** [comment] 2017-06-29 16:02
On a fresh ROS 1.8.1 install on Ubuntu 16.04 I get no logs in the log file, but the logs in the dashboard work as expected.

**Comment by kspangsege** [comment] 2017-06-29 16:16
Ok, so we need a new ROS level GH issue for this. I'll create it.

**Closed** 2017-06-30 13:54 UTC
Labels: T:Bug
