### ISSUE TITLE
Realm.delete is not working with class schema

### ISSUE THREAD

**Issue by amereii** [realm/realm-js#2848] opened 2020-04-28 05:24 UTC
## Goals

Realm.delete works on older versions , After upgrading from 3.4.1 to 5.0.3 , Realm.delete  is not working with class schema

## Actual Results

```
Argument to 'delete' must be a Realm object or a collection of Realm objects.
```

## Steps to Reproduce

```
class Person {
  get fullName() {
    return this.firstName + ' ' + this.lastName;
  }
}

Person.schema = {
  name: 'Person',
  properties: {
    firstName: 'string',
    lastName: 'string'
  }
};

Realm.open({schema: [Person]})
  .then(()=>{
realm.write(() => {
  const john = realm.create('Person', {
    firstName: 'John',
    lastName: 'Smith'
  });
  john.lastName = 'Peterson';
  realm.delete(john)
});
});
```

## Version of Realm and Tooling

- Realm JS SDK Version:  5.0.3
- Node or React Native: 10.15.3 - 0.62.2 
- Client OS & Version: ? Windows 10 10.0.18362
- Which debugger for React Native: None

**Comment by blagoev** [comment] 2020-04-29 10:34
@amereii 
Thanks for reporting this. I have managed to reproduce it and we will be looking into providing a fix for it. In the mean time you can do a 
```
class Person extends Realm.Object {
}
```
then `realm.delete` should work for you. Please report back if it does not.

In the future we are planning on phasing out the support of classes not explicitly extending `Realm.Object`

**Comment by amereii** [comment] 2020-05-02 07:51
@blagoev after extending from ` extends Realm.Object` , I have the following error , When my item rendered

```
TypeError: Reflect.construct requires the first argument be a constructor
```

**Comment by Jarzka** [comment] 2020-05-06 08:19
I also get the same error
`TypeError: Reflect.construct requires the first argument be a constructor`

It happens when calling `realm.create`, but not always.

This started to happen after I updated react-native 0.59 -> 0.62 and Realm 2.29.2 -> 5.0.4.

**Comment by Jarzka** [comment] 2020-05-15 09:15
Has anyone come up with any solution?

**Comment by bkbooth** [comment] 2020-05-19 00:00
I'm desperately needing a solution for this too. My app seems stuck in a broken state.

- If my classes `extend Realm.Object` I get the `Reflect.construct` errors
- If I don't `extend Realm.Object` then my `realm.delete`s are failing.

I'd be happy for temporary hacks or workarounds at this point.

**Comment by Gazzini** [comment] 2020-05-20 13:48
@bkbooth I've found a workaround for now. @blagoev mentioned this issue is specific to class-based schemas, so the workaround is to pass the schemas directly.

The change was actually pretty small for me. When I call `realm.open()`, I changed the config from:

`{
  schema: [Pool, LogEntry, ReadingEntry, TreatmentEntry],
  schemaVersion: 0
}`

to

`{
  schema: [Pool.schema, LogEntry.schema, ReadingEntry.schema, TreatmentEntry.schema],
  schemaVersion: 0
}`

So, I just appended `.schema` to each class in the array. This works if your schemas are defined statically 😄

**Comment by bkbooth** [comment] 2020-05-20 14:27
@Gazzini do you have instance methods on your classes? Do they still work when you only pass the schema objects to `realm.open()`?

If not I think what you've done is roughly the same as what I've ended up doing. I changed all of my class models to plain objects (with the schema object as a property that I'm passing to `realm.open()`)

I had to refactor any class instance methods to functions that took the instance as the first param instead of accessing as `this`. Effectively meaning just static methods.

If instance methods still work with your way, well, I wish I knew that yesterday, haha. Would have saved me a bunch of time refactoring things.

**Comment by Gazzini** [comment] 2020-05-20 14:37
Ah, no instance methods for me. I keep my models dumb.

**Comment by v0lume** [comment] 2020-05-25 02:22
Got the same error on RN 0.62.2 and realm 3.6.5 (didn't get this error on RN 0.61.5)
Using workaround with adding .schema solves problem.
But seems I got another error - now every query by pk (using objectForPrimaryKey) returns undefined even record with such PK exists. <-- this code works perfect before upgrading to RN 0.62 and applying workaround with .scheme

**Comment by amereii** [comment] 2020-05-27 05:35
@blagoev One month passed, Do you have plan to fix the bug? It must be a priority 
The temporary workaround needs too many refactoring, As we have two different error in

`realm.create` `TypeError: Reflect.construct requires the first argument be a constructor` 
and
`realm.delete` `Argument to 'delete' must be a Realm object or a collection of Realm objects.`

**Comment by v0lume** [comment] 2020-05-27 20:22
this problem may be related to RN 0.62
just tested this case using realm 3.6.5 and rn 0.62 - got the same exceptions with Reflect.construct
right now it really becomes like pain in ass, we need fix for this issue

**Comment by blagoev** [comment] 2020-05-28 07:03
we are with tight resources but I will try to investigate that.

**Comment by Jarzka** [comment] 2020-05-28 12:43
So, which one is the correct way to use Realm? Should we pass the whole class (like @amereii did) or only the schema object (like @Gazzini did) to `Realm.open`? The first one is indeed broken, but the later works.

**Comment by bkbooth** [comment] 2020-05-28 23:43
@Jarzka my understanding is that passing the whole class is a relatively new feature (maybe only since v5?), it seems like they're moving towards it being the preferred way to provide schema's, but in my experience it isn't production ready yet.

I refactored all of our usage of Realm away from classes to using plain objects and only passing the schema objects to `Realm.open`. I couldn't wait any longer, we needed to release our app.

**Comment by Jarzka** [comment] 2020-05-29 05:31
Interesting because in our app, we have passed the whole class. It has worked before I tried to upgrade Realm from version 2 to 5 and RN to 0.62. However, I'm not the original developer of our app so don't really know which one is the preferred way. :)

**Comment by bkbooth** [comment] 2020-05-29 05:45
Right, I could be completely wrong in my understanding then 🤷‍♂️ I've been building a new app, we only added Realm at `v5.0.3` and I've been trying to understand why the class support is in the docs and yet seems to be in a broken state for release builds.

**Comment by forkeer** [comment] 2020-05-29 11:37
I have this problem too
When do you solve ?

**Comment by Jarzka** [comment] 2020-06-01 08:34
I was able to solve the writing issue with the workaround explained by @Gazzini. But now, when I read things from Realm, it always returns empty objects...

**Comment by amereii** [comment] 2020-07-13 05:58
@kneth @blagoev @fealebenpae take a look please!!

**Comment by mtford90** [comment] 2020-07-23 07:15
Found a workaround without having to drop back to dumb objects:

```ts
const collection = this.objects(query => query.filtered(`id = $0`, id));
db.delete(collection);
```

This is a pretty bad bug and it was first reported 3 months ago. There's been all sorts of new versions since then with new features - does it not make sense perhaps to fix existing features before adding new features on top of them?

I don't know cpp but the issue seems to be here - https://github.com/realm/realm-js/blob/0a151f96d83063d96381c0c26bcb6df74158cc4c/src/js_realm.hpp#L1021

**Closed** 2020-07-30 12:06 UTC
Labels: O-Community

**Comment by blagoev** [comment] 2020-07-30 12:52
We have fixed the realm.delete error. It will be included in our next release. Thanks for reporting it.

**Comment by machadolucasvp** [comment] 2020-08-04 14:08
@blagoev and what about _Reflect.construct requires the first argument be a constructor_ when extending schema from Realm.Object ?

**Comment by SanjanaTailor** [comment] 2021-06-22 10:28
> Found a workaround without having to drop back to dumb objects:
> 
> ```ts
> const collection = db.objects('schema-name').filtered(`id = $0`, id)
> db.delete(collection);
> ```
> 
> This is a pretty bad bug and it was first reported 3 months ago. There's been all sorts of new versions since then with new features - does it not make sense perhaps to fix existing features before adding new features on top of them?
> 
> I don't know cpp but the issue seems to be here -
> 
> https://github.com/realm/realm-js/blob/0a151f96d83063d96381c0c26bcb6df74158cc4c/src/js_realm.hpp#L1021hell



Hello what is id here is it primary key ?
const collection = RealmDB.realm
        .objects('Student')
        .filtered(`ID = $105`,ID);
      RealmDB.realm.delete(collection);
      
error [ReferenceError: Can't find variable: ID ]
