### ISSUE TITLE
cant test React Realm for 11.0.0-rc.0 due to super expression

### ISSUE THREAD

**Issue by Hannah-reset** [realm/realm-js#5033] opened 2022-10-25 09:58 UTC
### How frequently does the bug occur?

All the time

### Description

I used React Realm as provided in https://www.mongodb.com/docs/realm/sdk/react-native/use-realm-react/ in a react native project and it went well.
But got  TypeError when I ran jest test. Need I follow the construction to writer a constructor for Task, how and why?
<img width="539" alt="image" src="https://user-images.githubusercontent.com/63138801/197742700-8c674675-0d56-48fa-812c-e7a53d3b8534.png">

    "react-native": "0.67.3",
"@types/jest": "^26.0.23",
    "realm": "11.0.0-rc.0",

> export class Task extends Realm.Object {
> _id!: Realm.BSON.ObjectId;
> description!: string;
> isComplete!: boolean;
> createdAt!: Date;
>  
> static generate(description: string) {
> return {
> _id: new Realm.BSON.ObjectId(),
> description,
> isComplete: false,
> createdAt: new Date(),
> };
> }
> 
> }
> 

### Stacktrace & log output

```shell
● Test suite failed to run

    TypeError: Super expression must either be null or a function

    
    > 23 |   createdAt!: Date;
         |                          ^
      24 |
     at _inherits (node_modules/@babel/runtime/helpers/inherits.js:5:11)
```

### Can you reproduce the bug?

Yes, always

### Version

11.0.0-rc.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

ios 10

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment] 2022-10-31 11:30
Best guess is that you haven't imported Realm in the file where you declare the Task class.

**Comment by Hannah-reset** [comment] 2022-11-01 02:40
> Best guess is that you haven't imported Realm in the file where you declare the Task class.

import 'Realm' from 'realm';

Thanks for your suggestion. But it seems to be more obsecure.
I have imported Realm before running test and got the error. What other statements should be covered?
If I delete the import declaration, then I will get another error that infers lack of import statement.

**Comment by kneth** [comment] 2022-11-01 14:23
It is difficult to guess what other statements you need from the sparse information you have provided. Is it possible to share a small project which can reproduce the issue?

**Comment by kneth** [comment] 2022-11-17 17:45
I am closing the issue due to no reply back. Please comment and reopen the issue if needed.

**Closed** 2022-11-18 09:52 UTC
Labels: T-Bug, O-Community, Waiting-For-Reporter

**Comment by vardan-arm** [comment] 2022-12-06 16:26
FWIW, I also encountered this problem. I was importing Realm this way:
`import * as Realm from 'realm';`

Changing the import statement to the following fixed the issue:
`import Realm from 'realm';`

**Comment by elsyslab-ark** [comment] 2022-12-07 16:47
I am also facing this issue



> ERROR  TypeError: Super expression must either be null or a function 
>  ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[1], "./models").TaskRealmContext')



**Package Versions:**

```
  "dependencies": {
    "@realm/react": "^0.4.1",
    "react": "18.1.0",
    "react-native": "0.70.6",
    "realm": "^11.3.1"
  },
```


**Code Snippet:**
```

import {createRealmContext} from '@realm/react';

// This JS version of the Task model shows how to create Realm objects by
// defining a schema on the class, which is required if your project does not
// use TypeScript. If you are using TypeScript, we recommend using
// `@realm/babel-plugin` (https://github.com/realm/realm-js/blob/master/packages/babel-plugin/),
// which allows you to define your models using TypeScript syntax.
//
// See `Task.ts` in the Realm example app for an example of using the plugin.

import Realm from 'realm';

export class Task extends Realm.Object {
  constructor(realm, description, userId) {
    super(realm, {description, userId: userId || '_SYNC_DISABLED_'});
  }

  // To use a class as a Realm object type in JS, define the object schema on the static property "schema".
  static schema = {
    name: 'Task',
    primaryKey: '_id',
    properties: {
      _id: {type: 'objectId', default: () => new Realm.BSON.ObjectId()},
      description: 'string',
      isComplete: {type: 'bool', default: false},
      createdAt: {type: 'date', default: () => new Date()},
      userId: 'string',
    },
  };
}
export const TaskRealmContext = createRealmContext({
  schema: [Task],
});
```



```
import {View, Text} from 'react-native';
import {Realm, createRealmContext} from '@realm/react';
import {TaskRealmContext} from './models';

const App = () => {
  const {RealmProvider} = TaskRealmContext;

  return (
    <RealmProvider>
      <View>
        <Text>Hello</Text>
      </View>
    </RealmProvider>
  );
};

export default App;

```


**

> hermes disabled

**
