### ISSUE TITLE
No property 'undefined' on object of type 'X'

### ISSUE THREAD

**Issue by MarcosHerreraF** [realm/realm-js#2704] opened 2020-01-28 16:35 UTC
##  Goals

Load all the data from the table Items and filter them to get a single element

## Expected Results

Get one single item filtered by the id

## Actual Results

> No property 'undefined' on object of type 'Item'

Though debugging it on the iPhone emulator I can't reproduce it. The errors I get are from sentry.

Looking for the error I've tried different things:
  - Emptying the db returns undefined (correctly)
  - Using an id that doesn't exist returns undefined (correctly)
  - Using a property that doesn't exist (idFake, instead of id), throws an error: "Unhandled JS Exception: No property 'idFake' on object of type 'Items'" (expected, but the error shows "idFake", not "undefined" unlike in sentry, so I don't know how it can be "undefined" since that property is hardcoded).

It was also working on previous releases and it started showing this error now.
It is also failing on different functions like this (get all items and then filtering), but filtering by other properties. But it only fails in this table.

## Steps to Reproduce

Create a db with at least the column we want to filter by.

## Code Sample

```
const items = realm.objects("Items");
return Array.from(items.filtered(`id = ${itemId}`))[0];
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.29.2
- Node or React Native: 0.59.9
- Client OS & Version: iOS and Android
- Which debugger for React Native: React native debugger

**Comment by kneth** [comment] 2020-02-03 09:53
Do you have access to the local Realm file? What type is `id` (can you post the schema)?

**Comment by MarcosHerreraF** [comment] 2020-02-04 10:45
Yes I can see the realm db in real time and modify it, the IDs go increasingly from 0 to up to 2000 or so

```
import Realm from "realm";

class Item extends Realm.Object {}
Item.schema = {
	name: "Items",
	primaryKey: "id",
	properties: {
		id: "int",
		name: "string",
		description: "string",
		positionId: "int",
		gameSlotId: "int"
	}
};

export default Item;

```

**Comment by kraenhansen** [comment] 2020-02-04 11:37
I can reproduce the error if `itemId` in your code sample is `undefined`: You're basically asking Realm to filter objects that have the same value in the two properties `"id"` and `"undefined"` and since `Item` doesn't have a property named `undefined` you get the error.

I suggest you used a prepared statement instead, inserting `$0` as a placeholder of the ID (see [documentation of filtered](https://realm.io/docs/javascript/latest/api/Realm.Results.html#filtered))

```javascript
const items = realm.objects("Items");
return Array.from(items.filtered("id = $0", itemId))[0];
```

Or even better, because your `Item` has `id` as its primary key, you can use the [objectForPrimaryKey](https://realm.io/docs/javascript/latest/api/Realm.html#objectForPrimaryKey) method to get an `Item` from its `id`:

```javascript
const items = realm.objects("Items");
return [ items.objectForPrimaryKey(itemId) ];
```

I'll close this issue for now as it seems related to the usage of Realm JS, rather than a bug in the library itself. Please feel free to reopen if you test out the suggestions above and feel otherwise. Thanks!

**Closed by kraenhansen** 2020-02-04 11:37 UTC
Labels: O-Community, T-Help
