### ISSUE TITLE
permissions().findOrCreate advertised on compile time, but not available on runtime

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-js#2131] opened 2018-11-26 13:01 UTC
@programaths commented on [Mon Nov 19 2018](https://github.com/realm/realm-object-server/issues/403)

## Goals

Add a `Realm` level permission

## Expected Results

Permission get added with role if non existant

## Actual Results

```
ros-server_1_7fe0db58f502 | 2018-11-19T16:32:57.867026142Z error: [http] HTTP response: 863878cd-5eb3-4eba-9872-8a873f1150dd
ros-server_1_7fe0db58f502 | 2018-11-19T16:32:57.867045308Z {}
ros-server_1_7fe0db58f502 | 2018-11-19T16:32:57.874735997Z error: Internal server error: TypeError: globalRealm.permissions(...).findOrCreate is not a function
ros-server_1_7fe0db58f502 | 2018-11-19T16:32:57.874758609Z     at Realm.globalRealm.write (/realm-object-server/src/providers/legacy-authprovider.ts:26:50)
ros-server_1_7fe0db58f502 | 2018-11-19T16:32:57.874773629Z     at LegacyAuthProvider.<anonymous> (/realm-object-server/src/providers/legacy-authprovider.ts:25:17)
ros-server_1_7fe0db58f502 | 2018-11-19T16:32:57.874778000Z     at Generator.next (<anonymous>)
ros-server_1_7fe0db58f502 | 2018-11-19T16:32:57.874791857Z     at fulfilled (/realm-object-server/dist/providers/legacy-authprovider.js:4:58)
ros-server_1_7fe0db58f502 | 2018-11-19T16:32:57.874795477Z     at <anonymous>
```

## Steps to Reproduce

Try to set permissions that way:

```typescript
/**
   *
   * @param server
   * @param {Realm} realm
   * @param userId
   * @param {permissionCallback} fn
   */
  async function setPermission(server:Server,realm:string,userId,fn){
    let globalRealm =await server.openRealm(realm);
    globalRealm.write(()=>{
      let permission = globalRealm.permissions().findOrCreate(`__User:${userId}`);
      fn(permission);
    });
    await globalRealm.close();
  }
```

## Code Sample

See above

## Version of Realm and Tooling

- Realm Object Server Version: 3.14.0
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [x] Enterprise
- Server OS & Version: ? (uname -a) Linux 0a062740427e 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 GNU/Linux Client SDK Version: JS 2.19.0 (Docker container)
- Client OS & Version: (uname -a) Linux christian-Aspire-TC-605 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## Logs

See above

## Possible cause

`realm-object-server` pulls `"realm": "2.19.0"`, so the `Realm` type is provided by the latest.
As we use the `server.openRealm` we are on a different execution path. (not the same implementation)

---

@nirinchev commented on [Mon Nov 19 2018](https://github.com/realm/realm-object-server/issues/403#issuecomment-439991650)

These methods only work for query-based Realms. `server.openRealm` opens the Realm in "full" mode, so these methods will be unavailable.

---

@bmunkholm commented on [Mon Nov 19 2018](https://github.com/realm/realm-object-server/issues/403#issuecomment-440010379)

@nirinchev Is that sufficiently documented?

---

@nirinchev commented on [Mon Nov 19 2018](https://github.com/realm/realm-object-server/issues/403#issuecomment-440027403)

This is the documentation for `openRealm`: https://realm.io/docs/realm-object-server/latest/api/ros/classes/server.html#openrealm - we don't explicitly state it's going to be opened in full mode, because this method has been around since before query-based sync, but also it doesn't make much sense to open Realms in query-based mode on the server.

Regarding the `permissions()` function - it's a recent addition, so @kneth or @cmelchior should know more about it.

---

@programaths commented on [Tue Nov 20 2018](https://github.com/realm/realm-object-server/issues/403#issuecomment-440153807)

So, it is not sufficiently documented.

Maybe methods should be tagged with "only query based", "only full" and "all".

A far **better** solution would be distinct types.

Also, you may consider that developpers can't always read all the sources of information and get in a quest of how it may work.

---

@cmelchior commented on [Tue Nov 20 2018](https://github.com/realm/realm-object-server/issues/403#issuecomment-440202076)

While it is true that the method only makes sense for query-based Realms (and we should probably document that), the method definition should still be available to call at runtime. I am a bit puzzled this is not the case and we need to investigate that.

@nirinchev 
> but also it doesn't make much sense to open Realms in query-based mode on the server.

This is not true, there are plenty of use cases for wanting to open a partial Realm on the server. Mostly because that is the only way to trigger populating permissions currently.

---

@bmunkholm commented on [Mon Nov 26 2018](https://github.com/realm/realm-object-server/issues/403#issuecomment-441630727)

@programaths Thanks for creating this. I'll move it to realm-js, so feel free to follow it there.

**Comment by cmelchior** [comment] 2018-11-26 13:17
It is happening because they use `openRealm` which does not open a Query-based Realm.
According to @nirinchev You can work around this by using `/<pathToRealm>/__partial/<adminId>/<hardcodedId>` as the path when opening the Realm to work around it. I'm writing a page in the docs right now to clarify this.

**Comment by cmelchior** [comment] 2018-11-26 13:29
If I remember correctly we did look into it, and the underlying error is more clear about the root cause (schema missing) but it got swallowed by this error when propagating back to the user.

**Comment by nirinchev** [comment] 2018-11-26 13:35
Ah... So maybe it would be nice if in the beginning of this method, we checked if the Realm is opened in query-based mode.

**Comment by cmelchior** [comment] 2018-11-26 13:41
Yes, we should add checks that throw a more appropriate error 👍

**Comment by cmelchior** [comment] 2018-11-27 13:47
#2151 has been merged with improvements to our error messages which I believe should fix this issue

**Closed by cmelchior** 2018-11-27 13:47 UTC
Labels: O:User PE/EE, Reproduction Required, T:Bug-Crash
