### ISSUE TITLE
 ERROR  Error: Exception in HostFunction: Failed to read Realm object constructor must have a 'schema' property.: schema must be of type 'object', got (undefined)

### ISSUE THREAD

**Issue by ThomasLuuu** [realm/realm-js#5669] opened 2023-03-30 08:01 UTC
### How frequently does the bug occur?

Always

### Description

I wrapped my child components with <RealmProvider> and I received this error.
Here is my realmContext: 

const config = {
  schema: [Category]
}
export default createRealmContext(config);

  **ERROR  Error: Exception in HostFunction: Failed to read Realm object constructor must have a 'schema' property.: schema must be of type 'object', got (undefined)**

### Stacktrace & log output

```shell
ERROR  Error: Exception in HostFunction: Failed to read Realm object constructor must have a 'schema' property.: schema must be of type 'object', got (undefined)
```

### Can you reproduce the bug?

Always

### Version

11

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Win 10

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment] 2023-03-30 08:14
@ThomasLuuu 

If `Category` is a class, you need to define `schema` as a static property as [described in the documentation](https://www.mongodb.com/docs/realm/sdk/react-native/realm-database/define-a-realm-object-model/#define-an-object-type)

**Comment by ThomasLuuu** [comment] 2023-03-30 08:29
@kneth 
Yes, I already defined chema for it.
`
export class Category extends Realm.Object<Category> {
  name!: string;

  static schema: Realm.ObjectSchema = {
    name: 'Category',
    properties: {
      name: {type: 'string', indexed: true},
    },
  };
}
`

**Comment by kneth** [comment] 2023-05-10 08:18
@ThomasLuuu 

It looks like you have a mixture of JavaScript and TypeScript and I assume you are using TypeScript. Your class should look something like:

```ts
export class Category extends Realm.Object<Category> {
  name!: string;

  static schema: Realm.ObjectSchema = {
    name: 'Category',
    properties: {
      name: {type: 'string', indexed: true},
    },
  };
}
```

**Comment by takameyer** [comment] 2023-06-27 12:06
Can you provide a simple repo that we can use to reproduce this?  I am not able to reproduce this with the current code provided.

**Comment by kneth** [comment] 2023-07-14 12:40
I am closing the issue due to no reply back. Please create a new issue if you have new observations to share.

**Closed by kneth** 2023-07-14 12:40 UTC
Labels: T-Bug, O-Community, Waiting-For-Reporter, SDK-Use:Local, Encryption:Off, Frequency:Always, Repro:Always
