### ISSUE TITLE
App Crashing on iOS on line 168 of js_results.hpp: parser::ParserResult result = parser::parse(query_string);

### ISSUE THREAD

**Issue by ZComwiz** [realm/realm-js#3638] opened 2021-03-12 01:26 UTC
## Goals

Be able to query multiple things without a crash.
## Expected Results

To Be able to query multiple things without a crash.

## Actual Results

Crash:
    parser::ParserResult result = parser::parse(query_string);
`com.facebook.react.JavaScript (6): EXC_BAD_ACCESS (code=2, address=0x16bc8bff8)`

## Steps to Reproduce

query multiple objects using a long predicate string "id = ${id} && id = ${id2} && ..." for say 2500 ids.

## Version of Realm and Tooling

- Realm JS SDK Version:     "realm": "10.1.4",
- Node or React Native:     "react-native": "0.63.4",
- Client OS & Version: iOS v14.2
- Which debugger for React Native: Metro

**Comment by kneth** [comment] 2021-03-12 09:24
I believe it is a duplicate of #1842. It has been fixed in Realm Core but we haven't produce a release with a update yet.

**Comment by ZComwiz** [comment] 2021-03-12 12:06
The issue appears on the release build on iOS, not on Android by the way. Hopefully we can get the update merged soon? Looks like it was completed in December of last year

**Comment by kneth** [comment] 2021-07-15 14:28
I believe it was fixed in v10.3.0.

**Closed** 2021-07-15 14:28 UTC
Labels: O-Community
