### ISSUE TITLE
Missing librealm-parser-maccatalyst.a

### ISSUE THREAD

**Issue by marcosrdz** [realm/realm-js#3577] opened 2021-02-11 04:17 UTC
## Goals

Compile Realm in Mac Catalyst
## Expected Results

Download librealm-parser-maccatalyst.a
## Actual Results
Only downloads ibrealm-sync-maccatalyst.a

Download ibrealm-parser-maccatalyst.a

## Steps to Reproduce

The last Realm release to include this file was 6.1.0

## Version of Realm and Tooling

- Realm JS SDK Version: ? 10.2.0
- Node or React Native: ? React Native
- Client OS & Version: ? macOS
- Which debugger for React Native: ?/None
- 
<img width="888" alt="Screen Shot 2021-02-10 at 11 05 31 PM" src="https://user-images.githubusercontent.com/4793122/107601975-3299d000-6bf6-11eb-937e-912b3de3b174.png">

**Comment by kneth** [comment] 2021-02-11 11:32
Duplicate of #3359

**Closed** 2021-02-11 11:33 UTC
Labels: O-Community
