### ISSUE TITLE
Failed to compile. .../realm/lib/browser/index.js Module not found: Can't resolve 'react-native' in '.../realm/lib/browser'

### ISSUE THREAD

**Issue by blyshchykroman5** [realm/realm-js#3927] opened 2021-08-28 00:00 UTC
Bumping this. Have tried a few of the suggestions here with no success. Has anyone successfully resolved:
`Failed to compile.`
`./node_modules/realm/lib/browser/index.js`
`Module not found: Can't resolve 'react-native' in '/Users/b/myApp/node_modules/realm/lib/browser'`
Surely even without officially supporting electron - the team could offer some pointers?
Thanking all in advance.

_Originally posted by @bentron2000 in https://github.com/realm/realm-js/issues/1060#issuecomment-464946917_

**Comment by kraenhansen** [comment] 2021-08-28 04:51
Please share a bit more about your setup, without it it's super difficult to help.

Are you for example using a bundler like webpack and have you tried externalizing your node modules from the bundle as I suggested in https://github.com/realm/realm-js/issues/1060#issuecomment-322767435?

**Comment by tsmarin** [comment] 2021-09-01 21:37
I've run into this issue as well using electron, webpack, and realm, and following your suggestion to use webpack-node-externals allowed me to run the app. However, now the node modules obviously aren't there when attempting to build a distributable. @kraenhansen do you have suggestions for packaging the app?

**Comment by Ngomana** [comment] 2021-09-10 20:48
Also came across this mess today, working with mongoDB technologies it a pain.

**Comment by blyshchykroman5** [comment] 2021-09-13 16:23
Hi, Tony

**Comment by kneth** [comment] 2021-09-14 12:52
Please see https://github.com/realm/realm-js/issues/1060#issuecomment-465934019

**Comment by kraenhansen** [comment] 2021-11-01 08:26
> @kraenhansen do you have suggestions for packaging the app?

@tsmarin since there are multiple ways to package the app, please create another issue with details on the tools you're using and any relevant errors that you might be seeing in the process.

I'll close this issue, since I didn't get a response from the original reporter. @blyshchykroman5 reopen this issue if you're still experiencing this, answering my questions above ☝️ 

For anyone else experiencing difficulties requiring `realm`, please feel free to open your own issue with details on how to reproduce and we'll be sure to take a look to help you resolve this.

**Closed by kraenhansen** 2021-11-01 08:26 UTC
Labels: T-Help, O-Community, More-information-needed

**Comment by jbeckton** [comment] 2022-05-18 23:17
Its an Angular Web App with SSR. Realm Web (according to the docs) can not be used in node.js. So for the Server Side Rendering I would use Realm and once the app is rendered in the browser I would use Realm Web. Your SDK's have alienated an entire framework user base, probably the number 2 SPA tech in the world. All of your competitors (that I am aware of) use a single js sdk for browser and node server. The only reason I am tolerating the issues with your sdk's is because I really want to use MongoDB (database), but I am second guessing that decision. Has the Realm team ever bothered to test your sdk's with the #2 javascript framework?

**Comment by jbeckton** [comment] 2022-05-18 23:20
The Atlas Data API is still in preview.

**Comment by jbeckton** [comment] 2022-05-19 00:36
@tomduncalf like I said in my first comment... "ditch the legacy port and rewrite your SDK's using modern module patterns for javascript apps". 

https://github.com/realm/realm-js/issues/1060#issuecomment-465934019

AWS Amplify, Firebase, FaunaDB, etc... all have modern implementations of their JS SDK's. MongoDB cut corners and used a legacy implementation to cobble into a modern javascript ecosystem. Depressing to say the least.

**Comment by tomduncalf** [comment] 2022-05-19 10:07
Hi @jbeckton, sorry to hear this is causing so many issues for you.

The `realm` module is only for use with Node.js, Electron and React Native. The library is primarily written in C++, so it needs to use Node or React Native's native modules capability to be able to run this native code. This doesn't just apply to Angular, you would also be unable to use the  `realm` package with React on web.

However, you should be able to use `realm-web` with Node, see https://github.com/realm/realm-js/tree/master/packages/realm-web#using-realm-web-in-a-nodejs-environment.

If you are still having issues, please could you open a new issue with details? 

Thanks

**Comment by jbeckton** [comment] 2022-05-26 05:54
@ianpward As I said before, i just want to use Realm app services to talk to MongoDB Atlas cluster while utilizing authentication and access rules so that I do not have to build a backend.  I don't care for the Realm embedded database, I don't plan on using it. I am trying to use realm-web and realm, they both have a mongoClient implementation that is very similar to the MongoDB driver that will allow me to interact with the collections stored in an Atlas cluster.

Has anyone at MongoDB ever thought of testing this? My tech stack is about as common as you can get, everyone is doing SSR now days and your SDK's don't work for this very common scenario because there has to be two of them for javascript apps. I did manage to get realm and realm-web working together with Next.js but only with a bastardized architecture that makes it difficult to share code between the browser and node environments. My current experiments are super simple and I am not yet convinced this will scale.  My preferred framework is Angular and that venture was an epic failure trying to use realm and realm-web together with Angular. Did you guys ever think to try realm with Angular Universal?

Realm App Services is a JamStack concept yet you don't even provide an SDK that will run within a JamStack environment. If a developer wants SEO for their app your SDK either makes it impossible or requires an awful architecture to juggle two different SDK's as a work around.

I invite you to go look at Google's Firebase SDK's, what a great developer experience! But Firestore is not an ideal database platform for what I need, MongoDB is. Realm SDK's are ruining it for me though.

Your SDK's just don't provide a productive experience for web developers, it's unfortunate because MongoDB is a great database platform. In this day and age a web developer can build a full-stack web app and a mobile app all with javascript and have the luxury of sharing code between them all. Realm has shot that idea in the foot with your SDK's.

**Comment by tomduncalf** [comment] 2022-05-26 09:23
@jbeckton Could you please open a new issue to discuss this further? 

My understanding is that it should be possible to use realm-web for both Node and web usage, so your app code can be isomorphic, but I have not tried this myself. If you need help with this, please open an issue with some details of what didn't work.

Equally if you have some concrete ideas for how we could improve the developer experience, please feel free to open a new issue with details, we always welcome feedback.

Thanks

**Comment by ianpward** [comment] 2022-05-26 12:24
@jbeckton It would be interesting to know why these instructions did not work for you - 
https://github.com/realm/realm-js/tree/master/packages/realm-web#using-realm-web-in-a-nodejs-environment

Because @kraenhansen did try this successfully and ended up writing this instructions.

**Comment by jbeckton** [comment] 2022-05-26 13:59
I am getting this error from this call to the SDK `mongoClient?.db(dbName)`, it returns `null`. The same exact code works properly when called in the proper context node vs web. Trying to use the realm-web sdk for both node and web does not work.

````
error - lib/realm/realmWebClient.ts (97:9) @ RealmWebClientService.db
Error: Could not find a database with the name basinsListDB_DEV
   95 |                 const database = this.mongoClient?.db(dbName);
   96 |                 if (!database) {
>  97 |                         throw new Error(`Could not find a database with the name ${dbName}`);
      |                              ^
   98 |                 }
   99 |                 return database;
  100 |         }
error - lib/realm/realmWebClient.ts (97:9) @ RealmWebClientService.db
Error: Could not find a database with the name basinsListDB_DEV
   95 |                 const database = this.mongoClient?.db(dbName);
   96 |                 if (!database) {
>  97 |                         throw new Error(`Could not find a database with the name ${dbName}`);
      |                              ^
   98 |                 }
   99 |                 return database;
  100 |         }
````

**Comment by tomduncalf** [comment] 2022-05-26 13:59
Please can you open a [new issue](https://github.com/realm/realm-js/issues/new/choose) @jbeckton and we will assist you there

**Comment by jbeckton** [comment] 2022-05-26 17:30
@tomduncalf @ianpward  I no longer need to open another issue for this. I was able to fix the previously posted error I was seeing after switching to the realm-web SDK for SSR operations.

In closing I ask you guys to put yourself in my position for a minute. I have wasted many hours of my free time trying get Realm App Services SDK's to work together because your official [documentation](https://www.mongodb.com/docs/realm/web/) clearly states...
 
> The Web SDK does not support JavaScript or TypeScript applications written for the Node.js (server-side) environment...

But yet you have demonstrated that it indeed does [here](https://github.com/tomduncalf/realm-ssr-test). I was under the impression that I had to figure out a way to juggle the 2 js SDK's so that I could have SSR and browser access to Realm App services because your official documentation leads one to this assumption. The React tutorial in your realm documentation relies on GraphQL and there is no SSR in that tutorial. The lack of transparency has caused a bit of frustration. I wonder how much revenue you are losing due to developers just giving up on Realm due to this?

As for the Angular community, If they manage to stumble upon the work around you provided you still have the issue with the bundle size caused by Realm SDK being **1MB** just for an out of the box hello world app. The vendor bundle alone is HUGE even without all the other potential libraries that one could commonly use in an Angular application.

**Comment by tomduncalf** [comment] 2022-05-27 08:29
@jbeckton I'm glad you've got it working, and sorry that the docs misled you. I've raised an issue to update that part of the documentation as it is indeed incorrect, and hopefully in future we can add some more explicit documentation on SSR scenarios.
