### ISSUE TITLE
React Native App crash after update from v10 beta 7 to 8/9

### ISSUE THREAD

**Issue by xlucxs** [realm/realm-js#3069] opened 2020-07-16 20:46 UTC
I am currently using 

> "realm": "v10.0.0-beta.7" 
> "react": "16.13.1",
> "react-native": "0.63.1",

With this configuration my application starts properly 

But after upgrading to

> "realm": "v10.0.0-beta.8"
or
> "realm": "v10.0.0-beta.9"

my app directly crash with the same code

![image](https://user-images.githubusercontent.com/42546473/87720065-a7b63b80-c7b4-11ea-8dd6-e4b6f12db421.png)

I had the same problem with

>  "react": "16.11.0",
> "react-native": "0.62.2",
> "realm": "v10.0.0-beta.8" or "realm": "v10.0.0-beta.9"

does anyone else have the same problem ?

**Comment by janfi** [comment] 2020-07-17 06:55
Hello,
I have the same problem with "realm": "v10.0.0-beta.9". All is fine in ios but in android, my app directly crash.
The log error in Android Studio is "java.lang.UnsatisfiedLinkError: Error when loading lib: dlopen failed: cannot locate symbol"
Thanks for your help.

**Comment by kneth** [comment] 2020-07-17 08:27
@xlucxs Can you confirm you only see it on Android?

@janfi Thanks for your comment. We will try to reproduce to see what it is.

**Comment by xlucxs** [comment] 2020-07-17 10:06
@kneth Hello, I have just tested with the beta 9 and yes I confirm that the application works well on IOS.

**Comment by kneth** [comment] 2020-07-17 11:19
@xlucxs Thank you for the update. It looks like our Android build is incorrect, and we will investigate it.

**Comment by BravenxX** [comment] 2020-07-30 14:03
Same problem. Any solution?

**Comment by MadeByRaymond** [comment] 2020-08-04 16:36
Anyway solution to this yet?

**Comment by BravenxX** [comment] 2020-08-05 22:22
> Anyway solution to this yet?

I had to go back to beta-7

**Comment by kneth** [comment] 2020-08-11 12:18
It has been fixed in #3074 but not yet released.

**Closed** 2020-08-17 08:00 UTC
Labels: O-Community

**Comment by MadeByRaymond** [comment] 2020-08-20 12:42
> It has been fixed in #3074 but not yet released.

Any progress yet?

**Comment by VinayakNivalkar** [comment] 2020-08-27 05:18
@kneth Is it Released or yet to be Released?

**Comment by kneth** [comment] 2020-08-27 06:23
@VinayakNivalkar @MadeByRaymond 

We have had some difficulties with our CI system preventing us from releasing. I hope that we can release this week or early next week.
