### ISSUE TITLE
Error loading shared library ld-linux-x86-64.so.2: No such file or directory

### ISSUE THREAD

**Issue by suresh-ignitershub** [realm/realm-js#4574] opened 2022-05-15 17:30 UTC
### How frequently does the bug occur?

All the time

### Description

It was working on with all the same server setup but it's started giving this error when we tried to deployed this on production. dev and production both are having same configuration with OS ubuntu. I almost spent 3 days and tried everything to fix it. linux-x86-64.so.2 is already available on /usr/lib64 but still giving the error however on dev it's working fine. Please help.

### Stacktrace & log output

```shell
ERROR Error in phase start: Could not run init tasks: Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/src/app/node_modules/realm/build/Release/realm.node)
```

### Can you reproduce the bug?

Yes, always

### Version

10.14

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Ubuntu 20

### Build environment

NodeJs

**Comment by tomduncalf** [comment] 2022-05-16 10:05
Hi @suresh-ignitershub, I tried to reproduce this on a Ubuntu 20.04.1 x86_64 VM and was unable to do so. I suspect there could be some server configuration issue, as you mentioned it does not occur on dev.

Could you try the following steps (which will create a new temporary Node.js project, install Realm into it, and then try to require Realm) to see if the issue is related to your application, or Realm in general?

1. Log in to a server exhibiting the issue
2. `cd /tmp`
3. `mkdir realm-test`
4. `cd realm-test`
5. `npm init -y`
6. `npm install realm`
7. `node -e 'require("realm")'`

**Comment by takameyer** [comment] 2022-06-07 07:12
Closing.  Feel free to reopen if you have tried the above steps and are still having problems.

**Closed by takameyer** 2022-06-07 07:12 UTC
Labels: T-Bug, O-Community, Waiting-For-Reporter

**Comment by Firanus** [comment] 2022-10-13 10:48
We actually experienced the same problem when trying to build and run a Docker container of our node realm app.

The error ended up being that our container was built on `node:gallium-alpine`, and the alpine image either didn't contain the required library or couldn't find it. We tried also tried to use `node:gallium`, and that found the library, but gave a different error, namely:

```
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /app/node_modules/realm/build/Release/realm.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1210:18)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at Module.Hook.Module.require (/app/node_modules/dd-trace/packages/dd-trace/src/ritm.js:73:33)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/app/node_modules/bindings/bindings.js:112:48)
    at getRealmConstructor (/app/node_modules/realm/lib/index.js:28:37)
    at Object.<anonymous> (/app/node_modules/realm/lib/index.js:53:26)
    at Module._compile (node:internal/modules/cjs/loader:1126:14) {
  code: 'ERR_DLOPEN_FAILED'
}
```

Basically, the version of glibc that node:16 ships wasn't up-to-date enough.

The **solution** to all this ended up being to move to building our docker images using node 18. The alpine images still lacked the requisite lib, but using `FROM node:18-slim` solved our problem. 😄

**Comment by kneth** [comment] 2022-10-13 14:57
@Firanus Thank you for providing a solution.

**Comment by aandea** [comment] 2022-10-20 03:42
@Firanus , Thank you for the solution. I had the same problem (with node:16.14). Confirm that the fix works (move to 18-slim). Weird, since the 16.14 image is supposed to include the needed dependency.
