### ISSUE TITLE
2.27.0: json.hpp not found 

### ISSUE THREAD

**Issue by sheodon** [realm/realm-js#2376] opened 2019-05-20 03:50 UTC
json.hpp was not imported into the project, the compilation failed

## Version of Realm and Tooling

- Realm JS SDK Version: 2.27.0
- Node or React Native: 0.59.8
- Xcode Version: 10.1

**Comment by renalpraba** [comment] 2019-05-20 03:55
*Realm 2.27.0

**Comment by sheodon** [comment] 2019-05-20 04:00
> *Realm 2.27.0

**Comment by sheodon** [comment] 2019-05-20 04:09
> Hey - looks like you forgot to add a T:* label - could you please add one?

Don't know how to add a T:* label

**Comment by renalpraba** [comment] 2019-05-20 06:41
@bmunkholm why closing this issue?

**Comment by bmunkholm** [comment] 2019-05-20 06:56
@sheodon closed this - looked like the bot's request to add a label was the only reason to reopen?

**Comment by sheodon** [comment] 2019-05-20 07:13
> @sheodon closed this - looked like the bot's request to add a label was the only reason to reopen?
> 
> If there is still a problem, please use the template to explain in more details what the problem is and how to replicate the issue.

It was accidentally closed by me, so i reopen it

**Comment by bmunkholm** [comment] 2019-05-20 07:22
@sheodon  Please use the full template. Describe exactly how to reproduce your issue. Thanks!

**Comment by sheodon** [comment] 2019-05-20 07:48
> @sheodon Please use the full template. Describe exactly how to reproduce your issue. Thanks!

when realmjs's version 2.27.0, xcode version 10.2.1 can compile success, but xcode version 10.1  compile fail。
when realmjs's version 2.26.1, xcode version 10.1 can compile success。
when realmjs's version:2.27.0 , i found json.hpp was not imported into the project

**Comment by kneth** [comment] 2019-05-20 14:06
@sheodon 

I haven't been able to reproduce it yet. If possible, can you provide a small app which does?

**Comment by janczizikow** [comment] 2019-05-22 13:15
I've experienced same error when running `react-native run-ios` after upgrading realm. However, when compiling with Xcode, everything worked fine. 

I couldn't reproduce the issue in a fresh project.

Error:
```
<path_to_project>/node_modules/realm/src/rpc.hpp:26:10: fatal error: 'json.hpp' file not found
#include "json.hpp"
         ^~~~~~~~~~
1 error generated.
```
## Version of Realm and Tooling

- Realm JS SDK Version: 2.28.0
- Node or React Native: node 10.15.3 / react-native 0.59.8
- Xcode: 10.2.1

**Comment by kneth** [comment] 2019-05-22 14:20
We moved the file recently, so I can easily imagine an upgrade can cause issues. Clearing the build files will probably help.

**Comment by janczizikow** [comment] 2019-05-22 15:29
@kneth thanks, indeed after removing `ios/build` compilation via `react-native run-ios` worked again 😬

**Comment by rardoz** [comment] 2019-05-23 00:20
https://github.com/realm/realm-js/blob/cd579770ad50bba5ce6dcfa89591334fd1735c53/src/rpc.hpp#L26

This is the file that is including the missing json.hpp

The json.hpp file is not in the repository.

https://github.com/realm/realm-js/tree/cd579770ad50bba5ce6dcfa89591334fd1735c53/src

Please advise.

**Comment by kneth** [comment] 2019-05-23 07:29
We use git submodules to include a number of other repositories. As our [object store](https://github.com/realm/realm-object-store) (shared between all our SDKs) recently got a need for `json.hpp`, we decided to move the file to that repository.

**Comment by rardoz** [comment] 2019-05-23 14:43
@kneth thanks for the explanation!

**Closed** 2019-05-23 19:02 UTC
Labels: O:User, T:Help

**Comment by mattpocock** [comment] 2019-06-10 12:53
Still getting this on 2.28.1, when cloning from fresh.

**Comment by kneth** [comment] 2019-06-12 14:19
@mattpocock After cloning, did you also initialize and update the submodules?

**Comment by mkremer-jemmic** [comment] 2019-06-14 08:17
I had the same issue using Realm 2.28.1. What solved the issue for me was the following:
1) Unlink RealmReact from my project
2) Do a `yarn upgrade realm`
3) Manually link RealmReact again (by dragging RealmReact.xcodeproj into the libraries folder in Xcode and by linking libRealmReact.a)

I'm using Xcode 10.2.1 btw

**Comment by kneth** [comment] 2019-06-25 12:34
@mkremer-jemmic Your procedure is supporting my [comment](https://github.com/realm/realm-js/issues/2376#issuecomment-495101211).

**Comment by ruslanaplid** [comment] 2019-06-26 09:19
Thanks!
How I fixed this:
1) Remove `RealmReact.xcodeproj` in dir `/Libraties` my Xcode-project
2) `$ yarn upgrade realm`
3) `$ react-native link`
4) Control shot:  Drag `.../node_modules/realm/react-native/ios/RealmReact.xcodeproj` to dir `/Libraties` my Xcode-project
