### ISSUE TITLE
Memory leak when reloading the app with Results/List Object listeners

### ISSUE THREAD

**Issue by dkpalmer** [realm/realm-js#2378] opened 2019-05-21 19:52 UTC
## Goals

Use Results/List Object listeners during development of a React Native app. This requires restarting the simulator or force-closing the app on device after a certain number of reloads.

## Expected Results

Reloading the app during development (__DEV__ mode) should not leak.

## Actual Results

Memory leaks when dev-reloading the app with listeners on `RealmResults` and List objects. It does _not_ leak on listeners on the `Realm` instance.

## Steps to Reproduce

* Call `addListener` on either a `RealmResults` object or a List object.
* Reload the app (CMD+R)
* See that memory climb

## Code Sample

I created a fresh React Native app to demonstrate the issue at https://github.com/dkpalmer/realm-rn-reload-leak/. Inside App.js there are 3 cases within `componentWillMount`:

Does not leak when reloading: (1) Realm listener

Does leak when reloading: (2) Results listener and (3) List object listener

Assuming you have the RN CLI and Xcode installed, app can be run by cloning, installing dependencies, and running `react-native run-ios`.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.27.0 and 2.28.0
- Node or React Native: RN 0.59
- Client OS & Version: iOS
- Which debugger for React Native: DEV Perf Monitor

**Comment by dkpalmer** [comment] 2019-05-21 20:18
Also, I have tried looking at this from the RN side about any sort of cleanup opportunities before the bundle gets reloaded. Unfortunately, it doesn't look like there is a good option on that side: https://github.com/facebook/react-native/issues/9773

**Comment by dkpalmer** [comment] 2019-06-10 14:37
Quick bump. Does anyone have any insights on the difference between a Realm Listener and a Results/Object listener and why the latter two would retain after reloading the JavaScript bundle, and/or suggestions on how to work around this?

**Comment by pedrobertao** [comment] 2019-06-14 17:02
I have similar problem with my project. On Android when we started to use listeners the App would just crash after a couple of reloads.

**Comment by kneth** [comment] 2019-08-19 09:56
From https://github.com/facebook/react-native/issues/9773 it sounds virtually impossible to make a solution which works every time.

Removing all listeners in `componentDidMount()` (before everything else) might be a work-around.

**Comment by dkpalmer** [comment] 2019-09-13 15:35
@kneth Do you have insights why Results and List object listeners do _not_ leak?

**Comment by kneth** [comment] 2019-09-23 09:46
@dkpalmer Results and List are based by Realm (the underlaying database engine) so they are native (C++) resources. Such resources are probably reclaimed by the operating system - even at reload. But the listener lives in the JS engine, and seems to survive a reload. I have label this issue as a bug as I believe listeners should be reclaimed too.

**Comment by SDSLeon** [comment] 2021-04-21 16:11
Still an issue. Found that old JSContext is not destroyed when addListener is present on Results;
![image](https://user-images.githubusercontent.com/6071034/115586220-0923b180-a2d5-11eb-959d-9dee4ba18e08.png)
![image](https://user-images.githubusercontent.com/6071034/115586316-23f62600-a2d5-11eb-892b-a7acd19cac5d.png)

**Comment by bmunkholm** [comment] 2021-11-18 09:11
This may be resolved with our [Hermes support](https://github.com/realm/realm-js/issues/3940). Will have to verify.

**Comment by kneth** [comment] 2022-10-20 11:44
We have released v11.0.0 which has a complete rewrite of the integration with JSC. I am closing the issue, and ask you to upgrade. If the issue is still observed, please create a new issue.

**Closed** 2022-10-20 11:51 UTC
Labels: T-Bug, O-Community
