### ISSUE TITLE
IOS build failed

### ISSUE THREAD

**Issue by gezichenshan** [realm/realm-js#1039] opened 2017-06-01 03:07 UTC
In file included from /Users/user/ryanown/newProject/node_modules/realm/src/object-store/src/impl/realm_coordinator.hpp:22:
/Users/user/ryanown/newProject/node_modules/realm/src/object-store/src/shared_realm.hpp:29:10: fatal error: 'realm/sync/client.hpp' file not found
#include <realm/sync/client.hpp>
         ^
1 error generated.

** BUILD FAILED **

The following build commands failed:

	CompileC /Users/user/ryanown/newProject/ios/build/Build/Intermediates/RealmJS.build/Debug-iphonesimulator/RealmJS.build/Objects-normal/x86_64/external_commit_helper.o object-store/src/impl/apple/external_commit_helper.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler

**Comment by blagoev** [comment] 2017-06-02 11:45
It seems you are trying to build a React Native project for ios and fails for you. I can't reproduce this error. Can you provide more details for what is your setup and environment. If you can provide a simple project that fails will be great as well.

**Comment by gezichenshan** [comment] 2017-06-03 01:33
I dont know why this happened.But when I copy the **node_modules** from my colleague , It works and no error again.So I think it might be something wrong when I do 'npm install'.

**Comment by blagoev** [comment] 2017-06-03 20:48
I will close this issue as not reproducible. Write us back when the error is more clear. 

cheers

**Closed by blagoev** 2017-06-03 20:48 UTC
Labels: S:Waiting For User, T:Help
