### ISSUE TITLE
Wrong Type Runtime Errors are Confusing

### ISSUE THREAD

**Issue by mbalex99** [realm/realm-js#986] opened 2017-04-27 20:50 UTC
If you have a schema property with a `null` value like this, you will get an unuseful error.

```javascript
const fxSchema: Realm.ObjectSchema = {
    name: 'Fx',
    properties: {
        errorMessage: { type: "string", default: null }
    }
}
export const realm = new Realm({ schema: [fxSchema] })
```

**Actual**: There will be a runtime error of:

`Error: 'Property' must be of type: string`

**Expected**

- [ ] It should specify the name of the Object 
- [ ] It should specify the property name
- [ ] It should specify the correct type (and whether or not it is optional)

`Error:  Object with name 'Fx' and property named 'errorMessage' must be of type: string (non-optional)`

**Comment by MrHubble** [comment] 2017-04-28 00:00
I agree with you. This is a prolonged problem and has been raised multiple times:
https://github.com/realm/realm-js/issues/787
https://github.com/realm/realm-js/issues/897
https://github.com/realm/realm-js/issues/730
https://github.com/realm/realm-js/issues/883

**Comment by kristiandupont** [comment] 2017-06-06 09:42
Closing this as a duplicate of #787

**Closed** 2017-06-06 09:42 UTC
Labels: T:Duplicate
