### ISSUE TITLE
Flex Sync Realm file cannot be opened with Realm Studio

### ISSUE THREAD

**Issue by devsales** [realm/realm-js#6046] opened 2023-08-08 15:02 UTC
I'm trying to open the Realm file after opening a flexible sync Realm. However in Realm Studio I see "History type not consistent" like this:

<img width="896" alt="Screenshot 2023-08-08 at 16 52 35" src="https://github.com/realm/realm-js/assets/47062834/087f78af-3b9c-4435-8fe8-86e769c1e8b7">

This is how I'm setting up the RealmProvider:

```JavaScript
<RealmProvider
    realmRef={realmRef}
    fallback={<LoadingScreen />}
    shouldCompact={shouldCompact}
    path={`mongodb-realm/${REALM_APP_ID}/${user.id}/flex_sync.realm`}
    schema={schema}
    schemaVersion={schemaVersion}
    sync={{
      user,
      flexible: true,
      //@ts-ignore
      existingRealmFileBehavior: realmFileBehavior,
      //@ts-ignore
      newRealmFileBehavior: realmFileBehavior,
      initialSubscriptions: {...},
      clientReset: {...},
      onError: async (syncSession, syncError) => {...},
    }}
  >
```

Does anyone know why this is happening?

**Comment by kneth** [comment] 2023-08-09 14:59
@devsales 

I am not able to reproduce it using Realm JS v11.10.1 and Realm Studio v14.0.3. Which versions do you use?

**Comment by devsales** [comment] 2023-08-10 14:27
@kneth I'm using Realm v11.8.0 and Realm Studio v14.0.3.

**Comment by kneth** [comment] 2023-08-11 14:35
@devsales I still can't reproduce it. Do you also see it if the file has been created on Android?

**Comment by kneth** [comment] 2023-10-31 13:03
I am closing the issue due to no reply back. Please create a new issue if you have new observations to share.

**Closed by kneth** 2023-10-31 13:03 UTC
Labels: O-Community, Waiting-For-Reporter
