### ISSUE TITLE
Write transaction's exceptions are not being caught by try catch block 

### ISSUE THREAD

**Issue by gauravbordoloi** [realm/realm-js#4747] opened 2022-07-31 05:09 UTC
### How frequently does the bug occur?

All the time

### Description

Exceptions are not being caught!!!

let realm;
    let response;
    try {
        realm = options.realm || await Realm.open(db);
        realm.beginTransaction();

        response = await getCustomer({ id: payload.id }, { realm: realm })
        if (response) {
            response.date_updated = Date.now();
            if (payload.name) {
                response.name = payload?.name;
            }
            if (payload.email) {
                response.email = payload?.email;
            }
            if (Array.isArray(payload.tags)) {
                response.tags = payload.tags;
            }
            if (payload.address) {
                response.address = realm.create(AddressModel, payload.address);
            }
            if (payload.remarks) {
                response.remarks = payload.remarks;
            }
        }
        realm.commitTransaction();

        if (!options.realm) {
            response = response?.toJSON();
        }
    } catch (error) {
        console.log(error)
        console.log("Hey")
        if (realm?.isInTransaction === true) {
            realm?.cancelTransaction();
        }
    } finally {
        if (!options.realm) {
            realm?.close();
        }
    }

### Can you reproduce the bug?

Yes, always

### Version

10.19.5

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Node 14.x.x

**Comment by kneth** [comment] 2022-08-02 12:58
@gauravbordoloi I have added a test in #4749 but the exception is caught as expected. Please take a look at my test to see if there is any misunderstanding from my side.

**Comment by gauravbordoloi** [comment] 2022-08-03 12:27
@kneth You are crashing the runtime manually by throwing the error, whereas in my case, the error was thrown internally by realm when I was passing payload with invalid schema (like different data type) to create the object. That internal error was not being caught by try-catch block.
Can you please verify my statement once by passing an invalid payload to the write transaction?

**Comment by kneth** [comment] 2022-08-04 12:50
@gauravbordoloi I have added a new test where `Realm#create()` fails. I cannot reproduce it.

**Comment by kneth** [comment] 2022-08-09 14:28
I am closing the issue as I cannot reproduce it. Don't hesitate to either reopen or create a new issue if you have further information to consider.

**Closed by kneth** 2022-08-09 14:28 UTC
Labels: T-Bug, Reproduction-Required, O-Community, Waiting-For-Reporter
