### ISSUE TITLE
Bad user authentication (BIND, REFRESH) (203)

### ISSUE THREAD

**Issue by atom2ueki** [realm/realm-js#858] opened 2017-02-10 17:30 UTC
get an error when trying use admin token access object server
Connection closed due to error reported by server: Bad user authentication (BIND, REFRESH) (203)

from docs: 203 “Bad user authentication (BIND, REFRESH)” Indicates that the server has produced a bad token, or that the SDK has done something wrong.
but the token get from admin_token.base64, how comes it will be wrong?

how to refresh a new token if this one is not correct?

**Comment by istx25** [comment] 2017-02-10 17:36
Hi @atom2ueki. Thanks for reaching out. Someone will follow-up with you soon. Cheers!

**Comment by aottenwess** [comment] 2017-02-15 16:18
Hi @istx25 , I just experienced the same issue when trying to run my event listener on the AWS AMI, professional edition

**Comment by ianpward** [comment] 2017-02-16 02:24
Hello, can you share the node.js code snippet you are using to log into the server?

**Comment by kristiandupont** [comment] 2017-02-16 14:30
@atom2ueki are you running the server locally or on AWS?

**Comment by atom2ueki** [comment] 2017-03-10 09:33
@kristiandupont I'm running on my Linode server inside a docker -> bbrodriges/realm-object-server

**Comment by atom2ueki** [comment] 2017-03-10 09:37
@ianpward 
```
var RealmBlog = exports.Realm = function() {
	let PostSchema = {
		...
	}
 	let schema = [PostSchema]
	// Open a Realm using the admin user
 	this.realm = new Realm({
 		sync: {
			user: Realm.Sync.User.adminUser(process.env.REALM_TOKEN),
			url: 'realm://'+process.env.REALM_SERVER_URL+'/~/blog-realm'
		},
		schema: schema,
	});
}
```

**Comment by kristiandupont** [comment] 2017-03-14 15:38
This all looks good. Are you absolutely sure you copied the entire admin token and nothing but it into your environment variable? If possible, could you try hardcoding it into your code to see if that makes a difference?

**Comment by atom2ueki** [comment] 2017-03-17 07:44
@kristiandupont when I run this code, get `Realm.Sync.User.adminUser` -> TypeError: Cannot read property 'User' of undefined

**Comment by kristiandupont** [comment] 2017-03-17 08:56
Ah, that's because you are running on Linux! We do not support sync on Linux in the free version. Yes, this is not clear in our messaging and it's something that we need to improve.

**Comment by atom2ueki** [comment] 2017-03-17 09:41
@kristiandupont oh...yea, no wonder same version of code and node, my mac able to run but my server cannot, but even when I use my mac, get this error (see pic below), I already give up 9443 https instead using 9080 now

<img width="1429" alt="screen shot 2017-03-17 at 5 36 50 pm" src="https://cloud.githubusercontent.com/assets/5100535/24037467/dfec977e-0b38-11e7-894b-d51ff41da1bf.png">

**Comment by kristiandupont** [comment] 2017-03-17 09:48
Ok, so that means that the admin token is bad. Did you try hardcoding it into your code to see if that makes a difference? Otherwise, would it be possible for you to share your project with us at help@realm.io so I can try and see if I can reproduce it?

**Comment by atom2ueki** [comment] 2017-03-17 11:28
@kristiandupont I may misunderstand, is the realm object server not support on linux or realm.js not support on linux, because my object server inside a docker with ubuntu 14.04, will share my project to that email also, thanks

**Comment by kristiandupont** [comment] 2017-03-17 11:37
The object server can run on Linux just fine. It's the developer (=free) edition of the node.js sdk that doesn't support sync on Linux. I will take a look at your project.

**Comment by blagoev** [comment] 2017-03-23 13:47
@atom2ueki Hi I couldn't to reproduce the issue with the project that you sent us and with the same environment as yours. 
Initially I had the same error as yours but when I changed the correct admin token to the correct one I had no problem connecting and working with the realm inside the docker container. 

I would suggest checking that the admin token is indeed the correct one and that you are not connecting to a different docker container while you are trying it.

cheers

**Comment by atom2ueki** [comment] 2017-04-03 03:07
@blagoev @kristiandupont thanks, now I can connect, yes, the token I used is not correct, and I found if I running it with docker (almost every version), the admin token (/etc/realm/admin_token.base64) will not update, the date of that token created always the date that docker file created, it's tricky

**Comment by atom2ueki** [comment] 2017-04-03 03:11
@blagoev @kristiandupont I've update the docker image, it seems working fine now, please ignore the last message, the docker image I used right now is `robertwtucker/realm-object-server`,  maybe you guys can release an official docker images will be appreciated, thanks again (;

**Comment by blagoev** [comment] 2017-04-03 07:38
great! closing this one

**Closed by blagoev** 2017-04-03 07:38 UTC
Labels: S:Waiting For User, T:Help
