### ISSUE TITLE
@realm/react - useObject stops updating after repeated calls with the same ID

### ISSUE THREAD

**Issue by bsluther** [realm/realm-js#5620] opened 2023-03-23 01:18 UTC
### How frequently does the bug occur?

Sometimes

### Description

I apologize if this is something I'm doing wrong, but I can't seem to find any explanations for the behavior other than `useObject`. I looked at the source code and it does some hard-to-follow reference updating, so it doesn't seem out of the realm of possibility that something is going wrong with repeated calls of the same value, although I would have expected someone else would have encountered the same problem.

Expected Results:
Pass different IDs to `useObject` throughout the lifetime of a component and get back the corresponding Realm object.

Actual Results:
The value returned by `useObject` behaves as expected the first time any particular ID is passed as an argument. But the second or third time `useObject` receives an ID that it has previously received, it fails to update the return value, continuing to return whatever the previous object was.

### Can you reproduce the bug?

Sometimes

### Reproduction Steps

I encountered it in a project I'm working on and reproduced it in another repo (based on the Realm Expo template) with a really basic setup as seen below. Basically just make a FlatList where clicking on an item will render a separate component which takes the `id` as a prop and then passes it to `useObject`. If you click around, the behavior is erratic:
- If I click through all items, each item will update as expected the first time.
- Typically exactly one repeated call to `useObject` will update with the appropriate data.
- After that, the value in `useObject` seems to be mostly "stuck" wherever it is.
- Occasionally an update will occur as expected after several calls to `useObject` (eg clicking the list items a bunch in my example).

```js
const PersonItem = ({ name, onPress }) => {
  return (
    <Pressable onPress={onPress}>
      <Text>
        {name}
      </Text>
    </Pressable>
  )
}

const ViewPerson = ({ personId }) => {
  const person = useObject(Person, personId)
  return <Text>{person.personName}</Text>
}

const BrowsePeople = () => {
  const people = useQuery(Person)
  const [selected, setSelected] = useState<BSON.ObjectId>()

  return (
    <View>
      <FlatList
        data={people}
        keyExtractor={el => el._id.toHexString()}
        renderItem={(el) => 
          <PersonItem  
            name={el.item.personName}
            onPress={() => setSelected(el.item._id)}
          />}
      />
      {selected && <ViewPerson personId={selected} />}
    </View>
  )
}
```

### Version

0.4.3, 0.4.1

### What services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

No

### Platform OS and version(s)

expo 48.0.6, react-native 0.71.4, realm 11.5.2

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment] 2023-03-23 11:08
@bsluther That should work.  I'll investigate this as soon as I can.

**Comment by jersonpl** [comment] 2023-03-31 17:40
same with react-native cli

Reviewing the code I think it happens because after comparing the input primaryKey and primaryKeyRef the primaryKeyRef is not being updated with the new value

**Comment by amlynarski** [comment] 2023-05-09 10:32
@takameyer we have the same issue. Current workaround is to use `useQuery`. 
It can be easily to reproduce with 2 schemas:


```

const SETTINGS_USER = 'USER';

const settingsSchema = {
    name: 'settings',
    primaryKey: 'name',
    properties: {
        name: 'string',
        value: 'string'
    }
}

const userSchema = {
    name: 'user',
    primaryKey: 'id',
    properties: {
        id: 'int',
        name: 'string'
    }
}
```

and with `useObject` it updates from time to time (mostly not):

```
/** not working */
const useCurrentUser = () => {
    const currentUserNumber = useObject('settings', SETTINGS_USER)
    const user = useObject('user', parseInt(currentUserNumber.value, 10))

    useEffect(() => {
        console.log('user', user); // it 'sometimes' updates, mostly not
    },[user])

    return user; // this should be always updated when current user is changed
}
```

but with `useQuery` it always updates:

```
/** working */
const useCurrentUser = () => {
    const currentUserNumber = useQuery('settings').filtered(`name = '${SETTINGS_USER}'`)[0]
    const user = useQuery('user').filtered(`id = '${currentUserNumber.value}'`)[0]

    useEffect(() => {
        console.log('user', user); // always updates
    },[user])

    return user;
}
```

version: 0.4.3
rn: 0.70.5

**Comment by MaxTibs** [comment] 2023-06-02 15:10
Any news on this? I'm experiencing the same issue... Updating the key of `useObject` doesn't update the return matching object

**Comment by HighDeck** [comment] 2023-06-02 16:00
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@realm/react/dist/useObject.js b/node_modules/@realm/react/dist/useObject.js
index af259d2..bf7376a 100644
--- a/node_modules/@realm/react/dist/useObject.js
+++ b/node_modules/@realm/react/dist/useObject.js
@@ -86,6 +86,7 @@ export function createUseObject(useRealm) {
                     updatedRef,
                 });
                 originalObjectRef.current = originalObject;
+                primaryKeyRef.current = primaryKey;
             }
             return cachedObjectRef.current;
         }, [realm, originalObject, primaryKey]);
```

We'll be using `patch-package` while waiting for this to be fixed :)

**Comment by amlynarski** [comment] 2023-06-08 11:27
> Hi! 👋
> 
> Firstly, thanks for your work on this project! 🙂
> 
> Here is the diff that solved my problem:
> 
> ```diff
> diff --git a/node_modules/@realm/react/dist/useObject.js b/node_modules/@realm/react/dist/useObject.js
> index af259d2..bf7376a 100644
> --- a/node_modules/@realm/react/dist/useObject.js
> +++ b/node_modules/@realm/react/dist/useObject.js
> @@ -86,6 +86,7 @@ export function createUseObject(useRealm) {
>                      updatedRef,
>                  });
>                  originalObjectRef.current = originalObject;
> +                primaryKeyRef.current = primaryKey;
>              }
>              return cachedObjectRef.current;
>          }, [realm, originalObject, primaryKey]);
> ```
> 
> We'll be using `patch-package` while waiting for this to be fixed :)

It doesn't work for me - actually sometimes it works sometimes not. Inside `useObject.js` looks like it returns new value for object when it switch between `null` -> `value` -> `null` but it doesn't refresh when it switch from `value1` -> `value2`.

What is more when it is working the change is not immediately visible, but when I use `useQuery` instead then it refresh in real time.

**Comment by MinisX** [comment] 2023-08-22 16:09
same problem here. id1 -> id2 -> id1 results in object with id2

**Comment by MinisX** [comment] 2023-08-22 16:21
> @takameyer we have the same issue. Current workaround is to use `useQuery`. It can be easily to reproduce with 2 schemas:
> 
> ```
> 
> const SETTINGS_USER = 'USER';
> 
> const settingsSchema = {
>     name: 'settings',
>     primaryKey: 'name',
>     properties: {
>         name: 'string',
>         value: 'string'
>     }
> }
> 
> const userSchema = {
>     name: 'user',
>     primaryKey: 'id',
>     properties: {
>         id: 'int',
>         name: 'string'
>     }
> }
> ```
> 
> and with `useObject` it updates from time to time (mostly not):
> 
> ```
> /** not working */
> const useCurrentUser = () => {
>     const currentUserNumber = useObject('settings', SETTINGS_USER)
>     const user = useObject('user', parseInt(currentUserNumber.value, 10))
> 
>     useEffect(() => {
>         console.log('user', user); // it 'sometimes' updates, mostly not
>     },[user])
> 
>     return user; // this should be always updated when current user is changed
> }
> ```
> 
> but with `useQuery` it always updates:
> 
> ```
> /** working */
> const useCurrentUser = () => {
>     const currentUserNumber = useQuery('settings').filtered(`name = '${SETTINGS_USER}'`)[0]
>     const user = useQuery('user').filtered(`id = '${currentUserNumber.value}'`)[0]
> 
>     useEffect(() => {
>         console.log('user', user); // always updates
>     },[user])
> 
>     return user;
> }
> ```
> 
> version: 0.4.3 rn: 0.70.5

@amlynarski thanks for the workaround, this works. Hopefully the issue with useObject will be fixed soon.

**Closed** 2023-08-23 07:59 UTC
Labels: T-Bug, O-Community
