### ISSUE TITLE
Can't download Realm。

### ISSUE THREAD

**Issue by liweijieok** [realm/realm-js#1879] opened 2018-06-20 03:49 UTC
hello ,I use Realm in my RN project, but when i use `npm install --save realm`,i't show me the follwing error.
the url of  `https://static.realm.io/node-pre-gyp/2.10.0/realm-v2.10.0-node-v64-darwin-x64.tar.gz ` is `404`.
What should i do .thanks.
My React Version is `16.3.1` ,ReactNative Version is `0.55.4`,node version is `10.4.1` ，npm version is `6.1.0`

```
> realm@2.10.0 install /Users/liweijie/dev/webstrome/Focaltv/node_modules/realm
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://static.realm.io/node-pre-gyp/2.10.0/realm-v2.10.0-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for realm@2.10.0 and node@10.4.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://static.realm.io/node-pre-gyp/2.10.0/realm-v2.10.0-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for realm@2.10.0 and node@10.4.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
  TOUCH Release/obj.target/OpenSSL.stamp
  TOUCH Release/obj.target/OpenSSL.stamp
  ACTION binding_gyp_vendored_realm_target_download_realm /Users/liweijie/dev/webstrome/Focaltv/node_modules/realm/vendor/realm-mac-x64
  ACTION binding_gyp_vendored_realm_target_download_realm /Users/liweijie/dev/webstrome/Focaltv/node_modules/realm/vendor/realm-mac-x64
Resolved requirements: { SYNC_SERVER_FOLDER: 'sync',
  SYNC_ARCHIVE: 'realm-sync-node-cocoa-3.5.6.tar.gz',
  SYNC_ARCHIVE_ROOT: 'realm-sync-node-cocoa-3.5.6' }
Resolved requirements: { SYNC_SERVER_FOLDER: 'sync',
  SYNC_ARCHIVE: 'realm-sync-node-cocoa-3.5.6.tar.gz',
  SYNC_ARCHIVE_ROOT: 'realm-sync-node-cocoa-3.5.6' }
No lockfile found at the target, proceeding.
No lockfile found at the target, proceeding.
Download url: https://static.realm.io/downloads/sync/realm-sync-node-cocoa-3.5.6.tar.gz
Download url: https://static.realm.io/downloads/sync/realm-sync-node-cocoa-3.5.6.tar.gz
Extracting realm-sync-node-cocoa-3.5.6.tar.gz => /Users/liweijie/dev/webstrome/Focaltv/node_modules/realm/vendor/realm-mac-x64
Extracting realm-sync-node-cocoa-3.5.6.tar.gz => /Users/liweijie/dev/webstrome/Focaltv/node_modules/realm/vendor/realm-mac-x64
^C
liweijiedeMacBook-Pro:Focaltv liweijie$ make: *** [/Users/liweijie/dev/webstrome/Focaltv/node_modules/realm/vendor/realm-mac-x64] Interrupt: 2
make: *** [/Users/liweijie/dev/webstrome/Focaltv/node_modules/realm/vendor/realm-mac-x64] Interrupt: 2
```

**Comment by kneth** [comment] 2018-06-20 11:59
Duplicate of #1813

**Closed by kneth** 2018-06-20 11:59 UTC
Labels: O:User
