### ISSUE TITLE
Not works with react-native-threads

### ISSUE THREAD

**Issue by joaom182** [realm/realm-js#1928] opened 2018-07-14 18:49 UTC
## Goals

Use `realm` with `react-native-threads`

## Expected Results

`realm` can be used with `react-native-threads`

## Actual Results

When start an thread with `react-native-threads` javascript thread bundle file stuck on top screen, and after press `cmd + r`, application crashes.

![](https://user-images.githubusercontent.com/15066459/39923244-83e3fbdc-552b-11e8-9682-efee4532faff.png)

## Steps to Reproduce

`npm install react-native-threads --save`
`react-native link react-native-threads`

`npm install realm --save`
`react-native link realm`

On `index.js` start a thread of `react-native-threads`

`react-native run-ios`

`cmd + r` the app should be crash or top green bar stucked with `Downloading Javascript bundle 100%`.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.13.0
- Node or React Native: 0.52.0
- Client OS & Version: Mac OSX High Sierra 10.13.5
- Which debugger for React Native: none

**Comment by bmunkholm** [comment] 2018-07-20 09:48
@joaom182 Why do you think it's related to Realm? Would it be possible to reduce this to a repro-case in a self-contained example?

**Comment by joaom182** [comment] 2018-07-20 17:38
@bmunkholm i've not discovered yet, but my project runs like a charm without `realm`. When i installed `realm` the app crashes on start unexpectedly. So i remove `react-native-threads`, and app not crashes anymore, and try install `react-native-threads` again, and.. crashes!

So i think that has any concurrence with threads instance on native implementation with the libraries. But is the good question if the issue is related to `realm` or with `react-native-threads`. In doubt I reported this incident in both repositories.

**Comment by kneth** [comment] 2018-08-13 11:37
The issues at `react-native-threads`: https://github.com/joltup/react-native-threads/issues/29

**Comment by kneth** [comment] 2018-08-13 11:42
My best guess is that accessing Realm across **processes** might be the issue here. Realm supports multi-process access server-side (for example two node.js processes) but not on mobile.

**Comment by gitTeub** [comment] 2018-10-12 09:39
Hi! Did anybody find a solution or workaround?

**Comment by z98361** [comment] 2018-11-24 10:48
same issue

**Comment by kneth** [comment] 2019-08-14 09:53
I close the issue. Once we implement multi-process support, I expect it to work.

**Closed by kneth** 2019-08-14 09:53 UTC
Labels: O:User, Reproduction Required, T:Help

**Comment by joaom182** [comment] 2019-08-14 15:01
@kneth thanks! i will try.

**Comment by tastyqbit** [comment] 2020-05-18 15:36
Are there any updates on this? I am still having issues where I cannot use react-native-threads while realm is installed. It works fine when I uninstall it

**Comment by kneth** [comment] 2020-05-19 06:54
@tastyqbit We have no estimate for when we will have multi-process support.

**Comment by mwri** [comment] 2020-08-09 15:14
> I close the issue. Once we implement multi-process support, I expect it to work.

I'm not sure closing the issue is on the basis that it will be resolved when X is implemented is really right. Closing it as "not supported" or "won't fix" would be OK, but if the issue is valid and it is accepted as WILL be supported, or at least is desirable to support it, and it's on the road map, however tenuously... then surely we are all best served by the issue being open.

**Comment by ZComwiz** [comment] 2022-08-19 15:27
There is a valid use case for this. A lot of high throughput data processing should not block the UI and should be offloaded to a background thread. A common case of this for this would be loading a lot of data in from a source, formatting the data to match a realm schema, and saving it to realm. This serialization process can be burdensome and block UI. The realm write needs to be on the same thread as this busy work.

It would need to be thread safe for the React UI to be updated eventually.
