### ISSUE TITLE
data source crashes the app

### ISSUE THREAD

**Issue by gritzko** [realm/realm-js#838] opened 2017-02-02 14:11 UTC
if we change
```js
<ListView dataSource={this.state.dataSource} renderRow={this.renderRow} />
```
to
```js
<ListView dataSource={this.state.dataSource} />
```
we get a core dump.
Which is shocking for a JavaScript developer.
Apparently, some null check is missing somewhere.

**Comment by fealebenpae** [comment] 2017-02-02 14:14
What is the stack trace of the dump? Running in Xcode ought to give us a nicely formatted trace.

**Comment by gritzko** [comment] 2017-02-02 14:15
```
#0	0x000000010bcb3dd6 in __pthread_kill ()
#1	0x000000010bceb787 in pthread_kill ()
#2	0x000000010ba2dfd7 in abort ()
#3	0x000000010b7f795a in abort_message ()
#4	0x000000010b81cce7 in default_terminate_handler() ()
#5	0x000000010810d4b4 in _objc_terminate() ()
#6	0x000000010b819e69 in std::__terminate(void (*)()) ()
#7	0x000000010b819af4 in __cxa_rethrow ()
#8	0x000000010810d3b7 in objc_exception_rethrow ()
#9	0x000000010921290b in CFRunLoopRunSpecific ()
#10	0x0000000106cdad78 in ::+[RCTJSCExecutor runRunLoopThread]() at /Users/gritzko/Projects/RealmTasks/RealmTasks React/node_modules/react-native/React/Executors/RCTJSCExecutor.mm:208
#11	0x0000000107bfe654 in __NSThread__start__ ()
#12	0x000000010bce8aab in _pthread_body ()
#13	0x000000010bce89f7 in _pthread_start ()
#14	0x000000010bce81fd in thread_start ()
```

**Comment by fealebenpae** [comment] 2017-02-02 14:41
Looking at the trace, `objc_exception_rethrow ()` seems to indicate that there has been an unhandled Objective-C exception. Is there something in the Xcode output window that mentions an exception?

**Comment by gritzko** [comment] 2017-02-07 12:22
Trying to reproduce. It only red-screens the app. No crash.

**Comment by kneth** [comment] 2018-03-05 14:14
I am closing it since you haven't reported any case to reproduce it.

**Closed by kneth** 2018-03-05 14:14 UTC
Labels: T:Bug-Crash
