### ISSUE TITLE
RealmDB error:: Failed to fetch

### ISSUE THREAD

**Issue by roma-hladilka** [realm/realm-js#4864] opened 2022-09-05 12:42 UTC
### How frequently does the bug occur?

Sometimes

### Description

I can see about 1500 - 2000 errors per day with this message on Sentry. We use this release (the last one) [Realm Web v1.7.1](https://github.com/realm/realm-js/releases/tag/realm-web-v1.7.1) Why could it happen?

### Stacktrace & log output

```shell
{
message: Failed to fetch, 
name: TypeError, 
stack: 
TypeError: Failed to fetch
    at r (https://edge.fullstory.com/s/fs.js:3:12094)
    at e.<anonymous> (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:2900993)
    at f (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:96325)
    at Generator._invoke (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:96078)
    at Generator.next (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:96692)
    at n (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:182196)
    at s (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:182399)
    at https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:182458
    at new Promise (<anonymous>)
    at e.<anonymous> (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:182339)
    at e.<anonymous> (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:2901233)
    at e.<anonymous> (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:2944930)
    at f (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:96325)
    at Generator._invoke (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:96078)
    at Generator.next (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:96692)
    at n (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:182196)
    at s (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:182399)
    at https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:182458
    at new Promise (<anonymous>)
    at e.<anonymous> (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:182339)
    at e.<anonymous> (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:2945631)
    at e.<anonymous> (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:2944788)
    at f (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:96325)
    at Generator._invoke (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:96078)
    at Generator.next (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:96692)
    at n (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:182196)
    at s (https://wallet.gooddollar.org/static/js/2.d216800a.chunk.js:2:182399)
}
```

### Can you reproduce the bug?

Not yet

### Version

1.7.1

### What SDK flavour are you using?

Atlas App Services (auth, functions, etc.)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Mainly android web, but others too (Windows, Linux, Mac...)

### Build environment

"react-app-rewired": "^2.1.8",
"react": "^17.0.2",

**Comment by kneth** [comment] 2022-09-06 08:08
@roma-hladilka You mention that you are primarily using Android but also Windows, Linux and Mac. Do you see the error on all platforms or only one of them?

Can you explain which functionality of Atlas App Services you are using? It it all functionality which are failing or only one specific one? I am trying to understand where in the Realm Web code base we need to examine further.

**Comment by roma-hladilka** [comment] 2022-09-06 11:37
Hi @kneth! I can see the error on all platforms, and 60% of all users that have it are from Android.

In the app we initialise App and Credentials
```
this.app = new Realm.App({ id: REALM_APP_ID })
      this.credentials = Realm.Credentials.jwt(jwt)
```
login with credentials
`this.app.logIn(this.credentials)`
and use mongoClient for database
   ```
 const mongodb = app.currentUser.mongoClient('mongodb-atlas')
 mongodb.db(_databaseName)
```
after that we work with some collections from db
`this.database.collection('some_collection')`

I think this is all what we do

**Comment by johnsmith-gooddollar** [comment] 2022-09-06 14:26
@roma-hladilka could you please check which values returned from the above polyfills imports ?

**Comment by kneth** [comment] 2022-09-07 07:36
@roma-hladilka @johnsmith-gooddollar 

It the polyfill is not correctly set up, it might explain it for your node.js cases. You mention Android Web, is it Chrome for Android? Is it a CORS issue (see https://stackoverflow.com/questions/69872077/javascript-fetch-not-working-on-mobile-devices)?

**Comment by sirpy** [comment] 2022-09-07 09:01
@kneth 
We are actually using realmjs on both webapp version and native(android/ios)
But we are seeing this error only from devices running the webapp either mobile or desktop, it actually doesnt happen on our react-native app

**Comment by roma-hladilka** [comment] 2022-09-08 11:21
@kneth 
Are CORS configured in the package? Maybe there is an issue with it?

**Comment by kneth** [comment] 2022-09-13 11:35
The error `Failed to fetch` could indicate that the mobile device is loosing connectivity. Sentry will log the error when connectivity is restored. To understand if sporadic connectivity issues are the cause, it could be interesting to compare your 1500-2000 daily errors to the number of fetches you have.

**Comment by johnsmith-gooddollar** [comment] 2022-09-13 13:23
@roma-hladilka  @kneth i think it could be closed

**Comment by kneth** [comment] 2022-09-14 07:48
@johnsmith-gooddollar @roma-hladilka I am curious how you solve the issue?

**Comment by kneth** [comment] 2022-09-29 15:09
I am closing the issue due to no reply back. Please comment and reopen the issue if needed.

**Closed by kneth** 2022-09-29 15:09 UTC
Labels: T-Bug, Reproduction-Required, O-Community, Waiting-For-Reporter

**Comment by sirpy** [comment] 2022-09-29 15:31
@kneth we mostly added backoff retries and it reduced the amount of issues significantly

**Comment by sirpy** [comment] 2022-09-29 15:31
@kneth how can we find out if it might be related to rate limiting on your side?

**Comment by kneth** [comment] 2022-09-30 07:03
@sirpy Depending on your [support plan](https://www.mongodb.com/docs/atlas/app-services/help/), you can reach out to our technical service engineers. They can help you digest the server side logs to understand. 

In our documentation you can find [examples of billing](https://www.mongodb.com/docs/atlas/app-services/billing/)
