### ISSUE TITLE
Realm makes JS FPS drop significantly when app stays offline for a long time

### ISSUE THREAD

**Issue by Baira** [realm/realm-js#3882] opened 2021-08-03 20:49 UTC
I use Realm in production in several applications developed with react native. Multiple users complained that the app slows down significantly when they use it for several hours offline. The app is intended for offline-first use. Weirdly, when they go online, the app functions normally. 

We use the latest realm-js version with react native, realm sync and react-native-navigation. I was able to reproduce the bug and realm is definitely the issue. I can give access to private repository if a contributor is interested.

**Comment by bmunkholm** [comment] 2021-08-04 07:03
Hi Baira!
Since you can reproduce this could you possibly try to debug it and reduce the problem to get to an understanding which Realm functionality is causing slowdown? Getting to a minimal reproducing sample would be great.
Thanks!

**Comment by Baira** [comment] 2021-08-12 22:27
Hello Brian, 

Thank you for your input! So I created a minimal reproducing example using `npx react-native init` which you can find at [https://github.com/Baira/realm-bug](url). To reproduce the issue open the app while connected, try clicking on the various links and notice that everything works fine. Then disconnect and close the app. After sometime (seems random), open the app and you will notice than clicking on the links doesnt produce the "TouchableOpacity" effect smoothly. If you listen to the MessageQueue, you will notice that all UI events (touch, tap, etc.) are fired with a big delay.

After days of digging into this, it seems the problem happens whenever realm is opened in sync mode while offline. Something realm does blocks the bridge and thus prevents smooth UI interaction. I noticed that opening the realm in `readonly mode` resolves it but we need sync in our use case. You will find via this dropbox link two flamecharts of the app with realm opened in sync mode (thus producing the bug) and one without realm opened. [https://www.dropbox.com/t/WD37tRBmP7nNLbOz](url)

**Comment by Baira** [comment] 2021-08-13 21:58
> Hello Brian,
> 
> Thank you for your input! So I created a minimal reproducing example using `npx react-native init` which you can find at https://github.com/Baira/realm-bug. To reproduce the issue open the app while connected, try clicking on the various links and notice that everything works fine. Then disconnect and close the app. After sometime (seems random) while disconnected, open the app and you will notice that clicking on the links doesnt produce the "TouchableOpacity" effect smoothly. If you listen to the MessageQueue, you will notice that all UI events (touch, tap, etc.) are fired with a big delay.
> 
> After days of digging into this, it seems the problem happens whenever realm is opened in sync mode while offline. Something realm does blocks the bridge and thus prevents smooth UI interaction. I noticed that opening the realm in `readonly mode` resolves the issue but we need sync in our use case. You will find via this dropbox link two flamecharts of the app with realm opened in sync mode (thus producing the bug) and one without realm opened. https://www.dropbox.com/t/WD37tRBmP7nNLbOz

I forgot to mention that this happens on Android. I didn't test this on iOS.

**Comment by kneth** [comment] 2021-08-16 15:00
@Baira Thank you for the example and the description. We will run your example to see the behaviour.

**Comment by Baira** [comment] 2021-08-16 19:14
> @Baira Thank you for the example and the description. We will run your example to see the behaviour.

@kneth Thank you very much! It's my pleasure to contribute to such a great piece of software.

**Comment by Baira** [comment] 2021-08-23 16:19
@kneth @bmunkholm any progress on this ? Just asking, I know you must have many things to do.

**Comment by mednche** [comment] 2021-10-03 10:30
I'm encountering the same issue on iOS (Realm 10.8.0). When the app is opened in offline mode after having been in offline mode for some time (in our case, a whole night), the UI is extremely slow. Is there any fix for this yet?

**Closed** 2021-11-15 09:51 UTC
Labels: O-Community

**Comment by takameyer** [comment] 2021-11-15 15:18
We have a fix in `realm-core`.  On the next release, this problem should be fixed!

**Comment by Baira** [comment] 2021-11-16 22:58
> We have a fix in `realm-core`. On the next release, this problem should be fixed!

Thanks a ton guys! can't wait for the next release!

**Comment by kneth** [comment] 2021-11-18 14:55
The fix is included in version 10.10.1.
