### ISSUE TITLE
Support for Hermes + RN68 + new architecture

### ISSUE THREAD

**Issue by KartikSubramaniam** [realm/realm-js#4488] opened 2022-04-11 13:41 UTC
Hi ,
The beta version of realm works fine with RN68 which is not running on new architecture. However if we switch to new architecture the build fails. Do we have a support for the same?

Please find below the error details

Undefined symbols for architecture arm64:
  "folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::deferredReaders", referenced from:
      void folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::applyDeferredReaders<folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::WaitForever>(unsigned int&, folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::WaitForever&) in AppDelegate.o
      void folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::applyDeferredReaders<folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::WaitForever>(unsigned int&, folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::WaitForever&, unsigned int) in AppDelegate.o
  "folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::unlock()", referenced from:
      std::__1::unique_lock<folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false> >::~unique_lock() in AppDelegate.o
  "folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::~SharedMutexImpl()", referenced from:
      std::__1::__shared_ptr_emplace<facebook::react::ContextContainer const, std::__1::allocator<facebook::react::ContextContainer const> >::__on_zero_shared() in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

_Originally posted by @KartikSubramaniam in https://github.com/realm/realm-js/discussions/4487_

**Comment by tomduncalf** [comment] 2022-04-12 15:22
Hi @KartikSubramaniam, thanks for the report. When you refer to the new architecture, do you mean when you run `pod install` with `RCT_NEW_ARCH_ENABLED=1` set? I just created a [sample project](https://github.com/tomduncalf/realm-newarchitecture4488) using React Native `0.68.0` and Realm `10.20.0-beta.4` and it works for me with the new architecture enabled. 

Could you please try with `realm@10.20.0-beta.4` and see if this fixes the issue for you?

**Comment by KartikSubramaniam** [comment] 2022-04-13 04:37
@tomduncalf Thanks for the advise , will try realm@10.20.0-beta.4 and check if it works.

**Comment by tomduncalf** [comment] 2022-04-13 09:14
Great thanks, please let me know either way!

**Comment by KartikSubramaniam** [comment] 2022-04-14 07:45
Hi @tomduncalf  The build works fine with Hermes + RN68 + New Architecture but it fails to archive
I Still get the same error

I had used the following command for pod install
fabric_enabled=1 hermes_enabled=1 RCT_NEW_ARCH_ENABLED=1 pod install

Error: 
Undefined symbols for architecture arm64:
  "folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::deferredReaders", referenced from:
      void folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::applyDeferredReaders<folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::WaitForever>(unsigned int&, folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::WaitForever&) in AppDelegate.o
      void folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::applyDeferredReaders<folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::WaitForever>(unsigned int&, folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::WaitForever&, unsigned int) in AppDelegate.o
  "folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::unlock()", referenced from:
      std::__1::unique_lock<folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false> >::~unique_lock() in AppDelegate.o
  "folly::SharedMutexImpl<false, void, std::__1::atomic, false, false, false>::~SharedMutexImpl()", referenced from:
      std::__1::__shared_ptr_emplace<facebook::react::ContextContainer const, std::__1::allocator<facebook::react::ContextContainer const> >::__on_zero_shared() in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tomduncalf** [comment] 2022-04-14 13:25
Hey @KartikSubramaniam, thanks for clarifying that the problem only occurs when archiving. I was actually able to reproduce this by archiving a new React Native project created `npx react-native init` and `RCT_NEW_ARCH_ENABLED=1 pod install`, so it seems like there might be a React issue here! Can you also repro this?

**Comment by Arkkeeper** [comment] 2022-05-02 10:50
Yes, it's a RN issue. As a temporary dirty fix you can add somewhat like:

<img width="819" alt="folly" src="https://user-images.githubusercontent.com/20115419/166222891-31eda1f4-8863-45f9-83c0-9db1da0fd4c6.png">

in the **post_install do |installer|** section of your Podfile

**Comment by tomduncalf** [comment] 2022-05-03 10:24
Thank you for sharing that workaround @Arkkeeper! Closing this as it is not a Realm-specific issue.

**Closed by tomduncalf** 2022-05-03 10:24 UTC
Labels: O-Community, Waiting-For-Reporter
