### ISSUE TITLE
Create a meaningful error message when the `Realm` binary is not bound to the JS environment

### ISSUE THREAD

**Issue by takameyer** [realm/realm-js#5981] opened 2023-07-12 12:22 UTC
Currently when users of `v12` end up in a state where `Realm` is not compiled/available in their environment (for example: for got to `pod install` or tried `expo web` or `expo go`), the error returned is:
```
TypeError: Cannot read property 'Helpers_get_table' of undefined
```
This is misleading and can lead to frustration, as it is very unclear what the issue actually is.  We should create a check for this problem and respond with a meaningful error message such as:
```
Realm could not be found in your environment.  Make sure you have followed the setup instructions at https://www.mongodb.com/docs/realm/sdk/react-native/install/
```

We also could create a `TROUBLESHOOTING.md` which goes provides some general guidance specific to these type of errors.  If this is done, than it should be linked in instead of the mdb installation docs.

**Comment by kneth** [comment] 2023-07-13 10:47
I agree that we should document it - maybe a troubleshooting section in `README.md` is a good place to start. I don't how if it is trivial to get if the `.so` or `dylib` file is loaded or not.

**Comment by kraenhansen** [comment] 2023-07-21 08:19
I don't know why https://github.com/realm/realm-js/issues/5905 was closed, but this issue is effectively a duplicate of that. I'm not suggesting to close this issue and reopen the original, but putting the link here for clarity and traceability :+1:

**Closed** 2023-08-11 13:58 UTC
