### ISSUE TITLE
Switching the build to 'prebuild' for supporting N-API, electron and nwjs

### ISSUE THREAD

**Issue by ab35** [realm/realm-js#2162] opened 2018-12-06 11:21 UTC
The current build system uses the old NAN system with node-pre-gyp, which implies to rebuild Realm for each new major version of node (#2149):

But since node 8 (stable in node 10), a new N-API build system, decoupled from the node javascript runtime, allows to build once for a major version of node and then all new major versions of node are supported out of the box:

> N-API allows modules compiled for one major version to run on later major versions of Node.js without recompilation. ([doc](https://nodejs.org/api/n-api.html#n_api_n_api))

Though N-API is also supported by node-pre-gyp, there is another build cli utility called "[prebuild](https://github.com/prebuild/prebuild)" which uses N-API and also supports both Electron and NWJS (#1646):

> A command line tool for easily making prebuilt binaries for multiple versions of Node.js, N-API, Electron and NW.js on a specific platform

Prebuild is actually used within the [Node repository](https://github.com/nodejs/abi-stable-node/issues/291#issuecomment-411512951) itself as well.

Switching to prebuild would allow to extend the use of realm across the JS ecosystem and ease the maintenance of realmjs.

**Comment by fealebenpae** [comment] 2018-12-06 12:17
That's a great idea, and something we have been wanting to do for some time, but unfortunately we are rather constrained and haven't been able to start tackling this.

Our immediate plans are to replace node-pre-gyp with prebuild, and node-gyp with cmake-js (I already took a stab at this in a branch: https://github.com/realm/realm-js/tree/yg/cmake-js), but switching to n-api would be a bigger task and require us to drop support for older Node.js versions.

It would be awesome if you or someone else in the community would like to integrate n-api, however.

**Comment by ab35** [comment] 2018-12-06 16:13
Yes, one is aware that switching to N-API involves a lot of rewrite... That is already a great move to switch to prebuild and cmake-js for interoperability, as both supports electron and nwjs out of the box, and that would also prepare for a future N-API integration...

As time goes, however, there will be no other choice than to drop support for older versions of node. The LTS is currently at node 10 and LTS long-term support will end next year for all node versions below 10 ([LTS long-term](https://github.com/nodejs/Release#release-schedule))...

So node 10 which supports N-API will be in one year (beginning of 2020) the minimum recommended target for node developers... At that time, a switch to N-API will be worth the effort and node 10 will be a reasonable move as a minimal target for all node developers.

**Comment by xmedeko** [comment] 2019-12-20 10:01
@bmunkholm @kneth is this duplicate of #2516 ?

**Comment by bmunkholm** [comment] 2019-12-20 10:47
@blagoev ?

**Comment by fealebenpae** [comment] 2019-12-20 16:13
I don't think this is a duplicate of #2516 - using N-API is orthogonal to the build and packaging system. Improving on the current `node-pre-gyp` setup in some way is still desirable.

**Comment by kneth** [comment] 2021-01-11 13:01
We have moved to CMake (using `cmake-js`) for our current development and it will eventually be merged to `master`.

**Closed** 2021-01-11 13:02 UTC
Labels: O-Community, T-Enhancement
