### ISSUE TITLE
[expo] While trying to resolve module `realm` from file

### ISSUE THREAD

**Issue by thanhloc-17** [realm/realm-js#5893] opened 2023-06-16 04:20 UTC
### How frequently does the bug occur?

Always

### Description

RN: 0.72.0-rc.5
Expo: ~49.0.0-alpha.4

There's a bug issue:
 ```
BUNDLE  ./index.js

error: Error: While trying to resolve module `realm` from file `/Users/<appName>/app/src/storage/realm/index.ts`, the package `/Users/<appName>/app/node_modules/realm/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/<appName>/app/node_modules/realm/dist/bundle.react-native.mjs`. Indeed, none of these files exist:

  * /Users/<appName>/app/node_modules/realm/dist/bundle.react-native.mjs(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs|.android.svg|.native.svg|.svg)
  * /Users/<appName>/app/node_modules/realm/dist/bundle.react-native.mjs/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs|.android.svg|.native.svg|.svg)
    at DependencyGraph.resolveDependency (/Users/<appName>/app/node_modules/metro/src/node-haste/DependencyGraph.js:289:17)
```

Here my file:
```
import Realm from 'realm';

export class RealmStorage {
  private realm!: Realm;
...
}

```

### Can you reproduce the bug?

Always

### Reproduction Steps

- Run metro start
- Waiting bundling
- Error in index.js

### Version

12.0.0-alpha.2

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

MacOs

### Build environment

Which debugger for React Native: ..

**Comment by kraenhansen** [comment] 2023-06-16 14:51
This is very curious. Can you try deleting the `/Users/<appName>/app/node_modules/realm` directory and running `npm install` again? If that doesn't work, can you comment with the output of running `ll /Users/<appName>/app/node_modules/realm/dist/`?

**Comment by kraenhansen** [comment] 2023-06-19 08:48
Thanks for reporting this. I first tried with Expo `48.0.19` and couldn't reproduce until I upgraded to `49.0.0-alpha.4`, so I'm tempted to close this as a bug in Expo. (Did you already create an issue with them?) ... I'll do a bit more digging first.

**Comment by kraenhansen** [comment] 2023-06-19 10:16
This far I've confirmed this is a regression introduced by the upgrade from `@expo/metro-config` 0.7.1 to 0.9.0 (introduced by `expo@49.0.0-alpha.1`).

**Comment by kraenhansen** [comment] 2023-06-19 11:30
I've communicated this through our backchannel with the Expo team and will report back as I learn more.

**Comment by kraenhansen** [comment] 2023-06-19 12:46
I've noticed that dropping in a `sourceExts.push('mjs');` after the `'cjs'` line here: https://github.com/expo/expo/blob/0ac93127f8db535533fde7c9679349c83bff3744/packages/%40expo/metro-config/build/ExpoMetroConfig.js#L185 is a valid workaround as well.

**Comment by kraenhansen** [comment] 2023-06-19 12:56
I was wondering if this was related to https://github.com/react-native-community/discussions-and-proposals/blob/main/proposals/0534-metro-package-exports-support.md#exact-path-specifiers but I tried deleting the `exports` property from our `package.json` and in any case Metro seem to resolve via the `react-native` main field on the root of our package.json.

**Comment by huntie** [comment] 2023-06-21 18:28
Looking at how recently `index.react-native.js` was modified and testing locally after installing `realm` (Yarn v1), I wonder if this is a configuration bug — as I can't seea  `dist/` bundle produced on install.

- Is the `bundle` npm script configured correctly?

![image](https://github.com/realm/realm-js/assets/2547783/d20a0429-2792-4e63-baca-3b5abe34ff1c)

**Comment by kraenhansen** [comment] 2023-06-22 08:08
@huntie please note the files you're referring to isn't released yet and the OR is using [`realm@12.0.0-alpha.2`](https://github.com/realm/realm-js/tree/v12.0.0-alpha.2/packages/realm).

**Comment by huntie** [comment] 2023-06-22 10:55
> I've noticed that dropping in a sourceExts.push('mjs'); after the 'cjs' line here: [expo/expo@0ac9312/packages/%40expo/metro-config/build/ExpoMetroConfig.js#L185](https://github.com/expo/expo/blob/0ac93127f8db535533fde7c9679349c83bff3744/packages/%40expo/metro-config/build/ExpoMetroConfig.js#L185) is a valid workaround as well.

@kraenhansen Very curious how this fixed anything — I'm on `main` now and all files concerned have `.js` extensions only:
- `package.json` — `"react-native": "./index.react-native.js"`
- `./index.react-native.js` — `require("./dist/bundle.react-native")`
- `./dist/bundle.react-native.js` (exists after expanding `sourceExts`)

In local testing, Metro is able to resolve up to this point (then fails on missing `bson` dependency). Can you share extra repro steps?

(If one of these files was to use `.mjs` as an extension, the fix would be that each `import`/`require()` must use the qualified import with file extension.)

**Comment by kraenhansen** [comment] 2023-06-22 11:36
> all files concerned have `.js` extensions only

Correct - we've changed the file extensions since the [v12.0.0-alpha.2](https://github.com/realm/realm-js/tree/v12.0.0-alpha.2/packages/realm) release that this issue is referring to.

To be clear, I tried and wasn't able to reproduce this using a clean RN `v0.72.0-rc.6` template app.

**Comment by thanhloc-17** [comment] 2023-06-23 07:20
> This is very curious. Can you try deleting the `/Users/<appName>/app/node_modules/realm` directory and running `npm install` again? If that doesn't work, can you comment with the output of running
> 
> ```
> ll /Users/<appName>/app/node_modules/realm/dist/
> ```

Hi @kraenhansen, thanks for your reply, there are result from your cmd:
```
% ll ./node_modules/realm/dist
total 20480
-rw-r--r--  1 <username>  staff   390K Jun 23 14:08 bundle.browser.mjs
-rw-r--r--  1 <username>  staff   1.8M Jun 23 14:08 bundle.browser.mjs.map
-rw-r--r--  1 <username>  staff   154K Jun 23 14:08 bundle.d.ts
-rw-r--r--  1 <username>  staff   394K Jun 23 14:08 bundle.node.js
-rw-r--r--  1 <username>  staff   802K Jun 23 14:08 bundle.node.js.map
-rw-r--r--  1 <username>  staff   391K Jun 23 14:08 bundle.node.mjs
-rw-r--r--  1 <username>  staff   801K Jun 23 14:08 bundle.node.mjs.map
-rw-r--r--  1 <username>  staff   383K Jun 23 14:08 bundle.react-native.mjs
-rw-r--r--  1 <username>  staff   792K Jun 23 14:08 bundle.react-native.mjs.map
-rw-r--r--  1 <username>  staff   113K Jun 23 14:08 realm-js-wasm.mjs
-rwxr-xr-x  1 <username>  staff   4.0M Jun 23 14:08 realm-js-wasm.wasm
```

**Comment by thanhloc-17** [comment] 2023-06-23 07:30
I try to fix my metro.config.js file.

```
const {getDefaultConfig} = require('expo/metro-config');

module.exports = (() => {
  const config = getDefaultConfig(__dirname);

  const {transformer, resolver} = config;

  config.transformer = {
    ...transformer,
    babelTransformerPath: require.resolve('react-native-svg-transformer'),
  };
  config.resolver = {
    ...resolver,
    **sourceExts: [...resolver.sourceExts, 'svg', 'mjs'],**
  };

  return config;
})();
```

Then I can pass that issue, but I face new issue **bson**, then i fix by install **bson** from npm and there's new issue:
```
ERROR  TypeError: Cannot read property 'Helpers_get_table' of undefined, js engine: hermes
 LOG  Running "main" with {"fabric":true,"initialProps":{},"rootTag":1}
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

**Comment by kraenhansen** [comment] 2023-06-23 08:09
@thanhloc-17 are you using the Expo Go App or a development build? You might be experiencing https://github.com/realm/realm-js/issues/5905#issuecomment-1597664109.

**Comment by thanhloc-17** [comment] 2023-06-26 03:48
@kraenhansen  i just only use Expo Modules Core, and still use React Native to build

**Comment by kraenhansen** [comment] 2023-06-27 12:39
We'll be releasing a new `v12.0.0-rc.0` in the coming days. Since we're changing how we export quite a bit in that, I suggest upgrading once it's out and hopefully it'll fix it 🤞

**Comment by thanhloc-17** [comment] 2023-06-29 09:49
@kraenhansen 
thanks for your help, but still not working as I expected

There are my steps maybe help you can reproduce this issue:
1. I upgrade v12.0.0-rc.0
2. remove yarn.lock and node_modules
3. yarn install and rebuild react native

`Error: While trying to resolve module `realm` from file `/<appname>/src/storage/realm/index.ts`, the package `/<appname>/node_modules/realm/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/<appname>/node_modules/realm/index.react-native.js`. Indeed, none of these files exist:`

**Comment by takameyer** [comment] 2023-06-29 11:28
@thanhloc-17 Great catch.  We had modified the entry points to `realm` to be compatible with CJS.  Seems we had forgotten to include these new entry points in the included files for packaging to NPM.  Sorry about that!  PR is open and we will have a new release out soon.

**Closed** 2023-06-29 14:52 UTC
Labels: T-Bug, O-Community, Needs-Attention, SDK-Use:Local, Encryption:Off, Frequency:Always, Repro:Always

**Comment by kriit24** [comment] 2023-08-11 02:41
package.json

{
  "name": "test",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/metro-config": "^0.7.1",
    "@realm/react": "^0.5.2",
    "bson": "^4.7.2",
    "expo": "^49.0.7",
    "expo-file-system": "^15.4.3",
    "expo-status-bar": "^1.6.0",
    "laravel-echo": "^1.15.2",
    "mongoose": "^7.4.1",
    "react": "18.2.0",
    "react-native": "^0.72.3",
    "react-native-get-random-values": "~1.9.0",
    "realm": "^12.0.0-rc.3",
    "socket.io-client": "^4.7.2",
    "uuid": "^9.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}


and error is the same 

 ERROR  TypeError: Cannot read property 'Helpers_get_table' of undefined, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
