### ISSUE TITLE
Realm-js in React Native not working in M1 chip

### ISSUE THREAD

**Issue by pushpender-singh-ap** [realm/realm-js#3599] opened 2021-02-19 07:45 UTC
## Goals

What are you trying to achieve? 
Installing Realm-js in React native project

## Steps to Reproduce

What are steps we can follow to reproduce this issue? 
Only In M1 Chip Not Working Realm
1. React-native init test
2. npm install realm
3. cd ios && pod install
4. cd .. && react-native run-ios

## Version of Realm and Tooling

- Realm JS SDK Version: 10.2.0
- Node or React Native: v14.15.3 Or RN:- 0.63.4
- Client OS & Version: big sur & version 11.2.1 (20D74) (M1 CHIP)

**Comment by steffenagger** [comment] 2021-02-19 09:08
Duplicate of https://github.com/realm/realm-js/issues/3527
This is already on our radar.

**Closed** 2021-02-19 09:09 UTC
Labels: O-Community

**Comment by pushpender-singh-ap** [comment] 2021-02-19 12:41
@steffenagger thanks for response but how can reconfigured because i was try its not working

**Comment by steffenagger** [comment] 2021-02-19 13:06
@pushpender-singh-ap it's not fixed yet, but we're already tracking it in another ticket. Please follow https://github.com/realm/realm-js/issues/3527 for updates.

**Comment by pushpender-singh-ap** [comment] 2021-02-19 13:45
@steffenagger thanks we all are waiting for update for m1 chip

**Comment by hoangdshp123** [comment] 2021-02-28 04:28
I downgrade version to 6.1.6 it worked

**Comment by pushpender-singh-ap** [comment] 2021-03-02 14:41
@hoangdshp123 thanks its working 👍
