### ISSUE TITLE
Performance issue with 10.20.0-beta.5 in Android

### ISSUE THREAD

**Issue by npjoge** [realm/realm-js#4497] opened 2022-04-19 06:38 UTC
### How frequently does the bug occur?
All the time

### Description
As we are working with **Realm 10.16.0**, and app working fine with **RN-0.63.4**.
But after migrate on **RN-0.67.4** & **react~~native~~reanimated-2.7.0** we migrated on Realm beta version i.e.  **Realm 10.20.0-beta.5**

But this Beta version of Realm is taking much time for Reading/Writing in db as compared with previous one.

**Realm 10.16.0 taking <1sec** time to execute Read/Write command in Android
but now Realm 10.20.0-beta.5 taking much more time, its near **about 7-8 sec in Android**

### Can you reproduce the bug?
Not yet

### Version
Realm 10.20.0-beta.5

### What SDK flavour are you using?
Local Database only

### Are you using encryption?
No, not using encryption

### Platform OS and version(s)
Android

### Build environment
Which debugger for React Native: ..

**Comment by tradebulls** [comment] 2022-04-19 06:41
Facing same issue on the beta version of Realm. Migrated to beta version to use RN 0.67.0 with Local Realm. Any help?

**Comment by takameyer** [comment] 2022-04-19 10:41
@npjoe thanks for reporting.  We are currently investigating performance regressions with the beta version and will keep update you here when we have made any progress.

**Comment by arish-panjwani** [comment] 2022-04-27 07:14
I am also facing the same issue. Any Solution?

**Comment by QureshiFaizan** [comment] 2022-04-28 06:56
I am also facing the same issue. Any Solution?

**Comment by dridi93** [comment] 2022-05-17 15:25
the same, any updates ?

**Comment by CoSNaYe** [comment] 2022-05-17 19:49
same here. Android app becomes extremely slow

**Comment by tradebulls** [comment] 2022-05-18 04:06
@takameyer Any update on the new beta version to be released? Can we expect this issue to be fixed in the upcoming release? Please help

**Comment by takameyer** [comment] 2022-05-18 07:24
Hi everyone, sorry for the late reply.  Multiple seconds for transactions to occur is not something we take lightly.  We do have a large block of time planned to investigate the performance problems with the Hermes branch.  I cannot give an exact timeline, but we will get to it soon.

That being said, we would be grateful if anyone can provide a reproducible project that inhibits large performance regressions.  This would help us pinpoint the issue much faster.

**Comment by tradebulls** [comment] 2022-06-10 07:33
@takameyer Can you please help me with an update on the performance issue?

**Comment by takameyer** [comment] 2022-06-10 07:49
@tradebulls yes, we have started investigating.  The progress so far has been documented in https://github.com/realm/realm-js/issues/4443

**Comment by takameyer** [comment] 2022-06-10 09:00
Closing as this is a duplicate of https://github.com/realm/realm-js/issues/4497

**Closed by takameyer** 2022-06-10 09:00 UTC
Labels: T-Bug, O-Community, hermes
