### ISSUE TITLE
[5.0.0] Android returns Results with length 1 but no keys or values

### ISSUE THREAD

**Issue by bimusiek** [realm/realm-js#2763] opened 2020-03-20 16:22 UTC
## Goals
I am trying to fetch some objects from database.

## Expected Results
Getting 1 object with all properties.

## Actual Results
I get Results of length 1 but when getting the object via index 0, it returns no properties.

## Steps to Reproduce
Run the code on Android

## Code Sample
```
const results = realm
        .objects<ImporterAuthenticationModel>(ImporterAuthenticationModel.schema.name)
        .filtered('importerId = $0', importer.importer.id);

      if (results) {
        console.log(results.length);
        console.log(results[0].id);
      }
```
Output is:
```
1
undefined
```

Schema:
```
export class ImporterAuthenticationModel extends BaseModel {
  public static schema = {
    ...BaseModel.schema,
    name: 'ImporterAuthenticationModel',
    primaryKey: 'uniqueId',
    properties: {
      ...BaseModel.schema.properties,
      uniqueId: 'string',
      id: 'string',
      title: 'string',
      subTitle: 'string?',
      imageUrl: 'string?',
      importerId: 'string',
      additionalDataString: 'string?',
      rawStatus: { type: 'int', default: ImporterAuthenticationStatus.AUTHENTICATED },
      expiresAt: 'int'
    }
  };
```
## Version of Realm and Tooling

- Realm JS SDK Version: 5.0.0
- Node or React Native: React Native
- Client OS & Version: Android 9PKQ1.181121.001 (Mi 9 Lite)
- Which debugger for React Native: React Native Debugger (but it also fails if using production build from FireBase)

<img width="511" alt="Screenshot 2020-03-20 17 12 16" src="https://user-images.githubusercontent.com/1025588/77183797-30ef8700-6acf-11ea-99e3-7f2a0787328c.png">

<img width="259" alt="Screenshot 2020-03-20 17 12 22" src="https://user-images.githubusercontent.com/1025588/77183811-35b43b00-6acf-11ea-8f43-e074f90dc1cb.png">
 
<img width="472" alt="Screenshot 2020-03-20 17 13 49" src="https://user-images.githubusercontent.com/1025588/77183864-406ed000-6acf-11ea-9093-c24e968ea579.png">

<img width="354" alt="Screenshot 2020-03-20 17 13 55" src="https://user-images.githubusercontent.com/1025588/77183889-4795de00-6acf-11ea-94c7-28ae332abbd4.png">

**Comment by bimusiek** [comment] 2020-03-20 16:46
I've checked on other device, same results.
Adding new realm models to database work and everything is synced to Realm Cloud. 

But fetching anything from Realm yields empty objects.

**Comment by florigo** [comment] 2020-03-22 08:39
Same here, Realm 5.0.2 and Node 10.19. The issue appeared only when I rebuilt the apk package, with the new Realm version. Not clear if it stores the objects correctly or not. I synchronously opened Realm for this task.

**Comment by steffenagger** [comment] 2020-03-23 08:08
I'm seeing the same issue in Realm `5.0.2`.
@florigo when creating new objects, they find their way correctly all the way to Realm Cloud, via Sync, with all values intact - so the data should be stored correctly.
@bimusiek's assumption, that the issue is with populating local models, seems correct.

As an extra note, this is not an issue for the latest beta `4.0.0-beta.2`, which is targeted for `6.0.0`.

**Comment by bimusiek** [comment] 2020-03-23 11:09
@steffenagger My guess is that 4.0.0-beta.2 works because it does not have new NAPI implementation merged yet (does not work with Node 13 whereas 5.0.x does). 

We had to make our react-native apps use 3.6.5 version where Electron app uses 5.0.1. Seems sketchy to have different versions but it works.

**Comment by Mavenic** [comment] 2020-03-23 12:43
Facing same issue as well, react native 61.5, node 10.15, realm 5.0.2

**Comment by kraenhansen** [comment] 2020-03-23 13:07
@Mavenic I just tried but failed reproducing this with Node.js v10.19.0 and v12.14.1, please create your own issue with exact instructions on how to reproduce this.

**Comment by kraenhansen** [comment] 2020-03-23 13:09
@bimusiek how are you creating the Realm instance? Specifically, are you passing the `ImporterAuthenticationModel` class or the static schema `ImporterAuthenticationModel.schema` property into the schema?

**Comment by bimusiek** [comment] 2020-03-23 13:15
@kraenhansen I am passing `ImporterAuthenticationModel.schema` to realm. 

```
  const user = await getRealmUser();
  const realmConfig = user.createConfiguration({
    schema,
    schemaVersion,
    sync: {
      url: `~/app`,
      fullSynchronization: true
    }
  });
  const realm = new Realm(realmConfig);
```
where schema & schemaVersion are:
```
export const schema = [
  ConfigRealmModel.schema,
  CollectionModel.schema,
  CollectionItemModel.schema,
  ImporterAuthenticationModel.schema,
  TransferModel.schema,
  TransferCollectionModel.schema,
  TransferCollectionItemModel.schema,
  LicenseRequestModel.schema
];
export const schemaVersion = 1;
```

The same code works on both 3.6.5 version and 4.0.0-beta2.
5.0.x works on iOS + Electron + Node Server but it does not return any keys and values on Android. Creating & updating models work though, and it is synced to the Cloud.

I tried bumping JSC to newest version, it did not help.

**Comment by kraenhansen** [comment] 2020-03-23 16:38
I can confirm the issue on with React Native 0.61.5 and Realm 5.0.2 on Android running in an emulator.
Thanks for reporting this @bimusiek!

**Comment by cristianoccazinsp** [comment] 2020-03-24 14:42
Same issue. RealmJS 5.0.2 (migrated from 3.x) is basically unusable on Android, all results are empty, and getting a bunch of errors here and there (failed deletes, empty objects, etc.). 

Any work around? Or should we just revert to 3.x until this is resolved?

**Comment by kraenhansen** [comment] 2020-03-24 14:48
I am working on getting this fixed as-we-speak, if you're not relying on the Node 12 + 13 support, we recommend reverting to 3.x until this issue is fixed. We'll be updating our latest tag on NPM to point to 3.x until we find a solution for the 5.x release.

**Comment by kraenhansen** [comment] 2020-03-24 19:53
> I'm having the same issue on 5.0.2 on iOS (Simulator)
@matt2legit I've tried but I've been unsuccessful at reproducing this issue on iOS. I would really appreciate if you could create an issue, separate from this, with details on the version of device/simulator, React Native and if possible a short piece of code / link to a small repository demonstrating the issue.

**Comment by saravanakumargn** [comment] 2020-03-26 17:27
I am facing the same issue. Android its not working. iOS Working.
```
    "realm": "^5.0.2",
```

This is the results i am getting in Android.
```
{"0": {}, "1": {}, "2": {}, "3": {}, "4": {}, "5": {}, "6": {}, "7": {}, "8": {}}
```

iOS (Simulator) it's working as expected Realm without any issues..

**Comment by Alphia** [comment] 2020-03-28 17:34
> I am facing the same issue. Android its not working. iOS Working.
> 
> ```
>     "realm": "^5.0.2",
> ```
> 
> This is the results i am getting in Android Device.
> 
> ```
> {"0": {}, "1": {}, "2": {}, "3": {}, "4": {}, "5": {}, "6": {}, "7": {}, "8": {}}
> ```
> 
> iOS (Simulator) it's working as expected Realm without any issues..

Get the same error.

**Comment by ducy23061999** [comment] 2020-03-31 17:48
> I am facing the same issue. Android its not working. iOS Working.
> 
> ```
>     "realm": "^5.0.2",
> ```
> 
> This is the results i am getting in Android Device.
> 
> ```
> {"0": {}, "1": {}, "2": {}, "3": {}, "4": {}, "5": {}, "6": {}, "7": {}, "8": {}}
> ```
> 
> iOS (Simulator) it's working as expected Realm without any issues..

+1

**Comment by blagoev** [comment] 2020-04-01 14:15
Realm JS 5.0.3 is released fixing this. Closing this issue. If it is not fixed for someone for some unexpected reason, just reopn it.

**Closed by blagoev** 2020-04-01 14:15 UTC
Labels: O-Community, T-Bug

**Comment by MrScorp** [comment] 2020-04-08 12:27
Checked out 5.0.3 with React Native 0.61.5. Doesn't work in iOS, works in android though!!

**Comment by blagoev** [comment] 2020-04-08 12:36
@MrScorp  did you used a debugger when checking that. Could you try without attaching a debugger

**Comment by MrScorp** [comment] 2020-04-08 12:57
Oh yes, tried without the debugger, and IT WORKS ! 

Thanks a Ton @blagoev  (y)

**Comment by cristianocca** [comment] 2020-04-08 13:37
Does this mean we can no longer debug apps that use Realm?

**Comment by blagoev** [comment] 2020-04-09 16:03
@cristianocca We have a bug in the RN debugger for Chrome and are working to fix it. You can follow it here https://github.com/realm/realm-js/issues/2799. 
Until then you can use the WebKit debugger to debug RN apps with Realm.

**Comment by bimusiek** [comment] 2020-04-09 16:11
I can confirm it works in Android and iOS 👍

**Comment by johanschram** [comment] 2020-04-11 10:05
Well, on my side it doesn't work on android, still getting empty objects from Realm. I didn't try on IOS though. (no debugger used) 

Reaml  5.0.3 (migrated from3.x)
React Native 0.62.2
Node 12.16.1

**Comment by vishaljadav24** [comment] 2020-05-16 11:15
@bimusiek  I am getting results with no keys and values in Android. Though I am creating realm instance by synchronous way( `const realm = new Realm({schema : [Table1, Table2])` ). Is this causing the problem?

**Comment by vishaljadav24** [comment] 2020-05-16 12:16
@bimusiek I have also tested  by create realm instance in asynchronous way(`Realm.open`) but it's also returning same results.

**Comment by BdN0** [comment] 2020-05-18 14:48
Eu estou Tentando depurar com Reactotron, Fllipper ,  com ` let allCliente = realmschema.objects('Cliente');` e obtenho o seguinte resultado `0:{},1:{},` 

Bibliotecas:
"react-native": "0.63.0-rc.1",
"realm": "^6.0.1",

**Comment by kneth** [comment] 2020-05-19 06:55
@BdN0 We have not Flipper support which might explain what you see.

**Comment by BdN0** [comment] 2020-05-19 14:27
> @BdN0 We have not Flipper support which might explain what you see.

But what about the Reactotron? before there was support for him

![image](https://user-images.githubusercontent.com/47547422/82338821-b2766f00-99c3-11ea-8d2f-3330383b2409.png)

libraries:
"react-native": "0.63.0-rc.1",
"realm": "^6.0.1",

**Comment by Jarzka** [comment] 2020-06-01 09:13
Seems that this issue should have been fixed in 5.0.3. However, I'm now running 5.0.5 and facing this issue. Any ideas how to fix it?

**Comment by akhilvasudev-kiwi** [comment] 2020-06-07 13:21
Hi @kraenhansen 
I am getting the issue on both IOS and android
Versions ->
"react-native": "0.62.2",
"realm": "^6.0.1",

**Comment by akhilvasudev-kiwi** [comment] 2020-06-08 05:27
Hi @blagoev @kraenhansen 
Any update on this issue ?

**Comment by keima** [comment] 2020-06-09 15:41
Same problem is here.
But our project uses `realm.objects()` methods everywhere and some method call is fine but others not working.

Upon investigation, we found that it worked fine for classes that inherited from `Realm.Object`, but returned an empty object for classes that didn't.
This is odd.


Working correctly:
```
export class RealmPlayLog extends Realm.Object {
  static readonly schema: ObjectSchema = schema

  ...
}
```

**Not** working correctly:
```
export class RealmPlayLog {
  static readonly schema: ObjectSchema = schema

  ...
}
```

"realm": "^6.0.1" (yarn.lock says 6.0.1)
"react-native": "0.61.5",

iOS Simulator: iPhone 11 (13.1)

**Comment by samuelrvg** [comment] 2020-07-29 15:10
@keima It worked, thank you!

**Comment by machadolucasvp** [comment] 2020-08-03 18:06
We are facing this issue with 5.0.4 and without debugger. realm.objects return empty object and my code base use it everywhere....

**Comment by Jarzka** [comment] 2022-04-11 12:38
Any update on this issue?
