### ISSUE TITLE
npm ERR! realm@1.2.0 install: node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by agersoncgps** [realm/realm-js#1008] opened 2017-05-10 01:40 UTC
I am trying to install Realm for React Native. After running 

`npm install --save realm` 

I get the error:

```
731 warn react-static-container@1.0.1 requires a peer of react@^0.13.0 || ^0.14.0 || ^15.0.0 but none was installed.
2732 verbose stack Error: realm@1.2.0 install: `node-pre-gyp install --fallback-to-build`
2732 verbose stack spawn ENOENT
2732 verbose stack     at ChildProcess.<anonymous> (/Users/agerson/.nvm/versions/node/v4.8.2/lib/node_modules/npm/lib/utils/spawn.js:33:16)
2732 verbose stack     at emitTwo (events.js:87:13)
2732 verbose stack     at ChildProcess.emit (events.js:172:7)
2732 verbose stack     at maybeClose (internal/child_process.js:862:16)
2732 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
2733 verbose pkgid realm@1.2.0
2734 verbose cwd /Users/agerson/Desktop/CGPSApp
2735 verbose Darwin 16.5.0
2736 verbose argv "/Users/agerson/.nvm/versions/node/v4.8.2/bin/node" "/Users/agerson/.nvm/versions/node/v4.8.2/bin/npm" "install" "--save" "realm"
2737 verbose node v4.8.2
2738 verbose npm  v4.5.0
2739 error file sh
2740 error code ELIFECYCLE
2741 error errno ENOENT
2742 error syscall spawn
2743 error realm@1.2.0 install: `node-pre-gyp install --fallback-to-build`
2743 error spawn ENOENT
2744 error Failed at the realm@1.2.0 install script 'node-pre-gyp install --fallback-to-build'.

```

**Comment by agersoncgps** [comment] 2017-05-10 23:58
I worked around it by manually installing node-pre-gyp with

`npm install --save node-pre-gyp`

Hope thats ok...

**Comment by blagoev** [comment] 2017-05-22 10:24
Hi, node-pre-gyp is a dependency of realm-js from quite some time now. I think somehow you didn't  get all the dependencies when this happened. Since you resolved it I will close this issue.

**Closed by blagoev** 2017-05-22 10:24 UTC

**Comment by chellong98** [comment] 2018-04-02 07:38
hi, installed node-pre-gyp but i still get error node-pre-gyp install --fallback-to-build :((

**Comment by phuongluu98** [comment] 2018-07-13 11:14
try npm install node-pre-gyp install --fallback-to-build --save
It's work for me. Hope you too!

**Comment by sheva007** [comment] 2018-08-25 10:15
@chellongCoder have you found a solution for node-pre-gyp install --fallback-to-build?
I am working in Mac and I get "realm spawn code ENOENT" in ios & Android, it seems node-pre-gyp is the reason for that.

**Comment by KGDeveloper** [comment] 2019-01-22 07:07
Hi, I have the same problem. Have you solved it

**Comment by lelehouse** [comment] 2019-02-27 08:22
i also have the problem , and try many methods , include npm the package node-pre-gyp, but not solved it ,

**Comment by pritasam** [comment] 2019-06-04 07:59
Why do you close issues without fixing them 👎

**Comment by bmunkholm** [comment] 2019-06-04 09:24
Please don't keep commenting on closed issues but create a new issue with all relevant details to reproduce the problem. Thanks!
