### ISSUE TITLE
[N-API] Cannot open inMemory Realm when another Realm is already opened

### ISSUE THREAD

**Issue by xmedeko** [realm/realm-js#2725] opened 2020-02-14 09:57 UTC
## Goals

I have an Electron app with opened realm `default.realm` file. Then I open another Electron instance (unit tests) and trying to open inMemory realm.

## Expected Results

I would expect I can open inMemory realm as I like in many Electron instances.

## Actual Results

An error is thrown:
```
Durability setting (as passed to the SharedGroup constructor) was not consistent across the session
Exception backtrace:
<backtrace not supported on this platform>
  at openLocalRealm @ C:\prace\reqview-realm\src\node_modules\realm\lib\extensions.js:99:35
  at Function.open @ C:\prace\reqview-realm\src\node_modules\realm\lib\extensions.js:124:24
```

## Version of Realm and Tooling

- Realm JS SDK Version: v3.7.0-alpha.2
- Node or React Native: Node v12.7.0, Electron v5.0.13
- Client OS & Version: Windows 10

**Comment by blagoev** [comment] 2020-02-14 11:15
This is by design. It has nothing to do with NAPI or Electron. If you try it with regular nodejs app using realm it will behave the same. 

We do not allow different processes to have the same realm file open with different durability options.

Closing this.

**Closed by blagoev** 2020-02-14 11:15 UTC
Labels: O-Community

**Comment by xmedeko** [comment] 2020-02-15 18:32
@blagoev I do **not open same file**, I open **`inMemory`** realm:
```js
Realm.open({inMemory: true, schema: ...});
```

**Comment by xmedeko** [comment] 2020-02-15 19:47
@blagoev Aha, I have read just the Realm Javascript doc https://realm.io/docs/javascript/3.6.0/#realms how to open the inMemory realm do I have used: 
```js
Realm.open({inMemory: true, schema: mySchema});
```

But lookin at the API doc https://realm.io/docs/javascript/latest/api/Realm.html#~Configuration I see that `inMemory` *This still requires a path ...* It's a bit confusing that when I omit the path the inMemory realm interferes with the persistent realm. It should be at least noted in the main doc, too.
