### ISSUE TITLE
Synced Realm not loading on Android, works fine on iOS

### ISSUE THREAD

**Issue by agersoncgps** [realm/realm-js#1369] opened 2017-10-01 15:59 UTC
"realm": "^1.12.0"
"react-native": "^0.47.2",

https://pastebin.com/t6c2xNpA

This code works great in the iOS simulator and on a real iOS device. It outputs a valid object for the realm user, the realm object and it prints the correct number of records from the parents table:

User {identity: "**********", isAdmin: false, server: "https://realm.mydomain.org:9443", token: "*********…***********", Symbol(realm): "(User object)"…}

Database.js:57 Realm {…}

Database.js:59 realm-- 2567

However, when I run it on the Android simulator or on a real Android device I get 0 records synced:

User {identity: "**********", isAdmin: false, server: "https://realm.mydomain.org:9443", token:
"************…***************==", Symbol(realm): "(User object)"…}

Database.js:57 Realm {…}

Database.js:59 realm-- 0

**Comment by blagoev** [comment] 2017-10-02 20:13
Hi, thanks for reporting. We will need to debug this since from the code there is no obvious reason for sync not happening.  If there is a simple app that reproduces this it will help us a lot. 

Also you can check at your side if the realm that is returned on the Android device has increased in size and probably report what are the file sizes. 
There is a new progress API available which you can use to see if any bytes are indeed synced. The way you do it is like so"

`Realm.open(config).progress()`

here is for example one of our tests that you can use to quickly check the syntax
https://github.com/realm/realm-js/blob/master/tests/js/session-tests.js#L588-L595

**Comment by agersoncgps** [comment] 2017-10-07 17:22
I tried adding .progress() to my Realm.open under iOS where I know everything is working. No data is output to the console from the .progress() block. Did I implement it correctly?

https://pastebin.com/rETyUxDN

**Comment by blagoev** [comment] 2017-10-07 18:18
Seems all right. with one minor thing that it should be 
```
return this.getEncryptionKeyFromApi(jwt).then(data => {..............
and then 
return Realm.open
```

otherwise on error it will `leak` a rejected promise and the `catch` block will not be called. 

Still it should be calling the progress callback if it is wokring

**Comment by agersoncgps** [comment] 2017-10-07 19:32
Thanks, I added the return, but still no progress data...

**Comment by blagoev** [comment] 2017-11-15 21:35
realm-js 2.0.7 was just released with a fix for this.
Please verify it is working for you and thanks for reporting.

**Comment by kneth** [comment] 2017-11-17 14:04
@agersoncgps I close the issue but don't hesitate to reopen if you experience it after upgrading.

**Closed by kneth** 2017-11-17 14:04 UTC
Labels: O:User PE/EE, P:2 Expected, T:Bug

**Comment by agersoncgps** [comment] 2017-11-23 16:29
I updated to v2 and now get this error:

Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8083/callbacks_poll'.

Can v2 of the library connect to older ROS v1 instances?

**Comment by ianpward** [comment] 2017-11-24 02:56
@agersoncgps No you need to be on a 2.x of ROS to use 2.x version of realm-js
