### ISSUE TITLE
addListener notification is empty (documentation only)

### ISSUE THREAD

**Issue by allenw23** [realm/realm-js#927] opened 2017-03-18 17:00 UTC
When using addListener(objects, changes) on React Native iOS it always returns empty on the first notification and the second notification returns what should have been in the first one.

I found in results-tests.js below that first notification is empty. 

Is this by design or am I doing something wrong here?  :grinning:

```
        realm.objects('TestObject').addListener((testObjects, changes) => {
            // TODO: First notification is empty, so perform these
            // assertions on the second call. However, there is a race condition
            // in React Native, so find a way to do this in a robust way.
            //TestCase.assertEqual(testObjects.length, 4);
            //TestCase.assertEqual(changes.insertions.length, 1);
            resolve();
        });
```

**Comment by kristiandupont** [comment] 2017-03-20 10:12
Yes, this can be a bit surprising. You can think of it as an async query -- the first notification gives you the "initial" result. We should document this better.

**Comment by bennybennet** [comment] 2017-05-07 18:20
If I get this right, the listener get triggered for the current change but the parameter ```changes``` have the changes from the last change, right? That doesn't feel right to me. I would like to have the current changes in an EventListener, not the one before the current.

What is the recommended solution to get the current changes when the event is triggered?

**Comment by kristiandupont** [comment] 2017-05-09 09:57
@bennybennet no, it's just that you will always get an initial, empty notification. After that, you will be notified with each change and the changeset represents that specific change.

**Comment by bennybennet** [comment] 2017-05-10 18:11
@kristiandupont 

1. I do get a notification for the first insertion with a changeset of 0 insertions.
2. When i do another insertion i do get a notification with a changeset of 1 insertion, but that one is the change from 1.

What i did now as a workaround is
```
    const txs = realm.objects('Transaction');
    let currentLength = txs.length;
    
    realm.addListener('change', (tx, changes, x, y, z) => {
      if(currentLength < txs.length) {
        currentLength = txs.length;
        let newTransactions = this.state.transactions;
        newTransactions.unshift(this.buildTxObject(txs[txs.length - 1]));
        this.setState({ 
          transactions: newTransactions
        });
      }
    });
```

**Comment by kristiandupont** [comment] 2017-05-11 09:02
Well in that case, there is a bug. Is it possible for you to share some code that reproduces the behavior?

**Comment by tybro0103** [comment] 2017-05-13 19:32
I'm experiencing the same thing in React Native. Realm `v1.2.0`. No special setup or code.

But another important note here... The initial invocation of the callback (the one that shows no changes), doesn't happen until the first change is triggered. Basically every single invocation receives the args from what should have been the previous invocation. Seems like they're getting queued up, but the queue has an off-by-1 bug.

**Comment by bennybennet** [comment] 2017-05-17 11:06
Yep, exactly what @tybro0103 is saying.
React Native, Realm 1.3.0, no special code.

**Comment by blagoev** [comment] 2017-05-17 11:37
thanks, added this as bug. we will be looking into it

**Comment by lamflam** [comment] 2017-06-24 22:09
Also having this issue in React Native with Realm 1.3.1. After banging my head for a few hours trying to figure out what I was doing wrong I finally realized that these notifications are just always one `realm.write()` behind. I eventually just added and additional `realm.write(() => {})` call which makes it trigger the notification I need right away. Definitely seems to work as a workaround, but looking forward to having a real fix for this.

**Comment by stefanocdn** [comment] 2017-06-26 20:16
Same problem here.

**Comment by jmparsons** [comment] 2017-07-05 21:53
I've just encountered this as well, it's one change behind every single time.

**Comment by kasperkronborg** [comment] 2017-07-18 09:17
I'm getting the same behaviour with realm 1.8.1 and React Native 0.44.3. No solution to this yet? I'm willing to upgrade versions to get this to work.

**Comment by sheshavpd** [comment] 2017-07-27 16:50
I'm experiencing the same bug with latest realm and RN 0.46.x. It's very critical.

**Comment by lamflam** [comment] 2017-07-27 17:35
@sheshavpd This was a critical issue for me as well, and for now I got it working by doing `realm.write(() => {})`  (basically a second empty write) after each write. Far from ideal and may not be feasible in your context, but it's been working well for me in the meantime.

**Comment by sheshavpd** [comment] 2017-07-28 06:57
@lamflam yes, I'm using the same workaround. It "works" for me too. But as per my understanding, the workaround might take one extra roundtrip time to database since it starts and commits a transaction.
Thanks.

**Comment by jjdp** [comment] 2017-08-01 10:45
+1

**Comment by sheshavpd** [comment] 2017-09-15 09:59
This issue has disappeared for me in the version `1.11.1`, for now. I never used chrome debugger, though.
I finally switched back to `adb logcat` command to get console logs. RN Apps that use Realm can never use chrome debugging due to huge performance issues. Someone please confirm if this issue still exist for you.

**Comment by elfman** [comment] 2017-09-17 05:52
@sheshavpd I still get the same problem in my app. 
Realm: `1.11.1`
RN: `0.47.1`
Platform: iOS 10.2 in simulator && Android 6.0

**Comment by sheshavpd** [comment] 2017-09-20 06:16
@elfman, Sorry for not specifying my environment.
Realm: `1.11.1`
RN: `0.48.3`
Platform:` Android 7.x`(Physical device).

**Comment by kosiakMD** [comment] 2017-09-27 13:58
Realm: 1.12.0
RN: 0.47
Platform: iOS 10.3

**Comment by brooksyott** [comment] 2017-10-15 14:37
I'm having the same issue, with version 1.6.0 of the C# library. If I trigger a refresh, I get the right change set.

**Comment by iosfeng** [comment] 2017-10-24 08:02
@kosiakMD 
I'm having the same issue, WITH Realm: 1.13.0

**Comment by niros001** [comment] 2017-11-29 15:46
+1

**Comment by xmedeko** [comment] 2019-12-17 08:02
The issue still exists in realm-js 3.5.0.

If you cannot fix it, what about to have some option for the `Realm.open()`, so that realm-js will issue one more empty write after each write automatically?

**Comment by AlexanderPinkerton** [comment] 2019-12-30 22:36
Still an issue, and the double-overhead "workaround" makes me depressed.

**Comment by kraenhansen** [comment] 2020-01-07 08:59
@AlexanderPinkerton. What happens if you upgrade to the latest version of Realm JS (3.6.0)?

**Closed** 2023-04-20 13:39 UTC
Labels: T-Bug, O-Community
