### ISSUE TITLE
Errors running npm install on MAC, missing files?

### ISSUE THREAD

**Issue by XingXiaoWu** [realm/realm-js#1935] opened 2018-07-22 05:41 UTC
yarn add realm

The error message：
node-pre-gyp http GET https://static.realm.io/node-pre-gyp/2.13.0/realm-v2.13.0-node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://static.realm.io/node-pre-gyp/2.13.0/realm-v2.13.0-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://static.realm.io/node-pre-gyp/2.13.0/realm-v2.13.0-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for realm@2.13.0 and node@10.6.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://static.realm.io/node-pre-gyp/2.13.0/realm-v2.13.0-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Tried to download(undefined): https://static.realm.io/node-pre-gyp/2.13.0/realm-v2.13.0-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for realm@2.13.0 and node@10.6.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http Connection closed while downloading tarball file

my mac version 10.13.5 (17F77)
node v10.6.0  npm 6.1.0

**Comment by 8BallBomBom** [comment] 2018-07-22 18:36
Same issue, not managing to install any realm versions with yarn or npm.

**Comment by nhachicha** [comment] 2018-07-23 15:49
full stack trace 
```
nvm use 10
npm install --save realm

> realm@2.13.0 install /private/tmp/sandbox/node_modules/realm
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://static.realm.io/node-pre-gyp/2.13.0/realm-v2.13.0-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for realm@2.13.0 and node@10.7.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://static.realm.io/node-pre-gyp/2.13.0/realm-v2.13.0-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for realm@2.13.0 and node@10.7.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
  TOUCH Release/obj.target/OpenSSL.stamp
  TOUCH Release/obj.target/OpenSSL.stamp
  ACTION binding_gyp_vendored_realm_target_download_realm /private/tmp/sandbox/node_modules/realm/vendor/realm-mac-x64
  ACTION binding_gyp_vendored_realm_target_download_realm /private/tmp/sandbox/node_modules/realm/vendor/realm-mac-x64
Resolved requirements: { SYNC_SERVER_FOLDER: 'sync',
  SYNC_ARCHIVE: 'realm-sync-node-cocoa-3.8.0.tar.gz',
  SYNC_ARCHIVE_ROOT: 'realm-sync-node-cocoa-3.8.0' }
Resolved requirements: { SYNC_SERVER_FOLDER: 'sync',
  SYNC_ARCHIVE: 'realm-sync-node-cocoa-3.8.0.tar.gz',
  SYNC_ARCHIVE_ROOT: 'realm-sync-node-cocoa-3.8.0' }
No lockfile found at the target, proceeding.
No lockfile found at the target, proceeding.
Download url: https://static.realm.io/downloads/sync/realm-sync-node-cocoa-3.8.0.tar.gz
Download url: https://static.realm.io/downloads/sync/realm-sync-node-cocoa-3.8.0.tar.gz
Downloading realm-sync-node-cocoa-3.8.0.tar.gz [=                                                                                                                         ] (303k)DownloDownloading realm-sync-node-cocoa-3.8.0.tar.gz [=                                                                                                                         ] (295k)DownloDownloading realm-sync-node-cocoa-3.8.0.tar.gz [=                                                                                                                         ] (221k)DownloDownloading realm-sync-node-cocoa-3.8.0.tar.gz [=                                                                                                                         ] (235k)DownloDownloading realm-sync-node-cocoa-3.8.0.tar.gz [=========                                                                                                                 ] (767k)DownloDownloading realm-sync-node-cocoa-3.8.0.tar.gz [==============                                                                                                            ] (1057k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [==============                                                                                                            ] (1062k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [===============                                                                                                           ] (1085k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [===================                                                                                                       ] (1298k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [========================                                                                                                  ] (1508k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [===========================                                                                                               ] (1494k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [===========================                                                                                               ] (1495k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [============================                                                                                              ] (1557k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [==============================                                                                                            ] (1539k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [======================================                                                                                    ] (1710k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [=======================================================                                                                   ] (1888k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [========================================================                                                                  ] (1847k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [============================================================                                                              ] (1866k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [=========================================================================                                                 ] (1932k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [=========================================================================                                                 ] (1921k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [==============================================================================                                            ] (1937k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [=================================================================================                                         ] (1986k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [===================================================================================                                       ] (1949k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [===============================================================================================================           ] (2030k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [====================================================================================================================      ] (2047k)DownlDownloading realm-sync-node-cocoa-3.8.0.tar.gz [========================================================================================================================= ] (2065k)
Extracting realm-sync-node-cocoa-3.8.0.tar.gz => /private/tmp/sandbox/node_modules/realm/vendor/realm-mac-x64
Downloading realm-sync-node-cocoa-3.8.0.tar.gz [==========================================================================================================================] (2071k)
Extracting realm-sync-node-cocoa-3.8.0.tar.gz => /private/tmp/sandbox/node_modules/realm/vendor/realm-mac-x64
Success
  TOUCH Release/obj.target/vendored-realm.stamp
  TOUCH Release/obj.target/realm-core.stamp
  TOUCH Release/obj.target/realm-sync.stamp
  CXX(target) Release/obj.target/object-store/src/object-store/src/binding_callback_thread_observer.o
Success
  TOUCH Release/obj.target/vendored-realm.stamp
  TOUCH Release/obj.target/realm-core.stamp
  TOUCH Release/obj.target/realm-sync.stamp
  CXX(target) Release/obj.target/object-store/src/object-store/src/binding_callback_thread_observer.o
rm: ./Release/.deps/Release/obj.target/object-store/src/object-store/src/binding_callback_thread_observer.o.d.raw: No such file or directory
make: *** [Release/obj.target/object-store/src/object-store/src/binding_callback_thread_observer.o] Error 1
gyp ERR!   CXX(target) Release/obj.target/object-store/src/object-store/src/collection_notifications.o
build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Nabil/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/Users/Nabil/.nvm/versions/node/v10.7.0/bin/node" "/Users/Nabil/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/private/tmp/sandbox/node_modules/realm/compiled/node-v64_darwin_x64/realm.node" "--module_name=realm" "--module_path=/private/tmp/sandbox/node_modules/realm/compiled/node-v64_darwin_x64"
gyp ERR! cwd /private/tmp/sandbox/node_modules/realm
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/Nabil/.nvm/versions/node/v10.7.0/bin/node /Users/Nabil/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/private/tmp/sandbox/node_modules/realm/compiled/node-v64_darwin_x64/realm.node --module_name=realm --module_path=/private/tmp/sandbox/node_modules/realm/compiled/node-v64_darwin_x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/private/tmp/sandbox/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command "/Users/Nabil/.nvm/versions/node/v10.7.0/bin/node" "/private/tmp/sandbox/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /private/tmp/sandbox/node_modules/realm
node-pre-gyp ERR! node -v v10.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/Users/Nabil/.nvm/versions/node/v10.7.0/bin/node /Users/Nabil/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/private/tmp/sandbox/node_modules/realm/compiled/node-v64_darwin_x64/realm.node --module_name=realm --module_path=/private/tmp/sandbox/node_modules/realm/compiled/node-v64_darwin_x64' (1)
../src/object-store/src/collection_notifications.cpp:21:10: fatal error: 'impl/collection_notifier.hpp' file not found
#include "impl/collection_notifier.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm WARN sandbox@1.0.0 No description
npm WARN sandbox@1.0.0 No repository field.

1 error generated.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! realm@2.13.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the realm@2.13.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
make: *** [Release/obj.target/object-store/src/object-store/src/collection_notifications.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Nabil/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/Users/Nabil/.nvm/versions/node/v10.7.0/bin/node" "/Users/Nabil/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/private/tmp/sandbox/node_modules/realm/compiled/node-v64_darwin_x64/realm.node" "--module_name=realm" "--module_path=/private/tmp/sandbox/node_modules/realm/compiled/node-v64_darwin_x64"
gyp ERR! cwd /private/tmp/sandbox/node_modules/realm
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Nabil/.npm/_logs/2018-07-23T15_46_55_905Z-debug.log
```

**Comment by fealebenpae** [comment] 2018-07-23 15:50
Try downgrading your Node.js version - Node.js 10 is known not to work at the moment.

**Comment by nhachicha** [comment] 2018-07-23 15:53
Duplicate of  https://github.com/realm/realm-js/issues/1813

**Closed by nhachicha** 2018-07-23 15:53 UTC
Labels: O:User
