### ISSUE TITLE
Realm not converting a flat number `1.0` into `double` correctly

### ISSUE THREAD

**Issue by maichongju** [realm/realm-js#6219] opened 2023-10-27 19:42 UTC
### How frequently does the bug occur?

Always

### Description

When inserting a flat number `1.0` into the MongoDB Atlas. Realm does not convert the number into `double`. When the schema is defined as only accept `double` datatype, insertion will failed. 

### Can you reproduce the bug?

Always

### Reproduction Steps

1. Create a collection named `test` on MongoDB atlas with the following validation schema.
```JSON
{
  "properties": {
    "geoLocation": {
      "bsonType": "object",
      "properties": {
        "type": {
          "bsonType": "string"
        },
        "coordinates": {
          "bsonType": "array",
          "items": {
            "bsonType": "double"
          }
        }
      },
      "required": [
        "type"
      ]
    },
    "_id": {
      "bsonType": "objectId"
    }
  }
}
```
2. On the client side connect to the MongoDB and execute the following code
```typescript
await mongoUser.mongoClient('mongodb-atlas').db('main').collection('test').insertOne({
    geoLocation: {
      type: 'Point',
      coordinates: [1.0, 2.0],
    }
  });
```
3. Client side received `insert not permit` error
4. MongoDB Atlas log shows following error message
```
role "readAndWriteAll" in "main.trip" does not have update permission for document with _id: ObjectID("652f3d4625b1458c017f723e"): could not validate document: 
	departureLocation.geoLocation.coordinates.1: Invalid type. Expected: type: undefined, bsonType: [double,null], given: [integer int long number mixed]
```

### Version

"realm": "^12.2.1",, "@realm/react": "^0.6.0",

### What services are you using?

Atlas App Services: Functions or GraphQL or DataAPI etc

### Are you using encryption?

No

### Platform OS and version(s)

Win11 23H2

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment] 2023-10-30 10:49
@maichongju Thank you for reporting. We will try to reproduce in our tests to find the root cause. If you have tried with a version prior to 12, did you observe the same error?

**Comment by maichongju** [comment] 2023-12-14 19:36
I am sorry, but I don't have a setup for pre12. 

Is there any update on this issue?

**Comment by maichongju** [comment] 2023-12-17 03:55
For whoever might have the same issue. The workaround I am using right now is to add or subtract a very small number (0.00001) when `int` is detected.

```typescript
const flat_number = 1.0
if (Number.isInteger(flat_number)){
  flat_number = flat_number + 0.00001;
}
```

**Comment by HugoBounoua** [comment] 2024-03-18 21:35
@kneth Did you release a fix for this? It's been more than a year, and Realm is still throwing exceptions for "int," "double," etc., due to the optimization of NodeJS converting to the smallest type possible. We are obliged to set everything as a "number," which is not ideal. Let me know if there's a workaround better than transforming the value itself. Thank you

**Comment by nirinchev** [comment] 2024-03-20 17:16
I believe this is a bug on app services, where we get the number 1 in json and treat it as an integer. Unfortunately, resolving it could impact many customers, so we'll have to be careful about how we approach it. In the meantime, you could do could try and tell the server that you explicitly want a double by passing in the ejson double representation:

```js
await mongoUser.mongoClient('mongodb-atlas').db('main').collection('test').insertOne({
    geoLocation: {
      type: 'Point',
      coordinates: [ { $numberDouble: "1.0" }, { $numberDouble: "2.0" }],
    }
  })
```

It is obviously less convenient and you could probably add a helper function to avoid having to write the expansion everytime.

**Closed** 2024-04-06 00:07 UTC
Labels: T-Bug, O-Community, More-information-needed, Waiting-For-Reporter, Encryption:Off, Frequency:Always, Repro:Always
