### ISSUE TITLE
Support Node 10. WAS: Realm fails to install via yarn or npm, with the error Failed to execute 'node-gyp build --fallback-to-build --module=[hidden_path]/node_modules/realm/compiled/node-v64_darwin_x64/realm.node --

### ISSUE THREAD

**Issue by edmofro** [realm/realm-js#1813] opened 2018-05-24 01:10 UTC
## Goals

Use yarn or npm to install realm

## Expected Results

Installs correctly

## Actual Results

404 on https://static.realm.io/node-pre-gyp/2.3.2/realm-v2.3.2-node-v64-darwin-x64.tar.gz which causes install to fail

## Version of Realm and Tooling

- Realm JS SDK Version: 2.3.2
- Node or React Native: React Native
- Client OS & Version: Mac 10.13.4
- Which debugger for React Native: None

**Comment by edmofro** [comment] 2018-05-24 02:12
Same on 2.6.0 https://static.realm.io/node-pre-gyp/2.6.0/realm-v2.6.0-node-v64-darwin-x64.tar.gz

**Comment by Paradox-AT** [comment] 2018-05-24 06:10
I am also having the same issue while installing the module.

**Comment by kneth** [comment] 2018-05-24 07:11
We don't support node version 10 yet.

**Comment by mnlbox** [comment] 2018-05-26 06:26
I'm also have same issue and switch from node v.10.1.0 to v9.0.0 and it's working now.

Guys when you plan to update to v10+?

**Comment by kneth** [comment] 2018-05-26 11:39
Once NaN is stabilized (API wise), we plan to return to it. I hope to include it in a release in June.

**Comment by kneth** [comment] 2018-06-08 13:14
I have investigated it a bit more. It is not Nan nor LZMA (at least 3.0.8 supports - `decompress-tarxz` depends on it) . It boils to that `ursa` hasn't released after https://github.com/JoshKaufman/ursa/pull/169 has been merged.

**Comment by esutton** [comment] 2018-06-14 20:29
@edmofro How do you downgrade node to 9.8.0?

I tried:
````
brew uninstall yarn
brew uninstall --force node
brew install node@9.8.0
Error: No available formula with the name "node@9.8.0" 
````

**Comment by edmofro** [comment] 2018-06-14 20:53
Check out https://www.npmjs.com/package/n

**Comment by rogerkerse** [comment] 2018-08-30 13:55
I am on node 10 right now and I still cannot install Realm. Has someone dealt with this issue?

**Comment by nirinchev** [comment] 2018-08-30 14:06
The issue is still open which indicates that it has not been resolved yet. Once we release a node 10 compatible version, we'll report here and close the issue.

**Comment by kuldeepoza** [comment] 2018-09-06 13:01
try 
npm install -g node@9.8.0
npm i --save realm

**Comment by Pinkal7600** [comment] 2018-10-02 09:37
Hello @kuldeepoza 

I have tried your solutions and downgrade node version from 10 to LTS version 8.12.0 but still I get an same error as mention below.

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! realm@2.17.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the realm@2.17.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pinkal/.npm/_logs/2018-10-02T09_32_46_843Z-debug.log

```

**Comment by tigranbalayan** [comment] 2018-10-03 10:17
the issue is actual also with:
node v8.11.2
npm  5.6.0

on CentOS

**Closed** 2018-11-08 08:39 UTC
Labels: O:User, P:1 Required, T:Enhancement

**Comment by fisherwise** [comment] 2018-11-15 05:59
On node 11 having same issue

**Comment by kneth** [comment] 2018-11-15 08:01
@fisherwise We haven't added support for node 11 yet. Please create an issue for it.

**Comment by crobinson42** [comment] 2018-11-19 20:46
Node `10.13` successful w/ `realm@2.19.1`.

**Comment by denizbas92** [comment] 2019-02-11 07:13
> 9.8.0

how di you downgraded node in macbook ?

**Comment by zoozalp** [comment] 2019-02-11 07:46
Try n or nvm.

**Comment by lienict** [comment] 2019-03-05 04:29
if you use node version 11 try this
1. install nvmw
 - npm install -g nvmw 
 - install node version 10 ex : nvmw install v10.12.0
 - use node version 10 using this command : nvmw use v10.12.0
2. edit your realm version in package.json to v2.19.0-rc.5
3. reinstall in cmd

**Comment by joshuapinter** [comment] 2019-04-08 00:58
I personally prefer [`nodenv`](https://github.com/nodenv/nodenv). It works the exact same way as [`rbenv`](https://github.com/rbenv/rbenv), if you're familiar with that. _But_, `realm` wants either `n` or `nvm`, which I think isn't fair. It should just want and expect _a_ version of `node`. Not any, or worse a specific, node package manager.

**Comment by AbhishekNairOfficial** [comment] 2019-08-04 06:19
You guys could also try NVM. It is pretty simple, and allows you to install and use multiple versions of node.
[https://github.com/nvm-sh/nvm

**Comment by toniton** [comment] 2020-12-25 02:24
From DOCs as found here: `node_modules/realm/node_modules/node-pre-gyp/lib/util/versioning.js`, you can add **target_arch** to suite the system configuration of your machine.

`npm i realm --save --target_arch=x64`
