### ISSUE TITLE
Fails to auto-sync until app reload; In a two partitioned app, private & public data

### ISSUE THREAD

**Issue by reanzi** [realm/realm-js#4395] opened 2022-03-03 18:33 UTC
### How frequently does the bug occur?

All the time

### Description

I expected to that user to have access to all public data and private data, but when the app load both data are there just fine.
But adding to a public data only adds to the local realm don't sync with the cloud also on reload all local data are not present only cloud data appears. Also changing cloud data doesn't sync to the app instantly, changes appears after reloading the app.

The private partition does work as expected, changes are live and everything is fine.

I wrap my components with RealmProvider just as usual passing different partitionValue and the currentActive user, because user should be able to add data to the public resource, so I would to know know who added what data

What will I be doing wrong?

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Here are my codes

``` file: RealmProviders.js ```
```
import {createRealmContext} from '@realm/react';
import Link from './src/models/LinkShema';
import FishermanSchema from './src/models/FishermenSchema';

const OpenRealmBehaviorConfiguration = {
  type: 'openImmediately',
};

// Public data Provider
const PublicDataContext = createRealmContext({
  schema: [
    FishermanSchema.schema,
  ],
  newRealmFileBehavior: OpenRealmBehaviorConfiguration,
  existingRealmFileBehavior: OpenRealmBehaviorConfiguration,
});

// Private data Provider
const PrivateContext = createRealmContext({
  schema: [
    Link.schema,
    Link.link_numbersSchema,
  ],
  newRealmFileBehavior: OpenRealmBehaviorConfiguration,
  existingRealmFileBehavior: OpenRealmBehaviorConfiguration,
  // deleteRealmIfMigrationNeeded: true,
});

export {PrivateContext, PublicDataContext};

```
I'm using context to manages authentications also to initialize the Realm App
``` file: AuthContext.js ```
```
import React from 'react';
import Realm from 'realm';

// ?instance of Realm app
const appId = 'realm-app-id';
const appConfig = {id: appId, timeout: 10000};

const app = new Realm.App(appConfig);

const AuthContext = React.createContext(null);

const AuthProvider = props => {
  const [user, setUser] = React.useState(app.currentUser);
  const [loading, setLoading] = React.useState(false);

  const state = {user, loading};

  React.useEffect(() => {
    if (!user) {
      console.log('No user found, Please Login');
      return;
    }
  }, [user]);

  //   Functions
  const signIn = (email, password) => {
    setLoading(true);
    const credentials = Realm.Credentials.emailPassword(email, password);
    app
      .logIn(credentials)
      .then(newUser => {
        setUser(newUser);
      })
      .catch(err => console.error('Errored: ', err))
      .finally(() => setLoading(false));
  };
  const signUp = async (email, password) => {
    try {
      await app.emailPasswordAuth.registerUser({email, password});
    } catch (error) {
      console.warn('Failed to signup: ', error.message);
    }
  };

  const signOut = async () => {
   // signOut logic
  };

  return (
    <AuthContext.Provider value={{signIn, signUp, signOut, state}}>
      {props.children}
    </AuthContext.Provider>
  );
};
const useAuth = () => {
  const auth = React.useContext(AuthContext);
  if (auth == null) {
    throw new Error('useAuth() was called outside of AuthProvider');
  }
  return auth;
};

export {AuthProvider, useAuth};
```

And here is my App file, 
```App.js```

```
import React from 'react';
import {TailwindProvider} from 'tailwind-rn';
import utilities from '../tailwind.json';

import {NavigationContainer} from '@react-navigation/native';
import {LogBox, Dimensions, View, ActivityIndicator} from 'react-native';
import {AppStack, AuthStack} from './navigations';
import {lightTheme, darkTheme} from './themes';
import {AuthProvider, useAuth} from './contexts/AuthContext';
import {PrivateContext, PublicDataContext} from '../RealmApp';

const {RealmProvider} = PrivateContext; // this RealmProvider for Private data
const {RealmProvider: PublicDataProvider} = PublicDataContext;  // this is RealmProvider for public data

const App = () => {

  return (
    <TailwindProvider utilities={utilities}>
      <AuthProvider>
        <RealmWrapper />
      </AuthProvider>
    </TailwindProvider>
  );
};

const RealmWrapper = () => {
  const {
    state: {user}, 
  } = useAuth(); // Cureent App user, logged in
  return (
    <NavigationContainer theme={lightTheme}>
      {user ? (
        <PublicDataProvider sync={{user, partitionValue: 'PUBLIC'}}> 
          <RealmProvider sync={{user, partitionValue: user.id}}>
            <AppStack />
          </RealmProvider>
        </PublicDataProvider>
      ) : (
        <AuthStack />
      )}
    </NavigationContainer>
  );
};
export default App;

```

And finally in the children components 
``` A normal react functional component ```
```
const {useQuery, useRealm} = PublicDataContext; // imported

const Home = ({navigation}) => {
  const result = useQuery('Fishermans');
  const fishermans = React.useMemo(() => result.sorted('name'), [result]);
console.log('Public Data: ', fishermans); // this once loaded doesn't refresh clouds data changes only stare and work with local realm
  const realm = useRealm(); // for adding data to the public resource

...... rest of the code
```

### Version

realm: 10.13.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

windows 10, android Emulator

### Build environment

Plain react-native

**Comment by takameyer** [comment] 2022-03-04 08:13
Hi @reanzi, thanks for filling out this issue and providing comprehensive example code.  We will investigate and let you know as soon as we have more information.

**Comment by reanzi** [comment] 2022-03-04 11:55
We meet again @takameyer ! :)
Thanks, I'll be waiting

**Comment by takameyer** [comment] 2022-03-14 07:10
@reanzi Sorry for not responding in a while.  I was very busy last week and wasn't able to get to this.  I'll see if I can reproduce the issue and get back to you when I find the cause.

**Comment by reanzi** [comment] 2022-03-14 07:13
Thanks @takameyer , I appreciate

**Comment by takameyer** [comment] 2022-03-15 10:55
@reanzi I am having problems reproducing this.  Can you try and add a [progress listener](https://docs.mongodb.com/realm-sdks/js/latest/Realm.App.Sync.Session.html#addProgressNotification) to sync?  
```
realm.syncSession.addProcessNotification("download", "forCurrentlyOutstandingWork", (transferred, transferable) => console.log(transferred, transferable))
```
That way you can monitor what is happening with sync.  It's possible that you may be experiencing latency.  Let us know if that helps! 🙂

**Comment by reanzi** [comment] 2022-03-15 10:57
Thanks, I'll try and let you know

**Comment by kneth** [comment] 2022-10-20 12:03
I am closing the issue due to no reply back. Please comment and reopen the issue if needed.

**Closed** 2022-10-20 12:06 UTC
Labels: T-Bug, O-Community
