### ISSUE TITLE
Unexpected token import { createSession } './session';

### ISSUE THREAD

**Issue by nataliajagiello** [realm/realm-js#3187] opened 2020-09-02 11:49 UTC
## Goals
Connect to MongoDb Realm Application

## Results
```
error: SyntaxError: ..\node_modules\realm\lib\browser\index.js: Unexpected token (34:25)

  32 | import * as util from './util';
  33 | import { static as staticUserMethods } from '../user';
> 34 | import { createSession } './session';
```
## Steps to Reproduce

Running getRealmApp code from the react native tutorial.

## Code Sample
```
import Realm from 'realm';

let app;

export function getRealmApp() {
  if (app === undefined) {
    const appId = 'my-app-id';

    const appConfig = {
      id: appId,
      timeout: 10000,
      app: {
        name: 'default',
        version: '0',
      },
    };
    app = new Realm.App(appConfig);
  }
  return app;
}
```
## Version of Realm and Tooling

- "realm": "^10.0.0-beta.11"
- "react-native": "0.63.2",
- Android 8.1.0

**Comment by steffenagger** [comment] 2020-09-02 12:09
Duplicate of https://github.com/realm/realm-js/issues/3181

**Closed by steffenagger** 2020-09-02 12:09 UTC
Labels: O-Community
