### ISSUE TITLE
[Android] Fixing Libjsc.so not Found with hermes engine true #2455

### ISSUE THREAD

**Issue by zxccvvv** [realm/realm-js#2792] opened 2020-04-02 07:29 UTC
cc @bmunkholm (sorry, i'm not following the issue template, since this is a fixing of https://github.com/realm/realm-js/issues/2455)

https://github.com/realm/realm-js/issues/2455 is locked i can't add a new comment there,

but i'm able to get realm working with hermes enabled,

Fixing https://github.com/facebook/react-native/issues/25537#issuecomment-509180637 :
open build.gradle (app/build.gradle) and add following code:
```
def useIntlJsc = false
```

and in dependencies add following code:
```
if (useIntlJsc) {
     implementation 'org.webkit:android-jsc-intl:+'
} else {
     implementation 'org.webkit:android-jsc:+'
}
```

Screenshot : 

![image](https://user-images.githubusercontent.com/19633881/78220936-a35b6080-74ec-11ea-9753-8270a32044f4.png)

snippet:
```
const info = this.state.realm
      ? 'Number of dogs in this Realm: ' + this.state.realm.objects('Dog').length
      : 'Loading...';

    console.log('info' , info)
    const isHermes = () => global.HermesInternal !== null
    console.log('hermes' , isHermes())
```

PS : I don't know what caused issue when i'm add `useIntlJsc`  *in the future*, becaused i'm not expeert about it, but now i can add realm with hermes enabled without any error (libjsc.so not found error)

ENV:
node : v10.19.0
npm : 6.13.4
"react-native": "0.61.5",
"realm": "^5.0.3"

EDIT: I've tested in `debug` mode, when i tried to tested in `release` mode i get the following error:
![image](https://user-images.githubusercontent.com/19633881/78223842-bde40880-74f1-11ea-9fc5-767a90ebe73c.png)

**Comment by blagoev** [comment] 2020-04-02 09:03
Hi, we don't support the Hermes engine yet.

**Comment by zxccvvv** [comment] 2020-04-02 09:10
hi @blagoev , with above setup, i can confirm that realm can run with Hermes together (Debug mode currently).

**Comment by kneth** [comment] 2020-06-12 09:49
I close the issue as a duplicate of #2455

**Closed by kneth** 2020-06-12 09:49 UTC
Labels: O-Community

**Comment by binbinla** [comment] 2020-07-07 09:54
@kneth 
hi, Hermes support seems to be an urgent and significant feature for so many team that had imported realm. Could you please share us a release plan for Hermes? That would be so appreciated! Or is there has any beta plan for Hermes support?

**Comment by ianpward** [comment] 2020-07-07 13:39
@binbinla It is not part of the plan right now but we are going into quarterly planning right now and will consider it - unfortunately it is a large amount of work - you can follow #2455 for updates

**Comment by flyskywhy** [comment] 2020-12-04 06:24
Edit your project/android/app/build.gradle from
```
    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
```
to
```
    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
        implementation jscFlavor
    } else {
        implementation jscFlavor
    }
```
