### ISSUE TITLE
Importing Realm returns the error "Undefined is not a constructor (evaluating 'new XMLHttpRequest')"

### ISSUE THREAD

**Issue by joshdhenry** [realm/realm-js#1788] opened 2018-05-10 23:16 UTC
## Goals

Import Realm into a React Native project.

## Expected Results

I should be able to import Realm and run the project in iOS with crashing.

## Actual Results

The app crashes in release mode completely. The app crashes in debug mode if not using Chrome Debugger and I get this error on the screen:
`Undefined is not a constructor (evaluating 'new XMLHttpRequest')`

I get this repeating error in the console 
`"Must first create RPC session with a valid host".`

## Steps to Reproduce

I'm trying to import Realm into my React Native project and run in iOS.  I've installed the npm and linked it.  It crashes when I add the following line:

`import Realm from 'realm';`

## Version of Realm and Tooling

- Realm JS SDK Version: 2.4.1
- Node or React Native: RN v0.46.2
- Client OS & Version: Mac OSX 10.13.4
- Which debugger for React Native: Xcode v9.3

**Comment by kneth** [comment] 2018-05-16 10:05
Maybe I misinterpret:

> crashes in debug mode if not using Chrome Debugger

but you can only debug React Native apps using [Chrome](https://facebook.github.io/react-native/docs/debugging.html#chrome-developer-tools).

**Comment by joshdhenry** [comment] 2018-05-17 02:52
I fixed this by upgrading the project to RN v0.47.0. Still not totally sure why that fixed it, but it did.

**Comment by joshdhenry** [comment] 2018-05-17 02:55
I fixed this by downgrading Realm. In package.json, the line for realm is now:
`"realm": "^1.11.1"`

instead of:
`"realm": "^2.4.1"`

**Comment by kneth** [comment] 2018-06-13 07:39
#1732 is a similar issue with some suggestion on how to solve it.

**Comment by sheva007** [comment] 2018-09-03 14:14
@arshbot were you able to overcome this issue?

**Comment by woodpav** [comment] 2018-09-05 23:01
It works when I am remote debugging (:8081).

It does not work when not remote debugging.

**Comment by sheva007** [comment] 2018-09-06 08:06
@woodpav what about the production build?

**Comment by woodpav** [comment] 2018-09-06 16:46
The production build would crash immediately. start_wqthread or something like that. Also if I let the debug build sit there it would crash after a few minutes due to a Realm error "attach notification listener". So I had 3 crashes including the one initially mentioned. I was using a fresh install of Realm from npm and the only Realm code I had was `import Realm from 'realm';` and a `Realm.open(), realm.objects().filtered()`. I'm afraid this is all the info I can provide as I had just added realm, got fed up, and switched to SQLite.

**Comment by sheva007** [comment] 2018-09-07 10:49
Thanks @woodpav & @arshbot for the help,
I tried also doing upgrade to react-native. So I had fresh gradle files, then i uaed reinstalling then relinking but it doesn't work.

In fresh app where I only have typescript & realm, it works.

Seems other packages maybe affecting it.

**Comment by bmunkholm** [comment] 2018-09-11 10:33
@Michaelvilleneuve @sheva007 @arshbot Any suggestions on how to reproduce this?

**Comment by Michaelvilleneuve** [comment] 2018-09-11 10:37
Honestly I have no idea. It just started happening and since then I can’t remove that error unless I active chrome remote debugging

**Comment by sheva007** [comment] 2018-09-11 10:42
Thanks @bmunkholm for the re-open, I have tested realm with typescript in a fresh project and all was smooth, But when tried with the current existing project I get this error.
I only have 2 other packages needed linking in the native side:
**react-native-vector-icons
react-native-svg**

in Android I get "can't find variable Symbol"; while in ios "Undefined is not a constructor (evaluating 'new XMLHttpRequest')"
I wanted to use realm to replace PouchDB

Apart from realm, here are my dependencies:
  "dependencies": {
    "axios": "^0.18.0",
    "i18n-js": "^3.0.11",
    "lodash": "^4.17.10",
    "pouchdb-adapter-asyncstorage": "^6.4.1",
    "pouchdb-find": "^6.4.1",
    "pouchdb-react-native": "^6.4.1",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-elements": "^0.19.1",
    "react-native-modal": "^6.4.0",
    "react-native-picker-select": "^4.2.1",
    "react-native-progress": "^3.5.0",
    "react-native-root-toast": "^3.0.1",
    "react-native-snap-carousel": "^3.7.2",
    "react-native-svg": "6.5.2",
    "react-native-vector-icons": "^5.0.0",
    "react-navigation": "^2.9.3",
    "redux": "^4.0.0",
    "rn-viewpager": "^1.2.9",
    "tslib": "^1.9.0"
  },
  "devDependencies": {
    "@types/i18n-js": "^3.0.0",
    "@types/lodash": "^4.14.112",
    "@types/pouchdb": "^6.3.2",
    "@types/pouchdb-find": "^6.3.3",
    "@types/react": "^16.3.14",
    "@types/react-native": "^0.56.3",
    "@types/react-native-snap-carousel": "^3.6.3",
    "@types/react-navigation": "^2.0.11",
    "eslint": "5.4.0",
    "prop-types": "15.6.2",
    "react-native-typescript-transformer": "1.2.10",
    "tslint": "^5.9.1",
    "tslint-eslint-rules": "^5.1.0",
    "tslint-react": "^3.5.1",
    "typescript": "^2.8.3"
  }

**Comment by Michaelvilleneuve** [comment] 2018-09-11 10:47
@sheva007  I share these packages with you :  
```json
"dependencies": {
    "react": "16.4.1",
    "react-native": "0.55.3",
    "react-native-vector-icons": "^5.0.0",
    "react-navigation": "2.7.0",
    "realm": "2.8.0",
  },
  "devDependencies": {
    "eslint": "4.19.1",
  },
```

I'm not sure why there would be a relation to them but still

**Comment by Michaelvilleneuve** [comment] 2018-09-11 13:27
By the way, something similar happens on Android. This message is iOS only but here is the error for both platforms : 

* ios crash : 

`undefined is not a constructor (evaluating 'new XMLHttpRequest()')`
`makeRequest - rpc.js:204:22`

* android crash :

`Can't find variable : Symbol`
`<unknown> - constants.js:30:24`

**Comment by JamesZhange** [comment] 2018-09-22 10:05
same issue.
after add 'web3' to my project follow [this](https://gist.github.com/dougbacelar/29e60920d8fa1982535247563eb63766), 
run ios crash: 
`undefined is not a constructor (evaluating 'new XMLHttpRequest()')`

Downgrading realm works for me, and I found the problem happened after version 2.0.2:
`"realm": "2.0.2"` works
`"realm": "2.0.3"` crash
@sheva007  I hope it helps

**Comment by tomershohet** [comment] 2018-10-29 12:00
I have the same issue too, any updates? (React native 0.54.5, Realm v2.17.0, Android)

**Comment by joshdhenry** [comment] 2019-02-12 17:05
I tried it again yesterday and I was able to get Realm 2.23.0 working in the same React Native 0.56 project.  Not sure why it works now and didn't work then. A lot has changed in the project since then.

**Comment by bachlongkocanh** [comment] 2019-03-01 08:11
I still have the same error, did anyone solve it?
`"realm":"2.24.0"`,
`"react-native":0.55.3"`

**Comment by v0lume** [comment] 2019-03-12 14:46
also facing this error, does anybody have any solutions?

**Comment by kneth** [comment] 2019-03-12 15:52
We have just released v2.25.0. Please try to upgrade.

**Comment by v0lume** [comment] 2019-03-14 09:49
error is not gone after realm upgrade. 
my thoughts that there was something wrong with our native builds. i tried to setup realm on fresh RN 0.59 and it works fine

**Comment by kneth** [comment] 2019-03-14 10:47
@v0lume Just to be clear: you only see an issue when you upgrade?

**Comment by v0lume** [comment] 2019-03-14 15:10
@kneth no, it was before upgrade also.

seems something was wrong in my project, when i init new CRNA application, add realm - i don't see any errors

**Comment by Michael4691** [comment] 2019-03-30 15:13
what happened to me is this error occurs while I stop debug js remotely, and if i enable remote debug, works fine.
What's the problem? should i continue to use realm to do the development since app could not finally release to work ?

**Comment by barbatus** [comment] 2019-04-12 05:06
seeing this issue as well w/ RN 0.59

**Comment by bmunkholm** [comment] 2019-05-07 12:35
Is someone able to make a clear self contained repro-case available in github?

**Comment by kneth** [comment] 2019-08-14 09:49
I close the issue, and we can reopen once it can be reproduced easily.

**Closed by kneth** 2019-08-14 09:49 UTC
Labels: O:User, Reproduction Required, T:Help

**Comment by YaoHuiJi** [comment] 2019-10-12 04:40
it's very weird, everything works fine yesterday, but when I open my app and turn on'Debug JS Remotely' today, this error popped up…… I do not change any code, it just happened. but if I turn off 'Debug JS Remotely',  this error will disappear.

react-native: 0.60.5
realm: 2.29.2

**Comment by kneth** [comment] 2019-10-15 15:25
> So I restart my wifi router, change ip of my mac and iPhone, and then the error disappeared.

Wow. Yes. Super strange.
