### ISSUE TITLE
Error: realm@2.29.2 install: `node-pre-gyp install --fallback-to-build`

### ISSUE THREAD

**Issue by fansilva1991** [realm/realm-js#2533] opened 2019-09-23 21:10 UTC
## Goals

Installing Realm js with npm install without any errors.

## Expected Results

Installing without any errors.

## Actual Results

Realm.js installation started to fail without any changes in the version of Realm or any package on my package.json file.

```
43853 verbose stack Error: realm@2.29.2 install: `node-pre-gyp install --fallback-to-build`
43853 verbose stack Exit status 6
43853 verbose stack     at EventEmitter.<anonymous> (/Users/vsts/hostedtoolcache/node/10.16.3/x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
43853 verbose stack     at EventEmitter.emit (events.js:198:13)
43853 verbose stack     at ChildProcess.<anonymous> (/Users/vsts/hostedtoolcache/node/10.16.3/x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
43853 verbose stack     at ChildProcess.emit (events.js:198:13)
43853 verbose stack     at maybeClose (internal/child_process.js:982:16)
43853 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
43854 verbose pkgid realm@2.29.2

```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.29.2
- React Native: 0.59.10
- Client OS & Version: macOS-10.14
- Node Version: 10.16.3

**Comment by fernando-sendMail** [comment] 2019-09-23 21:35
I'm having this exact same issue across multiple node versions:

```
ERR! npm install stderr:
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://static.realm.io/node-pre-gyp/2.29.2/realm-v2.29.2-node-v72-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for realm@2.29.2 and node@12.10.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
../src/object-store/src/sync/sync_session.cpp:567:17: warning: enumeration value 'http_tunnel_failed' not handled in switch [-Wswitch]
        switch (static_cast<ClientError>(error_code.value())) {
                ^
../src/object-store/src/sync/sync_session.cpp:567:17: note: add missing switch cases
        switch (static_cast<ClientError>(error_code.value())) {
                ^
1 warning generated.
```

It looks like a file is missing from the server.

**Comment by suark** [comment] 2019-09-23 23:10
basically same error except with version 2.29.1

**Comment by nirinchev** [comment] 2019-09-24 04:59
This is a duplicate of https://github.com/realm/realm-js/issues/2532. Essentially, seems like something broke node-gyp.

**Closed by nirinchev** 2019-09-24 04:59 UTC
Labels: O-Community
