### ISSUE TITLE
Really difficult to use realm.js with react.

### ISSUE THREAD

**Issue by gwl002** [realm/realm-js#2439] opened 2019-07-10 03:48 UTC
1. snapshot not deep frozed /immutable.  // 3years ago you say you areing working toward it
2.even no toObject or toArray common function in other database.
3.no `equal` or `is` function to compare two object or collection is updated or not.
As we all know in react we need to refine code in `shouldComponentUpdate` to improve performance,without this funciton it is really very difficult to use realm.js.
4.debug mode in react-native failure because of realm.js last for a long time never really solved.

**Comment by kneth** [comment] 2019-08-09 13:45
@gwl002 I'll move the issue to our backlog as it has some good suggestions for enhancements.

**Comment by Genhain** [comment] 2019-10-09 01:54
A performant Deep cloning snapshot would be a lifesaver. Currently having issues with a `FlatList` component because any changes made get handled by a realm listener and then forwarded to the `FlatList` then when i try to `memoize` or use `shouldComponentUpdate` to reduce unchanged prop render, the current prop and next prop are identical. So the fix for this is to make a deep clone of each object returned from the listener and then pass it to the `FlatList` , although this works on a small scale like [in this little repo I have here](https://github.com/Genhain/FlatList-Item-memoization), For my current project which handled a list with up to 100,000 of items with more complex UI, the cloning can take quite a while...if I had access to threads or background workers this would be a small pain, but i do not, so it is a big pain.

**Comment by Piero87** [comment] 2020-07-22 00:03
I have the same problem, @Genhain have you made some progress? Have you something to suggest?

**Comment by fronck** [comment] 2022-02-15 17:02
@Piero87 @gwl002 @Genhain Just to drop you an update:  we are still working on this project.  We have a pre-release of the upcoming Realm React package at [@realm/react](https://www.npmjs.com/package/@realm/react).  We'd appreciate it if could give it a kicking around the tires and tell us what you think.

**Comment by takameyer** [comment] 2022-02-15 19:32
Just wanted to add, we are working on a [PR](https://github.com/realm/realm-js/pull/4197) that will fix the issues with `FlatList`.  This is done by returning by returning new object references in a collection when any change has been made.  When this is live, just by using the `useQuery` hook, plugging the data into the `FlatList#data` prop, and wrapping your `renderItem` component in `React.Memo`, the `FlatList` will only render singular changes, and not re-render the list in its entirety.

**Comment by Piero87** [comment] 2022-02-17 08:30
@fronck Thank you for your suggestion, I have read the repository and it seems very very interesting to me, it's an upcoming package? what is its status?? alpha beta?

**Comment by channeladam** [comment] 2023-01-08 13:57
So I am new to Realm and finding that both the React and TypeScript integration is not easy to use...

Here are some notes:

1. React - useQuery currently isn't causing a rerender - but I don't know if it is a bug or something I have done. But having said that, see #2.

2. React - useQuery is actually pretty useless to me... subscribing to the entire collection without being able to specify a filter.  It would be rare that I want to subscribe to the entire collection. So as per the tip in https://www.mongodb.com/docs/realm/sdk/react-native/use-realm-react/#usequery I have to use filtered()... and then I can't use the hook, and have to register listeners myself...

3. TypeScript - calling the constructor in TypeScript always creates an object in the realm database... but I want to do an upsert... like in realm.create with an update mode of 'modified' - I think I instead have to retrieve the object first and then apply updates?   But that and other differences in behaviour with TypeScript seems to be lacking in the documentation.

**Comment by kneth** [comment] 2023-01-10 13:39
@channeladam 

ad 1: We rely on notifications to be fired and I don't believe you get a notification when you create a `Realm.Results` but only when there are changes.

ad 2: `@realm/react` is still in an early stage, and we can add the functionality. The API documentation has an [example](https://github.com/realm/realm-js/blob/master/packages/realm-react/src/useQuery.tsx#L40-L46) and we are working with the docs team on publishing the API documentation.  Adding info about using `useMemo()` is relevant to add to the link, you share.

ad 3 + 4: We have seen the issue on a number of times, and we are considering changing the API in v12 or v13 away from a constructor based API to calling a static method on `Realm.Object`. Your observations are good arguments for the (breaking) change.

**Comment by takameyer** [comment] 2023-01-10 14:16
@channeladam
> So as per the tip in https://www.mongodb.com/docs/realm/sdk/react-native/use-realm-react/#usequery I have to use filtered()... and then I have to register a listener myself on the filtered collection?

If you call `filtered` or `sorted` on the result of `useQuery` you will not have to register your own listeners.  This is handled by `@realm/react`. 

> useQuery currently isn't causing a re-render 

Can you create a new issue and provide an example to reproduce this?  If there is a bug in this, we want to track it.

I have also discovered those issues with embedded objects and our TypeScript classes and hope to get those resolved in future versions.

Really appreciate the feedback you have been providing us!  Sorry for any frustrations you are having, but rest assured we are dedicated to making the interface to Realm as ergonomic as possible.

**Comment by channeladam** [comment] 2023-01-12 02:44
> ad 3 + 4: We have seen the issue on a number of times, and we are considering changing the API in v12 or v13 away from a constructor based API to calling a static method on `Realm.Object`. Your observations are good arguments for the (breaking) change.

Thanks @kneth, this is possible change (along with the other TypeScript-related issues I have come across) is a key insight to help my decision making process.

**Comment by kneth** [comment] 2023-01-12 08:34
@channeladam As a general comment, we will ask you to create an issue with a feature request if you have suggestions of how to improve the API. We - and others users - can discuss in the issue to shape the API.

**Comment by channeladam** [comment] 2023-01-15 12:24
> @channeladam
> 
> > So as per the tip in https://www.mongodb.com/docs/realm/sdk/react-native/use-realm-react/#usequery I have to use filtered()... and then I have to register a listener myself on the filtered collection?
> 
> If you call `filtered` or `sorted` on the result of `useQuery` you will not have to register your own listeners. This is handled by `@realm/react`.
> 
> > useQuery currently isn't causing a re-render
> 
> Can you create a new issue and provide an example to reproduce this? If there is a bug in this, we want to track it.

Thanks @takameyer , the useQuery issue I was having there I believe was caused by babel schema generation issues.

However, now I have those resolved enough, I have the opposite problem with useQuery.
See #5264

**Comment by bimusiek** [comment] 2023-01-23 11:24
> If you call filtered or sorted on the result of useQuery you will not have to register your own listeners. This is handled by @realm/react.

@takameyer Just to make sure, as we want to start using realm/react as well:
If we do `const query = userQuery(SomeModel)` and then call `filtered` on it, the result will be to have re-renders only on changes that happened after filtering the query? 

We want to be able to present filtered results and have re-render only triggered when something changes in the filtered results, not in the whole results of the model.

**Comment by takameyer** [comment] 2023-08-24 09:15
@bimusiek We have added a callback as the second argument to `useQuery` which you can use to apply your filtered state.  Let us know what you think!

Closing this issue as it's very vague.  We now have a dedicated library for React, so if you have any specific issues, please open a separate issue.

**Closed by takameyer** 2023-08-24 09:15 UTC
Labels: T-Enhancement, O-Community
