### ISSUE TITLE
Global Notifier Throw Error if setAccessToken is not called

### ISSUE THREAD

**Issue by mbalex99** [realm/realm-js#1166] opened 2017-07-28 22:26 UTC
## Expected Results

Using Global Notifier API without calling `setAccessToken` should throw an error saying that the feature requires a paid token. 

## Actual Results

Using Global Notifier API without calling `setAccessToken` will not throw an error. It's silent.  It will fire __admin and __management realms but nothing else. 

## Steps to Reproduce

1. Create an index.js file with realm <= 1.10.x (as of reporting)
2. Create any global notifier without calling `Realm.Sync.setAccessToken(YOUR_PRO_TOKEN)`
3. Observe that no user realms will get called. It will fire __admin and __management realms but nothing else.

**Comment by kristiandupont** [comment] 2017-07-31 11:48
Duplicate of #1157

**Closed by kristiandupont** 2017-07-31 11:48 UTC
Labels: S:Backlog, T:Duplicate
