### ISSUE TITLE
Support catalyst/UIKit for Mac

### ISSUE THREAD

**Issue by LeoLeBras** [realm/realm-js#2629] opened 2019-12-02 22:24 UTC
## Goals

Compile and use Realm for iOS in a Project Catalyst (iPad app for macOS) project.

➡️https://github.com/realm/realm-cocoa/issues/6163

## Expected Results

A successful build.

## Actual Results

```
ld: in /Users/xxx/Documents/xxx/node_modules/realm/vendor/realm-ios/librealm-ios.a(placeholder.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, file '/Users/xxx/Documents/xxx/node_modules/realm/vendor/realm-ios/librealm-ios.a' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
## Steps to Reproduce

Create a RN project with `realm` and select the Mac target :

![67369890-16de6680-f57a-11e9-9c6e-a0ac2deac569](https://user-images.githubusercontent.com/856188/70000027-5b3a2a80-155a-11ea-95e0-afcbb276cbfa.png)

## Version of Realm and Tooling

- Realm JS SDK Version: `4.0.0-alpha.2`
- Node or React Native: `0.61.5`
- Client OS & Version: `Xcode 11.2.1`
- Which debugger for React Native: ?/None

**Comment by tgoyne** [comment] 2019-12-03 00:40
CocoaPods does not support prebuilt libraries with catalyst yet. https://github.com/CocoaPods/CocoaPods/pull/9334 is a PR which will add the required functionality.

**Comment by LeoLeBras** [comment] 2019-12-17 16:19
http://blog.cocoapods.org/CocoaPods-1.9.0-beta/ 🍾

**Comment by dev-two** [comment] 2020-05-10 17:11
So what do we do now to get RealmJS with CocoaPods 1.9 running on Catalyst?

**Comment by marcosrdz** [comment] 2020-08-27 19:18
For Catalyst, I changed the Podspec:

s.ios.vendored_libraries = 'vendor/realm-ios/librealm-maccatalyst.a', 'vendor/realm-ios/librealm-parser-maccatalyst.a'

**Comment by kneth** [comment] 2021-01-29 13:57
Duplicate of #2883

**Closed by kneth** 2021-01-29 13:57 UTC
Labels: O-Community
