### ISSUE TITLE
Coop with Jisti-Meet library: Realm has no setter or ivar for its bridge, which is not permitted.

### ISSUE THREAD

**Issue by saadqbal** [realm/realm-js#2193] opened 2019-01-03 16:16 UTC
## Goals

I want to use Jitsi-Meet (Video calling library) with Realm
## Expected Results

App should run without any issue

## Actual Results

When I run the app on iOS, Realm does not work. It shows the following error:

`2018-12-28 16:22:34.504 [error][tid:main][RCTModuleData.mm:179] Realm has no setter or ivar for its bridge, which is not permitted. You must either @synthesize the bridge property, or provide your own setter method.`

Realm works fine if I remove Jisti-Meet Library
## Steps to Reproduce

1. Create a new react-native app: `react-native init AwesomeProject`
2. Install realm-js: `npm install realm --save` and `react-native link realm`
3. Install React Native Jisti Meet: `npm install react-native-jitsi-meet --save` 
4.  Under Build setting set **Dead Code Stripping** to No, set **Enable Bitcode** to No and **Always Embed Swift Standard Libraries** to Yes
5. add `node_modules/react-native-jitsi-meet/ios/WebRTC.framework` and `node_modules/react-native-jitsi-meet/ios/JitsiMeet.framework` to the Embed Binaries. 
6.  select `Build Settings`, find `Search Paths` . Edit BOTH `Framework Search Paths` and `Library Search Paths`. and  add path on BOTH sections with: `$(SRCROOT)/../node_modules/react-native-jitsi-meet/ios` with `recursive`

Now run the app and the app will show the error. 

## Code Sample

filename: App.js

`import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, Button} from 'react-native';
import Realm from 'realm';
`
`const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' + 'Cmd+D or shake for dev menu',
  android:
    'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

type Props = {};
export default class App extends Component<Props> {

  constructor(props) {
    super(props);
    this.state = { realm: null };
  }

  componentWillMount() {
    Realm.open({
      schema: [{name: 'Dog', properties: {name: 'string'}}]
    }).then(realm => {
      realm.write(() => {
        realm.create('Dog', {name: 'Rex'});
      });
      this.setState({ realm });
    });
  }

  render() {
    
    const info = this.state.realm
    ? 'Number of dogs in this Realm: ' + this.state.realm.objects('Dog').length
    : 'Loading...';
    

    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
        <Button title="Video" 
        // onPress = {() => initiateVideoCall()} 
        />
        <Text style={styles.welcome}>
          {info}
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
`

## Version of Realm and Tooling

- Realm JS SDK Version: 2.21.1 (Lower versions also have the same issue )
- Node or React Native: RN 0.57.8
- Client OS & Version: iOS Real Device - 12.1.2
- MacOS: 10.13.6 High Sierra
- Which debugger for React Native: React Native Debugger

**Comment by saadqbal** [comment] 2019-01-06 17:44
Update:

When the remote debugging is set, the app runs without showing the redbox.
But the iOS console still shows the following error:

`2019-01-06 22:39:59.268 [error][tid:main][RCTModuleData.mm:179] Realm has no setter or ivar for its bridge, which is not permitted. You must either @synthesize the bridge property, or provide your own setter method.
`
The app does not run in release mode

**Comment by saadqbal** [comment] 2019-01-06 17:53
Hey @kneth, could you please look into this? I am completely stuck. we have been working on this project for 4 months and now we are stuck in this issue.

**Comment by kneth** [comment] 2019-01-07 11:30
@saadqbal We have seen a similar issue before which was fixed by #1065. But from your description, it sounds like the combination with`react-native-jitsi-meet` is making trouble. I see that you have opened https://github.com/skrafft/react-native-jitsi-meet/issues/17 too.

Can you create a very small project which shows the issue? Such a project might help us when investigating.

**Comment by saadqbal** [comment] 2019-01-07 11:48
@kneth thank ou very much for the response.

Realm shows this error even if you skip the library and add webrtc and jitsi frameworks.

The app runs runs in enabling remote debugging though. 

Let me know if you want me to push the code in a repo.

**Comment by saadqbal** [comment] 2019-01-08 13:44
@kneth I can pay for this task if you are ready to look into it.

**Comment by bmunkholm** [comment] 2019-01-08 14:16
@saadqbal A repo where it's superfast to replicate the issue is always a great help!
We do provide professional support and contract work if you have an urgent need like this you want to expedite. You are welcome to contact sales@realm.io for inquiries about the options.

As you can see realm-js is also open source and we appreciate PR's in case you can resolve the issue yourself.

Otherwise we will resolve issues with our internal priorities.

**Comment by saadqbal** [comment] 2019-01-08 14:18
@bmunkholm I have added you to the repo.

**Comment by bmunkholm** [comment] 2019-01-08 14:20
@saadqbal Please add @kneth and @cmelchior as well. Thanks!

**Comment by saadqbal** [comment] 2019-01-08 14:21
@bmunkholm sure. Just added them both.

**Comment by saadqbal** [comment] 2019-01-11 17:53
@kneth @bmunkholm @cmelchior Any leads on this? I know you guys are super busy in doing an amazing job. I am badly stuck with the project and need some help.

**Comment by saadqbal** [comment] 2019-01-17 11:02
@bmunkholm I have sent an email to sales@realm.io. Could you please look into it? We have a fast approaching deadline. If it is taking time, we will have to shift to WatermelonDB.

**Comment by diegolmello** [comment] 2019-02-13 18:02
@saadqbal @kneth Any news on this?
I'm having the same issue adding jitsi to my app.

**Comment by saadqbal** [comment] 2019-02-13 18:05
@diegolmello Nope. I shifted to WaterMelonDB finally.

**Comment by diegolmello** [comment] 2019-02-13 18:13
@saadqbal Nice! I just saw you [asked](https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/576#issuecomment-453595518) at RocketChat.ReactNative about it.
Now I'll finally start the migration.
Thanks :)
Hahaha

**Comment by saadqbal** [comment] 2019-02-13 18:15
Best of luck :)

**Closed** 2019-08-14 07:59 UTC
Labels: O:User, T:Help
