### ISSUE TITLE
[5.0.3] Adding an existing item to a collection throws error

### ISSUE THREAD

**Issue by gablorquet** [realm/realm-js#2831] opened 2020-04-21 17:01 UTC
## Goals

Before updating to 5.0.3, I could create an object then add it to a collection property of another object in 2 steps. Now it seems like pushing the object into the collection tries to create it anew and the primary key being the same, it throws an exception

## Actual Results

Throws "Attempting to create an object of type Entity with an existing primary key value `GUID`

## Code Sample

Example of the class used
```
class Entity {
    entityId: string; */this is the primary key/*
    relations: Realm.List<Entity>;
}

...

function AddRelation(currentId: string, friendId: string){
    realm.write(() => {
        let current = realm.objectForPrimaryKey('Entity', currentId);
        let friend = realm.objectForPrimaryKey('Entity', friendId);
        current.relations.push(friend);
    })
}
```

## Version of Realm and Tooling

- Realm JS SDK Version: 5.0.3
- Node or React Native: React Native
- Client OS & Version: Android 
- Which debugger for React Native: None

**Comment by v0lume** [comment] 2020-05-29 11:40
#2843 same situation, it's a blocker for our applications

**Comment by kneth** [comment] 2020-06-25 12:29
I close it as a duplicate of #2843.

**Closed** 2020-06-25 12:33 UTC
Labels: O-Community
