### ISSUE TITLE
JSON.Stringify dont work for realm classes

### ISSUE THREAD

**Issue by enigmablue** [realm/realm-js#3138] opened 2020-08-15 01:41 UTC
Hi, i took a completely new init, and compared a JSON.stringify of a class vs non class.
It appears that a class dosen't seem to show the properties of the schema. Not sure if its expected.

You will realize the code is exactly the same as the docs. (using the person class example and the dog json example)
And you can see the dog works but the person does not

![image](https://user-images.githubusercontent.com/35584085/90302785-6318df80-dedb-11ea-83e3-a3b4f9cc1a76.png)

  "react-native": "0.63.2",
    "realm": "^6.0.4"

```
class Person {
  get fullName() {
    return this.firstName + ' ' + this.lastName;
  }
}

Person.schema = {
  name: 'Person',
  properties: {
    firstName: 'string',
    lastName: 'string',
  },

};

const App: () => React$Node = () => {

  const [realm, setRealm] = useState(null)

  useEffect (()=>{


    Realm.open({
      schema: [
      {
        name: 'Dog', properties: {name: 'string'}
        }, Person
        ]
        }).then(realm => {
          realm.write(() => {
            realm.create('Dog', {name: 'Rex'});

            const john = realm.create('Person', {
              firstName: 'John',
              lastName: 'Smith',
              });
              });

              let dogs = realm.objects('Dog');
              let persons = realm.objects('Person');

              for (let d of dogs)    console.log("dog ", JSON.stringify(d))  
              for (let p of persons) console.log("person ", JSON.stringify(p))              

              setRealm({ realm });
              });
              }, [])
```

Linked to https://github.com/realm/realm-js/issues/3117

**Comment by kraenhansen** [comment] 2020-08-17 09:03
@enigmablue what happens if you let `Person` extend from `Realm.Object`, like so:

```javascript
class Person extends Realm.Object {
  get fullName() {
    return this.firstName + ' ' + this.lastName;
  }
}

Person.schema = {
  name: 'Person',
  properties: {
    firstName: 'string',
    lastName: 'string',
  },
};
```

**Comment by TNielsen92pro** [comment] 2020-08-31 18:05
Got the exact same issue. Also get the same error when trying the suggested solution.
The issue arose when upgrading from realm 3.3.0 to 6.0.5.
Any solutions?

**Comment by davx1992** [comment] 2020-09-01 10:20
Having same issue, issue appeared when upgraded to 6.1.0. Also it looks like Documentation is not up to date, as part of extending object, is missing there.

**Comment by steffenagger** [comment] 2020-09-01 11:04
I can confirm that I'm also seeing the `Reflect.construct requires the first argument be a constructor` error when extending `Realm.Object` in RN, and will be investigating how this slipped through our tests.

The error arises as soon as a class model extends `Realm.Object`. My apologies for guiding in that direction.

A _temporary_ solution for getting serialization working on class models would be (_instead_ of extending `Realm.Object`) to implement `toJSON` on your class models like so:

```js
class Person {
  firstName;
  lastName;

  get fullName() {
    return this.firstName + ' ' + this.lastName;
  }

  toJSON() {
    return Realm.Object.prototype.toJSON.call(this);
  }
}
```

This will still not include `fullName`, as JavaScript per design does not include getters in these operations.

You can though opt in by manually extending the object for serialization:
```js
toJSON() {
  return {
    fullName: this.fullName,
    ...Realm.Object.prototype.toJSON.call(this),
  };
}
```

**Comment by enigmablue** [comment] 2020-09-01 11:14
i think the problem is a lot of people (including myself) are currently having code that extends Realm.object
So we can't upgrade, and I dont know if I want to change the type of class... as I remember there were other issues... maybe i'd have to try again...

I currently also have static methods in the class.. so I can do stuff like Person.getById(), Person.doSomething() ,  may have to check that. 

My current class..

```
class Share extends Realm.Object {

  static getShares(ids) {
    if (!ids || ids.length < 1) {
      return;
    }
    try {
      let realmResult = realm
        .objects(SHARE_SCHEMA)
        .filtered(ids.map(_id => '_id == ' + `'${_id}'`).join(' OR '));
      return realmResult;
    } catch (e) {
      handleError(e, 'getShares');
    }
  }

  static schema = {
    name: SHARE_SCHEMA,
    primaryKey: '_id',
    properties: {
      _id: {
        type: 'string',
        optional: true,
      },
      tag: {
        type: 'string',
        optional: true,
      },  
  };
}
```

**Comment by steffenagger** [comment] 2020-09-03 07:25
@enigmablue completely understandable, we're working on this issue.
Will post here when we have something concrete.

**Comment by enigmablue** [comment] 2020-09-03 07:27
> @enigmablue completely understandable, we're working on this issue.
> Will post here when we have something concrete.

Thanks so much! Was stuck on this for a while, was wondering why no one else had this issue haha.

**Comment by steffenagger** [comment] 2020-09-03 07:35
I think many has worked around this issue by passing in `Person.schema` instead of `Person`, when initiating the Realm. But this neglects getting the actual class models when fetching - so again, not really a solution I can recommend.

**Comment by kraenhansen** [comment] 2020-09-10 08:24
Closing this as a duplicate of https://github.com/realm/realm-js/issues/3110 - please watch that issue to get notified when we get this fixed.

**Closed by kraenhansen** 2020-09-10 08:24 UTC
Labels: O-Community
