### ISSUE TITLE
Missing Realm Constructor (React Native - Android)

### ISSUE THREAD

**Issue by noelzappy** [realm/realm-js#6041] opened 2023-08-06 22:31 UTC
### How frequently does the bug occur?

Always

### Description

My app crashes on Android whenever I run it, I followed the steps described [HERE](https://www.mongodb.com/docs/realm/sdk/react-native/). iOS works fine, but Android doesn't. I'm able to compile an APK but that crashes also when installed. Here is the error shown in development:

``` 
Error: Missing Realm constructor. Did you run "pod install"? Please see https://docs.mongodb.com/realm/sdk/react-native/install/ for troubleshooting, js engine: hermes 
```

![Screenshot_1691359844](https://github.com/realm/realm-js/assets/38583057/afb7e9c2-18c5-4b28-ad08-2a3af1713a30)

Here is my `App.tsx` content

```typescript
import React from 'react';
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/lib/integration/react';
import { store, persistor } from './store';
import ApplicationNavigator from './navigators';

import { Colors, FontSize } from './theme/Variables';
import { RealmProvider } from './models';


const App = () => (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <RealmProvider>
              <ApplicationNavigator />
        </RealmProvider>
      </PersistGate>
    </Provider>
);

export default App;
```

And my `model/index.ts` looks like this:

```typescript
import Realm from 'realm';
import { createRealmContext } from '@realm/react';
import Account from './account.model';
import Contact from './contact.model';
import Transaction from './transaction.model';

export const schemas = [Account, Contact, Transaction];

const realmConfig: Realm.Configuration = {
  schema: schemas,
  deleteRealmIfMigrationNeeded: true, // TODO: remove in production
};

const { RealmProvider, useRealm, useObject, useQuery } = createRealmContext(realmConfig);


export { RealmProvider, useRealm, useObject, useQuery };

```

I don't think I'm doing anything wrong given this same setup works on iOS.
I'm on React Native "0.72.1".

### Stacktrace & log output

```shell
Error: Missing Realm constructor. Did you run "pod install"? Please see https://docs.mongodb.com/realm/sdk/react-native/install/ for troubleshooting, js engine: hermes 
    at loadModuleImplementation (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.builtlite&modulesOnly=false&runModule=true:328:14)
    at RCTView
    at View (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.builtlite&modulesOnly=false&runModule=true:59444:43)
    at RCTView
    at View (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.builtlite&modulesOnly=false&runModule=true:59444:43)
    at AppContainer (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.builtlite&modulesOnly=false&runModule=true:59305:36)
    at builtlite(RootComponent) (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.builtlite&modulesOnly=false&runModule=true:108523:28)
```

### Can you reproduce the bug?

Always

### Reproduction Steps

- Create a new React Native app
- Follow the installation steps described [HERE](https://www.mongodb.com/docs/realm/sdk/react-native/)
- Run the app on Android

### Version

    "@realm/react": "^0.5.1",     "realm": "^11.10.1",

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android API 32

### Build environment

Which debugger for React Native: ..

### Cocoapods version

1.12

**Comment by TheVitya** [comment] 2023-08-08 10:15
Same issue on:

react-native: 0.72.3
realm: 11.10.1
@realm/react: 0.5.1

Any workarounds so far?

**Comment by takameyer** [comment] 2023-08-08 10:56
@TheVitya @noelzappy Thanks for reporting this.  I just tested this out and it appears `newArchitecture` is enabled for Android by default on `react-native@0.72.x`. 

There are two workarounds:
 
* You can fix this by editing the `android/gradle.properties` and setting `newArchEnabled` to `false`.
* You can upgrade to our latest release candidate `npm install realm@next`.  `realm` v12 is quite stable and will be released in the near future.  It also works with `newArchEnabled`

**Comment by TheVitya** [comment] 2023-08-08 13:22
@takameyer 

Thanks for the answer.

I have tried the workarounds that you gave, but none of these help. 

By default the `newArchitecture` is set to false on `react-native@0.72.x`. (when creating a new application with `npx react-native@latest init AwesomeProject` command)

I have created a brand new application, installed `realm@next`, built with `newArchEnabled=false`, but unfortunately the constructor still can not be called, when trying creating a new instance of `Realm`.

I have tried with `newArchEnabled=true`, then a different error message arrived: `Cannot read property 'Helpers_get_table' of undefined`.

I have checked and the module can not be accessed through neither `NativeModules.Realm` nor `TurboModuleRegistry.get("Realm")`.

react-native: 0.72.3
realm: 12.0.0-rc.3

**Comment by kriit24** [comment] 2023-08-10 09:51
Not worked for me.
 ERROR  TypeError: Cannot read property 'Helpers_get_table' of undefined, js engine: hermes

{
  "name": "test",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@realm/react": "^0.5.1",
    "bson": "^4.7.2",
    "expo": "~48.0.18",
    "expo-file-system": "~15.2.2",
    "expo-status-bar": "~1.4.4",
    "laravel-echo": "^1.15.2",
    "mongoose": "^7.4.1",
    "react": "18.2.0",
    "react-native": "0.71.8",
    "react-native-get-random-values": "~1.9.0",
    "realm": "^12.0.0-rc.3",
    "socket.io-client": "^4.7.2",
    "uuid": "^9.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}



That realm is unbelievable crap.

**Comment by TheVitya** [comment] 2023-08-10 11:48
@kriit24

Firstly, Realm is a great solution for lot of things, so can not be called crap. 

Secondly, the above mentioned solution does not include expo at all. You are using `react-native: 0.71.8`, despite @noelzappy and me are using `react-native: 0.72.x`.

Finally, please try to upgrade `react-native` to the `latest` version. If you `do not want to/can not` please check the compatibility table that can be found [here](https://github.com/realm/realm-js/blob/main/COMPATIBILITY.md). If the issue still exists even if you updated, it could be helpful if you give us a bare minimum `package.json` to reproduce it.

**Comment by noelzappy** [comment] 2023-08-10 12:15
> @TheVitya @noelzappy Thanks for reporting this. I just tested this out and it appears `newArchitecture` is enabled for Android by default on `react-native@0.72.x`.
> 
> There are two workarounds:
> 
> * You can fix this by editing the `android/gradle.properties` and setting `newArchEnabled` to `false`.
> * You can upgrade to our latest release candidate `npm install realm@next`.  `realm` v12 is quite stable and will be released in the near future.  It also works with `newArchEnabled`

This is right. After disabling the new architecture, it worked. Thanks @TheVitya

**Comment by kriit24** [comment] 2023-08-11 02:32
@TheVitya 

now i have 
npm -v
9.8.0
node -v
v16.15.0

this is a package.json
{
  "name": "test",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@realm/react": "^0.5.2",
    "bson": "^4.7.2",
    "expo": "^48.0.0",// also dried with 48.0.19 and 49.0.7
    "expo-file-system": "^15.4.3",
    "expo-status-bar": "^1.6.0",
    "laravel-echo": "^1.15.2",
    "mongoose": "^7.4.1",
    "react": "18.2.0",
    "react-native": "^0.72.3",
    "react-native-get-random-values": "~1.9.0",
    "realm": "^12.0.0-rc.3",
    "socket.io-client": "^4.7.2",
    "uuid": "^9.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}

and the same error occurs.
if u cannot install to blank project and with all the requirements then its not a great solution ... crap.

 ERROR  TypeError: Cannot read property 'Helpers_get_table' of undefined, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

**Comment by takameyer** [comment] 2023-08-11 07:08
@kriit24 Hello :) The issue here is that Realm is a 3rd party library to Expo, so you need to install the `expo-dev-client` to use this.  They really should just have this installed out of the box, to make using Realm or any other 3rd party library in a clean project easier.
The following steps should get you up and running:
```
npm install expo-dev-client
npx expo run:ios
npx expo run:android
```

Also we will be updating shortly to catch this error with the `Helpers_get_table`, which is a side effect of the Realm binary not being available (need expo-dev-client).

**Comment by takameyer** [comment] 2023-10-05 09:11
Closing as this issue can be resolved on the user side.  Please create a new issue if you are still having issues using Realm with Expo or React Native.

**Closed by takameyer** 2023-10-05 09:11 UTC
Labels: T-Bug, O-Community, SDK-Use:Local, Encryption:Off, Frequency:Always, Repro:Always
