### ISSUE TITLE
Realm Provider in jest returns null

### ISSUE THREAD

**Issue by kieran-osgood** [realm/realm-js#4762] opened 2022-08-09 10:46 UTC
### How frequently does the bug occur?

All the time

### Description

During a refactor to replace our current realm hooks with @realm/react have experienced issues with jest tests failing.

Is there any test integration guides I've missed for using the @realm/react package in jest?

I have a realm context which I'm creating in a separate file like so:
```
export const RealmContext = createRealmContext({
  schema: [
      // ... schemas
  ],
  inMemory: true,
})
```
then importing and using it like so:
```
import { RealmContext } from '@/contexts/Realm'

// ...

const AppProviders = ({ children }: { children: ReactNode }) => {
  const { RealmProvider } = RealmContext
  return (
    <NativeBaseProvider initialWindowMetrics={inset} theme={theme}>
      <RealmProvider fallback={<Text>abc</Text>}>{children}</RealmProvider>
    </NativeBaseProvider>
  )
}
```

The stacktrace below will show that the provider is always just rendering the fallback component 

Is there a standard mock or anything to utilise, maybe a way to wait for the realm to be available for the  I've seen mocks for realm but not for @realm/react 

I don't explicitly test the realm implementation but some of the components use 

### Stacktrace & log output

```shell
It appears to just be showing the fallback 

  ● ScreenHeader › Provides the back arrow when it should

    No instances found with accessibilityLabel /back/i

      12 |     )
      13 |     t.debug()
    > 14 |     const backButton = t.getByA11yLabel(/back/i)
         |                          ^
      15 |     fireEvent(backButton, 'press')
      16 |     expect(mockBack).toHaveBeenCalledTimes(1)
      17 |   })

      at Object.<anonymous> (src/components/atoms/ScreenHeader/ScreenHeader.test.tsx:14:26)

  console.log
    <RNCSafeAreaProvider
      onInsetsChange={[Function anonymous]}
      style={
        Array [
          Object {
            "flex": 1,
          },
          undefined,
        ]
      }
    >
      <Text
        dataSet={Object {}}
        style={
          Object {
            "backgroundColor": undefined,
            "color": "#171717",
            "fontFamily": "WorkSans-Regular",
            "fontSize": 14,
            "fontStyle": undefined,
            "fontWeight": undefined,
            "letterSpacing": 0,
            "lineHeight": 21,
            "textDecorationLine": undefined,
          }
        }
      >
        abc
      </Text>
    </RNCSafeAreaProvider>
```
```


### Can you reproduce the bug?

Yes, always

### Reproduction Steps

In order to reproduce fire up any test app you have the @realm/react hooks as the means of accessing realm, and run a jest test where the UI is rendered in a provider from RealmContext

### Version

@realm/react: 0.3.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

jest 26.6.3

### Build environment

Which debugger for React Native: ..


### Cocoapods version

_No response_

**Comment by takameyer** [comment] 2022-08-10 12:14
@kieran-osgood On the very first render of the `<RealmProvider>` the fallback will be shown.  This is due to an internal call to `Realm.open` which is an asynchronous function.  Due to the nature of async, a single tick must occur before the opened `realm` is added to the provider context and re-rendered.  

You can see an example of this in our [integration tests](https://github.com/realm/realm-js/blob/master/packages/realm-react/src/__tests__/RealmProvider.test.tsx) for `@realm/react`.   Here `waitForNextUpdate` is being called in order for the component to render its children.

You can add something similar in your tests as well.  For example, one could use `setTimeout` to accomplish this:
```
await new Promise(resolve => setTimeout(resolve, 0));
```

I'm going to close this issue, as this is working as designed.  Let us know if this works for you and thanks for submitting this issue.

**Closed by takameyer** 2022-08-10 12:14 UTC
Labels: T-Bug, O-Community

**Comment by kieran-osgood** [comment] 2022-08-11 16:49
Thanks for that - used the `await new Promise(resolve => setTimeout(resolve, 0));` after rendering components to fix the issue.
Do you think it'd be worth using this issue to track a documentation update to make it easier for people to get started with the @realm/react package? 
Not sure this is immediately obvious from the documentation unless I missed it
