### ISSUE TITLE
Iterating over results: random error `undefined is not an object (evaluating 'v.next')`

### ISSUE THREAD

**Issue by cristianoccazinsp** [realm/realm-js#4300] opened 2022-02-02 14:31 UTC
### Description

At some point all code running queries start failing with the following error: undefined is not an object (evaluating 'v.next'). I'm sorry I don't have a stack trace, the the user that sent this log basically got this error from everywhere a realm query was looped over, and ultimately ended up in a hard crash: EXC_BAD_ACCESS: Attempted to dereference garbage pointer 0x1c.

I got error logs from 3 different places in the app that run queries asynchronously / with timers or in a loop. They all happened at almost the same time while looping through collections.

Code example that threw the error:
```

// Query 1
let res = realm.objects('QueueItem').filtered(`groupId=${groupId}`);

res = res
  .sorted([
    ['locked', false],
    ['error', false],
    ['mobile', true],
    ['priority', false],
    ['added', false],
  ])
  .slice(0, count)
  .map((obj) => {
    let res = toPlainObject(obj);
    return res;
  });

return res;


// query 2 in a completely different location in the code
let items = realm
      .objects('GalleryItem')
      .filtered(`added <= ${timestamp} and webId != null`);
for (let ele of items)....


// Helper func
export function toPlainObject(realmObject, schemaProperties) {
  let res = {};
  for (let k of Object.keys(schemaProperties)) {
    res[k] = realmObject[k];
  }
  return res;
}
```

### Stacktrace & log output

```shell
Only the error message is available as our logging handles the unhandled exception and only logs the message.
```

### Can you reproduce a bug?

Not yet

### Reproduction Steps

Unknown. Just filtering, querying and looping.

### Version

10.20.0-alpha.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 14.4.2 (iPhone XR)

**Comment by takameyer** [comment] 2022-02-03 08:13
@cristianoccazinsp Thanks for reporting!  Such bugs are difficult for us to diagnose without a reproduction path.  That being said, I have a few suggestions that may or may not help:

- `Realm.Object`s and `Realm.Collection`s have a `toJSON` function you can use to achieve the same result as your `toPlainObject` function
- We have made significant improvements since version `10.20.0-alpha.2`.  I would recommend updating to `10.20.0-beta.1`

Let us know if the problem persists and if possible, any reproduction steps to isolate the issue.

**Comment by cristianoccazinsp** [comment] 2022-02-03 12:37
@takameyer I recall using `toJSON` at some point but it didn't work as expected, as the returned object was still not "stringifiable", but I will certainly give it a try again.

I've also tried beta.1 but it has some breaking changes for iOS that prevent me from using it, so until that's fixed I cannot test it.

**Comment by takameyer** [comment] 2022-02-04 08:55
@cristianoccazinsp Which breaking changes are preventing you from updating?  Is there an open issue you can link here?

**Comment by cristianoccazinsp** [comment] 2022-02-16 15:09
https://github.com/realm/realm-js/issues/4297#issuecomment-1040129817 is a release blocker so we cannot upgrade.

Haven't checked whether or not this was fixed with beta.2

**Comment by kneth** [comment] 2022-03-09 10:21
@cristianoccazinsp Did you have a chance to check beta.2?

**Comment by cristianoccazinsp** [comment] 2022-03-09 13:03
@kneth I am testing with beta.2 as of now, but we've only released to beta users so the the issue may not have showed yet.  Can we keep this open for a little longer?

**Comment by kneth** [comment] 2022-03-09 14:20
@cristianoccazinsp Sure, we can keep it open.

**Comment by tomduncalf** [comment] 2022-04-12 09:26
@cristianoccazinsp Did you have a chance to determine if the issue is fixed yet? Also please note [10.20.0-beta.4](https://www.npmjs.com/package/realm/v/10.20.0-beta.4) is now out.

**Comment by cristianoccazinsp** [comment] 2022-04-12 14:09
Hi @tomduncalf , I haven’t seen the issue with beta3 yet, although it’s been only a week since we released for iOS so we haven’t got so many testers yet.

I will look into beta4 when I have a chance, thanks for the reminder .

**Comment by tomduncalf** [comment] 2022-04-12 14:10
OK cool, thanks for the update, I can leave this open until you have more feedback!

**Comment by tomduncalf** [comment] 2022-05-20 08:45
Hi @cristianoccazinsp, I'm going to close this issue as I've not heard anything back. If you are still experiencing the issue, please feel free to re-open with more details. Thanks

**Closed by tomduncalf** 2022-05-20 08:45 UTC
Labels: Reproduction-Required, O-Community, hermes

**Comment by cristianoccazinsp** [comment] 2022-05-20 12:07
Hi @tomduncalf , thanks, I have not seen the error anymore, but I will let you know if it appears again.
