### ISSUE TITLE
App crashing in react-native 0.58.x

### ISSUE THREAD

**Issue by c081110653** [realm/realm-js#2261] opened 2019-03-01 08:56 UTC
## Goals

Development on react native project

## Actual Results

`SoLoader: couldn't find DSO to load: librealmreact.so caused by: dlopen failed: "/data/data/
xxxxx.xxxxx.xxxxx/lib-main/librealmreact.so" is 32-bit instead of 64-bit`
`E/AndroidRuntime: FATAL EXCEPTION: create_react_context`
`java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealmreact.so caused by: dlopen failed: "/data/data/xxxxx.xxxxx.xxxxx/lib-main/librealmreact.so" is 32-bit instead of 64-bit`

## Version of Realm and Tooling

- Realm JS SDK Version: 2.24.0
- React Native: 0.58.6
- Client OS & Version: Windows 10
- Testing Device and Android version: Samsung S9 with Android 9.0

**Comment by fealebenpae** [comment] 2019-03-01 14:55
Realm doesn't support 64bit Android devices with React Native yet. Please track https://github.com/realm/realm-js/issues/2221 for the progress of resolving that.

**Closed by fealebenpae** 2019-03-01 14:55 UTC
Labels: O:User

**Comment by AugustoAleGon** [comment] 2019-04-15 23:26
This is still an issue.

**Comment by Guilleanto** [comment] 2019-08-08 14:54
> This is still an issue. @AugustoAleGon 

https://github.com/realm/realm-js/releases/tag/v2.28.0

**Comment by mostafiz93** [comment] 2019-08-18 14:38
I'm also facing similar issue. In my case error is: 

` FATAL EXCEPTION: create_react_context
    Process: com.x.x, PID: 19173
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealmreact.so caused by: Didn't find class "io.realm.react.util.SSLHelper" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.x.x-EooDdHW0dESneU22oMVpFA==/base.apk"],nativeLibraryDirectories=[/data/app/com.x.x-EooDdHW0dESneU22oMVpFA==/lib/arm64, /data/app/com.x.x-EooDdHW0dESneU22oMVpFA==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)`

**Note that Realm now supports 64 bit architecture: https://github.com/realm/realm-js/releases/tag/v2.28.0**
