### ISSUE TITLE
Trouble query data when query condition has type number on Android

### ISSUE THREAD

**Issue by DuCaoTien** [realm/realm-js#3773] opened 2021-06-02 09:21 UTC
Hi guys! The realm library was so useful for our project. Appreciate your team efforts. 
According to what we found out. The feature query with number values did not require quotes (" ") to cover the value. But I don't know why when using the realm version 10.4.0. We can't query data as expected. Two points to note:
1. We didn't change any query statement or code on our project, only update the realm lib (10.2.0 -> 10.4.0).
2. The trouble is only on Android.
Right now, We resolved the trouble by adding quotes (" ") to cover the value like this and it worked:
timestamp >= 1622623523121 AND timestamp <= 162262370312 (not working)
![Screen Shot 2021-06-02 at 03 53 07](https://user-images.githubusercontent.com/26642281/120454166-414cf400-c359-11eb-8cd2-96e34d45108f.png)
timestamp >= "1622623523121" AND timestamp <= "162262370312" (worked)
![Screen Shot 2021-06-02 at 03 57 21](https://user-images.githubusercontent.com/26642281/120454188-47db6b80-c359-11eb-8e63-31fb2b826d35.png)
Questions:
I. Will there be any trouble if we change all our related codes (add  " " to cover the number value on statements query) to solve this problem?
II. Can you explain to me why there is such trouble? (The trouble is only on Android with version realm is 10.4.0. It worked fine on IOS)
Your supports were so helpful to our team. Thanks.

## Version of Realm and Tooling

- Realm JS SDK Version: 10.4.0
- React Native: 0.64.0
- Client OS & Version: macOS Catalina (10.15.7)
- Which debugger for React Native: None

**Comment by ironage** [comment] 2021-06-02 19:32
Hi @DuCaoTien, what is the Realm property type of `Reading.timestamp`? Is this actually a timestamp or is it an integer type or something else?

**Comment by DuCaoTien** [comment] 2021-06-03 02:01
Hi @ironage. Timestamp is integer type
<img width="606" alt="Screen Shot 2021-06-02 at 21 00 06" src="https://user-images.githubusercontent.com/26642281/120574871-ad753980-c3e5-11eb-9837-0a864a1c5ca0.png">

**Comment by kneth** [comment] 2021-06-03 09:18
@DuCaoTien Can you try the same query in Studio?

**Comment by DuCaoTien** [comment] 2021-06-03 10:00
Hi @kneth, It works fine when I try the same query in Studio both normal and add " " to cover the number value on statements query.
<img width="1218" alt="Screen Shot 2021-06-03 at 04 57 09" src="https://user-images.githubusercontent.com/26642281/120626743-94da4300-c428-11eb-8256-4cabd88d8d9d.png">
<img width="1223" alt="Screen Shot 2021-06-03 at 04 57 24" src="https://user-images.githubusercontent.com/26642281/120626772-9d327e00-c428-11eb-9b80-579c84c3424b.png">

**Comment by ironage** [comment] 2021-06-03 22:22
Thanks for the info @DuCaoTien, can you confirm if the Android device that is not working is a 32 bit? It looks like you discovered a regression introduced in our new query parser which affects integer constants which use more than 32 bits of storage. It should be addressed by https://github.com/realm/realm-core/pull/4736. But in the meantime, I would recommend passing argument into the query string with argument substitution instead of trying to do the formatting yourself. That would look like this:
`this.realm?.objects('Reading').filtered("timestamp >= $0 AND timestamp <= $1", now - SYNC_INTERVAL * 1000, now)`

**Comment by DuCaoTien** [comment] 2021-06-04 04:18
Great. Your idea seems to be correct. I'm working on an emulator 32-bit. I tried to change to a 64-bit and it worked with the old query statements so there is more evidence to confirm that this problem only occurs on 32-bit boards. 
I also tried to query with your recommend this format and it worked fine both on 32-bit and 64-bit emulators. Thanks for your help. @ironage

**Comment by ironage** [comment] 2021-06-04 17:39
Thanks for confirming the 32 bit issue @DuCaoTien!

**Closed** 2021-07-03 16:52 UTC
Labels: O-Community
