### ISSUE TITLE
How to build realm application and how to run the application from build folder

### ISSUE THREAD

**Issue by SatishReddy006** [realm/realm-js#3520] opened 2021-01-24 05:47 UTC
I build realm application and running fine in local. Now I would like to deploy to production. How to build the application using script and how to run the application that was build

- Realm JS SDK Version: 6.1.5
- Node or React Native: 12.18.1
- Client OS & Version: Windows 10

**Comment by kraenhansen** [comment] 2021-01-26 09:46
Hi there 🙂  Thanks for reaching out.

> How to build the application using script and how to run the application that was build

The same way that you would build and run any React Native application.

For reference, this is the React Native guide on preparing your app to be published on the Google Play store: https://reactnative.dev/docs/signed-apk-android

For general questions about MongoDB Realm I suggest posting in the MongoDB community forum: https://developer.mongodb.com/community/forums/tags/c/realm-sdks/58/react-native (using the Realm SDK category and `react-native` tag. And since this is more a question than an actual bug report, I'll close it for now.

If you're having issues building for a specific platform (Android / iOS), please reopen this or create another issue following the template and remember to add details around  the steps to reproduce and any errors you might be seeing in the process.

**Closed by kraenhansen** 2021-01-26 09:46 UTC
Labels: O-Community, T-Help

**Comment by SatishReddy006** [comment] 2021-01-26 19:20
I build realm application using express js and running fine in local. Now I would like to deploy to production. How to build the application into windows executable for production using script and to build as executable use compiled/build files

- Realm JS SDK Version: 6.1.5
- Node or React Native: 12.18.1
- Client OS & Version: Windows 10

**Comment by kraenhansen** [comment] 2021-01-27 09:55
@SatishReddy006

Since you're using Express.js I suppose you're writing some sort of web service, right?
In general you wouldn't need to build a windows executable, but simply run the JavaScript using the Node.js interpreter on the machine you're targeting to run this.

There are multiple ways to deploy something like this, more than I can reasonably cover in a comment here.

I encurage you to create a post on our community forums https://developer.mongodb.com/community/forums/ or StackOverflow. Perhaps you can get started from something like this (if you're certain that you want to deploy on Windows): https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?pivots=platform-windows

**Comment by SatishReddy006** [comment] 2021-01-27 20:22
we would like to deploy webservice in client system, so we can't share source code. Need to build the source code compiled/minifued JS files then use the build files in executable. This is our requirement

**Comment by kraenhansen** [comment] 2021-01-27 20:37
Again, StackOverflow is probably your best bet.
How to distribute a Node.js application as an executable has very little to do with the Realm JS project 🙂 
Having said that, are you aware of the Electron project? https://www.electronjs.org/ That's probably your best bet.

**Comment by SatishReddy006** [comment] 2021-01-27 20:49
I have already package UI electron application, but express JS application is different from electron + react application
