### ISSUE TITLE
Realm is already in a write transaction inside live collection listener!?

### ISSUE THREAD

**Issue by sheshavpd** [realm/realm-js#1188] opened 2017-08-05 10:30 UTC
Hello,
I'm using the latest realm js lib for my react native app. Thanks for the great library.
When` realm.write` emits a notification, my collection listener is catching it as expected.
I'm changing some values of other collection inside listener again.
But, in one of my Android device which is super fast(OnePlus 5) there's no error.
But in my other device( LETV le2), which is considerably slower than Oneplus, the error `Realm is already in a write transaction triggers up`. Am I missing something?

**Comment by kneth** [comment] 2017-08-07 08:36
@sheshavpd Thanks for reporting it. It is a bit hard to say anything definitely without seeing the code. It is possible for you to share it (or part of it)?

**Comment by sheshavpd** [comment] 2017-08-07 14:28
@kneth, hello, let me explain this as clearly as I can.
As #927 suggests, there's a bug where the notification for current transaction is triggered when the next realm transaction is called.
I've a `collection of users` and `list of messages` affiliated to that user.
When the message is received from internet, I need to marked it as `read` when user is online and has seen it.
So this is what I'm doing right now:
```
function onMessageReceived(userId,message)
{
   let user=realm.objects("User").filtered("id==$0",userId);
   realm.write(()=>{
       user.messages.push(message);
  });
   //#927 bug's workaround
   realm.write(()=>{});
}
```
and in the below snippet, I've attached a listener to messages of user in a component:
`let messages=realm.objects("User").filtered("id==$0",userId)[0].messages;
messages.addListenet(function(messages,changes){
   //Some code to push message to listview here on new insertions
   .......
  //End of UI tweeks
  //Here I showed the message and should mark it as delivered
   changes.insertions.forEach(function(index){
      if(userInThisScreen)
      {
        //Here is where I'm getting the error
        realm.write(()=>{
         messages[index].seen_time=Date.now();
        });
        //#927 bug's workaround
        realm.write(()=>{});
      }
   });
});
`
So, this code snippet is not producing error for OnePlus5, which is apparently very fast. But when it's run(fresh installation) on Le2, it says realm is already in a write transaction in the line I've shown above.

This happens to me whenever I need to change the Realm data inside listeners. Here's what I use as workaround:

`let messages=realm.objects("User").filtered("id==$0",userId)[0].messages;
messages.addListenet(function(messages,changes){
   //Some code to push message to listview here on new insertions
   .......
  //End of UI tweeks
  //Here I showed the message and should mark it as delivered
   changes.insertions.forEach(function(index){
      if(userInThisScreen)
      {
        //This is my workaround
       setTimeout(function(){
           //Here is where I'm getting the error
          realm.write(()=>{
           messages[index].seen_time=Date.now();
          });
          //#927 bug's workaround
          realm.write(()=>{});
       },10);
      }
   });
});
`
It works when placed `inside setTimeout` for my Le2 device. This makes me feel it has got something to do with time, since with 10ms delay, it works on Le2. But I'm scared how it might run on different devices.
Please assist me if I'm going wrong, which I'm hopefully not. Thanks.

**Comment by kneth** [comment] 2017-08-10 14:22
It might be a help if we expose the method or property similar to https://realm.io/docs/objc/2.9.1/api/Classes/RLMRealm.html#/c:objc(cs)RLMRealm(py)inWriteTransaction.

Our other products suggest that you use such a method/property in the situation as ours. See 
 https://realm.io/docs/objc/latest/#how-notifications-are-delivered and https://realm.io/docs/java/latest/#how-notifications-are-delivered.

**Comment by sheshavpd** [comment] 2017-08-11 07:36
Thanks for the links, @kneth. I think this must we well documented in Realm Javascript documentation.

> Our other products suggest that you use such a method/property in the situation as ours. See
> https://realm.io/docs/objc/latest/#how-notifications-are-delivered and https://realm.io/docs/java/latest/#how-notifications-are-delivered.

1) When they say "When Realm advances to latest version", do they mean, when realm is done processing all the prior transactions? I'm not clear :/ Can you please help me understanding why notification listeners are called within the scope of write transactions?

2) There are no methods to check if Realm is in already in a write transaction. Since this is necessary, I think this must be exposed.

3) What workaround do you suggest, since this is not exposed, for now?

**Comment by kneth** [comment] 2017-08-11 08:58
Yes, we definitely need to improve the documentation 😅 

ad 1. Yesterday I tried to write a test similar to your code. I got another error, namely that I used all the stack space. The reason was that doing a write in a listener will trigger a call to the listener. 

ad 2. Realm JS is a bit behind Realm Cocoa and Java on features (JS is a much younger product).

ad 3. No workaround, and it shows that we should get 2. done soon :smile:

**Comment by sheshavpd** [comment] 2017-08-11 09:11
I see people are really frustrated with Chrome debug issues, issues that arise with time etc. and are finding alternatives to Realm.
React native is growing exponentially, and it's time realm-js to keep up the pace too, because javascript is making its remark in the field of full stack development.
Are there any ideas to speed-up realm js development process?
Because, I want realm to lead the js-database market too. It's an amazing product.

Hoping to get this(isInWrite) feature as soon as possible.
Thanks.

**Comment by bmunkholm** [comment] 2017-08-11 13:15
@sheshavpd It's great to hear you want the realm-js project to succeed - thanks to the support!
We have just moved @kneth from the Java team to the JS team to help out. I'm sure he will do a great job, but we sure could use more help. This is an open source project, so if you have ideas on how to get the community to actively help out or would like to contribute yourself - that would be awesome :-)
As an example, adding the in-transaction feature should be pretty simple. But perhaps @kneth can do that and use it as a showcase for how to add simple features in case we can inspire others to help out.

**Comment by kneth** [comment] 2017-08-28 08:19
We have merged `is_in_transaction` but haven't released it yet.

**Closed by kneth** 2017-08-28 08:19 UTC
Labels: T:Help

**Comment by sheshavpd** [comment] 2017-08-28 09:13
Thanks @kneth :)

**Comment by thatjuan** [comment] 2018-01-21 04:46
This is what I've been doing since isInTransaction was added.

```
export function safeAddListener( results, callback ){

    if( !results || !results.addListener ){
        console.log( "⚠️ safeAddListener called for non addListener compliant object" ); // todo: check type instead?
        return;
    }

    if( realm.isInTransaction ){

        setTimeout( ()=>{
            safeAddListener( results, callback );
        }, 200 );

    } else {

        results.addListener( callback );

    }

}
```

**Comment by thatjuan** [comment] 2018-01-21 04:50
This is what I've been doing since isInTransaction was added. Is it possible to do away with the timeout?

```
export function safeAddListener( results, callback ){

    if( !results || !results.addListener ){
        console.log( "⚠️ safeAddListener called for non addListener-compliant object" );
        return;
    }

    if( realm.isInTransaction ){

        setTimeout( ()=>{
            safeAddListener( results, callback );
        }, 200 );

    } else {

        results.addListener( callback );

    }

}
```

**Comment by kneth** [comment] 2018-01-22 09:02
@thatjuan I don't see the need to check `isInTransaction` when adding a listener. `isInTransaction` is primarily useful when you do write transactions in a listener.

**Comment by thatjuan** [comment] 2018-01-23 00:58
@kneth I was getting a crash when calling `addListener()` while the realm was in a transaction. This fixed it.

**Comment by kneth** [comment] 2018-01-23 08:01
@thatjuan Thanks for sharing the observation. You are more than welcome to create a new issue/bug report.

**Comment by thatjuan** [comment] 2018-01-24 19:46
@kneth I was trying to set up a more constrained case to reproduce it, but ran out of time. I will try to complete it soon. thanks!

**Comment by ZComwiz** [comment] 2021-01-24 01:08
> @kneth I was getting a crash when calling `addListener()` while the realm was in a transaction. This fixed it.

@thatjuan — what was your fix?
