### ISSUE TITLE
[v3.7.0-alpha.2] CreatedAt must be of type 'date', got 'object'

### ISSUE THREAD

**Issue by bimusiek** [realm/realm-js#2755] opened 2020-03-17 19:08 UTC
## Goals
Save model on node server with createdAt being `new Date()`

## Expected Results
Model is saved

## Actual Results
Got error
```
Error: LicenseRequestModel.createdAt must be of type 'date', got 'object' (Tue Mar 17 2020 20:03:14 GMT+0100 (Central European Standard Time))
```

## Steps to Reproduce
Try to create new model on node server with `new Date()` 

## Code Sample

```
  static create<T>(this: RealmModelThis<T>, realm: Realm, props: any): T {
    return realm.create<T>(
      this.schema.name,
      {
        ...props,
        createdAt: new Date(),
        modifiedAt: new Date()
      },
      Realm.UpdateMode.All
    );
  }
```

## Version of Realm and Tooling

- Realm JS SDK Version: v3.7.0-alpha.2
- Node or React Native: Node v13.3.0
- Client OS & Version: jest

**Comment by bimusiek** [comment] 2020-03-17 19:45
Workaround for now was to use `int` and store date as a number. 😢

**Comment by kneth** [comment] 2020-03-18 08:15
@bimusiek Could you post the schema?

**Comment by kneth** [comment] 2020-03-18 08:49
@bimusiek We have release v5.0.0. Please try to upgrade.

**Comment by bimusiek** [comment] 2020-03-18 12:25
I will check, thanks.

And do you know @kneth when are your team planning to release 4.0.0 beta with Node 13 support? 3.7.0 seems to work with newest node already.

**Comment by bimusiek** [comment] 2020-03-18 23:54
@kneth With 5.0.0 there is the same issue.
```Error: LicenseRequestModel.subscriptionExpiresAt must be of type 'date?', got 'object' (Thu Mar 12 2020 11:48:52 GMT+0100 (Central European Standard Time))``` 

Schema:
```
  public static schema = {
    ...BaseModel.schema,
    name: 'LicenseRequestModel',
    primaryKey: 'licenseId',
    properties: {
      ...BaseModel.schema.properties,
      licenseId: 'string',
      token: { type: 'string', default: '' },
      email: { type: 'string', default: '' },
      status: { type: 'int', default: LicenseRequestStatus.INITIALIZED },
      type: { type: 'int', default: LicenseRequestType.WEB },
      hasSubscription: { type: 'bool', default: false },
      subscriptionExpiresAt: 'date?'
    }
  };

export abstract class BaseModel {
  public static schema = {
    properties: {
      createdAt: 'int',
      modifiedAt: 'int'
    }
  };

```

**Comment by kneth** [comment] 2020-03-19 08:44
@bimusiek Thank you for the update. Could you try `subscriptionExpiresAt: { type: 'date', optional: true}` instead. If that works, we have a bug in the schema parser, and if it does, the bug is in the object creation code.

**Comment by bimusiek** [comment] 2020-03-19 13:08
Unfortunately, the same issue.

**Comment by xmedeko** [comment] 2020-03-24 07:19
We use JS, Realm 5 and `date`, `date?` are ok. E.g.
```js
const schema = [
    {
        name: "Something",
        properties: {
            data: "string",
            createdOn: "date",
            changedOn: "date?"
        }
    }];
   Realm.open(schema);
```

**Comment by kneth** [comment] 2020-03-26 13:55
It looks like the issue is how we interact with classes rather than a `Date` issue. @bimusiek Can you try to write your schema as suggested in https://github.com/realm/realm-js/issues/2755#issuecomment-603070264

**Comment by bimusiek** [comment] 2020-04-03 08:14
@kneth The schema I pass to Realm constructor is 
```ts
  const realmConfig = user.createConfiguration({
    schema,
    schemaVersion,
    sync: {
      url: `~/app`,
      fullSynchronization: true
    }
  });
  const realm = new Realm(realmConfig);
```
where schema is:
```ts
export const schema = [
  ConfigRealmModel.schema,
  CollectionModel.schema,
  CollectionItemModel.schema,
  ImporterAuthenticationModel.schema,
  TransferModel.schema,
  TransferCollectionModel.schema,
  TransferCollectionItemModel.schema,
  LicenseRequestModel.schema
];
export const schemaVersion = 1;
```

So as I understand, it is done in the same manner by passing JS object directly. 
Also, it worked with 4.0.0 alpha.

I forgot to mention that I use in memory realm for Jest tests, maybe there is an issue?

**Comment by ioveracker** [comment] 2020-04-08 17:56
> I forgot to mention that I use in memory realm for Jest tests, maybe there is an issue?

I'm also running into this issue only while using an in-memory Realm for Jest tests.

**Comment by mtford90** [comment] 2020-04-10 11:42
Facing this issue myself with jest tests using inMemory Realm.

Works fine on 3.6.5

**Comment by d3v2a** [comment] 2020-04-20 23:45
I'm also running into this issue only in jest test (in-memory or not)

the same code directly in node work fine 

to get it working in jest:
`
new Date().toISOString();
`

**Comment by thomasarogers** [comment] 2020-04-22 08:44
Same having this issue in Jest only when run inmemory

**Comment by bimusiek** [comment] 2020-04-29 16:52
@kneth I would like to propose changing label from `T-Help` to `T-Bug`

**Comment by aj3x** [comment] 2020-07-08 16:40
This may be related, `obj.createdAt instanceof Date` returns false. When using Realm 3.6.5 this returned true. Debugging reveals all the functions of Date are there.

**Comment by martnst** [comment] 2020-07-11 19:40
I am also facing this issue with Realm 5.0.5 and jest 24.9.0

**Comment by bharadwajagali** [comment] 2020-08-28 14:21
Hi @kneth any update on the above issue, I am also facing same issue with below configuration.

Works fine on 3.6.5.

- Realm 6.0.4 + Jest 25.1.0
- Realm 6.0.4 + Jest 26.3.0
- React-native version 0.61.2
- Node js Version 10.18.0

**Comment by kneth** [comment] 2020-08-31 08:43
@bharadwajagali No real progress. Mostly because we are migrating to [MongoDB Realm Cloud](https://docs.mongodb.com/realm/) as our future platform.

**Comment by blagoev** [comment] 2020-09-17 10:55
this was fixed and will be part or our next release

**Closed by blagoev** 2020-09-17 10:55 UTC
Labels: O-Community, T-Bug

**Comment by McFlyssss** [comment] 2020-12-09 14:33
Hey guys, I'm facing the same issue with Realm 6.1.5 when running on Jest. This was supposed to be fixed, right @blagoev?


Thanks in advance!

**Comment by kneth** [comment] 2020-12-09 15:22
@McFlyssss Yes, it should be fixed.

Could you try to build from source: `npm install --build-from-source --save realm@6.1.5`

Currently we support node v10 which has end-of-life late April next year. After that we can bump the N-API version to 5. But building from source using node v12 (or later), you will N-API version 5 (or later), and my hypothesis is that another code plan is exercised with version 5 (or later).

**Comment by McFlyssss** [comment] 2020-12-14 11:25
Dear @kneth ,

Thank you so much for your answer. Sorry I could not get back to it earlier.
Unfortunately, this raises the same exception. Any other idea?

**Comment by kneth** [comment] 2020-12-14 11:53
@McFlyssss It might be related to Jest (see https://github.com/facebook/jest/issues/2549) and unfortunately I don't have a simple solution (but it might be worth to read https://github.com/realm/realm-js/issues/2490#issuecomment-555994222).

**Comment by McFlyssss** [comment] 2020-12-15 09:10
FYI I tried with v10 and having the exact same problem. I'll take a look at those links you shared @kneth

**Comment by kneth** [comment] 2020-12-16 12:03
@McFlyssss When you have had time to investigate, you are welcome to open a new issue with your observations.

**Comment by McFlyssss** [comment] 2020-12-22 14:21
So finally got it working. 
Updating the node version made it work. I was running on 10.16.3 and now I'm at 10.22.1.
It seems there are some changes in regards to dates on 10.17: https://github.com/nodejs/node/pull/25917
