### ISSUE TITLE
Change stream times out after a few minutes

### ISSUE THREAD

**Issue by klaussner** [realm/realm-js#3489] opened 2020-12-31 11:23 UTC
## Goals

I would like to open a change stream to get notified of changes to a collection.

## Expected Results

The client receives changes until the change stream is closed.

## Actual Results

The change stream times out after a few minutes (according to the Realm logs, the stream stays open for about 90 to 240 seconds) and receives no more change events. The following error message is logged in the browser console.

```
Uncaught (in promise) WatchError: execution time limit exceeded
    WatchError https://unpkg.com/realm-web@1.1.0/dist/bundle.iife.js:9540
    feedSse https://unpkg.com/realm-web@1.1.0/dist/bundle.iife.js:9686
    feedLine https://unpkg.com/realm-web@1.1.0/dist/bundle.iife.js:9611
    advanceBufferState https://unpkg.com/realm-web@1.1.0/dist/bundle.iife.js:9746
    feedBuffer https://unpkg.com/realm-web@1.1.0/dist/bundle.iife.js:9590
    watch https://unpkg.com/realm-web@1.1.0/dist/bundle.iife.js:9916
```

## Steps to Reproduce

1. Open a change stream for a collection.
2. Wait for two to four minutes.
3. Insert or update a document in the collection to trigger a change event.
4. The client doesn't receive the event and the error message appears in the console.

## Code Sample

```js
async function reproduction() {
  const app = new Realm.App("<app id>");
  await app.logIn(Realm.Credentials.anonymous());

  const collection = app.currentUser
    .mongoClient("mongodb-atlas")
    .db("<database>")
    .collection("<collection>")

  for await (const change of collection.watch()) {
    console.log(change);
  }
}
```

## Version of Realm and Tooling

- Realm JS SDK Version: 1.1.0
- Node or React Native: Browser
- Client OS & Version: Linux, Firefox 85

**Comment by kneth** [comment] 2021-01-04 11:33
I believe it is a duplicate of https://github.com/realm/realm-js/issues/3283

**Comment by klaussner** [comment] 2021-01-05 19:01
@kneth The issues look similar but the `WatchError` messages are different (`execution time limit exceeded` in this issue and `rule with id="000000000000000000000000" no longer exists on mongodb service, closing watch stream` in #3283). According to [this comment](https://github.com/realm/realm-js/issues/3283#issuecomment-733826164) in the other issue, there is a server-side bug if Sync is enabled but I have Sync disabled in my project and still get the timeout error.

Is there anything I can do to help? I'd be happy to put together a small reproduction repository or Realm project if that helps with debugging.

**Comment by versoworks** [comment] 2021-02-17 20:42
We're experiencing this exact same issue using the latest version of realm-web. Any fixes coming @kraenhansen ?

**Comment by kraenhansen** [comment] 2021-02-18 10:31
@versoworks we're still missing a reproduction case for this.

I retested with an app on CodeSandbox (https://codesandbox.io/s/realm-watch-test-9c8bw) but I cannot reproduce the error above. I would appreciate any steps or details that might help me reproduce this: I.e. browser name, version and MongoDB Realm rules used, would be great.

**Comment by klaussner** [comment] 2021-02-18 17:11
@kraenhansen Thank you for trying to reproduce the issue! I looked into it a little more and found out what causes the error. The change stream times out if a function is called in an `apply_when` expression. To reproduce, create a function named `testFunction` that returns `true`:
```
exports = function () {
  return true;
};
```
Then add this `apply_when` expression for the `runs` collection:
```
{
  "%%true": {
    "%function": {
      "name": "testFunction"
    }
  }
}
```
I tested it with your CodeSandbox and the change stream stops with the `execution time limit exceeded` error after a minute or two.

**Comment by rvanmil** [comment] 2021-02-25 20:03
Can confirm this issue, we have seen this happen as well. I've taken the liberty to write a small app to reproduce the issue over here: https://realm-change-stream-test.netlify.app

**Comment by nverba** [comment] 2021-05-17 14:54
@kraenhansen Now that there is a reproduction case for this, is there any more info?   

Would it be practical to try and handle the error in the client and resume watching in the meantime?

**Comment by kraenhansen** [comment] 2021-05-18 07:11
@nverba & @rvanmil since the issue is reproduced by changing a server-side configuration this is most likely not an issue with the Realm JS / Web SDKs. That being said, I've relayed this as a question internally and I'll update this issue when I get more information.

You might want to ask on the community forums as well (linking to this issue) if you want to speed things up and get other members of the community a chance to tip in: https://community.mongodb.com/

**Closed** 2021-05-18 07:11 UTC
Labels: O-Community

**Comment by brycedewitt** [comment] 2022-02-11 21:16
@kraenhansen Do you have any updates to this? We're still unable to open a stream using `realm-web` for more than a couple minutes.

**Comment by kraenhansen** [comment] 2022-02-12 09:44
@brycedewitt are you using a function as @rvanmil and @klaussner above? Would you mind creating a new issue with a minimal app reproducing the issue?
