### ISSUE TITLE
Missing Realm constructor after codepush update

### ISSUE THREAD

**Issue by tuandinh0801** [realm/realm-js#4422] opened 2022-03-16 06:02 UTC
### Description

I use hermes branch combine with codepush. After installing codepush and restart, the error occurs Missing Realm constructor. I tried to update codepush in the next restart but the issue still happens.
However, the issue can be resolved after couple of times retry (restart the app), seems like there is a race condition on initial JS bundle between Realm and codepush update.

### Stacktrace & log output

```shell
Non-fatal Exception: JavaScriptError
Missing Realm constructor. Did you run "pod install"? Please see https://docs.mongodb.com/realm/sdk/react-native/install/ for troubleshooting
0  ???                            0x0 anonymous + 1878 (main.jsbundle:1878:387:1878)
1  ???                            0x0 h + 2 (main.jsbundle:2:1586:2)
2  ???                            0x0 d + 2 (main.jsbundle:2:1029:2)
3  ???                            0x0 o + 2 (main.jsbundle:2:497:2)
4  ???                            0x0 anonymous + 3307 (main.jsbundle:3307:148:3307)
5  ???                            0x0 h + 2 (main.jsbundle:2:1586:2)
6  ???                            0x0 d + 2 (main.jsbundle:2:1029:2)
7  ???                            0x0 o + 2 (main.jsbundle:2:497:2)
8  ???                            0x0 anonymous + 3306 (main.jsbundle:3306:148:3306)
9  ???                            0x0 h + 2 (main.jsbundle:2:1586:2)
10 ???                            0x0 d + 2 (main.jsbundle:2:1029:2)
11 ???                            0x0 o + 2 (main.jsbundle:2:497:2)
12 ???                            0x0 anonymous + 3305 (main.jsbundle:3305:711:3305)
13 ???                            0x0 h + 2 (main.jsbundle:2:1586:2)
14 ???                            0x0 d + 2 (main.jsbundle:2:1029:2)
15 ???                            0x0 o + 2 (main.jsbundle:2:497:2)
16 ???                            0x0 anonymous + 3281 (main.jsbundle:3281:852:3281)
17 ???                            0x0 h + 2 (main.jsbundle:2:1586:2)
18 ???                            0x0 d + 2 (main.jsbundle:2:1029:2)
19 ???                            0x0 o + 2 (main.jsbundle:2:497:2)
20 ???                            0x0 anonymous + 3280 (main.jsbundle:3280:692:3280)
21 ???                            0x0 h + 2 (main.jsbundle:2:1586:2)
22 ???                            0x0 d + 2 (main.jsbundle:2:1029:2)
23 ???                            0x0 o + 2 (main.jsbundle:2:497:2)
24 ???                            0x0 anonymous + 3222 (main.jsbundle:3222:337:3222)
25 ???                            0x0 h + 2 (main.jsbundle:2:1586:2)
26 ???                            0x0 d + 2 (main.jsbundle:2:1029:2)
27 ???                            0x0 o + 2 (main.jsbundle:2:497:2)
28 ???                            0x0 anonymous + 2999 (main.jsbundle:2999:420:2999)
29 ???                            0x0 h + 2 (main.jsbundle:2:1586:2)
30 ???                            0x0 d + 2 (main.jsbundle:2:1029:2)
31 ???                            0x0 o + 2 (main.jsbundle:2:497:2)
32 ???                            0x0 anonymous + 2998 (main.jsbundle:2998:169:2998)
33 ???                            0x0 h + 2 (main.jsbundle:2:1586:2)
34 ???                            0x0 d + 2 (main.jsbundle:2:1029:2)
35 ???                            0x0 o + 2 (main.jsbundle:2:497:2)
36 ???                            0x0 anonymous + 2589 (main.jsbundle:2589:631:2589)
37 ???                            0x0 h + 2 (main.jsbundle:2:1586:2)
38 ???                            0x0 d + 2 (main.jsbundle:2:1029:2)
39 ???                            0x0 o + 2 (main.jsbundle:2:497:2)
40 ???                            0x0 anonymous + 717 (main.jsbundle:717:693:717)
41 ???                            0x0 h + 2 (main.jsbundle:2:1586:2)
42 ???                            0x0 d + 2 (main.jsbundle:2:1029:2)
43 ???                            0x0 o + 2 (main.jsbundle:2:497:2)
44 ???                            0x0 anonymous + 6 (main.jsbundle:6:109:6)
45 ???                            0x0 h + 2 (main.jsbundle:2:1586:2)
46 ???                            0x0 d + 2 (main.jsbundle:2:959:2)
47 ???                            0x0 o + 2 (main.jsbundle:2:497:2)
48 ???                            0x0 global + 3781 (main.jsbundle:3781:4:3781)
```

### Can you reproduce a bug?

Yes, sometimes

### Reproduction Steps

- Send codepush update to the app
- Install then restart through install(codePush.InstallMode.IMMEDIATELY) or install(codePush.InstallMode.ON_NEXT_RESTART)

### Version

10.20.0-beta.2

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 15.3.1/15.4.0

**Comment by kneth** [comment] 2022-03-18 12:37
We haven't tested 10.20.0-beta.2 with CodePush. Are you enable to

1. Make an app work with CodePush and Hermes (but no Realm)?
2. Make an app work with CodePush, Hermes and Realm (using v10.13.0 and JSC)?

**Comment by tuandinh0801** [comment] 2022-03-30 10:17
> We haven't tested 10.20.0-beta.2 with CodePush. Are you enable to
> 
> 1. Make an app work with CodePush and Hermes (but no Realm)?
> 2. Make an app work with CodePush, Hermes and Realm (using v10.13.0 and JSC)?

1. Make an app work with CodePush and Hermes (but no Realm)? Works fine
2. Make an app work with CodePush, Hermes and Realm (using v10.13.0 and JSC)? Same issue

I just found a workaround solution. Idea is that lazy load the App to avoid Realm import before the bundle get updated

```javascript
const RootApp = () => {
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    setIsLoading(false)
  }, [])

  if (isLoading) {
    return <LoadingApp />
  }

  const App = require('./src/App').default

  return <App />
}

const codePushOptions = { checkFrequency: codePush.CheckFrequency.MANUAL }
const CodePushedApp = codePush(codePushOptions)(RootApp)

AppRegistry.registerComponent(appName, () => CodePushedApp)
```

**Comment by tomduncalf** [comment] 2022-04-12 13:27
Hi @tuandinh0801, I've been able to reproduce this error (just adding Codepush to project was enough, I didn't need to trigger an update).

I will create an issue for us to investigate what is happening here. I'm glad you have a workaround for now!

**Comment by tomduncalf** [comment] 2022-04-12 14:20
Sorry, please ignore my previous message – I thought I had been able to reproduce the issue, but I had actually made a typo in my code!

I created a simple test app using `realm@10.20.0-beta.4`:

```js
import React, {useState} from 'react';
import {SafeAreaView, Text, Pressable} from 'react-native';

import codePush from 'react-native-code-push';

import Realm from 'realm';

const TestSchema = {
  name: 'Test',
  properties: {
    name: 'string',
  },
};

const realm = new Realm({
  schema: [TestSchema],
});

const App = () => {
  const [object, setObject] = useState(undefined);

  realm.addListener('change', () => {
    const objects = realm.objects('Test');
    setObject(objects[objects.length - 1]);
  });

  const handleWrite = () => {
    realm.write(() => {
      realm.create('Test', {name: Math.random().toString()});
    });
  };

  return (
    <SafeAreaView>
      {object && <Text>{object.name}</Text>}

      <Pressable
        onPress={handleWrite}
        style={{padding: 20, backgroundColor: 'yellow'}}>
        <Text>Create one</Text>
      </Pressable>
    </SafeAreaView>
  );
};

export default codePush({
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
  installMode: codePush.InstallMode.IMMEDIATE,
})(App);
```

and set up CodePush, and I was able to push a few updates without any issues. I wonder if there's something different about your project, or if `beta4` has maybe fixed the issue. Could you please try the newest Realm beta and see if it helps?

**Comment by takameyer** [comment] 2022-06-07 07:06
Closing since we cannot reproduce this.  Feel free to reopen when you can provide a reliable way to reproduce this.

**Closed by takameyer** 2022-06-07 07:06 UTC
Labels: O-Community, More-information-needed, hermes
