### ISSUE TITLE
 ERROR  TypeError: Super expression must either be null or a function 

### ISSUE THREAD

**Issue by elsyslab-ark** [realm/realm-js#5167] opened 2022-12-07 16:52 UTC
### How frequently does the bug occur?

All the time

### Description

I am facing this issue while I try to set up react-realm with the latest RN project.

```
> ERROR  TypeError: Super expression must either be null or a function 
>  ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[1], "./models").TaskRealmContext')

```

### Stacktrace & log output

```shell
I am also facing this issue



> ERROR  TypeError: Super expression must either be null or a function 
>  ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[1], "./models").TaskRealmContext')



**Package Versions:**


  "dependencies": {
    "@realm/react": "^0.4.1",
    "react": "18.1.0",
    "react-native": "0.70.6",
    "realm": "^11.3.1"
  },
```

**Code Snippet:**
```

import {createRealmContext} from '@realm/react';

// This JS version of the Task model shows how to create Realm objects by
// defining a schema on the class, which is required if your project does not
// use TypeScript. If you are using TypeScript, we recommend using
// `@realm/babel-plugin` (https://github.com/realm/realm-js/blob/master/packages/babel-plugin/),
// which allows you to define your models using TypeScript syntax.
//
// See `Task.ts` in the Realm example app for an example of using the plugin.

import Realm from 'realm';

export class Task extends Realm.Object {
  constructor(realm, description, userId) {
    super(realm, {description, userId: userId || '_SYNC_DISABLED_'});
  }

  // To use a class as a Realm object type in JS, define the object schema on the static property "schema".
  static schema = {
    name: 'Task',
    primaryKey: '_id',
    properties: {
      _id: {type: 'objectId', default: () => new Realm.BSON.ObjectId()},
      description: 'string',
      isComplete: {type: 'bool', default: false},
      createdAt: {type: 'date', default: () => new Date()},
      userId: 'string',
    },
  };
}
export const TaskRealmContext = createRealmContext({
  schema: [Task],
});
```

```
import {View, Text} from 'react-native';
import {Realm, createRealmContext} from '@realm/react';
import {TaskRealmContext} from './models';

const App = () => {
  const {RealmProvider} = TaskRealmContext;

  return (
    <RealmProvider>
      <View>
        <Text>Hello</Text>
      </View>
    </RealmProvider>
  );
};

export default App;

```

```
project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
]
```
```


### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Just Try to setup react-realm on a new RN

### Version

0.4.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 12

### Build environment

Which debugger for React Native: ..


### Cocoapods version

_No response_

**Comment by kneth** [comment] 2022-12-08 12:28
You might need `default` when exporting `TaskRealmContext`.

**Comment by takameyer** [comment] 2023-01-03 08:35
@elsyslab-ark Thanks for submitting this issue.  I unfortunately cannot reproduce this.  The code appears to be taken from [our templates](https://github.com/realm/realm-js#template-apps).  Can you try one of those out and see if you can still reproduce the issue?

**Comment by avinashsahoo** [comment] 2023-01-05 18:41
I've update react-native version to 0.71. getting same issue.

E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
com.facebook.react.common.JavascriptException: TypeError: Super expression must either be null or a function, js engine: hermes

**Comment by takameyer** [comment] 2023-01-09 12:35
@avinashsahoo Do you get this issue using our templates?  The current release of Realm-JS does not support RN 0.71.

**Comment by kneth** [comment] 2023-01-25 10:20
I am closing the issue due to no reply back. Please comment and reopen the issue if needed.

**Closed by kneth** 2023-01-25 10:20 UTC
Labels: T-Bug, O-Community, Waiting-For-Reporter

**Comment by sootood** [comment] 2023-06-13 10:56
same issue when update react-native from 0.69.3 to 0.71.10
