### ISSUE TITLE
Object.values on realm results always returns [] when not attached to a debugger

### ISSUE THREAD

**Issue by Kdoherty11** [realm/realm-js#1230] opened 2017-08-18 21:44 UTC
## Goals / Expected Results

I would like realm to work normally while **not** connected to a remote debugger.

## Actual Results

https://youtu.be/0NImX4RWXDM

While attached to a debugger, realm works as expected. When it is not attached, nothing is saved to realm. I am also having a hard time debugging this issue because, as noted, it doesn't happen while attached to a debugger.

Note: I have followed the steps described in the documentation for how to handle this error. I have also looked at other issues and haven't seen anything related to the debugger being active/inactive.

## Steps to Reproduce

I'm not sure how to reproduce this for everybody but it is consistently reproducible for me by:

1) turning on the debugger and seeing that realm works normally
2) turn on the debugger and see that realm is not storing or retrieving any results
3) turn debugger back on and works as expected

## Code Sample

https://github.com/Kdoherty11/realm-test

## Version of Realm and Tooling

- Realm JS SDK Version: 1.10.2
- React Native: 0.47.1
- Client OS & Version: iOS 10.3
- Which debugger for React Native: Chrome

**Comment by kneth** [comment] 2017-08-21 07:40
@Kdoherty11 Thanks for reporting. Did you try to `react-native link realm` as suggested in https://realm.io/docs/javascript/latest/#missing-realm-constructor?

**Comment by Kdoherty11** [comment] 2017-08-22 15:27
@kneth I created a new project/repo and was able to reproduce the issue. I also created a youtube video showing the problem.

Git Repo:
https://github.com/Kdoherty11/realm-test

Issue Demo:
https://youtu.be/0NImX4RWXDM

**Comment by Kdoherty11** [comment] 2017-08-23 05:54
I found the issue. `Object.values(results)` always returns `[]` when not attached to a debugger. If replaced with `Object.keys(results).map(key => deserialize(results[key]))` it works as expected.

**Comment by kneth** [comment] 2017-08-23 08:12
@Kdoherty11 Thanks for the effort, you have put into it. We have issue with the debugger so I would have assume that you would have been the opposite effect.

**Comment by ashwinphatak** [comment] 2017-08-23 10:00
@Kdoherty11 thanks for the test code. Could you try and see if the problem is reproducible on an Android emulator (without your Object.values fix)?

**Comment by TGPSKI** [comment] 2017-09-27 01:09
A search of node_modules/realm (1.12.0) for Object.values(results)` returns 0 matches. @Kdoherty11, where in the code did you make this change?

@kneth @ashwinphatak any updates on this issue? We are continuing to see hundreds of prod users impacted by this issue. Are there plans to release a 1.13.0 this week which address RN 0.48 + dev port assignment issue, + `Error: Missing Realm constructor. Did you run "react-native link realm"`? 

I am really close to pulling realm from our project completely because of these issues. I know asyncStorage / SQLite implementations are slower, but they don't cause crashes and unneeded devOps time for me. Everything was working great up to the last few releases.

**Comment by kneth** [comment] 2017-09-27 16:02
@TGPSKI I am planning to do a release sometimes next week.

**Comment by Hatko** [comment] 2017-09-29 16:41
Is it possible to resolve this issue temporary?

**Comment by NavaneeBaskaran** [comment] 2017-09-30 17:57
Change version:
buildToolsVersion "25.0.0" in android

in nodeModules -> Realm -> android -> build.gradle

**Comment by Hatko** [comment] 2017-10-01 07:41
What about iOS?

**Comment by TGPSKI** [comment] 2017-10-02 17:43
@NavaneeBaskaran: This issue only shows itself for iOS users. Has to be a core Realm issue, not related to the build toolchain

**Comment by TGPSKI** [comment] 2017-10-02 17:45
@kneth: any updates on the release date? We have iOS and Android binary releases pending bundling the realm update. Would love to take our crash rate down a few % as a result of removing the constructor issue.

**Comment by Mellemel** [comment] 2017-10-04 23:15
I'm having this problem too, if I fix this before @kneth does, would you guys give me an interview? =D

**Comment by TGPSKI** [comment] 2017-10-04 23:18
Apparently @Kdoherty11 has some kind of solution, but I haven't figured out where to put this code change yet. 

@kneth Still targeting end of week for a release? I'm continuing to hold iOS + Android binary releases back until this fix is released! 

@Mellemel : where are you looking? This is a pretty critical issue for us - hundreds of users.

**Comment by Kdoherty11** [comment] 2017-10-05 03:54
Sorry for the delay...

@TGPSKI  `Missing Realm constructor` did not turn out to be the cause of my actual issue. I was experiencing unexpected behavior (described above) and the missing constructor error was the only realm related crash showing up in my crash reported so I falsely suspected they were related. I updated the issue title to reflect this. Also, the `Object.values` was a reference to this line https://github.com/Kdoherty11/realm-test/blob/87b341eb653fc2f90ab041be4fdea5a63d471204/realm/daos/dog.js#L13 not any realm code. 

I'm sorry to say the missing constructor issue was fixed for me by exactly following the recommended instructions from https://realm.io/docs/javascript/latest/#troubleshooting several times. Just running `react-native link` was not enough.

@kneth Using my sample repo, I was not able to reproduce the issue on Android.

**Comment by kneth** [comment] 2017-10-05 07:34
@Kdoherty11 Great to hear

**Comment by kneth** [comment] 2017-10-05 11:42
@TGPSKI We have just released 1.13.0.

**Comment by Mellemel** [comment] 2017-10-05 15:32
@TGPSKI I just switched 
```$(SRCROOT)/../../../../Pods/Headers/Public``` 
to 
```$(SRCROOT)/../../../../ios/Pods/Headers/Public```
in the RealmReact.xcodeproj header search paths and it did the trick for me.

See this, https://github.com/realm/realm-js/issues/884

**Comment by TGPSKI** [comment] 2017-10-05 18:24
@kneth @Mellemel @Kdoherty11  Thank you for the responses & information!!! Getting ready to release binaries right now.

**Comment by kneth** [comment] 2017-10-09 15:01
@TGPSKI Great to hear. I am closing the issue!

**Closed by kneth** 2017-10-09 15:01 UTC
Labels: T:Bug

**Comment by dimlksin2** [comment] 2019-07-26 10:24
?

**Comment by Jarzka** [comment] 2020-04-09 10:31
I faced this issue with version 2.29.2, `Object.values` returns `[]` if called for Realm object.

Is is issue fixed in later versions? I did not find any reference in the changelog.

**Comment by blagoev** [comment] 2020-04-09 16:10
@Jarzka I suggest you test the latest version. Object.values will not work this is documented in the CHANGELOG.md
Realm Objects now have `keys` and `entries` methods that you can use like so:
```
obj = realm.create(...);
let keys = obj.keys();
```
