### ISSUE TITLE
I am seeing crashes on some devices

### ISSUE THREAD

**Issue by syedrahaman92** [realm/realm-js#3133] opened 2020-08-14 05:46 UTC
Here is the crash report
```
backtrace:
  #00  pc 0000000000083064  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160)
  #01  pc 000000000071c9b0  /data/app/com.kartbites.mobileapp-sLR-Kungoe6Yl4Bcp52CqQ==/lib/arm64/librealmreact.so (__gnu_cxx::__verbose_terminate_handler()+348)
  #02  pc 00000000006c9100  /data/app/com.kartbites.mobileapp-sLR-Kungoe6Yl4Bcp52CqQ==/lib/arm64/librealmreact.so (__cxxabiv1::__terminate(void (*)())+8)
  #03  pc 00000000006c916c  /data/app/com.kartbites.mobileapp-sLR-Kungoe6Yl4Bcp52CqQ==/lib/arm64/librealmreact.so (std::terminate()+12)
  #04  pc 00000000006c92a8  /data/app/com.kartbites.mobileapp-sLR-Kungoe6Yl4Bcp52CqQ==/lib/arm64/librealmreact.so (__cxa_throw+136)
  #05  pc 0000000000157a34  /data/app/com.kartbites.mobileapp-sLR-Kungoe6Yl4Bcp52CqQ==/lib/arm64/librealmreact.so
  #06  pc 0000000000157ab0  /data/app/com.kartbites.mobileapp-sLR-Kungoe6Yl4Bcp52CqQ==/lib/arm64/librealmreact.so
  #07  pc 00000000001c874c  /data/app/com.kartbites.mobileapp-sLR-Kungoe6Yl4Bcp52CqQ==/lib/arm64/librealmreact.so
  #08  pc 00000000002438a8  /data/app/com.kartbites.mobileapp-sLR-Kungoe6Yl4Bcp52CqQ==/lib/arm64/librealmreact.so
  #09  pc 000000000028f8d4  /data/app/com.kartbites.mobileapp-sLR-Kungoe6Yl4Bcp52CqQ==/lib/arm64/librealmreact.so
  #10  pc 0000000000293cac  /data/app/com.kartbites.mobileapp-sLR-Kungoe6Yl4Bcp52CqQ==/lib/arm64/librealmreact.so
  #11  pc 0000000000293d74  /data/app/com.kartbites.mobileapp-sLR-Kungoe6Yl4Bcp52CqQ==/lib/arm64/librealmreact.so
  #12  pc 0000000000291954  /data/app/com.kartbites.mobileapp-sLR-Kungoe6Yl4Bcp52CqQ==/lib/arm64/librealmreact.so
  #13  pc 00000000002ac0e8  /data/app/com.kartbites.mobileapp-sLR-Kungoe6Yl4Bcp52CqQ==/lib/arm64/librealmreact.so
  #14  pc 00000000003490b4  /data/app/com.kartbites.mobileapp-sLR-Kungoe6Yl4Bcp52CqQ==/lib/arm64/librealmreact.so
  #15  pc 00000000002ee558  /data/app/com.kartbites.mobileapp-sLR-Kungoe6Yl4Bcp52CqQ==/lib/arm64/librealmreact.so
  #16  pc 00000000002eefb0  /data/app/com.kartbites.mobileapp-sLR-Kungoe6Yl4Bcp52CqQ==/lib/arm64/librealmreact.so
  #17  pc 0000000000017d50  /system/lib64/libutils.so (android::Looper::pollInner(int)+856)
  #18  pc 0000000000017958  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+56)
  #19  pc 0000000000166630  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
  #20  pc 00000000002cf34c  /system/framework/arm64/boot-framework.oat (art_jni_trampoline+140)
  #21  pc 000000000074df50  /system/framework/arm64/boot-framework.oat (android.os.MessageQueue.next+192)
  #22  pc 000000000074a978  /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+680)
  #23  pc 00000000001375b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568)
  #24  pc 000000000014608c  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+276)
  #25  pc 00000000002e0784  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384)
  #26  pc 00000000002dba64  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+912)
  #27  pc 000000000059c768  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+368)
  #28  pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20)
  #29  pc 000000000031713e  /data/app/com.kartbites.mobileapp-sLR-Kungoe6Yl4Bcp52CqQ==/oat/arm64/base.vdex (com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run+74)
  #30  pc 00000000002b13d0  /apex/com.android.runtime/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.2430230120769319602)+240)
  #31  pc 000000000058b1c4  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1012)
  #32  pc 0000000000140468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88)
  #33  pc 00000000001a5568  /system/framework/arm64/boot.oat (java.lang.Thread.run+72)
  #34  pc 0000000000137334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548)
  #35  pc 000000000014606c  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244)
  #36  pc 00000000004ab234  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
  #37  pc 00000000004ac2c8  /apex/com.android.runtime/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+416)
  #38  pc 00000000004ec5dc  /apex/com.android.runtime/lib64/libart.so (art::Thread::CreateCallback(void*)+1176)
  #39  pc 00000000000e2270  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36)
  #40  pc 0000000000084ba0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```
- Realm JS SDK Version: 3.6.5
- Node or React Native:  0.61.5
- Client OS & Version: Android 10

**Comment by kraenhansen** [comment] 2020-08-17 08:40
Hi @syedrahaman92.

Can you share more details on what the app is doing while crashing?
- Are you calling specific methods of the Realm SDK?
- Does this happen at a particular time of the lifecycle of the app? (eg. on startup or shutdown, etc.).

In other words, anything you can do to help isolate what / where is triggering this crash, would be highly appreciated.

**Comment by syedrahaman92** [comment] 2020-08-17 08:59
@kraenhansen Thanks for your reply. Actually I am unable to reproduce the crash in development. I am seeing this in google play console's crash report(in production app). I will let you know if I have any leads.

**Comment by kraenhansen** [comment] 2020-09-10 08:19
@syedrahaman92 I'll close this for now, please reopen (or open another issue) if you manage to reproduce it.

It also looks like this is an older version (3.6.5) of Realm JS and it would probably be beneficial for you to upgrade to the latest version.

**Closed by kraenhansen** 2020-09-10 08:19 UTC
Labels: O-Community, Reproduction-Required
