### ISSUE TITLE
in ios in debug mode every thing is ok but in release mode no data write or read 

### ISSUE THREAD

**Issue by MohamedShaw** [realm/realm-js#4302] opened 2022-02-03 09:29 UTC
### How frequently does the bug occur?

All the time

### Description

react-native 66 
realm latest

### Can you reproduce the bug?

Yes, sometimes

### Version

10.12.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

IOS 

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment] 2022-02-04 08:21
@MohamedShaw Thanks for reporting.  We will investigate.  Are there any error logs or crash reports you can provide?

**Comment by takameyer** [comment] 2022-02-04 08:40
I have ran a sample application with Realm in release mode for iOS and didn't witness any problems.  Can you provide some sample code that fails for you?

**Comment by MohamedShaw** [comment] 2022-02-06 11:18
there is no any problem or logs error

**Comment by MohamedShaw** [comment] 2022-02-06 11:25
<img width="800" alt="Screen Shot 2022-02-06 at 1 24 23 PM" src="https://user-images.githubusercontent.com/40764791/152678544-aaaa2bdb-b500-466e-8fb6-5a45f92ef431.png">
this snipt of code 
this project was working with version 2.5
but now i update for last version

**Comment by MohamedShaw** [comment] 2022-02-06 11:25
@takameyer

**Comment by tomduncalf** [comment] 2022-02-07 11:10
Hi @MohamedShaw, are you able to supply a project reproducing this problem?

**Comment by MohamedShaw** [comment] 2022-02-07 19:07
it works only if i open remote debug 
@tomduncalf 
i can share project with you provide your email

**Comment by tomduncalf** [comment] 2022-02-08 09:41
That's strange, it only works in _Release_ mode if you have remote debug enabled? Remote debug should have nothing to do with release mode.

Please could you send your project to [realm-help@mongodb.com](mailto:realm-help@mongodb.com)? If you mention this issue number in the subject that will make it easier for me to identify. Thanks

**Comment by takameyer** [comment] 2022-03-03 10:08
Closing as we cannot reproduce this.  If anyone has some reproducible example code we can try out, please reopen with a link to a project that reproduces this issue.

**Closed** 2022-03-03 10:08 UTC
Labels: T-Bug, Reproduction-Required, O-Community, Waiting-For-Reporter
