### ISSUE TITLE
Realm returns blank when not using React Native Debugger

### ISSUE THREAD

**Issue by christian-hess-94** [realm/realm-js#2500] opened 2019-08-27 18:55 UTC
## Goals
I'm trying to add an entity into Realm and then read and list it in another scene.

## Expected Results
The data that is read is supposed to be rendered as a list. It does happen but the data itself is not present.

## Actual Results
The data is saved to the database and is subsequently read from the database. A single item is rendered to the list, but all its values are empty. When clicking the item, a new screen opens which showcases all the data from that specific item (the item itself only shows 2 of the details)
This only happens if I'm not running the React Native debugger. I've generated the debug APK for testing purposes and the error still persisted.

## Steps to Reproduce
I'm not sure what can be done to reproduce this. I'm saving one item to a schema and later reading it. The data is retrieved but all the values in it are empty.

## Code Sample

1.This is the code that reads the data from the database. None of the values are undefined or null. This return the blank data when not using the debugger:
```js
const data = realm.objects('Visita').filtered(`matricula == '${this.props.matricula}' AND idObra == ${this.props.data.id}`)
```
2. This is the code that created the data prior to it being read in another page:
```js
 getRealm()
                .then(realm => {
                    /*Some boilerplatecode*/
                    realm.write(() => {
                        realm.create('Visita', visita)
                    })
```
3. This is the schema that is being added:

```js
export default class VisitaSchema {
    static schema = {
        name: 'Visita',
        primaryKey: 'idVisita',
        properties: {
            idVisita: { type: 'int', indexed: true },
            descricao: 'string',
            latitude: 'string',
            longitude: 'string',
            matricula: 'string',
            idObra: 'int',
            data: 'string'
        }
    }
}
```

## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by YaoHuiJi** [comment] 2019-08-29 12:59
OMG, same here!  I have spent more than 3 hours to locate the weird bug ,but have no clue, the only thing I am quite sure is the issue is  related to the method objectForPrimaryKey and react native debug mode  in my case.

My app use realm 2.29.2 & react native 0.60.5:

After an object with several fields  is saved to realm, I  use objectForPrimaryKey to retrieve it back，but weird things will happen when objectForPrimaryKey is called，if I turn react native “Debug JS Remotely” on，objectForPrimaryKey will return the right object，but if I turn“Debug JS Remotely” off，objectForPrimaryKey will return a blank object. I happened every time with the same result.

**Comment by christian-hess-94** [comment] 2019-08-29 22:02
> OMG, same here! I have spent more than 3 hours to locate the weird bug ,but have no clue, the only thing I am quite sure is that it is all about trying to retrieve object(objectForPrimaryKey in my case) under or not under the react native “Debug JS Remotely” mode.
> 
> My app use realm 2.29.2 & react native 0.60.5:
> 
> After an object with several fields is saved to realm, I use objectForPrimaryKey to retrieve it back，but weird things will happen when objectForPrimaryKey is called，if I turn react native “Debug JS Remotely” on，objectForPrimaryKey will return the right object，but if I turn“Debug JS Remotely” off，objectForPrimaryKey will return a blank object(not undefined). I happened every time with the same result.

I'm still waiting on a response from the actual maintainers of the repo. Did you try anything else? I just simply stopped using the debugger and started debugging by using alerts all around my code

**Comment by kneth** [comment] 2019-08-30 09:29
@christian-hess-94 @YaoHuiJi Sounds like a bug in the RPC calls between the debugger and the device/simulator. We'll investigate early next week.

**Comment by YaoHuiJi** [comment] 2019-08-30 10:10
@christian-hess-94  I have found a way to solve my issue , but to be honest I do not know why.....here is something I've found, not sure if it's helpful for you .

In my last comment, I said if “Debug JS Remotely” is turned on, objectForPrimaryKey will return the right object('yes'), if it's turned off will return a blank object('no'),  looks like this

```
let obj = this.objectForPrimaryKey('xxx', id);

if(obj){
    if(obj.id)
        console.log('yes')   //when “Debug JS Remotely” turned on
    else
        console.log('no')   //when “Debug JS Remotely” turned off
}else
    console.log('duh')
```
but actually , code like this works fine,  the output will always be 'yes' not matter debugger is turned on or off.  

the code with  weird bug actually looks like this:
```
let  objRelam = this.objectForPrimaryKey('xxx', id);

let obj = Object.assign({}, objRelam);  // !!!

if(obj){
    if(obj.id)
        console.log('yes')    //when “Debug JS Remotely” turned on
    else
        console.log('no')   //when “Debug JS Remotely” turned off
}else
    console.log('duh')
```

I use Object.assign to copy data into my own object, but weird things happened then,  in debug mode, it will copy data as expect, but if debug mode is off it will copy nothing, just an empty object.

I have googled some issue about Object.assign, like [2282](https://github.com/realm/realm-js/issues/2282#issuecomment-495748901),[2282](https://github.com/realm/realm-js/issues/2282#issuecomment-515896814),[1299](https://github.com/realm/realm-js/issues/1299) , but they are all not answered too. 

I guess maybe it's about javascript runtime？ when 'Debug JS Remotely' is turned ON, the code is running in V8,  when it's turned off, the code is running in JavaScriptCore, maybe Object.assign in these two runtimes has different behavior？It was just a shot in the dark, I totally have no idea why it's so weird😫

**Comment by kneth** [comment] 2019-09-03 08:36
@YaoHuiJi Thank you for investigating.

**Comment by fxricky** [comment] 2020-03-29 11:02
this issue is still remain, I'm using Objects.find as a workaround.

`realm.objects(tablesname).find(({ID}) => ID === paramID)`

**Comment by havi-b** [comment] 2020-04-06 22:36
So I had the same issue as well. I was able to resolve it by following these steps:

1. Upgrade the realm package to 5.0.3  `yarn upgrade realm`

2. Run `npx react-native link realm` (Realm does not fully support auto-linking yet)

3. Verify that the linking happened properly by following the instructions at the top of: https://realm.io/docs/javascript/latest/

4. Make sure to add this line --> `import io.realm.react.RealmReactPackage;` to the top of your MainApplication.java in android/app/src/main/java/com/`<your-app-name>`/MainApplication.java

5. Check your package list in android/app/src/main/java/com/`<your-app-name>`/MainApplication.java to ensure it is configured as followed:

```
        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
+         packages.add(new RealmReactPackage()); // <-- This line adds in the realm package.
          packages.add(new RNSensitiveInfoPackage());
          return packages;
        }
```

6. cd into /android directory and clean by running `./gradlew clean`

7. Re-compile and run again from your project's root directory `npx react-native run-android`

** If you get an error that looks something like this: 
```
Native module realm tried to override realm for module name realm. If this was your intention, set canOverrideExistingModule=true
```

1. Open `<your-app-name>`/node_modules/realm/android/src/main/java/io/realm/react/RealmReactModule.java

2. Add the following lines inside the RealmReactModule class:

```
    @Override
    public boolean canOverrideExistingModule() {
        return true;
    }
```

Hope this helps! 🙂

**Comment by blagoev** [comment] 2020-04-07 10:54
@havi-b Thanks for the description. One note: you should be able to do it without changing the `getPackages` method
so this line is not needed or shouldn't be needed now
` packages.add(new RealmReactPackage()); // <-- This line adds in the realm package.`

**Comment by havi-b** [comment] 2020-04-07 17:32
@blagoev Ahh it seems you are right. This saves a lot me some work. Having to go into the module and adding the override is pretty annoying 😅.

**Comment by wellmmer** [comment] 2020-04-12 19:29
Same issue here also guys! Thank you @havi-b and @blagoev for this workaround. It saves my life now! =)

**Comment by samuelrvg** [comment] 2020-07-29 15:11
Working correctly:

export class RealmPlayLog extends Realm.Object {
  static readonly schema: ObjectSchema = schema

  ...
}

**Comment by machadolucasvp** [comment] 2020-08-04 14:36
@samuelrvg extends from `Realm.Object` gives me `Reflect.construct requires the first argument be a constructor` running in a android with `react-native:0.61.5`. Using dumb schemas resolve my issue in `realm: 5.0.4` and this stills reproducible in 6.0.4 @blagoev can you take a look at it ?

**Comment by manoj-fareye** [comment] 2020-08-28 03:44
`let obj = Object.assign({}, objRelam);  // !!!`

**Comment by manoj-makkuboy** [comment] 2020-08-28 04:11
`let obj = Object.assign({}, objRealm);`
Still giving {} in `realm:6.0.5` and `react-native:0.62.1` 
Tried with `loadash`'s `_.clone(objRealm)` and `_.deepClone(objRealm)` same result, {}. 
For now as a workaround to copy objects using `JSON.parse(JSON.stringify(objRealm))`.

**Comment by steffenagger** [comment] 2020-08-28 08:26
@manoj-makkuboy in realm@6.0.5 you should be able to use `objRealm.toJSON()` to get at plain JS structure (both on Realm objects & collections).
It will give you the same result as `JSON.parse(JSON.stringify(objRealm))`, but without first serializing & then deserializing.

**Comment by steffenagger** [comment] 2020-08-28 08:29
@manoj-makkuboy in realm@6.1.0 you should be able to use `objRealm.toJSON()` to get at plain JS structure (both on Realm objects & collections).
It will give you the same result as `JSON.parse(JSON.stringify(objRealm))`, but without first serializing & then deserializing.

**Comment by manoj-makkuboy** [comment] 2020-09-01 06:06
@steffenagger 
I tried `let obj = Object.assign({}, objRealm);`
`obj.toJSON()` also `obj.toJson()`

**Comment by steffenagger** [comment] 2020-09-01 07:34
@manoj-makkuboy if you are using class models, please try extending from `Realm.Object`, like so:
```js
class MyModel extends Realm.Object {
  ...
}
```

**Comment by manoj-fareye** [comment] 2020-09-02 11:12
@steffenagger I tried it and it worked. Thank you

**Comment by aqos156** [comment] 2021-03-24 08:23
Unfortunately can confirm that we are still facing the same issue even in the newest version of realm. We have to still use the realm version 3

**Comment by nicotroia** [comment] 2021-05-26 22:45
I'm running realm `^10.4.0` and also experiencing this or a similar issue

`const realm = await Realm.open(latestConfig);`

When debugging, the realm object logs `{"inMemory":false,"path":"....../Documents/6f02083c-3d30-11ea-814f-22000b07855a.realm","readOnly":false,"syncSession":null}` as normal
when not debugging, the realm object logs `{}` 

when not debugging, any subsequent fetches such as `const recipients = realm.objects('Recipient');` will throw an error somewhere down the line, such as `recipients.filtered is not a function` or `item.toJSON is not a function`

These issues go away when react-native has "remote debugging" enabled

I'm trying to import several polyfills at the start of my RN project, but no luck so far.

**Comment by rjberry95** [comment] 2021-06-09 21:00
@kneth Any updates on this? I seem to be seeing the same issue as @nicotroia with similar versions. We're currently running React Native 0.64.1 with Realm 10.4.1.

On both android and ios, we see an array with our full schema in the realm object `schema` property, but when we call `realm.schema` an empty array is returned. This causes our call for a specific object in the realm to return an error.

This problem only occurs the first time the app is launched on the device. If we refresh the app, either by changing the code or refreshing the simulator, the schema and realm objects are returned properly. This also does not occur if we are running the Chrome debugger at the same time although I think that's just because the debugger forces a refresh when you enable it.

**Comment by kneth** [comment] 2021-06-10 17:06
@rjberry95 We released v10.4.2 today, and we have a fix for reloading the app on Android (see also https://github.com/realm/realm-js/issues/3668). From your description, v10.4.2 might not solve it.

Have you observe a similar behaviour with other versions of React Native?

**Comment by kneth** [comment] 2021-06-18 10:45
@rjberry95 Thanks for your feedback. We are using an [unconventional approach](https://github.com/realm/realm-js/blob/master/src/android/jsc_override.cpp) to hook into Javascript Core, and my best hypothesis is that recent RN versions will require some adjustments.

**Comment by Ervzz** [comment] 2021-06-29 19:59
After a day of trying to get realm to work with a fresh react-native app, we've abandoned all hope. Best fix for this 2 year old issue is:

 `yarn remove realm`

**Comment by slatqh** [comment] 2021-07-08 20:52
I have a same issue with latest realm version and RN 0.64
Very sad that no one really care about that bug and unfortunately force us to use different local db.

**Comment by bmunkholm** [comment] 2021-11-18 09:18
Closing this as it will be resolved with the support for Hermes and the Flipper debugger. Please see [here](https://github.com/realm/realm-js/issues/3940) to try it out and provide feedback. Thanks for your patience!

**Closed by bmunkholm** 2021-11-18 09:18 UTC
Labels: T-Bug, O-Community, Pipeline-Soon-Backlog

**Comment by gopi-hrbl-c** [comment] 2023-02-08 15:05
Still facing the issue for react native 0.66.0 version.

**Comment by kneth** [comment] 2023-02-09 09:01
@gopi-hrbl-c 

It is possible to use JSC with our latest releases. Of course, in order to use debug, you will need to use Flipper and Hermes.

We are not fixing any bugs in the support for the Chrome Debugger as it is too slow to be used in any practical cases.

**Comment by gopi-hrbl-c** [comment] 2023-02-09 09:20
can we connect for a quick call? devarapallli.gopi8@gmail.com pls send google meet link?

**Comment by gopi-hrbl-c** [comment] 2023-02-09 09:37
> @gopi-hrbl-c
> 
> It is possible to use JSC with our latest releases. Of course, in order to use debug, you will need to use Flipper and Hermes.
> 
> We are not fixing any bugs in the support for the Chrome Debugger as it is too slow to be used in any practical cases.

but we not using hermes. Please suggest something.

**Comment by gopi-hrbl-c** [comment] 2023-02-09 09:53
@kneth I want to work realm with react native 0.68.0. And any of the realm version is fine. Please suggest.

**Comment by kneth** [comment] 2023-02-09 15:15
@gopi-hrbl-c 

If you do `console.log(realm_object)` you will see `{}` since `realm_object` is a JavaScript proxy object for a Realm object. Instead you can do `console.log(JSON.stringify(realm_object))`.

**Comment by kneth** [comment] 2023-02-10 08:41
@gopi-hrbl-c `instance.path` returns a string, right?

I would like to know what you are looking for with `JSON.stringify(instance)`? Do you want to see all objects in your database? Or the schema (`JSON.stringify(instance.schema)` is likely more direct).

**Comment by gopi-hrbl-c** [comment] 2023-02-10 09:10
@kneth , Yes instance.path is returning string. But I am not able to see the log of instance.objects('CustomerValidation'), I want to see the result from instance.objects.  Please observe the below screenshot there is no log for CustomerValidation. 

As you said I can see instance.schema but instance.objects('CustomerValidation') is returning nothing. It is just throwing from that line and I am not able to catch it what is the error even by using try catch.

<img width="993" alt="image" src="https://user-images.githubusercontent.com/101787125/218049592-1422a0c9-7d05-4cf0-a205-0df2e84f30ee.png">
