### ISSUE TITLE
node 12

### ISSUE THREAD

**Issue by email2019** [realm/realm-js#2418] opened 2019-06-19 10:51 UTC
## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by kneth** [comment] 2019-06-27 11:08
@email2019 We hope to be able to allocate time in late summer to work on Node 12 support.

**Comment by MIREX** [comment] 2019-07-08 11:54
Is node 10 already supported?

**Comment by arashmilani** [comment] 2019-07-08 12:14
Yes node >= 8.15.0 and 10.15.1 are supported

**Comment by kneth** [comment] 2019-08-28 07:45
@wellmonge Before we get to support node 12, you need to either use node 8 or node 10.

**Comment by bmunkholm** [comment] 2019-08-29 07:21
Thanks for the offer @wellmonge - that's highly appreciated! There is already a PR with some outstanding work in the last comment here: https://github.com/realm/realm-js/pull/2425. Let us know if you feel that's up your alley as it may be a bit involved.

There is a lot of work to do to support each new node version, and all that work can be avoided by moving to n-api instead and we would never be behind on support for new node versions. That is however a larger effort of perhaps 1 month or so. That's what we would really like to do.

**Comment by reynaldpn** [comment] 2019-10-21 15:03
Node js v12 is the latest LTS version now

**Comment by kneth** [comment] 2019-10-22 08:04
And we are working hard migrate to N-API in order to support it :-)

**Comment by xmedeko** [comment] 2019-11-08 13:30
@bmunkholm @kneth is this duplicate of @2516 ?

**Comment by bmunkholm** [comment] 2019-11-08 13:36
@xmedeko Thanks again - yes this is a dupe.

**Closed by bmunkholm** 2019-11-08 13:36 UTC
Labels: O-Community, T-Feature
