### ISSUE TITLE
Linking issue: building for iOS Simulator, but linking in object file built for iOS

### ISSUE THREAD

**Issue by kdo1234** [realm/realm-js#3375] opened 2020-11-01 01:21 UTC
## Goals

I'm trying to build a react native app with realm.

## Expected Results

I expect it to build.

## Actual Results

The build fails when linking the arm64 version with this error:
In /path/to/app/node_modules/realm/vendor/realm-ios/librealm-ios.a(placeholder.o), building for iOS Simulator, but linking in object file built for iOS, file '/path/to/app/node_modules/realm/vendor/realm-ios/librealm-ios.a' for architecture arm64

## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.1 or 6.0.4
- Node or React Native: react-native 0.63.2
- Client OS & Version: macOS 10.15.4
- Which debugger for React Native: ?/None
- CocoaPods 1.10.0
- Xcode 12.0.1

**Comment by kneth** [comment] 2020-11-02 08:16
@kdo1234 Thank you for reporting.

**Comment by kneth** [comment] 2020-12-07 12:29
@kdo1234 Do you experience the issue if you are using Xcode 11.x?

**Comment by fronck** [comment] 2020-12-09 08:59
@kdo1234:  We are aware of this issue, which is caused by XCode 12.x including the new Apple silicon in the default build targets.  We are working on a fix.  In the meantime, installing XCode 11.x (which can be installed alongside 12.x) should allow you to build and link Realm correctly.
Please let us know whether this works for you.

**Comment by bennettk** [comment] 2021-01-05 00:47
I'm trying to get our app to compile on a new M1 Mac but this issue still exists- linking fails. AFAIK there's no option to go back to Xcode 11 on an M1 Mac. @fronck  Any idea on a timeline for when this fix is expected? Happy to be an early tester if you need someone with an apple silicon Mac to verify the fix.

`In /Users/<path-to-app>/node_modules/realm/vendor/realm-ios/librealm-sync-ios.a(decimal128.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
`

**Comment by sky-sergiosilva** [comment] 2021-01-25 11:18
@fronck do you have an issue for the M1 fix or a timeline?

**Comment by havi-b** [comment] 2021-02-05 22:46
I am experiencing the same on an older iMac... Is there any update as to when this will be fixed?

Also, can someone please specify what exactly causes this issue?

Realm JS: 10.2.0
Node or React Native: react-native 0.63.4
Client OS & Version: macOS 10.15.7
CocoaPods 1.10.0
Xcode 12.4

**Comment by roycechua23** [comment] 2021-02-10 04:11
I am also encountering this issue @havi-b but I found this temporary workaround on Stackoverflow [(https://stackoverflow.com/a/65399525)](https://stackoverflow.com/a/65399525) and it worked for me. What he did was mainly clean the build then exclude the **arm64** architecture in the build settings for debug and release like I did below

<img width="962" alt="Screen Shot 2021-02-10 at 12 08 04 PM" src="https://user-images.githubusercontent.com/25720149/107463285-b4f3a700-6b98-11eb-9b50-7ebfbca25c50.png">

realm js 6.0.2,
Node v15.5.0
Xcode 12.4 
CocoaPods 1.10.1
macOS 10.15.7

**Comment by kneth** [comment] 2021-07-15 08:28
We have been support Apple M1 since v10.4.1

**Closed by kneth** 2021-07-15 08:28 UTC
Labels: O-Community
