### ISSUE TITLE
Realm Migration Error

### ISSUE THREAD

**Issue by bharadwajagali** [realm/realm-js#3270] opened 2020-09-28 11:15 UTC
## Goals

We are trying to migrate realm from old version to new version it is throwing below error

No Such Column

## Expected Results

It should migrate successfully.

## Actual Results

**Error: No such column**

## Steps to Reproduce

1) We are changing one optional field in a table to mandatory and making that as primary key to that table schema. 

## Code Sample

Previous Code:

const EmpDetails = {
  name: 'EmpDetails',
  primaryKey: 'UId',
  properties: {
    UId: 'string',
    EmployeeId: 'string?',
    Name: 'string',
  },
};

New Code for Migration

const EmpDetails = {
  name: 'EmpDetails',
  primaryKey: 'EmployeeId,
  properties: {
    UId: 'string',
    EmployeeId: 'string',
    Name: 'string',
  },
};

## Version of Realm and Tooling

- Realm JS SDK Version: 6.1.0 (Working fine in 3.6.5)
- Node or React Native: 0.61.2
- Client OS & Version: Android 10
- Which debugger for React Native: None

**Comment by fronck** [comment] 2020-09-29 14:18
@bharadwajagali Is there any data in the table you're trying to migrate?  If so, could it be that some records are missing the `EmployeeId` field because it was optional before?

**Comment by fronck** [comment] 2020-09-29 15:17
@bharadwajagali Is the code you posted above copy-pasted from your project?  If so, it seems to be missing a closing quote on this line:

> `primaryKey: 'EmployeeId,`

**Comment by bharadwajagali** [comment] 2020-09-30 10:42
> @bharadwajagali ~Is there any data in the table you're trying to migrate? If so, could it be that some records are missing the `EmployeeId` field because it was optional before?~

@fronck Yes we have data in that table we checked that data in Realm Studio before migration ,every record have that optional EmployeeId field. 
same code we tested with realm 3.6.5 it is working fine. Few days back we upgraded realm version to 6.1.0 it is throwing error in new version.Can you please check and tell us know what causing the issue.

**Comment by bharadwajagali** [comment] 2020-09-30 10:49
> @bharadwajagali Is the code you posted above copy-pasted from your project? If so, it seems to be missing a closing quote on this line:
> 
> > `primaryKey: 'EmployeeId,`

@fronck provided sample code here where we can reproduce the same scenario we are facing with realm time data.No syntactic errors in real time code.

**Comment by bharadwajagali** [comment] 2020-09-30 11:37
@kneth can you please help us with above issue.

**Comment by jedelbo** [comment] 2020-10-01 08:10
@bharadwajagali there must be some migration code involved in this. How does it look like?

**Comment by jedelbo** [comment] 2020-10-01 08:19
If you could share a realm file as it is before migration, it might help us find the bug. You can share it privately by sending it to jorgen.edelbo@mongodb.com.

**Comment by jedelbo** [comment] 2020-10-01 10:19
It seems like we can reproduce the error. So hopefully we have a solution soon.

**Closed** 2020-10-02 18:49 UTC
Labels: O-Community

**Comment by bharadwajagali** [comment] 2020-10-05 10:33
@jedelbo  thanks for understanding and fixing the issue, can we expect this fix as part of realm version 6+ or in the coming version's.

**Comment by kneth** [comment] 2020-10-05 11:17
@bharadwajagali We will try to get it release during the week (the sooner the better).

**Comment by bharadwajagali** [comment] 2020-10-06 05:08
@kneth thank you
