### ISSUE TITLE
posix_fallocate() failed: Operation not permitted while opening .realm file using nodejs

### ISSUE THREAD

**Issue by mithunph** [realm/realm-js#2512] opened 2019-09-06 15:46 UTC
Hi,
I get the below error when i try to open and download .realm file in /tmp directory of aws lambda using nodejs.
{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: posix_fallocate() failed: Operation not permitted" }

**Comment by kneth** [comment] 2019-09-09 07:37
Duplicate of #1832

**Closed by kneth** 2019-09-09 07:37 UTC
Labels: O-Community
