### ISSUE TITLE
[IOS] Can't build with Node 14.2.0 and Realm 5.0.4

### ISSUE THREAD

**Issue by cristianoccazinsp** [realm/realm-js#2871] opened 2020-05-08 16:13 UTC
## Version of Realm and Tooling

- Realm JS SDK Version: 5.0.4
- Node or React Native: RN 0.61.5 / Node 14.2.0
- Client OS & Version: MacOS Catalina
- Which debugger for React Native: -

Trying to upgrade from realm 5.0.3 to 5.0.4 using Node 14.2.0 is giving issues.  For Android it seems to work fine, but when building for iOS, pretty much all of the realm build/compile process fails due to `undefined symbol` errors.  I can't tell for sure if this was me upgrading from node 10 to 14, or the Realm upgrade. Still researching...

**Comment by kraenhansen** [comment] 2020-05-08 19:57
When are these errors reported? (at install, build or runtime)? If you do determine that this is due to an issue related to Realm, please add the specific log messages and a set of steps to reproduce the error (ideally also a repository with code reproducing it).

Did you clean the iOS build folder and node_modules after switching node version?

**Comment by cristianoccazinsp** [comment] 2020-05-08 20:05
I'm sorry for the vague report, was in a hurry and this didn't help at all.

The errors were at build time (from XCode), and I had already cleared all build folders, reset cache, and even downloaded everything from scratch. I've already resolved it by downgrading to Realm 5.0.3 (which seems to download and build node from scratch), so I can confirm that this issue is related to Realm 5.0.4. It seems like the build step was not able to find the required headers/C files.

I will try to upgrade again next week, and I will provide the detailed error logs then.

**Comment by kneth** [comment] 2020-06-25 12:08
@cristianoccazinsp Any updates to share?

**Comment by cristianoccazinsp** [comment] 2020-06-25 12:13
Haven't tried to update to 6.x yet, but I will shortly.

**Comment by kneth** [comment] 2020-07-13 10:46
@cristianoccazinsp Any updates to share?

**Comment by cristianoccazinsp** [comment] 2020-07-13 20:06
I'm sorry, I haven't been able to test it yet since we have had other issues and couldn't update yet.  I will try to resolve this this week and come back at you.

**Comment by cristianoccazinsp** [comment] 2020-07-14 14:50
@kneth I was able to successfully install Realm 6.0.2 now.  Note that I still had to downgrade to Node 12.x. (for other compatibility reasons), so I'm not sure if Node 14 will work or not.

**Comment by kneth** [comment] 2020-08-17 12:19
@cristianoccazinsp I close the issue. If you experience the issue with node 14, please create a new issue.

**Closed** 2020-08-17 12:20 UTC
Labels: O-Community
