### ISSUE TITLE
Issues with debug mode when running on Android devices

### ISSUE THREAD

**Issue by Kufert** [realm/realm-js#571] opened 2016-08-18 15:23 UTC
Hi,

When I run  `import Realm from 'realm'` on android while remote js Debugging mode in enabled, the app breaks with the message:

> Module AppRegistry is not a registered callable module.

I do not have anything running on port 8082. It works fine on iOS, and on android while I disable 'Remote JS Debugging'

How can I overcome this issue? 

Also, I think it would be helpful if instead of crashing the app, I could handle this kind of issues myself. Now when importing Realm, it might throw exceptions. If instead it could be moved to an init function I could wrap in try/catch or if the init will return a promise, that would be very helpful to keep my app stable.

**Comment by paldepind** [comment] 2016-08-22 06:38
I also experience this bug :cry: I've already reported it in #562.

> Also, I think it would be helpful if instead of crashing the app, I could handle this kind of issues myself. Now when importing Realm, it might throw exceptions. If instead it could be moved to an init function I could wrap in try/catch or if the init will return a promise, that would be very helpful to keep my app stable.

I think that sounds like a great idea.

**Comment by alazier** [comment] 2016-08-24 15:03
@Kufert - does this issue only happen when running on device or when using genymotion/emulator as well? The realm debug server is running on port 8082 which is needed for things to work properly in chrome debug mode. We have been having issues making this work/connect properly with device, but things should work properly when running chrome debug mode using an emulator.

**Comment by fauno** [comment] 2016-08-25 19:10
Same here, it happens when using remote debugging on an Android device, even after forwarding port 8082 as @paldepind suggests.

I also had an exception during linking for iOS but since I'm only developing for Android I don't know if it affects me too.  

```bash
./node_modules/rnpm/bin/cli link realm
rnpm-link info Android module realm is already linked
rnpm-link info Linking realm ios dependency
rnpm-link ERR! It seems something went wrong while linking. Error: Cannot read property 'length' of undefined
Please file an issue here: https://github.com/rnpm/rnpm/issues
```

**Comment by Kufert** [comment] 2016-08-29 15:46
@alazier it happened while using a real device, also after rerouting port 8082 with adb.

I think for me the most helpful thing now would be instead of crashing the app, return some sort of error. If the module init was in a function instead of the constructor, I could wrap it will try/catch.

**Comment by alazier** [comment] 2016-09-13 15:06
I think the linking issue were due to rnpm being subsumed by react-native. You now need to run `react-native link realm` when including Realm in your project. Not sure if this would resolve your linking issue though. I made another issue to track fixing Realm so it throws an exception instead of crashing here #598

**Comment by avishayil** [comment] 2016-09-19 09:57
Happens here as well with real device.

**Comment by CreatineDevelopment** [comment] 2017-01-04 21:44
I've confirmed this issue happening as well on a real device.  My error message reads

`Realm is not defined`

All references to Realm except for the const declaration have been removed and the error still appears.  I have re-run `react-native link realm` as well and still no luck.

**Comment by kristiandupont** [comment] 2017-01-05 08:36
@CreatineDevelopment Which version of Realm is this? 0.15.2?

**Comment by CreatineDevelopment** [comment] 2017-01-05 15:43
Yes.  I just installed it yesterday.  Double checked package.json and I'm on 0.15.2

**Comment by kristiandupont** [comment] 2017-01-06 09:06
Got it, I will investigate this then. Thank you!

**Comment by kristiandupont** [comment] 2017-01-10 16:06
Closing this as it's a duplicate of #562

**Closed** 2017-01-10 16:06 UTC
Labels: T:Bug
