### ISSUE TITLE
In React native how to store and display json array object data need code for it provide code snippet

### ISSUE THREAD

**Issue by keerthipativinaykumar** [realm/realm-js#3884] opened 2021-08-04 11:49 UTC
I was developing app in REACT NATIVE new to react native so, you people help me in this 
I want to store api response json array objects in realm database and display that data in one screen

i want code for to store responseJson data in local database using realm and display that data in a screen

the api url represented in the below code snippet please check it and help me in writing code for it 

## Goals

I want to store api response json array objects in realm database and display that data in one screen

## Expected Results

I want to store api response json array objects in realm database and display that data in one screen

## Actual Results

 ERROR  error message in loginScreen : [Error: Array must contain values for all object properties]

## Code Sample

my code looks like this 

 var url = 'http://' + LoginUrl.USER_LOGIN_API + 'user=' + this.state.user + '&pwd=' + this.state.pwd + '&deviceid=' +this.state.deviceId+'';
        fetch(url, {
            method: 'POST',
            body: JSON.stringify(collection),
            headers: new Headers({
                Accept: 'application/json',
                'Content-Type': 'application/json'
            })
        }).then((response) => response.json())
            .catch(error => console.error('Error1:', error))
            .then((responseJson) => {
                // this.setState({
                //     data: responseJson
                //  })
                if (responseJson.msg === 'success') {
                    console.log('login success response : ', responseJson.empdata);
                    realm.write(() => {
                            realm.objects('empdata');
                        realm.create('empdata', [{
                            emp_code: this.state.emp_code,
                            emp_name: this.state.emp_name,
                            emp_desgname: this.state.emp_desgname,
                            comp_name: this.state.comp_name,
                        }]);
                        // console.log('login realm create response : ', responseJson.empdata);
                        Alert.alert(
                            'Success',
                            'Your login success',
                            [
                                {
                                    text: 'Ok',
                                    // onPress: () => this.props.navigation.navigate('Home'),
                                },
                            ],
                            { cancelable: false }
                        );
                    });
                    // this.props.navigation.navigate('Home')
                } else {
                    console.log('login failed message in login screen : ', responseJson.msg);
                    alert('enter your correct details LOGIN FAILED');
                }
            })
            .catch((error) => {
                console.error('error message in loginScreen :', error);
            });
====================

My api response is like this

{
    "msg": "success",
    "empdata": [
        {
            "emp_code": "0011",
            "emp_name": "ABCDEFG",
            "emp_desgname": "LMNOPQRS",
            "comp_name": "WXYZ",
        }
    ]
}

**Comment by takameyer** [comment] 2021-08-04 16:43
Hello @keerthipativinaykumar 
Happy to see you are trying Realm out.  I would recommend that you take a look through our [documentation](https://docs.mongodb.com/realm/sdk/react-native/examples/define-a-realm-object-model/).  There are loads of examples there which will help you achieve what you are trying to do.  

Unfortunately, as this issue is not a bug or feature request, I will be closing this issue.  

If you do experience a specific issue with Realm, please make a new issue with some example code showing exactly what is going wrong.

**Closed by takameyer** 2021-08-04 16:43 UTC
Labels: O-Community
