### ISSUE TITLE
Error: Missing Realm constructor. Did you run "pod install" on iOS

### ISSUE THREAD

**Issue by Pingou** [realm/realm-js#5758] opened 2023-04-22 08:58 UTC
### How frequently does the bug occur?

Sometimes

### Description

Here is another case of this bug.
It happens to a few of my users, iOS version doesn't seem to make a difference.
Users are upset because they can't even open the app.
Compatibility matrix seems to be respected.

### Stacktrace & log output

```shell
Fatal Exception: RCTFatalException: Unhandled JS Exception: Error: Missing Realm constructor. Did you run "pod install"? Please see https://docs.mongodb.com/realm/sdk/react-native/install/ for troubleshooting
0  CoreFoundation                 0x9e38 __exceptionPreprocess
1  libobjc.A.dylib                0x178d8 objc_exception_throw
2  app                            0x2711c8 RCTFormatError + 167 (RCTAssert.m:167)
3  app                            0x2e4710 -[RCTExceptionsManager reportFatal:stack:exceptionId:extraDataAsJSON:] + 77 (RCTExceptionsManager.mm:77)
4  app                            0x2e4f54 -[RCTExceptionsManager reportException:] + 147 (RCTExceptionsManager.mm:147)
5  CoreFoundation                 0x746b4 __invoking___
6  CoreFoundation                 0x20b1c -[NSInvocation invoke]
7  CoreFoundation                 0x20534 -[NSInvocation invokeWithTarget:]
8  app                            0x29f4b8 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 587 (RCTModuleMethod.mm:587)
9  app                            0x2a149c facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext) + 183 (RCTNativeModule.mm:183)
10 app                            0x2a10ec invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) + 419 (Optional.h:419)
11 libdispatch.dylib              0x2460 _dispatch_call_block_and_release
12 libdispatch.dylib              0x3f88 _dispatch_client_callout
13 libdispatch.dylib              0xb640 _dispatch_lane_serial_drain
14 libdispatch.dylib              0xc18c _dispatch_lane_invoke
15 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread
16 libsystem_pthread.dylib        0xdf8 _pthread_wqthread
17 libsystem_pthread.dylib        0xb98 start_wqthread
```

### Can you reproduce the bug?

No

### Version

11.2.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 15, iOS 16

### Build environment

npm 6.14.17
node v16.15.1
react-native 0.70.8
realm: 11.2.0
Hermes disabled

### Cocoapods version

1.11.3

**Comment by kneth** [comment] 2023-04-25 11:00
You mention that it only happens in few cases, and you haven't been able to see a pattern. I wonder if it is a collision with another dependency. It is possible to share `package.json`?

If the new architecture is enabled, you will have to disable to this old version of Realm.

Moreover, do you have any issues on Android?

**Comment by Pingou** [comment] 2023-04-25 11:12
Hi @kneth, thank you for your answer.
New architecture is disabled, and I do not have the issue on Android.

package.json
`{
    "name": "app",
    "version": "0.0.1",
    "private": true,
    "scripts": {
      "android": "react-native run-android",
      "ios": "react-native run-ios",
      "start": "react-native start",
      "test": "jest",
      "lint": "eslint .",
      "postinstall": "patch-package"
    },
    "dependencies": {
      "@bugsnag/react-native": "^7.16.7",
      "@fortawesome/fontawesome-svg-core": "^1.2.35",
      "@fortawesome/free-solid-svg-icons": "^5.15.3",
      "@fortawesome/react-native-fontawesome": "^0.2.6",
      "@georstat/react-native-image-cache": "^1.2.7",
      "@react-native-community/async-storage": "^1.6.1",
      "@react-native-community/clipboard": "^1.2.3",
      "@react-native-community/datetimepicker": "^2.2.1",
      "@react-native-community/image-editor": "^2.3.0",
      "@react-native-community/netinfo": "^5.5.0",
      "@react-native-community/slider": "^2.0.7",
      "@react-native-cookies/cookies": "^6.2.1",
      "@react-native-firebase/analytics": "^14.11.0",
      "@react-native-firebase/app": "^14.11.0",
      "@react-native-firebase/crashlytics": "^14.11.0",
      "@react-native-firebase/messaging": "^14.11.0",
      "@react-native-google-signin/google-signin": "^8.0.0",
      "@react-native-masked-view/masked-view": "^0.2.7",
      "@react-native-picker/picker": "^2.4.1",
      "@react-navigation/bottom-tabs": "^6.3.1",
      "@react-navigation/native": "^6.0.10",
      "@react-navigation/native-stack": "^6.6.2",
      "@sayem314/react-native-keep-awake": "^1.1.0",
      "axios": "^0.26.1",
      "base-64": "^0.1.0",
      "buffer": "^6.0.3",
      "countries-list": "^2.6.1",
      "dropbox": "^4.0.30",
      "email-misspelled": "^3.3.9",
      "lottie-ios": "3.4.1",
      "lottie-react-native": "^5.1.5",
      "mixpanel-react-native": "^1.5.0",
      "moment": "^2.24.0",
      "moment-timezone": "^0.5.23",
      "node-html-parser": "^1.1.16",
      "pako": "^1.0.11",
      "patch-package": "^6.4.7",
      "react": "18.1.0",
      "react-moment": "^0.7.9",
      "react-native": "0.70.8",
      "react-native-admob-native-ads": "^0.6.0",
      "react-native-animatable": "^1.3.0",
      "react-native-app-auth": "^6.4.3",
      "react-native-auto-grow-textinput": "^1.2.1",
      "react-native-autocomplete-input": "^5.1.0",
      "react-native-autogrow-textinput": "^5.3.0",
      "react-native-autolink": "^1.9.2",
      "react-native-base64": "0.0.2",
      "react-native-blob-util": "0.17.1",
      "react-native-calendars": "^1.1293.0",
      "react-native-camera": "^3.40.0",
      "react-native-canvas": "^0.1.38",
      "react-native-chart-kit": "^6.12.0",
      "react-native-deep-linking": "^2.2.0",
      "react-native-device-country": "^1.0.2",
      "react-native-device-info": "^8.4.8",
      "react-native-dialog": "^9.2.2",
      "react-native-document-picker": "^6.1.1",
      "react-native-draggable": "^1.0.14",
      "react-native-draggable-flatlist": "^1.1.9",
      "react-native-dropdown-picker": "^4.0.2",
      "react-native-fast-image": "^8.5.11",
      "react-native-fetch-polyfill": "^1.1.3",
      "react-native-file-access": "^2.4.2",
      "react-native-file-type": "git://github.com/efstathiosntonas/react-native-file-type#d45e1d6",
      "react-native-fs": "^2.20.0",
      "react-native-gesture-handler": "^2.9.0",
      "react-native-global-props": "^1.1.5",
      "react-native-google-drive-api-wrapper": "^1.2.0",
      "react-native-google-mobile-ads": "^8.2.3",
      "react-native-iap": "12.5.0",
      "react-native-image-crop-picker": "^0.35.1",
      "react-native-image-crop-tools": "^1.6.2",
      "react-native-image-picker": "^4.1.1",
      "react-native-image-resizer": "^1.4.4",
      "react-native-image-zoom-viewer": "^3.0.1",
      "react-native-keyboard-manager": "^4.0.13-16",
      "react-native-keychain": "^8.0.0",
      "react-native-linear-gradient": "git://github.com/react-native-linear-gradient/react-native-linear-gradient#master",
      "react-native-localization": "^2.3.1",
      "react-native-orientation-locker": "^1.2.0",
      "react-native-paper": "^4.6.0",
      "react-native-pdf": "6.6.0",
      "react-native-percentage-circle": "^1.0.7",
      "react-native-permissions": "^3.3.1",
      "react-native-png": "git://github.com/richburke/react-native-png.git#master",
      "react-native-progress": "^5.0.0",
      "react-native-reanimated": "^2.14.4",
      "react-native-receive-sharing-intent": "^2.0.0",
      "react-native-render-html": "^4.2.0",
      "react-native-rest-client": "^0.1.1",
      "react-native-safe-area-context": "^4.3.1",
      "react-native-safe-area-view": "^1.0.0",
      "react-native-screens": "^3.13.1",
      "react-native-share": "^7.2.1",
      "react-native-shared-preferences": "^1.0.2",
      "react-native-simple-radio-button": "^2.7.4",
      "react-native-simple-toast": "^1.1.2",
      "react-native-snap-carousel": "^3.9.1",
      "react-native-sound-player": "^0.11.0",
      "react-native-stars": "^1.1.5",
      "react-native-svg": "^12.4.3",
      "react-native-tracking-transparency": "^0.1.1",
      "react-native-tts": "^4.1.0",
      "react-native-vector-icons": "^7.0.0",
      "react-native-video": "^6.0.0-alpha.1",
      "react-native-view-shot": "^3.1.2",
      "react-native-watch-connectivity": "^1.1.0",
      "react-native-webview": "12.0.2",
      "react-native-zip-archive": "^5.0.6",
      "react-redux": "^7.1.3",
      "react-timestamp": "^4.4.0",
      "realm": "11.2.0",
      "recyclerlistview": "^3.0.0",
      "recyclerlistview-gridlayoutprovider": "^1.0.1",
      "redux": "^4.0.5",
      "redux-devtools-extension": "^2.13.8",
      "redux-thunk": "^2.3.0",
      "simple-common-utils": "^2.6.0",
      "utf8": "^3.0.0"
    },
    "devDependencies": {
      "@babel/core": "^7.12.9",
      "@babel/runtime": "^7.12.5",
      "@bugsnag/source-maps": "^2.3.1",
      "@react-native-community/eslint-config": "^2.0.0",
      "babel-jest": "^26.6.3",
      "eslint": "^7.32.0",
      "jest": "^26.6.3",
      "metro-react-native-babel-preset": "0.72.3",
      "react-test-renderer": "18.1.0"
    },
    "jest": {
      "preset": "react-native"
    },
    "react-native": {
      "@react-native-firebase/admob": false
    }
  }`

**Comment by kneth** [comment] 2023-05-03 14:02
We have seen issues like this with `react-native-reanimated` in the past. And you might have to double-check your `package-lock.json` if the versions are compatible.

**Comment by takameyer** [comment] 2023-06-27 12:03
Can you provide a repo that reproduces this issue?

**Comment by kneth** [comment] 2023-07-14 12:40
I am closing the issue due to no reply back. Please create a new issue if you have new observations to share.

**Closed by kneth** 2023-07-14 12:40 UTC
Labels: T-Bug, O-Community, Waiting-For-Reporter, Repro:No, SDK-Use:Local, Encryption:Off, Frequency:Sometimes
