### ISSUE TITLE
Accessing object of type X which has been invalidated or deleted

### ISSUE THREAD

**Issue by L3V147H4N** [realm/realm-js#1031] opened 2017-05-24 14:40 UTC
Even though the `.isValid` method is present in both collection and object, neither of them is doing anything to prevent this error.

I tried using Collection.isValid, Object.isValid, Results.snapshot .. nothing works

I'm rendering the Results on one view and if I delete one Object in another view and then return it throws this error.

![photo_2017-05-24_11-37-18](https://cloud.githubusercontent.com/assets/5846479/26408903/6d05675a-4075-11e7-8aa1-46f709d7cc17.jpg)

here is my code for the 2 views

```jsx
import React, { Component } from 'react';
import {
  InteractionManager
} from 'react-native';
import {
  Body,
  Button,
  Container,
  Content,
  Fab,
  Footer,
  FooterTab,
  Header,
  Icon,
  Input,
  Item,
  Left,
  List,
  ListItem,
  Right,
  Text,
  Title,
  View
} from 'native-base';
import realm from '../realm';

class CharactersScreen extends Component {

  constructor (props) {
    super(props);

    this.characters = realm.objects('Character');
    this.state = {
      searchBar: {
        active: false
      },
      characters: this.characters
    };
  }

  navigateToAddCharacter = () => {
    let { navigate } = this.props.navigation;

    navigate('AddCharacter');
  }

  static navigationOptions = {
    title: 'Characters',
    headerRight: <View style={{ flexDirection: 'row' }}>
      <Button transparent><Icon name="md-search"/></Button>
      <Button transparent><Icon name="md-funnel"/></Button>
    </View>
  }

  listenToRealm = (name, changes) => {
    this.setState({
      characters: this.characters
    });
  }

  componentWillMount () {
    InteractionManager.runAfterInteractions(() => {
      this.characters.addListener(this.listenToRealm);
    });
  }

  componentWillUnmount () {
    this.characters.removeListener(this.listenToRealm);
  }

  render () {
    let { navigate } = this.props.navigation;
    let {
      searchBar,
      characters
    } = this.state;

    return (
      <Container>
        {
          searchBar.active ?
            <Header searchBar rounded>
              <Item>
                <Icon name="md-search" />
                <Input placeholder="Search" />
                <Icon name="md-people" />
              </Item>
              <Button transparent>
                <Text>Search</Text>
              </Button>
            </Header> : null
        }
        <Content>
          <List>
            {
              characters.map((character, index) => {
                return (
                  <ListItem
                    key={index} onPress={navigate.bind(null, 'CharacterDetails', {
                      character
                    })}>
                    <Body>
                      <Text>{character.name}</Text>
                      <Text note>{character.note}</Text>
                    </Body>
                    <Right>
                      <Icon name="md-arrow-round-forward" />
                    </Right>
                  </ListItem>
                );
              })
            }
          </List>
        </Content>
        <Fab
          active={false}
          direction="top"
          containerStyle={{ marginLeft: 10 }}
          style={{ backgroundColor: '#5067FF' }}
          position="bottomRight"
          onPress={this.navigateToAddCharacter}>
            <Icon name="md-add" />
        </Fab>
      </Container>
    );
  }
}

export default CharactersScreen;

```

Here is the view where I delete the object

```jsx
import React, { Component } from 'react';
import {
  Alert
} from 'react-native';
import {
  Body,
  Button,
  Card,
  CardItem,
  Container,
  Content,
  Icon,
  Left,
  Right,
  Text
} from 'native-base';
import realm from '../realm';

class CharacterDetailsScreen extends Component {

  static navigationOptions = {
    title: 'Character: Details'
  }

  promptDelete = () => {
    Alert.alert(
      'Delete Character',
      'Deleting is irreversible, are you sure?',
      [
        { text: 'Cancel', onPress: () => false },
        { text: 'OK', onPress: () => this.deleteCharacter() }
      ],
      { cancelable: false }
    );
  }

  deleteCharacter = () => {
    let {
      state: {
        params: {
          character
        }
      }
    } = this.props.navigation;
    let { goBack } = this.props.navigation;

    realm.write(() => {
      realm.delete(character);
    });

    goBack();
  }

  render () {
    let {
      navigate,
      state: {
        params: {
          character
        }
      }
    } = this.props.navigation;

    return (
      <Container>
        <Content>
          <Card>
            <CardItem header>
              <Left>
                <Icon name={character.favorite ? 'md-star' : 'md-person'}/>
                <Body>
                  <Text>{character.name}</Text>
                  <Text note>{character.note}</Text>
                </Body>
              </Left>
            </CardItem>
            <CardItem>
              <Body>
                <Text>{character.description}</Text>
              </Body>
            </CardItem>
            <CardItem>
              <Body>
                <Text>Status</Text>
                <Text note>{character.status}</Text>
              </Body>
            </CardItem>
            <CardItem>
              <Left>
                <Button onPress={this.promptDelete} transparent>
                  <Icon name="md-close" style={{ color: '#FF0000' }} />
                  <Text style={{ color: '#FF0000' }}> Delete</Text>
                </Button>
              </Left>
              <Right>
                <Button transparent>
                  <Icon name="md-create" />
                  <Text> Edit</Text>
                </Button>
              </Right>
            </CardItem>
          </Card>
        </Content>
      </Container>
    );
  }
}

export default CharacterDetailsScreen;

```

**Comment by EyalSi** [comment] 2017-05-28 13:02
I have the same Error!. It seems that if you pass an object to navigation, delete this object (while the object is still in the navigation stack), - it will trigger this error. I found it is working if I pass an id, retrieve again the object on the navigated view and then make the deletion. 
But this is sure not the right solution...

**Comment by JamesLi2013** [comment] 2017-06-22 09:41
I have the same Error too.situation : React Native Android ,Navigation ,delete the object,when click back,error happen.

**Comment by gutoglup** [comment] 2017-09-05 17:24
I have the same situation in iOS.

**Comment by lossen** [comment] 2017-09-12 11:35
I have the same error :(

**Comment by irsyadmhdilham** [comment] 2017-09-14 18:39
+1

**Comment by jgreen01** [comment] 2017-09-18 18:09
You need to use [`Realm.open`](https://realm.io/docs/javascript/1.11.0/api/Realm.html#.open) and you'll need to [query](https://realm.io/docs/javascript/1.11.0/api/Realm.Collection.html) for the object you want to delete.

Also it's a good idea to separate your realm code from your presentation code, see discussion [here](https://github.com/realm/realm-js/issues/141).

This is how I'm using realm to dispatch a redux action using `redux-thunk`.
```
const retriveSettings = () => (dispatch) => {
  return Realm.open({
    schema: [SettingsSchema],
    schemaVersion: SettingsSchema.schemaVersion
  })
  .then(realm => {
    const settings = realm.objects('Settings').find(({ id }) => (id === 0));
    dispatch({
      type: types.RETRIEVED_SETTINGS,
      settings
    });
  })
  .catch(e => console.log(e));
}
```

**Comment by EyalSi** [comment] 2017-09-26 06:29
Any chance to check this one? Otherwise, it's a massive refactor...

**Comment by lossen** [comment] 2017-09-27 03:41
I found what I was a mistake. After removal of the **Realm Object**, I have not updated the store and apply to him on the screen where I had this error. That is, the problem was that I apply to already remote data. _I solved the problem_, just updating the store after deleting the **Realm Object**.
Perhaps someone it will be useful.

**Comment by martijngerrits** [comment] 2017-09-27 19:54
I had this issue as wel. The reason why was that I was referencing to an object of the Realm DB in a list view. In my particular case the solution was creating a clone of the object to use in the list:
`Object.assign({}, realmObject);`

This way when a row was deleted all references within the row pointed to that cloned object instead of an object from realm that did not exist anymore.

Maybe this is of some use for someone ;)

**Comment by radiegtya** [comment] 2017-10-08 00:47
+1

**Comment by lodev09** [comment] 2017-10-31 05:27
in your schemas, extend them with `Realm.Object`. You can then call `object.isValid()` to check if the object still exists in realm.

see [example here](https://github.com/realm/realm-js/issues/141#ref-issue-231063626)

**Comment by stlemon** [comment] 2017-12-01 11:59
how to resolve this problem? had the same error

**Comment by prabhu** [comment] 2017-12-02 23:26
Wasted everyone's time in the last couple of days with this bug which was getting wrapped in another error in our codebase. Any fixes in sight?

**Comment by minhcasi** [comment] 2018-01-06 08:30
same error !

**Comment by inspireui** [comment] 2018-01-06 12:36
resolved my issues, just make sure the Realm object not loading from Redux store after deleted then it will be fixed.

**Comment by vance-liu** [comment] 2018-01-09 09:13
same error ! I delete one then query all, red box~

**Comment by vance-liu** [comment] 2018-01-09 09:35
resolved this error, just do not filter array of RealmObject, I convert each RealmObject to PlainObject, and it works well.

**Comment by stlemon** [comment] 2018-01-13 08:31
@vance-liu 你好，convert each RealmObject to PlainObject 如何实现？可以贴一下代码吗？被这个问题困扰好久了～

**Comment by huuquan95** [comment] 2018-02-26 02:19
Thanks all, I make the copy of the Realm array object, so I did well. Maybe it has links between realm objects. Can you guys explain more for me? I have just do with ReactNative for 2 months.

**Comment by esutton** [comment] 2018-03-06 01:53
@objectForPrimaryKey Can you please elaborate on how you resolved your issue?

> resolved my issues, just make sure the Realm object not loading from Redux store after deleted then it will be fixed.

I have several detail views of the opened realm object loaded in scenes from react-native-router-flux.  

When objected being viewed is deleted I can find no way to get these detail views to gracefully release the deleted the object to prevent a crash no matter how many try catch blocks I add to the detail view scene.

I feel like to avoid a crash I must mark it for deletion and then actually delete it when I know no views are referencing it.

**Comment by EyalSi** [comment] 2018-03-13 11:52
We're almost celebrating this bug it's first birthday, and from the number of people involved here, it seems like it cost a lot of us hours of investigation, with no elegant solution. Is there any chance this one will be solved?
10x!!!

**Comment by adrianolsk** [comment] 2018-04-18 15:45
@EyalSi More then a year (yay),  so to solve the problem here I did this:

```
export const listTasks = (start=0, take=10) =>
  new Promise((resolve, reject) => {
    Realm.open(config)
      .then(realm => {
        let tasks = realm.objects(TASK_SCHEMA).slice(start, start+ take );
        resolve(tasks.map(x=>x));
      })
      .catch(error => reject(error));
  });
```
So doing `tasks.map(x=>x)` transform the realm objects in plain objects
Now when I delete the object from the realm it wont give the `Accessing object of type X which has been invalidated or deleted` error.

Another way to avoid the error is using a listener in the filtered realm, so when you delete your objects will be updated. But I was having performances issues with huge lists so I had to paginate the records.

**Comment by deboyblog** [comment] 2018-04-23 09:49
```
let arrayResults = Array.form(realmResults)
plainResults = JSON.parse(JSON.stringfy(results)) // array
```

**Comment by EyalSi** [comment] 2018-04-29 09:30
Duplicating the object will result in performance degradation. Hopped to get a fix in realm.

**Comment by donni106** [comment] 2018-05-11 15:33
For me the array transformation does not work.

```
people() {
  const people = realm.objects('Person').filtered('name != $0', null);
  setTimeout(() => {
    realm.close();
  }, 100);
  return Array.from(people);
}
``` 

1. without the `setTimeout` I get: `Error: Access to invalidated Results objects`, why? And what time could be chosen wisely?
2. Error: `Accessing object of type Person which has been invalidated or deleted`

What can I do in order to continue working?

**Comment by erick2014** [comment] 2018-05-17 02:00
Same problem here :/

**Comment by theapache64** [comment] 2018-05-26 16:59
In Node.js, I could "PATCH" the issue with below given code. 
```
const genreJsonString = JSON.stringify(genre);

    genreRealm.write(()=>{
       genreRealm.delete(genre);
    });

    resp.send(JSON.parse(genreJsonString));
```

**Comment by kunalqss** [comment] 2018-07-03 07:12
@lossen how do we reset the redux store ? I created a dispatch action (I'm using redux sage) to "reset" the state to its initial state but still got this error. I followed [this](https://alligator.io/redux/reset-state-redux/).

**Comment by kenkotch** [comment] 2018-07-04 17:06
I've gotten this error a few times but cant get it to reliably repeat. Can anyone confirm this only happens in debug builds, not release? Obviously on release we wouldn't get the warning, just failure.

**Comment by shllg** [comment] 2018-07-17 11:33
Same issue here. I'm writing an object to realm and it's visible via Realm Studio. So it's definitely persisted. Then when fetching the Objects of the Model, each value of each model ist "Accessing object..." like the error message. The objects were loaded once in development. Since then, it didn't work anymore. No code changes in between...

**Comment by kunalqss** [comment] 2018-07-17 11:44
This is how I solved this problem - 

First I created a function in my utils package - 

```
export function convertToArray(realmObjectsArray)
{
    let copyOfJsonArray = Array.from(realmObjectsArray);
    let jsonArray = JSON.parse(JSON.stringify(copyOfJsonArray));
    return jsonArray;
}
```

Then, I used it to query Realm - 
```
...
let allServicePlans = realm.objects(ScheduleSchema.name);
allServicePlans = convertToArray(allServicePlans);
return allServicePlans;
...
```

Haven't noticed any performance issues till now, and have also gotten rid of that error for now it seems.

**Comment by adrianolsk** [comment] 2018-07-19 18:44
@kunalqss Could you try just this to see if it works for you?

```
let allServicePlans = realm.objects(ScheduleSchema.name);
return allServicePlans.map(service=>({ ...service })));;
```

**Comment by bibodeng** [comment] 2018-07-29 17:12
same error

**Comment by esutton** [comment] 2019-02-21 15:29
@lodev09 Thank you for the [example](https://github.com/realm/realm-js/issues/141#ref-issue-231063626) on how to extend my class
````
class Car extends Realm.Object {
````
I can now call isValid() on my object.

Unfortunately this is no a solution to my crashes as it **always** returns true.

**Comment by lodev09** [comment] 2019-02-21 19:52
@esutton it shouldn't return `true` if the object is not valid e.g. deleted from realm

**Comment by mitchclevertronics** [comment] 2019-03-20 23:56
try 

 if realmobject.isInvalidated {
}

**Comment by bachlongkocanh** [comment] 2019-03-29 07:13
I still issues, how to resolve it?

**Comment by diegolmello** [comment] 2019-04-10 14:22
Hi, there.
IMO this is *not* a Realm issue, because it's just a mutable object being passed around as a prop and being deleted.
One of the first things a new developer using Realm will do is fetch data, save it in Realm and pass it through props to another component as a master/detail.
It's pretty obvious he's going to use navigation too and he won't have any idea this will break.

I don't know if there's a best practice for this case yet and I use Realm for about three years 🤔 
What should we do?
- `JSON.parse(JSON.stringify(object))` or `Object.assign`? (this is error prone)
- pass only object id as prop and query on children?
- another way?

Related issues: #394, #443, #1671, #2091 

@tgoyne @cmelchior @kraenhansen @kneth 
Sorry about the flood. Just trying to raise attention.

**Comment by onderonur** [comment] 2019-10-09 19:38
I have a lot of doubts about using realm.js with react-native. I agree it is fast as a lightning. But speed is **not** everything. Realm mutates its data (which doesn't play well with react), its listeners don't give you a lot of information about data changes (so you would maybe update your state/store using some immutable way), it messes a lot with chrome debugging and making it useless and finally this issue. I don't see a benefit of realm other than its speed. I made a demo by using realm vs TypeOrm + SQLite and yep, realm was faster. But when you use TypeOrm the right way, it really comes close to realm.

Using realm for a complex react-native project can become a million dollar mistake easily. You can't debug it (they say it works with Safari but a lot of people use Google Chrome, react-native-debugger etc.), it becomes so unpredictable because of mutations, you just try to understand what is going on by using `console.warn` or `react-native log-android`.

I think realm should have a package to integrate with react. Like mobx does. Or react-redux. Or react-apollo. They integrate your react components with the library itself. And that's it. You don't have to worry about that anymore. All the complex things to handle just abstracted away from you.

I really don't understand how so many people and blog posts just recommend realm for react-native and don't show you a good way to handle data mutations, debugging etc.

[react-realm-context](https://github.com/realm/react-realm-context) may look like a good package. We are using a mildly modified version of it. It definitely eases a lot of hard work for you. But this issue still stands there.

Anyway, when we come to this problem, I think using JSON.parse(JSON.stringify(...)) may cause a lot of performance problems. It may cause a lot of unnecessary re-renders. And you know, react-native needs some performance optimizations and best practices to handle complex components or lists. So it might cause much more problems.

We are using some kind of a "soft delete" way. We don't delete any record from realm. We create each table with a `__isDeleted` field. When we delete a record, we just flip its value to `true`. Just filter them to not show on screens. Don't post them to your APIs. You can choose some time (like the initiliazationn of the application) to **really** delete this soft deleted records.

**Comment by kraenhansen** [comment] 2019-10-10 07:29
> We are using a mildly modified version of it. It definitely eases a lot of hard work for you. But this issue still stands there.

@onderonur: I would love to know what mild modifications you've made, what would make the [react-realm-context](https://github.com/realm/react-realm-context) package better. We would love upstream PRs too :)

**Comment by onderonur** [comment] 2019-10-14 08:31
> > We are using a mildly modified version of it. It definitely eases a lot of hard work for you. But this issue still stands there.
> 
> @onderonur: I would love to know what mild modifications you've made, what would make the [react-realm-context](https://github.com/realm/react-realm-context) package better. We would love upstream PRs too :)

Actually, I don't think our modifications will be useful for the package itself :)
Like I said, we simply use a flag for deleted items. And we are always checking if the `__isDeleted` field is true or false. So instead of doing it on every single query component, our base query component filters them by default. And we added a component called "garbage cleaner" to wipe these soft deleted records out at a particular time like initialization of the app.

An additional and useful component is `QueryById`. It simply gets a `type` and a `id` prop to return a single record. It just wraps the `Query` component, you know. But it is something we use very often.

On of the changes was, we are still using the `RealmProvider`, but we initialize realm as a singleton and pass it to the provider. Like `Provider` of `react-redux`. We wanted to use the realm instance in places like redux action creators etc. Accessing it through the provider is a great pattern inside components. But rather than passing the realm instance as a parameter to external functions, we just wanted to use a singleton.

This might have a lot of side-effects for some cases. I wouldn't recommend to add this to the package itself. It is just something useful for our cases :)

**Comment by SrikaraBhat** [comment] 2020-01-22 05:09
> Even though the `.isValid` method is present in both collection and object, neither of them is doing anything to prevent this error.
> 
> I tried using Collection.isValid, Object.isValid, Results.snapshot .. nothing works
> 
> I'm rendering the Results on one view and if I delete one Object in another view and then return it throws this error.
> 
> ![photo_2017-05-24_11-37-18](https://cloud.githubusercontent.com/assets/5846479/26408903/6d05675a-4075-11e7-8aa1-46f709d7cc17.jpg)
> 
> here is my code for the 2 views
> 
> ```js-jsx
> import React, { Component } from 'react';
> import {
>   InteractionManager
> } from 'react-native';
> import {
>   Body,
>   Button,
>   Container,
>   Content,
>   Fab,
>   Footer,
>   FooterTab,
>   Header,
>   Icon,
>   Input,
>   Item,
>   Left,
>   List,
>   ListItem,
>   Right,
>   Text,
>   Title,
>   View
> } from 'native-base';
> import realm from '../realm';
> 
> class CharactersScreen extends Component {
> 
>   constructor (props) {
>     super(props);
> 
>     this.characters = realm.objects('Character');
>     this.state = {
>       searchBar: {
>         active: false
>       },
>       characters: this.characters
>     };
>   }
> 
>   navigateToAddCharacter = () => {
>     let { navigate } = this.props.navigation;
> 
>     navigate('AddCharacter');
>   }
> 
>   static navigationOptions = {
>     title: 'Characters',
>     headerRight: <View style={{ flexDirection: 'row' }}>
>       <Button transparent><Icon name="md-search"/></Button>
>       <Button transparent><Icon name="md-funnel"/></Button>
>     </View>
>   }
> 
>   listenToRealm = (name, changes) => {
>     this.setState({
>       characters: this.characters
>     });
>   }
> 
>   componentWillMount () {
>     InteractionManager.runAfterInteractions(() => {
>       this.characters.addListener(this.listenToRealm);
>     });
>   }
> 
>   componentWillUnmount () {
>     this.characters.removeListener(this.listenToRealm);
>   }
> 
>   render () {
>     let { navigate } = this.props.navigation;
>     let {
>       searchBar,
>       characters
>     } = this.state;
> 
>     return (
>       <Container>
>         {
>           searchBar.active ?
>             <Header searchBar rounded>
>               <Item>
>                 <Icon name="md-search" />
>                 <Input placeholder="Search" />
>                 <Icon name="md-people" />
>               </Item>
>               <Button transparent>
>                 <Text>Search</Text>
>               </Button>
>             </Header> : null
>         }
>         <Content>
>           <List>
>             {
>               characters.map((character, index) => {
>                 return (
>                   <ListItem
>                     key={index} onPress={navigate.bind(null, 'CharacterDetails', {
>                       character
>                     })}>
>                     <Body>
>                       <Text>{character.name}</Text>
>                       <Text note>{character.note}</Text>
>                     </Body>
>                     <Right>
>                       <Icon name="md-arrow-round-forward" />
>                     </Right>
>                   </ListItem>
>                 );
>               })
>             }
>           </List>
>         </Content>
>         <Fab
>           active={false}
>           direction="top"
>           containerStyle={{ marginLeft: 10 }}
>           style={{ backgroundColor: '#5067FF' }}
>           position="bottomRight"
>           onPress={this.navigateToAddCharacter}>
>             <Icon name="md-add" />
>         </Fab>
>       </Container>
>     );
>   }
> }
> 
> export default CharactersScreen;
> ```
> 
> Here is the view where I delete the object
> 
> ```js-jsx
> import React, { Component } from 'react';
> import {
>   Alert
> } from 'react-native';
> import {
>   Body,
>   Button,
>   Card,
>   CardItem,
>   Container,
>   Content,
>   Icon,
>   Left,
>   Right,
>   Text
> } from 'native-base';
> import realm from '../realm';
> 
> class CharacterDetailsScreen extends Component {
> 
>   static navigationOptions = {
>     title: 'Character: Details'
>   }
> 
>   promptDelete = () => {
>     Alert.alert(
>       'Delete Character',
>       'Deleting is irreversible, are you sure?',
>       [
>         { text: 'Cancel', onPress: () => false },
>         { text: 'OK', onPress: () => this.deleteCharacter() }
>       ],
>       { cancelable: false }
>     );
>   }
> 
>   deleteCharacter = () => {
>     let {
>       state: {
>         params: {
>           character
>         }
>       }
>     } = this.props.navigation;
>     let { goBack } = this.props.navigation;
> 
>     realm.write(() => {
>       realm.delete(character);
>     });
> 
>     goBack();
>   }
> 
>   render () {
>     let {
>       navigate,
>       state: {
>         params: {
>           character
>         }
>       }
>     } = this.props.navigation;
> 
>     return (
>       <Container>
>         <Content>
>           <Card>
>             <CardItem header>
>               <Left>
>                 <Icon name={character.favorite ? 'md-star' : 'md-person'}/>
>                 <Body>
>                   <Text>{character.name}</Text>
>                   <Text note>{character.note}</Text>
>                 </Body>
>               </Left>
>             </CardItem>
>             <CardItem>
>               <Body>
>                 <Text>{character.description}</Text>
>               </Body>
>             </CardItem>
>             <CardItem>
>               <Body>
>                 <Text>Status</Text>
>                 <Text note>{character.status}</Text>
>               </Body>
>             </CardItem>
>             <CardItem>
>               <Left>
>                 <Button onPress={this.promptDelete} transparent>
>                   <Icon name="md-close" style={{ color: '#FF0000' }} />
>                   <Text style={{ color: '#FF0000' }}> Delete</Text>
>                 </Button>
>               </Left>
>               <Right>
>                 <Button transparent>
>                   <Icon name="md-create" />
>                   <Text> Edit</Text>
>                 </Button>
>               </Right>
>             </CardItem>
>           </Card>
>         </Content>
>       </Container>
>     );
>   }
> }
> 
> export default CharacterDetailsScreen;
> ```

Solution: 

Inside the constructor add one realm listener: So that, soon after change in DB, Screen Data should get refresh.
Your action should contain one realm listener to monitor changes in db. Something like this: 

realm.addListener('change', () => {
      this.loadData();
    });

**Comment by mshavima** [comment] 2020-03-28 13:34
```
export function convertToArray(realmObjectsArray)
{
    let copyOfJsonArray = Array.from(realmObjectsArray);
    let jsonArray = JSON.parse(JSON.stringify(copyOfJsonArray));
    return jsonArray;
}
```
I have used the same it is working fine but having performance issue for large data in db. Below is the code that working for me with better performance.

```
export async function getData(schema, filterVariables){
    return await Realm.open(databaseOption).then( async realm => {
        try {
          let data = [];
            if(filterVariables){
                data = realm.objects(schema).filtered(filterVariables);
                data =  cloneDeep(_.toArray(data));
            }else{
              data = realm.objects(schema);
              data =  cloneDeep(_.toArray(data));
            }
            realm.close();
            return {success: true, data: data};
        }
        catch (e) {
            realm.close();
            return {success: false};
        }
    })
};
```

**Comment by BruceSuperProgramer** [comment] 2020-06-04 00:35
> @vance-liu 你好，convert each RealmObject to PlainObject 如何实现？可以贴一下代码吗？被这个问题困扰好久了～

Object.assign({}, realmObject);

**Comment by BruceSuperProgramer** [comment] 2020-06-04 01:35
> We're almost celebrating this bug it's first birthday, and from the number of people involved here, it seems like it cost a lot of us hours of investigation, with no elegant solution. Is there any chance this one will be solved?
> 10x!!!

It has two years old in 2020.

**Comment by techromantic** [comment] 2020-06-07 18:33
I had this problem today - deleting an object from the underlying realm store will break any flatlist relying on a list of its results. 

The majority of solutions in this discussion are the wrong way of working with realm. The entire point of using a no-copy mobile database is exactly that - not to copy - converting & deconverting objects is adding extra overhead that will get worse as n gets higher. 

For my specific problem i was able to skirt the issue, FlatLists can use an ExtraData prop to know when to rerender themselves. In your delete action, you must trigger the change of this extra data flag before you actually delete. Additionally you must set up your component to query realm directly when it starts up. 

This is the best way to handle it for my particular and seems to be working well.

**Comment by BruceSuperProgramer** [comment] 2020-06-09 00:40
@techromantic  Thanks for the nice post. I haven't tried the extra data option to solve this issue. It sounds a bit complex than using listeners to solve the problem. I used the listener to solve this issue and it works out great.

**Comment by earonesty** [comment] 2020-07-27 17:47
@techromantic your post frames the problem precisely: realm is a zero copy system... an object should be properly ref-counted when used so that it's always valid.  the "correct" solution would be to a) fix realm or b) ref count the object yourself... so that deletions are "lazy" and only proceed when all refs are freed up.

**Comment by AmalMenachery** [comment] 2020-08-27 07:00
@alazier / @tgoyne / @kneth /  @appden - Any Updates on this one ?

**Comment by Captn-Nemo** [comment] 2020-09-08 07:10
This problem occurs when you try to access a realm object (which has been already deleted by you ) from store , or any variable. The solution is simple , when you're deleting realm data along side clear that data from global variables and stores ,ie just clear out all the variables that are holding the corresponding.

**Comment by AmalMenachery** [comment] 2020-09-08 11:34
> This problem occurs when you try to access a realm object (which has been already deleted by you ) from store , or any variable. The solution is simple , when you're deleting realm data, along side clear that data from global variables and stores variables, ,ie just clear out all the variables that are holding the corresponding realm data.

@Captn-Nemo I had already fetched and stored the realm data in redux state.  If I delete the data from realm, what it has to do with the data in the redux state. Ideally if I fetch data from DB and store it locally, unless I delete the local variable, the data should be available in the local variable regardless of operations I do in the DB. This issue sounds like a copy by reference issue to me from realm side. Realm-js provides a reference to realm object in the realm get call. Hence the problem.
@earonesty 's comments too suggest in that direction.

**Comment by AmalMenachery** [comment] 2020-09-08 11:37
> > This problem occurs when you try to access a realm object (which has been already deleted by you ) from store , or any variable. The solution is simple , when you're deleting realm data, along side clear that data from global variables and stores variables, ,ie just clear out all the variables that are holding the corresponding realm data.
> 
> @Captn-Nemo I had already fetched and stored the realm data in redux state. If I delete the data from realm, what it has to do with the data in the redux state?
> Ideally if I fetch data from DB and store it locally, unless I delete the local variable, the data should be available in the local variable regardless of operations I do in the DB. This issue sounds like a copy by reference issue to me from realm side. Realm-js provides a reference to realm object in the realm get call. Hence the Issue. @earonesty 's comments too suggest in that direction.

btw Yes, I had the fixed the issue as you suggested, but Isn't a patch rather than actual fix ?

**Comment by Ritcheyy** [comment] 2020-12-13 19:22
Adding `realm.addListener('change', () => {
    this.fetchData(); 
});` to the constructor block worked for me.

or in `useEffect(() => {
}, [])` for a function component.

**Closed** 2021-01-29 14:37 UTC
Labels: O-Community, T-Bug

**Comment by ploureiro** [comment] 2021-02-03 13:03
Hey community,
I followed this issue during its past 3 years life. And the motive for the issue to happen is pretty obvious with known solutions. I'dont know why it's now considered "**closed**".

I think this ticket somehow worked like a documentation ticket for RN devs.

Here my suggestion to really close it, with an usefully impact in the community:
- Change the error title and description with something more understandable by the developer.
- Add to the documentation some comments in this ticket, very usefully in the implementation process.

Thanks again to all, who worked on this!

**Comment by kneth** [comment] 2021-02-24 08:34
@ploureiro Thank you for your feedback. I closed the issue as "answered by the community" which seems to be accurate as you mention it has served as documentation. The RJS team will have to find a way to document issue like this.

**Comment by kneth** [comment] 2021-02-26 16:23
I have created a [new issue](https://github.com/realm/realm-js/issues/3615) to track us documenting it.

**Comment by MrGVSV** [comment] 2021-03-31 00:19
> We are using some kind of a `soft delete` way.

I needed to keep a reference to deleted objects for some animations (something just fetching after a change can't do without copying data). This solution works nicely and also has the added benefit of allowing an easy "undo" for free.

**Comment by abhilashiic** [comment] 2021-11-11 10:20
I don't know what is happening here. But when I was trying to run delete query, and after that when I try to go on other screens, it returns the above error. 
Then I reload the list after deleting the object on the same screen. **The error forgave me.** 

Hence, for me, the solution was to 'query' the same collection immediately after deleting records.  

1. `delete the records`
2. `find query in the same collection`

**Comment by fajzanetti** [comment] 2021-11-18 15:06
same error

**Comment by lilingxi01** [comment] 2022-03-12 14:17
Just a memo: this issue can also be triggered by the "hot refresh" of react native dev. If you are facing this issue and have no idea on that, check if it only happens after a hot refresh.

**Comment by stlemon** [comment] 2022-03-12 14:18
这是来自 郎需磊 邮箱的自动回复邮件。
 
您好，感谢您的来信！
我查阅后，会尽快回复您！

**Comment by evaldovega** [comment] 2022-07-20 17:50
/*
obj es un objeto realm preguntar si es valido antes de renderizar la vista
*/

if (!obj.isValid()) {
    return null;
  }

**Comment by stlemon** [comment] 2022-07-20 17:51
这是来自 郎需磊 邮箱的自动回复邮件。
 
您好，感谢您的来信！
我查阅后，会尽快回复您！

**Comment by thespacemanatee** [comment] 2022-08-07 09:56
This is still happening and honestly, sometimes I wish I didn't choose Realm even though it has merits in other areas. This kind of bug breaks the entire experience for our team.

**Comment by stlemon** [comment] 2022-08-07 09:56
这是来自 郎需磊 邮箱的自动回复邮件。
 
您好，感谢您的来信！
我查阅后，会尽快回复您！

**Comment by kneth** [comment] 2022-08-08 08:32
@thespacemanatee Do you see an exception or a crash? An exception could indicate an issue in the app.

Please create a new issue with a reproduction case.

**Comment by stlemon** [comment] 2022-10-11 08:04
这是来自 郎需磊 邮箱的自动回复邮件。
 
您好，感谢您的来信！
我查阅后，会尽快回复您！

**Comment by stlemon** [comment] 2022-10-27 18:22
这是来自 郎需磊 邮箱的自动回复邮件。
 
您好，感谢您的来信！
我查阅后，会尽快回复您！

**Comment by anupsamanta** [comment] 2023-01-11 13:38
What is obj here?
> 
> 
>     
>       
>     
> 
>       
>     
> 
>

**Comment by stlemon** [comment] 2023-01-11 13:39
这是来自 郎需磊 邮箱的自动回复邮件。
 
您好，感谢您的来信！
我查阅后，会尽快回复您！

**Comment by EM-Sabeel** [comment] 2023-01-11 13:58
> What is obj here?
> 
> >

Pls check updated 
Obj is just reference of realm object

**Comment by Marcuspo** [comment] 2023-01-27 19:52
+1

**Comment by stlemon** [comment] 2023-01-27 19:52
这是来自 郎需磊 邮箱的自动回复邮件。
 
您好，感谢您的来信！
我查阅后，会尽快回复您！
