### ISSUE TITLE
Realm crash when model extends another class extending Realm.Object 

### ISSUE THREAD

**Issue by GregoryEsberci** [realm/realm-js#5126] opened 2022-11-21 20:53 UTC
### How frequently does the bug occur?

All the time

### Description

When one or more models indirectly extends 'Realm.Object' the app reports an error

### Stacktrace & log output

```shell
Error: Exception in HostFunction: Class 'Task' must extend Realm.Object
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

using the [JavaScript template](https://github.com/realm/realm-js/tree/master/templates/react-native-template-realm-js#readme) replace the file `app/models/Task.js` content for this and try run the app

```js
import Realm from 'realm';

class ModelBase extends Realm.Object {
  someMethod() {
    console.log('someMethod');
  }
}

export class Task extends ModelBase {
  constructor(realm, description, userId) {
    super(realm, {description, userId: userId || '_SYNC_DISABLED_'});
  }

  // To use a class as a Realm object type in JS, define the object schema on the static property "schema".
  static schema = {
    name: 'Task',
    primaryKey: '_id',
    properties: {
      _id: {
        type: 'objectId',
        default: () => new Realm.BSON.ObjectId(),
      },
      description: 'string',
      isComplete: {type: 'bool', default: false},
      createdAt: {type: 'date', default: () => new Date()},
      userId: 'string',
    },
  };
}

console.log('Task', Task.prototype instanceof Realm.Object); // => true

```

### Version

11.2.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 11 and ios 16.1

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment] 2022-11-22 18:21
@GregoryEsberci 

Currently we don't support polymorphic inheritance, but we understand that it is a useful feature. Across the Realm SDKs we are looking at how we can provide a good solution but unfortunately I can't give you a timeline for when we can introduce it.

**Comment by kneth** [comment] 2022-11-23 08:20
I close it as a duplicate of https://github.com/realm/realm-js/issues/1839

**Closed by kneth** 2022-11-23 08:20 UTC
Labels: T-Bug, O-Community
