### ISSUE TITLE
Inverse relationship with realm-js

### ISSUE THREAD

**Issue by logileifs** [realm/realm-js#588] opened 2016-09-07 16:08 UTC
In the Realm swift [documentation](https://realm.io/docs/swift/latest/#inverse-relationships) it is described how to create a many-to-many (inverse relationship). Is there no way yet to create such a relationship in realm-js ?

**Comment by alazier** [comment] 2016-09-08 17:29
We definitely plan to add this soon. There is more information in #343. Closing this as a duplicate of that issue.

**Closed** 2016-09-08 17:30 UTC
Labels: T:Duplicate
