### ISSUE TITLE
compiler error with Xcode 10.2

### ISSUE THREAD

**Issue by ssg1110** [realm/realm-js#2311] opened 2019-03-31 18:08 UTC
## Goals

When I were compiling the React Native Project with "react-native run-ios", the compiler prompts an error.

## Expected Results

No error.

## Actual Results

** BUILD FAILED **

The following commands produced analyzer issues:

        Analyze /*****/node_modules/react-native/React/Base/RCTModuleMethod.mm normal x86_64
        Analyze /*****/node_modules/react-native/Libraries/Network/RCTNetInfo.m normal x86_64
(2 commands with analyzer issues)

The following build commands failed:
        CompileC /*****/ios/build/Build/Intermediates.noindex/RealmJS.build/Debug-iphonesimulator/RealmJS.build/Objects-normal/x86_64/rpc.o /*****/node_modules/realm/src/rpc.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/*****.app
An error was encountered processing the command (domain=IXErrorDomain, code=13):
Failed to get bundle ID from /*****/ios/build/Build/Products/Debug-iphonesimulator/*****.app
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/*****.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/*****.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:601:13)
    at Object.execFileSync (child_process.js:621:13)
    at Promise.then (/*****/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)
    at <anonymous>

## Version of Realm and Tooling

- Realm JS SDK Version: 2.25.0
- React Native: 0.57.8
- Node: v8.11.4
- Client OS & Version: iOS 12.2.0

Also checked with 
- React Native: 0.58.6 and latest, same issue
- Node: 10.15.2

**Comment by gsklee** [comment] 2019-04-02 04:38
Guess it's same issue:
```
** BUILD FAILED **


The following commands produced analyzer issues:

	Analyze /Users/hellohellohello/Projects/rnapp/node_modules/react-native/React/Base/RCTModuleMethod.mm normal x86_64
	Analyze /Users/hellohellohello/Projects/rnapp/node_modules/react-native/Libraries/Network/RCTNetInfo.m normal x86_64
(2 commands with analyzer issues)

The following build commands failed:
	CompileC /Users/hellohellohello/Projects/rnapp/ios/build/Build/Intermediates.noindex/RealmJS.build/Debug-iphonesimulator/RealmJS.build/Objects-normal/x86_64/rpc.o /Users/hellohellohello/Projects/rnapp/node_modules/realm/src/rpc.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by Vadim7394** [comment] 2019-04-03 09:55
I was helped by this solution in solving this problem:
https://github.com/realm/realm-js/issues/2305#issuecomment-476552419

**Comment by ssg1110** [comment] 2019-04-03 11:29
Thanks @Vadim7394 
But In my case, I am getting issue in different file 
##"/ios/build/Build/Intermediates.noindex/RealmJS.build/Debug-iphonesimulator/RealmJS.build/Objects-normal/x86_64/rpc.o"

**Comment by ssg1110** [comment] 2019-04-03 18:34
Thanks @Vadim7394 
I tried solution [#2305 (comment)](https://github.com/realm/realm-js/issues/2305#issuecomment-476552419) and it's works for me

**Comment by ferrannp** [comment] 2019-05-11 13:22
This is fixed in v2.26.1. This should be closed. cc @kneth.

**Comment by hayatae** [comment] 2019-05-20 00:11
Was there a regression in version 2.27.0 for this issue? Just updated to realm v2.27.0 and I'm also getting the following error:

```** BUILD FAILED **

The following commands produced analyzer issues:
	Analyze /Users/user/projects/my-app-new/node_modules/react-native/ReactCommon/jsi/jsi.cpp normal x86_64
	Analyze /Users/user/projects/my-app-new/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp normal x86_64
	Analyze /Users/user/projects/my-app-new/node_modules/react-native/React/Base/RCTModuleMethod.mm normal x86_64
(3 commands with analyzer issues)

The following build commands failed:
	CompileC /Users/user/projects/my-app-new/ios/build/my/Build/Intermediates.noindex/RealmJS.build/Debug-iphonesimulator/RealmJS.build/Objects-normal/x86_64/rpc.o /Users/user/projects/my-app-new/node_modules/realm/src/rpc.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
. Run CLI with --verbose flag for more details.
```

**Comment by kneth** [comment] 2019-05-20 06:22
@hayatae It looks like you are compiling for 64 bit. We are working on it - see #2366.

**Comment by kneth** [comment] 2019-05-21 06:51
@hayatae I might have been too quick to close the issue as a 64 bit issue.

**Comment by claudepark** [comment] 2019-07-25 13:46
I solved this issue.
1. xcode update to recent
2. rebooting mac
3. delete ios/build
4. react-native run-ios

**Closed** 2019-08-07 10:01 UTC
Labels: O:User, T:Enhancement
