### ISSUE TITLE
"TypeError: snapshot method was not called on a Realm object!" when running with RN debugger

### ISSUE THREAD

**Issue by febeling** [realm/realm-js#1765] opened 2018-04-26 09:30 UTC
## Goals

Create a frozen result collection from a query result in react-native while debugging.

## Expected Results

Expect this to work the same way it does when remote debugging is not running.

## Actual Results

An exception is thrown: "TypeError: snapshot method was not called on a Realm object!"

Note that this same query works well when the debugger isn't running. 

This is what the object looks like in the debugger.

<img width="509" alt="screen shot 2018-04-26 at 11 17 25" src="https://user-images.githubusercontent.com/4313/39297839-dcb6946a-4944-11e8-9154-969d3b6e0a20.png">

## Steps to Reproduce

Hope to be able to provide those soon.

## Code Sample

Hope to be able to provide those soon.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.2.20, also 2.4.0.
- Node or React Native: RN 0.55.3
- Client OS & Version: macOS 10.13.4 (17E199), simulating iOS 11.3
- Which debugger for React Native: regular builtin, using Chrome

**Comment by febeling** [comment] 2018-04-26 14:18
Same problem on 2.4.0

**Comment by kneth** [comment] 2018-05-02 12:08
@febeling Thanks for reporting. Just a quick question: are `filtered()` and `sorted()` working in debug mode?

**Comment by febeling** [comment] 2018-05-03 10:11
@kneth I get the same problem with `sorted()` and `filtered()` results here.

**Comment by febeling** [comment] 2018-05-03 10:12
The results are in fact coming from a result listener. Not sure if that adds relevant information.

**Comment by kneth** [comment] 2018-05-04 12:47
@febeling Thanks for the update. Combining your two observations hint that we should investigate the listener code.

**Comment by Sovent** [comment] 2018-08-08 18:53
Hello, any progress on this issue? It's getting really hard to proceed without a debugger

**Comment by febeling** [comment] 2018-09-15 20:02
@kneth Is there anything I can do to help with this?

**Comment by kneth** [comment] 2018-09-24 09:43
@febeling @Sovent No, but if methods like `sorted()` and `snapshot()` ain't working in the debugger, it sounds like the RPC is not triggered in all cases as it should.

**Comment by febeling** [comment] 2018-10-04 06:19
For us this prevents using the debugger anywhere in app development, which is quite a burden. As there has been no progress since late April and apparently no priority on solving this, we now consider replacing realm with an alternative.

**Comment by jaumevn** [comment] 2018-11-29 09:18
Same problem here. Any news on this issue?

**Comment by hcliff** [comment] 2018-12-17 17:20
@kneth I'm running into this without trying to use the browser REPL. that is, if the the debugger isn't attached my code here works:
```
realmListener = (collection: Collection<Match>, changes: CollectionChangeSet) => {
    try{
        const matches = collection.snapshot().slice().map(toPlainMatch);
        console.log("real listener called", matches);
        this.setState({
            matches
        })
    }catch(e){
        console.log("Error", e, collection);
    }
}

componentDidMount() {
    openRealm().then((realm: Realm): void => {
        this.realmStore.addListener(this.realmListener);
    })
}
```
and when remote debugging is enabled I receive the error 
```
Error TypeError: snapshot method was not called on a Realm object!
    at Proxy.<anonymous> (util.js:43)
    at Proxy.MatchesComponent._this2.realmListener (component.tsx:130)
    at sendRequest (rpc.js:290)
    at rpc.js:307
    at JSTimers.js:256
    at _callTimer (JSTimers.js:152)
    at Object.callTimers (JSTimers.js:405)
    at MessageQueue.__callFunction (MessageQueue.js:349)
    at MessageQueue.js:106
    at MessageQueue.__guard (MessageQueue.js:297) Proxy {Symbol(realm): undefined, Symbol(id): 14, …}
```

**Comment by hcliff** [comment] 2018-12-27 21:15
@kneth I got to the bottom of this - another thread was closing the db. the error message wasn't very helpful but really PEBCAK

thanks!

**Comment by kneth** [comment] 2019-01-07 10:19
@hcliff Happy to hear that you got it fixed. I agree that the error message didn't help you. If you can create a very short example to reproduce the situation and error message, we might be able to understand it better - and provide a better error message in the future.

**Comment by xcxooxl** [comment] 2019-01-26 00:54
I also have this issue, But I cant think of a thread that does close on the database
because I didn't implement anywhere a close function.

**Comment by xcxooxl** [comment] 2019-01-26 01:03
@kneth Seems the problem was 

entities is coming from addListener callback
```
this.store.dispatch({type: "UPDATE_CONVERSATIONS", data: [...entities]})
```
doing this instead solved me problem
```let entitiesCopy = entities.map((item) => {return item});
this.store.dispatch({type: "UPDATE_CONVERSATIONS", data: entitiesCopy});```

**Comment by kneth** [comment] 2019-01-28 10:10
@xcxooxl Thanks. And an interesting solution. `entities` are managed objects, and dispatching them seems to the problem. Maybe https://www.npmjs.com/package/realm-react-redux can be useful.

**Comment by febeling** [comment] 2019-05-20 16:13
@kneth I which way is it possible, that dispatching managed objects leads to a crash?

**Comment by chelovekdrakon** [comment] 2019-12-20 11:17
I have the same issue 😔

I have a listener over the results. 
Inside the listener, if I call `.snapshot` over the collection... It leads to a crash in the "debug" mode.

It works well in "release" mode, but in "debug" mode it crashes the app with `Error: "results.snapshot was called on non-Realm object"`

Here is the code sample:
```
const currentFoldersList = FoldersDB
    .objects()
    .filtered(`parentFolderId = "${currentFolderId}" && name CONTAINS[c] "${searchText}"`)
    .sorted('name');
        
currentFoldersList.addListener(this.updateFolders);

this.unsubscribeFolders = () => {
    currentFoldersList.removeListener(this.updateFolders);
};
```
Where 
```
updateFolders = (collection) => {
    this.setState({
        folders: collection.snapshot()
    }); 
}
```

As workaround I did a hack:
```
updateFolders = (collection) => {
    this.setState({
        folders: __DEV__ ? collection : collection.snapshot()
    }); 
}
```

**Comment by chelovekdrakon** [comment] 2019-12-20 11:22
You may ask why do I need a `snapshot()` of the results...

Here is more interesting thig... 
The **results** works very well in **debug** mode and triggers rerender. 
But in **release** mode it **can not rerender** component by `setState`. 
Event `forceUpdate` does not impact! that's crazy :0

**Comment by chelovekdrakon** [comment] 2019-12-20 13:54
@kneth is it any way to **run Realm in release** mode **while I'm actualy in debug** mode?

I found a lot of **inconsistencies** when I test the app first time **in release** mode! 
Many things which **worked in debug** - **does not work in release** anymore and reverse! :)

**Comment by kneth** [comment] 2020-01-06 10:59
No way to using in release mode when debugging. I believe that might actually lead to many more inconsistencies (we have to keep the Realm in the debugger and the device in sync).

The `"results.snapshot was called on non-Realm object"` error does sound like a bug and we need to investigate it.

**Comment by chelovekdrakon** [comment] 2020-01-07 15:09
@kneth would be nice :) May I help somehow?)

**Comment by kneth** [comment] 2020-01-08 08:23
@chelovekdrakon If you can create a small, self-contained example which can reproduce it, it would be a very good start.

**Comment by likern** [comment] 2020-02-12 19:31
@febeling I could confirm this error. Very frustrating experience. Javascript and React Native support always was second-class citizen.

And this is a very critical bug.

Even though according to https://blog.bitrise.io/state-of-app-development-in-2019 React Native has 14% of mobile market share. And definitely will grow.

**Comment by nirinchev** [comment] 2020-02-12 20:13
@likern as Kenneth said, if you can create a small, self-contained example which can reproduce the issue, we'd be happy to take a look.

**Comment by TuTejsy** [comment] 2020-02-19 11:48
https://github.com/realm/realm-js/issues/2730

**Comment by blagoev** [comment] 2020-02-19 15:58
@TuTejsy Could you explain why you insert your issue number in every other issue you can find ?

**Comment by TuTejsy** [comment] 2020-02-20 07:15
> @TuTejsy Could you explain why you insert your issue number in every other issue you can find ?

I think my issue has the same case and connected with mutating objects in realm. The difference that i use one object and here used collection. I insert it here because think, that its possible to reproduce it in my environment

**Comment by kneth** [comment] 2021-01-29 14:12
We have reworked a large part of the Chrome debugger support, and I suggest an upgrade to v10.1.4.

If the issue is still observed, please create a new issue.

**Closed by kneth** 2021-01-29 14:12 UTC
Labels: O-Community, Pipeline-Discussion, T-Bug
