### ISSUE TITLE
More understandable error reporting while doing realm.write()

### ISSUE THREAD

**Issue by csotiriou** [realm/realm-js#773] opened 2017-01-03 10:28 UTC
When trying to write objects with nested lists, I frequently end up getting this:

```
'Property' must be of type: string
```

React native points to the write transaction, and realm does not tell you the name of the property which has the error. It only implies that "some property, somewhere" should be a string, and it isn't. This causes many problems when consuming a big web service, with hundreds of objects inside lists returned, trying to figure out what went wrong (hundreds of man-hours in debugging).

Is it possible to have the name of the property which has the error returned in the error message?

**Comment by kristiandupont** [comment] 2017-01-03 10:36
You are absolutely right, this is something that needs to be improved.

**Comment by csotiriou** [comment] 2017-01-03 11:57
Thanks for confirming. 

Sorry if that sounds pressing but do you have an estimate on when do you intend to take a look at it?

 It's getting really difficult to debug in my case, I am writing hundreds of unit tests to test very simple things. Any suggestions on workarounds (even ugly) would be great in my case. I suspect this is the case with many other devs.

**Comment by csotiriou** [comment] 2017-01-09 10:45
@kristiandupont do you have an estimation on that? We are building a fairly complex application and it's getting increasingly difficult to debug (hours per wrong field), even with excruciating unit testing.

**Comment by kristiandupont** [comment] 2017-01-09 14:05
I'm looking into it now. It will be at least improved in the next release, if not completely fixed.
I'm closing this issue as it's a duplicate of #730.

**Closed by kristiandupont** 2017-01-09 14:05 UTC
Labels: S:P1 Backlog, T:Duplicate
