### ISSUE TITLE
fatal error: 'impl/weak_realm_notifier.hpp' file not found

### ISSUE THREAD

**Issue by RamNalluri** [realm/realm-js#5557] opened 2023-03-11 11:46 UTC
### How frequently does the bug occur?

Always

### Description

/Users/ramnal/.jenkins/workspace/TechConnect-iOS-Dev/Pods/Realm/Realm/ObjectStore/src/impl/weak_realm_notifier.cpp:19:10: fatal error: 'impl/weak_realm_notifier.hpp' file not found #include "impl/weak_realm_notifier.hpp" ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 1 error generated.

The following build commands failed: CompileC /Users/ramnal/Library/Developer/Xcode/DerivedData/TechConnect-etauhdvyspymdnhiwznrmhfgfomr/Build/Intermediates.noindex/ArchiveIntermediates/DEV/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/Realm.build/Objects-normal/arm64/weak_realm_notifier.o /Users/ramnal/.jenkins/workspace/TechConnect-iOS-Dev/Pods/Realm/Realm/ObjectStore/src/impl/weak_realm_notifier.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Realm' from project 'Pods')

While run application through XCode application running properly but running with Xcodebuild it getting above error.

### Can you reproduce the bug?

Always

### Version

2.10.2

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS

### Build environment

objective-c

### Cocoapods version

1.12.0

**Comment by kneth** [comment] 2023-03-13 10:17
@RamNalluri 

In order for us to provide some feedback, it is important that you describe how to reproduce it.

Moreover, you mention version 2.10.2. What does it refer to? Realm JavaScript v2.10.0 was followed by v2.11.0 and v2.10.2 was never released.

**Comment by kneth** [comment] 2023-03-28 11:13
I am closing the issue due to no reply back. Please comment and reopen the issue if needed.

**Closed by kneth** 2023-03-28 11:13 UTC
Labels: T-Bug, O-Community, Waiting-For-Reporter, SDK-Use:Local, Encryption:Off, Frequency:Always, Repro:Always
