### ISSUE TITLE
No matching configuration of project :realm was found. The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'RNN.reactNativeVersion' with value 'reactNative57_5' but:

### ISSUE THREAD

**Issue by ChurikiTenna** [realm/realm-js#4962] opened 2022-09-30 05:45 UTC
### How frequently does the bug occur?

All the time

### Description

command:
```
% ./gradlew bundleRelease
```
I am trying run old project on my M1 Mac.

### Stacktrace & log output

```shell
* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :realm.
     Required by:
         project :app
      > No matching configuration of project :realm was found. The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'RNN.reactNativeVersion' with value 'reactNative57_5' but:
          - None of the consumable configurations have attributes.
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

I can give an access to my repository if that'll help.

### Version

10.21.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Mac OS

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment] 2022-09-30 09:26
@ChurikiTenna 

Are you using RN 0.57.5 (from the title: "attribute 'RNN.reactNativeVersion' with value 'reactNative57_5'")? If so, you need to upgrade RN - see https://github.com/realm/realm-js/blob/master/COMPATIBILITY.md for information about which RN version you need to upgrade to.

**Comment by kneth** [comment] 2022-10-20 08:22
I am closing the issue due to no reply back. Please comment and reopen the issue if needed.

**Closed** 2022-10-20 08:23 UTC
Labels: T-Bug, O-Community, Waiting-For-Reporter

**Comment by shubhamstackmint** [comment] 2022-12-09 12:00
No matching configuration of project :realm was found. The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.ProductFlavor:react-native-camera' with value 'general', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.2.1'

**Comment by MagicWilliams** [comment] 2023-09-27 14:29
@kneth Can we reopen this? Has any solution for this error surfaced?

**Comment by kneth** [comment] 2023-09-28 08:12
@MagicWilliams If you are using version 10.21.1, I suggest you upgrade to a recent version. If you experience the issue with a recent version, please create a new issue with all information and how to reproduce it.
