### ISSUE TITLE
Realm Listener Stop Or detached before it go to Sync Error

### ISSUE THREAD

**Issue by sshakilms** [realm/realm-js#2074] opened 2018-10-16 11:41 UTC
## Steps to Reproduce
1: Realm Listener Stop Sync and after 2 to 3 minute later it goes to error 
2: coming from error it again attached or it takes 1 to 2 minutes to attache 
3:  it frequently detached after 5 to 7 minutes idle state 

## Code Sample
app.locals.attacheConfigListner=function(realm)
{
  var collectionListenerRetainer = realm.objects('AppConfigEntity');
  // Observe Collection Notifications
  function listener(messages, changes) {

  // Update UI in response to inserted objects
        changes.insertions.forEach((index) => {
          console.log("inserted");
          let insertedMsg = messages[index];
            console.log(insertedMsg);
        });

  // Update UI in response to modified objects
        changes.modifications.forEach((index) => {
          console.log("modifiedMsg");
          let modifiedMsg = messages[index];
          console.log(modifiedMsg);
        });

  // Update UI in response to deleted objects
      changes.deletions.forEach((index) => {
        console.log("deletions");
        // Deleted objects cannot be accessed directly
        // Support for accessing deleted objects coming soon...
      });
}

 Realm.Sync.User.login(app.locals.realmAuthUrl,app.locals.realmAdminUser,  app.locals.realmPassword).then(user => {
    console.log("*****Succesfully Login");  
    console.log(user.isAdmin); 
     
    app.locals.realmUser=user;

    const config = {
      schema: [app.locals.schema.AppConfigEntity],
      schemaVersion: 1,
      sync: { 
        user: user,
        url: app.locals.realmConfig,
        error: err => console.log(err)
      }
    };

realmConfig = Realm.open(config)
    .progress((transferred, transferable) => {
      console.log("****Progress:"+transferred); 
    })
    .then(realm => {
        // ...use the realm instance here
      console.log("****Succesfully config Login:"+realm); 
      app.locals.attacheConfigListner(realm);
     })
     .catch((e) => {
       console.log(e);
       console.log("--------realm--------");
       console.log(realm);
       app.locals.attacheConfigListner(realm);
       //openConfig();
      });

 }).catch(error => {
      console.log("*****Error Login:"+error);  
      console.log(error);  
  });
## Version of Realm and Tooling

- Realm JS SDK Version: 2.14.2
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by kneth** [comment] 2019-08-16 12:38
Hypothesis: duplicate of #2461

**Closed by kneth** 2019-08-16 12:38 UTC
Labels: O:User
