### ISSUE TITLE
I'm enable to install realm on M1 Mac getting below error

### ISSUE THREAD

**Issue by salmankhadim36** [realm/realm-js#3617] opened 2021-02-28 20:36 UTC
[2021-02-28T20_29_10_805Z-debug.log](https://github.com/realm/realm-js/files/6057906/2021-02-28T20_29_10_805Z-debug.log)

## Version of Realm and Tooling

- Realm JS SDK Version: latest version 6.1.6
- Node or React Native: node : v15.10.0 
- Client OS & Version: m1 Mac
- Which debugger for React Native: ?/None

**Comment by kneth** [comment] 2021-03-01 08:16
I believe it is a duplicate of #3527.

**Closed** 2021-03-01 08:20 UTC
Labels: O-Community
