### ISSUE TITLE
Support Hermes engine

### ISSUE THREAD

**Issue by duarte-evocorp** [realm/realm-js#2729] opened 2020-02-18 19:50 UTC
Make Hermes engine to work with Realm. Hermes comes from react-native 0.60.2 and significantly improves app performance on Android.

Steps to Reproduce
Following https://facebook.github.io/react-native/docs/hermes. if enableHermes: true, you will get the following:

java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealmreact.so caused by: dlopen failed: library "libjsc.so" not found
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at io.realm.react.RealmReactModule.<clinit>(RealmReactModule.java:56)
        at io.realm.react.RealmReactPackage.createNativeModules(RealmReactPackage.java:31)
With enableHermes: false, everything works as expected.

Version of Realm and Tooling
Realm JS SDK Version: 3.6.0
React Native: 0.61.5

**Comment by aksmfosef11** [comment] 2020-02-19 00:57
#2455

**Comment by bmunkholm** [comment] 2020-02-19 08:39
Closing as duplicate of #2455

**Closed** 2020-02-19 08:41 UTC
Labels: O-Community

**Comment by irvingchenn** [comment] 2020-06-20 14:18
@bmunkholm 
hi, Hermes support seems to be an urgent and significant feature for some many team that import the realm. Could you please share us a release plan for Hermes? That would be so appreciated!

**Comment by flikQ** [comment] 2020-07-16 13:54
> Closing as duplicate of #2455

Duplicate yes but the other thread is only available for collaborators. Preventing the rest of us from commenting doesn't make the issue go away. We would be very grateful to be able to take advantage of the performance improvements Hermes offers. 

If this is not actually possible by Realm we should be made away so we can migrate away to a different DB system or wait for the support to be offered should you be capable. 

The issue for most is not the lack of support but the lack of updates and information on if it will even happen leaving a lot of us on the cusp of making very serious resource decisions to out products.

**Comment by bmunkholm** [comment] 2020-07-16 14:44
@flikQ We surely don't want the issue to go away, but having multiple issues isn't helping anyone. I've unlocked the original, and hope people can just upvote instead of commenting "+1" - that's noisy for everyone i think. I've given an update there as well although it doesn't help much.
