### ISSUE TITLE
Using ObjectClass throws error upon write in Node.js.

### ISSUE THREAD

**Issue by tybro0103** [realm/realm-js#998] opened 2017-05-04 02:41 UTC
The following works fine on ReactNative, but throws an error in Node.js.

- `realm-js v1.2.0`
- `Node v7.0.0`

Error:
```
realm.write(() => {
      ^
TypeError: Class constructor Car cannot be invoked without 'new'
```

Code:
```
const Realm = require('realm');

const CarSchema = {
  name: 'Car',
  properties: {
    color: 'string',
  },
};

class Car {};

Car.schema = CarSchema;

const realm = new Realm({
  path: 'foo.realm',
  schema: [Car],
});

realm.write(() => {
  realm.create('Car', {color: 'red'});
});
```

I have also tried making these changes, but had the same results:

- `realm.create(Car, {color: 'red'});`
- `class Car extends Realm.Object {};`

**Comment by vikkio88** [comment] 2017-05-04 07:40
I use it this way
```
realm.create('Car', {color: 'red'});
```
with Car being a string representing the object name

**Comment by tybro0103** [comment] 2017-05-04 12:52
@vikkio88 not sure I understand... I believe that's the same as my example? Are you using that node without error? If so, what version of node and what version of realm-js?

**Comment by vikkio88** [comment] 2017-05-04 13:00
Your example
```
realm.create(Car, {color: 'red'});
```
My example
```
realm.create('Car', {color: 'red'});
```
**'Car'** is wrapped in quote, is a string, not the model object

**Comment by tybro0103** [comment] 2017-05-04 14:35
I have _both_ of those in my examle... both of them work in React Native, but both of them result in the same error on Node.

@vikkio88 Are you running this on Node, or?

**Comment by vikkio88** [comment] 2017-05-04 17:52
Oh sorry didn't get what you meant, was react native

**Comment by petebacondarwin** [comment] 2017-05-14 16:26
Is this a node 7 related thing? I.E. is it because native classes in node are treated unlike regular functions?

**Comment by blagoev** [comment] 2017-05-22 12:40
Hi, sorry for the late reply. 
We don't support ES6 classes natively on node. On react that code is being transpiled before running the app so it works there. On node you will need to transpile your code before running it.

cheers

**Comment by tybro0103** [comment] 2017-05-23 00:51
@blagoev Ah, I see. So much of it worked in Node 7 without transpiling I didn't think of that.

**Comment by blagoev** [comment] 2017-05-23 10:19
You could transpile or you could write the above sample with 
```JavaScript
......
var Car = function Car() {
}

Car.schema = CarSchema;
.........
```

**Comment by tybro0103** [comment] 2017-05-24 15:44
I'd think that if the realm-js lib is expected to be transpiled, then even if you can get it to work without transpiling, it'd still be unsafe. Because even a patch version bump could contain a change that no longer works in your setup without transpiliation.

Since realm-js supports both React Native and Node, it might be worth considering pre-transpiling the npm releases. Since the newer versions of Node support most of ES6, many Node users may find it ideal to not transpile their projects.

**Comment by blagoev** [comment] 2017-06-03 20:56
True. ES6 is in our radar. will move this to a backlog for future consideration

**Comment by fronck** [comment] 2022-02-17 15:45
I'm closing this issue as we no longer support RealmJS < v6.  I haven't been able to reproduce the issue on v6 or v10.

**Closed by fronck** 2022-02-17 15:45 UTC
Labels: T-Enhancement, O-Community
