### ISSUE TITLE
'cmake-js' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by talaikis** [realm/realm-js#3686] opened 2021-04-10 20:13 UTC
## Goals

Install realm on RN project.

## Expected Results

Successful install.

## Actual Results

```
npm i -S realm --force
npm WARN using --force Recommended protections disabled.
npm ERR! code 1
npm ERR! path \node_modules\realm
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c prebuild-install || cmake-js rebuild
npm ERR! 'cmake-js' is not recognized as an internal or external command,
npm ERR! operable program or batch file.
```

## Steps to Reproduce

Windows 10:

```
npm i -S realm
```

## Version of Realm and Tooling

- Realm JS SDK Version: 10.3.0
- Node or React Native: 14.16.0/ 0.64.0
- Client OS & Version: Windows 10 Pro 19042.906
- Which debugger for React Native: Not applicable

**Comment by kneth** [comment] 2021-04-12 11:54
It is a duplicate of #3670. We believe we have a fix, and we hope to release it this week.

**Closed by kneth** 2021-04-12 11:54 UTC
Labels: O-Community
