### ISSUE TITLE
Realm for react-native gives IOS version warning

### ISSUE THREAD

**Issue by uc-bkr** [realm/realm-js#508] opened 2016-06-28 12:57 UTC
After installing the latest version of Realm using npm, when I tried to run my react-native app
The build failed with the following error:

d: targeted OS version does not support use of thread local variables in __ZN5realm4util13get_thread_idEv for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by appden** [comment] 2016-06-28 15:21
Closing as duplicate of #509

**Closed by appden** 2016-06-28 15:21 UTC
Labels: T:Duplicate
