### ISSUE TITLE
Must first create RPC session with a valid host

### ISSUE THREAD

**Issue by Muzzamil75** [realm/realm-js#3361] opened 2020-10-26 06:45 UTC
URGENT

Getting this error when debugging from chrome. Its been a while but issue is not resolved till now.

**Comment by kneth** [comment] 2020-10-26 08:05
@Muzzamil75 Thank you for reporting.

**Comment by kraenhansen** [comment] 2020-11-16 13:21
I'm actively working on this, but I'm unable to provide a good ETA since all the work needed is not entirely clear to me at this point in time. I appreciate the patience and will update here as I approach a solution.

**Comment by charleycesar** [comment] 2020-11-16 22:41
Thanks I'm waiting for this solution.

**Comment by kraenhansen** [comment] 2020-11-23 12:53
I'm closing this as a duplicate of https://github.com/realm/realm-js/issues/3358 - please follow that issue instead of this.

**Closed by kraenhansen** 2020-11-23 12:53 UTC
Labels: O-Community
