### ISSUE TITLE
App crashed about encryption key in React Native

### ISSUE THREAD

**Issue by ozsirma** [realm/realm-js#954] opened 2017-03-31 14:14 UTC
These are my codes for creating realm database.
var key = new Int8Array(64);

for (var i = 0; i < key.length; i++) {
  key[i] = _.random(-128, 127);
}

const realm = new Realm({ schema: [Tickets, UserTickets], encryptionKey: key });

![glass_and_iphone_se_ _ios_10_3__14e269_](https://cloud.githubusercontent.com/assets/17460410/24554104/124c2e30-1635-11e7-85eb-d22e88ea2654.png)

I am getting this error ok. I remove my app from simulator. I run again my app but I still get this error.

**Comment by fealebenpae** [comment] 2017-03-31 14:41
Hey @ozsirma,

I just tried your code and it works for me with Realm 1.2.0, React Native 0.42.3, and Xcode 8.3. Could you try making a new app, or maybe send an app that exhibits this behavior to help@realm.io?

**Comment by ozsirma** [comment] 2017-03-31 15:33
Thank you . I understood where my mistake is happened.

**Comment by VinAppFun** [comment] 2017-03-31 17:25
Try this my code. It's working for me

`
function getKey(yourKeyString) {
    let buf = new ArrayBuffer(str.length);
    let bufView = new Uint8Array(buf);
    for (var i = 0, strLen = str.length; i < strLen; i++) {
        bufView[i] = str.charCodeAt(i);
    }
    return buf;
}
`

**Comment by blagoev** [comment] 2017-04-12 19:54
Glad the issue is resolved. closing this

**Closed by blagoev** 2017-04-12 19:54 UTC
Labels: S:Waiting For User, T:Help
