### ISSUE TITLE
Realm.open and Realm.asyncOpen do not work in the Chrome debugger

### ISSUE THREAD

**Issue by agersoncgps** [realm/realm-js#1064] opened 2017-06-13 18:33 UTC
I am able to open my synced realm just fine with  this.realm = new Realm

But when I try to use Realm.openAsync I get the error:

```
TypeError: realmConstructor._waitForDownload is not a function
    at Function.openAsync (extensions.js:60)
    at Database.js:134
    at user-methods.js:127
    at tryCallOne (core.js:37)
    at core.js:123
    at JSTimers.js:117
    at Object.callTimer (JSTimersExecution.js:95)
    at Object.callImmediatesPass (JSTimersExecution.js:199)
    at Object.callImmediates (JSTimersExecution.js:214)
    at MessageQueue.js:228
```

Here is my specific implimention:

```
Realm.Sync.User.registerWithProvider(
        "http://localhost:9080",
        "custom/cgpsauth",
        accessToken,
        (error, user) => {
          if (error) {
            console.log(error);
          } else {
            console.log(user);
            this.realmUser = user;
            Realm.openAsync(
              {
                sync: {
                  user: user,
                  url: "realm://localhost:9080/cgps-app-test"
                },
                schema: [
                  StudentSchema,
                  ParentPhonesSchema,
                  ParentsSchema,
                  ParentAdressSchema,
                  DirectoryFavoritesSchema
                ]
              },
              (error, realm) => {
                if (error) {
                  console.log(error);
                  return;
                }
                // Realm is now downloaded and ready for use
                this.realm = realm;
                this.loading = false;
                console.log("Realm sycn done");
              }
            );
          }
          // console.log("user: " + user);
        }
      );
```

**Comment by fealebenpae** [comment] 2017-06-13 18:54
Hey @agersoncgps,

Are you running with a React Native debugger attached?

**Comment by agersoncgps** [comment] 2017-06-13 19:21
Yes

**Comment by fealebenpae** [comment] 2017-06-13 19:46
Thank you, we'll address this right away.

**Comment by blagoev** [comment] 2017-06-15 11:36
I manged to reproduce the issue. Will investigate further

**Comment by blagoev** [comment] 2017-06-15 11:45
@agersoncgps  It turns out we have fixed this and it will be part of the next release. Thanks for reporting.

**Comment by blagoev** [comment] 2017-06-16 08:44
The latest version 1.8.1 was released yesterday. This should be fixed. Closing this issue

**Closed by blagoev** 2017-06-16 08:44 UTC
Labels: S:In Progress, T:Bug-Crash

**Comment by agersoncgps** [comment] 2017-06-19 02:00
@blagoev I dont see version 1.8.0 on the releases page and when I run the [upgrade instructions](https://realm.io/docs/realm-object-server/#upgrading-linux) I get 1.7.6

**Comment by fealebenpae** [comment] 2017-06-19 06:20
@agersoncgps that's version 1.8 of realm-js - simply `npm install --save realm` to upgrade.
