### ISSUE TITLE
Cordova / Ionic 3.X Wrapper for Realm Native IOS / Android

### ISSUE THREAD

**Issue by tryadelion** [realm/realm-js#1582] opened 2017-12-19 10:58 UTC
Feature Request:

## Goals

To achieve realm connection between a  cordova-based hybrid app  and the native library code by creating a cordova  Typescript plugin that takes a generically Inputted syntax (RealmJS syntax?, swift syntax?) that redirects to the desired methods in the native code.

Examples of how this works:

https://github.com/arnesson/cordova-plugin-firebase

## Expected Results

TS:

```
import { RealmDB, RealmObject} from "Realm";
private car : RealmObject = {brand: "honda",subtype:"civic",codename:"grizzlybear",year:"2017",id: 12043};
constructor(realmInstance : RealmDB){
    realmInstance.open().subscribe( () => {
        realmInstance.write(car).subscribe( (res : Boolean) => {
          console.log(res);
        }
    });
}

```
Native IOS:

_let realm = try! Realm()

etc...

native Android:_

_new Realm()

etc,,,,_

## REASON

Realm.JS isn't made to be used as front end for webview-based hybrid apps, so there must be a way to use it. the easiest is to move the code "behind", and connect to the desired core when platform meets needs.

## Possible compatible versions
Android
Ios
Windows 10 UWP  (surface, desktop, windows phone All in One)

**Comment by nirinchev** [comment] 2017-12-19 11:12
This is a duplicate of  https://github.com/realm/realm-js/issues/261. In order to keep the discussion focused and easy to navigate, please share any thoughts or suggestions you may have in that issue.

**Closed by nirinchev** 2017-12-19 11:12 UTC

**Comment by tryadelion** [comment] 2017-12-19 11:15
The issue has not been adressed nor updated since ages, hence i reject the closing as is, be it dupe or not.

**Comment by nirinchev** [comment] 2017-12-19 11:30
I understand your point but opening multiple issues for the same thing will not change the team's priorities or resources. Unfortunately, at the moment we have more pressing issues we'd like to address before adding support for another platform. If you'd be willing to help though, both we and the community will greatly appreciate it! If that's the case, feel free to reach out and we'll try to help as much as we can.
