### ISSUE TITLE
Realm/react - Cannot create asynchronous query while in a write transaction

### ISSUE THREAD

**Issue by WenLonG12345** [realm/realm-js#4306] opened 2022-02-04 03:02 UTC
### How frequently does the bug occur?

All the time

### Description

Hi, I am recently using the new hooks library `@react/realm`, but I get some error when using it with redux saga.

My situation is to call API to get a list of room, insert it to realm and display in UI. 

Here is my code.
```
const Room = ({}) => {
 
 const roomList = useQuery('Room');

 const realm = useRealm();  <-- from RealmContext
 
 useEffect(() => {
    dispatch({ type: 'roomModel/getRoomList', realm }); <-- dispatch action to sagas
  }, []);
}
```

```
  *getRoomList({realm}, { put, call }) {
    const { roomType } = constant;

    const response = yield call(roomService.getRoomList, { roomType });

    if (response) {
      const { status, data } = response;

      if (status === 200) {
        const { rooms } = data;

        rooms.map(room => {
      
          realm.write(() => {
            realm.create('Room', room, "modified");
          });
        });
      }
    }
  }
```

Sagas is responsible to perform the insert operation, but somehow I keep getting the error on `Cannot create asynchronous query while in a write transaction`. 
I was wondering if it is a race condition on these hooks library? 

By the way, I am still beginner in React, do correct me if I made any mistake. 

### Stacktrace & log output

```shell
Error: Cannot create asynchronous query while in a write transaction
```

### Can you reproduce the bug?

Yes, always

### Version

10.11.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 11

### Build environment

Which debugger for React Native: ..
Flipper

**Comment by takameyer** [comment] 2022-02-04 09:40
@WenLonG12345 Strange issue.  It does feel like a race condition.  What would help us investigate would be a sample project that we could run that causes this issue.  Can you provide that for us?

**Comment by WenLonG12345** [comment] 2022-02-17 14:04
Hi sorry for the delay. I am changing hooks approach to use the traditional way, but yet still get the same error. 

https://github.com/WenLonG12345/RealmRaceCondition

Here is my example on implementing realm, and the error occurs when `onAdd()` to adding new value to db, the `addListener` seems throwing this async query error.

Or maybe I did a wrong approach?

**Comment by takameyer** [comment] 2022-02-17 14:25
I would recommend using the hooks approach for querying your data.  This will make sure the listeners are correctly persisted.  You can still use your same approach for writing data.  As I said in the other thread, opening `realm` with the same config will just give you a shared instance.

**Comment by WenLonG12345** [comment] 2022-02-18 02:59
Hi, I had changed to hooks approach, yet the error `Cannot create asynchronous query while in a write transaction` still occurs. Any idea why? 

![image](https://user-images.githubusercontent.com/39330565/154609214-ef87d318-b770-4327-9d6f-0e61760a6ce8.png)

**Comment by takameyer** [comment] 2022-02-18 08:17
@WenLonG12345 I have made a PR on the repository you sent me.  This is working with no errors in both Android and iOS.
https://github.com/WenLonG12345/RealmRaceCondition/pull/1/files

**Comment by tomduncalf** [comment] 2022-03-23 10:56
This sounds like it could be related to or a duplicate of https://github.com/realm/realm-js/issues/4375.

@WenLonG12345 are you still having this problem? If so please feel free to reopen this issue with more details.

**Closed by tomduncalf** 2022-03-23 10:56 UTC
Labels: T-Bug, O-Community, Waiting-For-Reporter
