### ISSUE TITLE
Realm got error Read-only file system with android 8.1

### ISSUE THREAD

**Issue by lytrunghieu** [realm/realm-js#4450] opened 2022-03-29 03:39 UTC
### How frequently does the bug occur?

All the time

### Description

I created new react native project and install realm. When I call open connection then I got error  "Read-only file system", it is working on android version less 8.1. 
Note: it still working on android 8.1 if I use default path of realm.

my package.json:

```
{
  "name": "awesomeproject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "17.0.2",
    "react-native": "0.67.4",
    "realm": "^10.14.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
Code for open connection realm:

```
const AppInfoSchema = {
  name: 'AppInfoRealmSave',
  properties: {
    packageName: 'string',
    isPostponeLater: 'bool',
    isUpdateUsingLauncher: 'bool',
  },
  primaryKey:'packageName'
};

 Realm.open({
      path: "/storage/emulated/0/AppUpdate/app_update.realm",
      schema: [AppInfoSchema],
      schemaVersion:42
})
```
I appreciate any help.

### Can you reproduce the bug?

Yes, always

### Version

10.14.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android

### Build environment

Which debugger for React Native: ..

**Comment by kraenhansen** [comment] 2022-03-29 07:59
Would it be a possible solution to copy the realm to [the App specific storage](https://developer.android.com/training/data-storage/app-specific)? You might be able to use something like https://www.npmjs.com/package/react-native-fs#API to get the path of that directory.

**Comment by lytrunghieu** [comment] 2022-03-29 08:07
Hi @kraenhansen 

I need to share realm file with other app. If I save file realm for only specific app then other app can not access realm file. It is weird, because this bug is only exist on android version larger than 8.0.

**Comment by kraenhansen** [comment] 2022-03-29 08:32
@lytrunghieu I imagine your app has to ask the OS for permission to write to this directory. Are you using any of the Android APIs to request access to [the shared storage](https://developer.android.com/training/data-storage/shared)?

**Comment by lytrunghieu** [comment] 2022-03-29 08:41
@kraenhansen 


Yes, I have added permission in AndroidManifest.xml

```
 <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

And in app I requested permission as well

```
   const grantedWrite = await PermissionsAndroid.requestMultiple([
            PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,
          PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE]);
```

**Comment by kraenhansen** [comment] 2022-03-30 12:50
@lytrunghieu to be honest, I'm clueless on what might be happening here then.

I'll require further investigations.
Getting a minimal reproduction (a simple GitHub repository showing this error) would be a great help!

**Comment by lytrunghieu** [comment] 2022-03-30 13:20
@kraenhansen Have you try reproduce on android 8.1 ?

**Comment by kraenhansen** [comment] 2022-03-31 09:08
Nope. I havn't reproduced this yet. My expectation is that the security model was change / tightened with Android 8.1 which is why Realm core can't open the Realm in write-mode.

**Comment by tomduncalf** [comment] 2022-04-13 12:53
Hi @lytrunghieu, were you able to create a minimal repro of this issue?

**Comment by kneth** [comment] 2022-05-30 15:19
I am closing the issue due to no reply back. Please comment and reopen the issue if needed.

**Closed by kneth** 2022-05-30 15:19 UTC
Labels: T-Bug, O-Community, Waiting-For-Reporter

**Comment by thucnguyenpfs** [comment] 2023-03-21 17:10
Hello, I have the same problem but on aws nodejs. There was an error in the log.
```{
    "errorType": "RealmError",
    "errorMessage": "Failed to create directory at '/var/task/mongodb-realm/': Read-only file system",
    "code": "PermissionDenied",
    "name": "RealmError",
    "stack": [
        "RealmError: Failed to create directory at '/var/task/mongodb-realm/': Read-only file system",
        "    at /var/task/src/handler.js:1:1555",
        "    at Generator.next (<anonymous>)",
        "    at /var/task/src/handler.js:1:1234",
        "    at new Promise (<anonymous>)",
        "    at o (/var/task/src/handler.js:1:979)",
        "    at Runtime.t.creditLoyalty [as handler] (/var/task/src/handler.js:1:1464)",
        "    at Runtime.handleOnceNonStreaming (/var/runtime/Runtime.js:74:25)"
    ]
}```

My code
```const app: Realm.App = new Realm.App({ id: process.env.REALM_APP_ID });

  let creditAvailables, cogintoToken;
  try {
    const appLogged = await app.logIn(
      Realm.Credentials.apiKey(process.env.REALM_API_KEY)
    );

    const creditAvailablePromise = await appLogged.functions.getCreditAvailableByBrand({
        brandShopCode: partnerCode,
      });
   } catch (err) {
    console.error('Failed to log in', err);
  }
```
Do you have any idea?

**Comment by kneth** [comment] 2023-03-22 07:15
@thucnguyenpfs It is unrelated to the original issue, and creating a new issue is the best approach.

Said that, `/var/task/` is probably read-only on your server, and you should either make the directory writable or use a directory with fewer restrictions.

**Comment by sinhgithub** [comment] 2023-12-16 14:50
why this issue is closed :(

**Comment by nirinchev** [comment] 2023-12-16 22:47
Because the author didn't reply with repro case. If you're experiencing a similar problem, file a new issue and fill in the template.
