### ISSUE TITLE
"Module AppRegistry is not a registered callable module" with remote debugging

### ISSUE THREAD

**Issue by paldepind** [realm/realm-js#562] opened 2016-08-10 13:57 UTC
When I include Realm in my project and use remote JS debugging I see the following error on the phone: "Module AppRegistry is not a registered callable module". And the Chrome log shows:

```
POST http://10.8.239.5:8082/create_session net::ERR_CONNECTION_REFUSED
10.141.19.252:8082/create_session:1 POST http://10.141.19.252:8082/create_session net::ERR_CONNECTION_REFUSED
DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://10.141.19.252:8082/create_session'.(…)
Realm failed to connect to the embedded debug server inside the app. If attempting to use Chrome debugging from a device, ensure the device is reachable on the same network as this machine.
Module AppRegistry is not a registered callable module.
```

It seems odd that the errors mention port 8082 since my local dev server is running on port 8082.

This is likely related to #465. The last comment in that thread mentions that remote debugging may not work at all. If that is the case then it would be really helpful if that was mentioned somewhere in the documentation.

**Comment by alazier** [comment] 2016-08-10 14:03
If you are running something locally on port 8082 then this is probably conflicting with the debug server which is trying to run on the same port. You can try changing the port which is used. On iOS you would need to change the port used here: https://github.com/realm/realm-js/blob/master/react-native/ios/RealmReact/RealmReact.mm#L41

**Comment by paldepind** [comment] 2016-08-10 14:17
I'm fairly certain that 8081 is the default port. If you look at the React Native documentation that is port they mention: https://facebook.github.io/react-native/docs/debugging.html

**Comment by alazier** [comment] 2016-08-10 14:26
Yes that is the port used for react-native. Realm also runs its own RPC server on 8082 to support chrome debugging. We need to do this because some of the features of our apis are not supported by the native module apis provided by react-native.

**Comment by alazier** [comment] 2016-08-10 14:38
You can change the port locally for testing purposes - after you npm install realm you can simply change the port in the installed files and in theory that should work.

**Comment by paldepind** [comment] 2016-08-12 07:10
Ok. Thank you for the explanation. I was not aware that Realm used a port in addition to the one used by React Native. I'll see if I can get it to working.

But I guess it's not the intention to throw the "Module AppRegistry is not a registered callable module" error. It makes using the app with just normal Chrome debugging impossible.

**Comment by paldepind** [comment] 2016-08-12 13:29
I've tried

```
adb forward tcp:8082 tcp:8082
```

but it doesn't seems to work.

**Comment by alazier** [comment] 2016-08-12 15:36
I'm not sure what the issue is. If you are able to share your project I could try to take a look. From searching online it seems like you could have an error unrelated to Realm in your `index.js` file which might cause this issue but I'm not really sure. Also just wnat to make sure you know remote debugging currently only works when using the emulator/genymotion so if you are trying to run on device that could also be causing issues.

**Comment by alazier** [comment] 2016-08-15 15:57
Were you able to make any progress with this? Does chrome debugging work for you on a newly generated react-native project which included Realm?

**Comment by paldepind** [comment] 2016-08-17 07:15
Sorry for the delay. I highly appreciate the your answers.

When I run the application on my device _without_ remote JS debugging everything seems fine. But when I activate remote JS debugging I get the error I posted in OP.

If I run in an emulator I see exact same. However, after running `adb forward tcp:8082 tcp:8082` everything does work in the emulator without errors. So it seems to me like Realm not being able to connect is what is causing the `Module AppRegistry is not a registered callable module.` error.

I will try setting up Realm in a new react-native project and let you know how it turns out.

**Comment by paldepind** [comment] 2016-08-17 08:04
I've just setup a new react-native project by doing the following:

```
react-native init RealmReactTest
npm install --save realm
rnpm link realm
```

I then added the line

```js
const Realm = require('realm');
```

To `index.android.js`.

When running the project at that point I got the error: `Missing Realm constructor - please ensure RealmReact framework is included`. I fixed that by following the instructions [here](https://github.com/realm/realm-js/issues/375#issuecomment-232469631).

I now experience exactly the same as what I described in my last post. No problems without debugging enabled and `Module AppRegistry is not a registered callable module` when it is.

**Comment by paldepind** [comment] 2016-08-27 08:09
@alazier Have you had any luck reproducing the issue from the steps I posted above?

**Comment by alazier** [comment] 2016-08-29 20:43
@paldepind there is definitely something wrong - when following your steps the required lines are not added to `MainApplication.java` by rnpm. Can you ensure that the ```protected List<ReactPackage> getPackages()``` method returns ```new RealmReactPackage()```? If not adding this line along with ```import io.realm.react.RealmReactPackage;``` should fix the issue. I will look into what is going wrong with rnpm.

**Comment by paldepind** [comment] 2016-08-30 07:30
Yes. As I mentioned I added the line manually by following the instructions [here](https://github.com/realm/realm-js/issues/375#issuecomment-232469631). So the rnpm problem was quite easily solved. What I'm reporting here happens unrelated to that issue I think.

**Comment by alazier** [comment] 2016-09-26 15:49
Were you ever able to resolve this?

**Comment by paldepind** [comment] 2016-10-06 07:20
Hello @alazier. No, unfortunately not. Debugging on device is still impossible. Probably same issue as in #571. I'm hoping that maybe #598 will make it possible to at least make debugging possible.

**Comment by barbarossusuz** [comment] 2017-06-01 10:33
Still no solution for this issue?

**Comment by Damnum** [comment] 2017-06-27 04:05
Same issue here.

**Comment by Frogmouth** [comment] 2017-07-07 08:06
Same here. 👍

**Comment by shanghongshen001** [comment] 2017-08-16 10:42
i can debug on realm 1.31   
But nothing else

**Comment by Looveh** [comment] 2017-08-30 12:59
I am able to do remote Chrome debug on an iOS device with `1.10.1` and React Native `0.45.1` but encounter this problem when the app is woken up through Bluetooth State Restoration, which makes it impossible to debug Bluetooth issues and unfortunately is a deal breaker for us.

Is there any plan on fixing this issue? Otherwise we will unfortunately have no other choice but to look for alternative database libraries.

**Comment by MrHubble** [comment] 2017-10-15 23:45
@shanghongshen001 did you mean realm `1.3.1`? I'm on `1.11.0` and I still have this problem with Android (but not iOS).

**Comment by shanghongshen001** [comment] 2017-10-30 07:02
@MrHubble I can run on 1.3.1 .
The update to 1.10.1 will not be done.
I don't know why not.

**Comment by rexxars** [comment] 2018-01-22 22:54
This still seems to be an issue. After about 30 seconds, I get a timeout error:
`POST http://77.18.14.132:8083/create_session net::ERR_CONNECTION_TIMED_OUT`

What's interesting is that the IP reported seems to be the public IP of my 4G connection instead of the wifi connection as is probably intended.

**Comment by brithbutter** [comment] 2018-04-02 07:35
Does this issue fixed? I am facing same problem

**Comment by paldepind** [comment] 2018-04-02 08:36
@brithbutter I don't think so. We had so many problems with Realm on React Native (this one, in particular, performance, etc) that we moved to [react-native-sqlite-storage](https://github.com/andpor/react-native-sqlite-storage). We have been happy ever since.

**Comment by Frmisk** [comment] 2018-04-24 09:06
same issue :(

**Comment by stlemon** [comment] 2018-05-11 09:58
same+1

**Comment by duxiwei** [comment] 2018-06-06 14:55
the same problem

**Comment by tangyaogang** [comment] 2019-09-23 09:37
same issue here

**Comment by whalemare** [comment] 2020-08-04 15:24
same issue

**Comment by kneth** [comment] 2021-01-29 14:21
We have reworked the Chrome debugger support, and I suggest an upgrade to v10.1.x.

I am closing the issue but it is still observe, please create a new issue.

**Closed** 2021-01-29 14:22 UTC
Labels: O-Community, T-Bug
