### ISSUE TITLE
[iOS] build failed when pods are updated

### ISSUE THREAD

**Issue by kyo504** [realm/realm-js#2810] opened 2020-04-14 16:41 UTC
## Goals 

> This is related #2703.

I've updated realm from 3.6.3 to 5.0.3 to support node lts. Unfortunately after this update, build failed if pods are updated with the following error messages.

```
The following build commands failed:
	Ld /Users/daniel/Library/Developer/Xcode/DerivedData/RN62-ejoxauigsqhssxgqbznzbyvdyltb/Build/Products/Debug-iphonesimulator/RN62.app/RN62 normal x86_64
(1 failure)
```

It works fine if I delete Pods folder and reinstall pods but it's pretty annoying especially on ci. Normally I use cached one in order to reduce the build time if there is no change. However I can't use the cache strategy anymore due to this issue.

## Expected Results

Successfully build app without removing and reinstalling pods when pods are updated.

## Actual Results

Build failed with error messages.

## Steps to Reproduce

1. Init template project (npx react-native init RN62)
2. Install realm (yarn add realm & pod install)
3. Run iOS build (npx react-native run-ios)
4. Install any package which has native deps (yarn add react-native-svg & pod install)
5. Run iOS build again.

## Code Sample

No need code sample

## Version of Realm and Tooling

- Realm JS SDK Version: 5.0.3
- Node or React Native: React Native(Node 13.12.0)
- Client OS & Version: macOS 10.15.4
- Which debugger for React Native: ? N/A

**Comment by hadus07** [comment] 2020-04-15 08:43
+1

**Comment by kneth** [comment] 2020-06-25 12:41
Upgrading from one major version to another is hard and painful. You have also been upgrading node.js (we didn't support node 13 before v5.0.0), and moving to the new auto-linking in RN will require that you wipe your build cache.

**Closed** 2020-06-25 12:45 UTC
Labels: O-Community

**Comment by jeremyeaton89** [comment] 2020-09-17 20:25
we definitely experienced this issue bumping realm with move to RN 60+, but we've also been seeing these issues when we change branches in our local dev process, and our only known workaround is to wipe the pods and install from scratch, which is quite time consuming... is this issue considered resolved or is there a solution i'm not aware of?

**Comment by cristiano-linvix** [comment] 2020-11-30 18:30
I have same problem, and i initialized an app with RN 0.63 and realm 6.1.5 and i getting same error.

Some solution?

**Comment by kneth** [comment] 2020-12-01 08:28
@cristiano-linvix 

> and i initialized an app with RN 0.63 and realm 6.1.5 and i getting same error

Just to clarify: it is a fresh app, no upgrade of React Native?

**Comment by ouabing** [comment] 2020-12-01 09:40
I have been experiencing this issue for a long time since upgrading to RN 60 (for maybe 1 year). At least I can confirm it's not caused by specfic RN or Xcode version. I suspect it's related to some Xcode settings but still no proofs.

**Comment by cristiano-linvix** [comment] 2020-12-01 21:24
@kneth Yes! it is a fresh app. I initialized directly on RN 0.63.
I noticed that the problem happens when installing a new package via yarn in my case.
And not when you install a new pod.
I installed pods via podfile and the problem did not occur.

**Comment by kneth** [comment] 2020-12-02 12:14
@cristiano-linvix Are you doing:

1. `react-native init ...`
1. `yarn install realm`
1. `cd ios && pod install`
1. `react-native run-ios`
1. `yarn install awesome-package` -> and now it breaks

**Comment by cristiano-linvix** [comment] 2020-12-02 16:09
I'm using this commands:

1. `npx react-native init AwesomeProject`
2. `yarn add realm@6.1.5`
3. `cd ios && pod install`
4. `Install my application into Xcode.`
5. `yarn install awesome-package -> and now it breaks`
