### ISSUE TITLE
Windows 7 realm installation issue

### ISSUE THREAD

**Issue by prashantrishu** [realm/realm-js#826] opened 2017-01-31 18:56 UTC
![image](https://cloud.githubusercontent.com/assets/8378405/22479612/65f6bb92-e7bc-11e6-9247-628118a04cd0.png)
I'm getting the error after npm install on windows 7 (node 7.0) . I'm running the terminal in Admin mode.
 I was able to link it successfully. 
![image](https://cloud.githubusercontent.com/assets/8378405/22479722/d1de57b6-e7bc-11e6-819b-8e46ae5bb9f5.png)

When I run-android, I'm getting the following error:-
![image](https://cloud.githubusercontent.com/assets/8378405/22479791/13ea6852-e7bd-11e6-83dd-dc51432becd2.png)

Please help.

**Comment by kristiandupont** [comment] 2017-02-03 10:31
This seems to be a duplicate of #687, so I will close it and refer you to that. Perhaps [this](https://github.com/realm/realm-js/issues/687#issuecomment-276757579) is helpful?

**Closed** 2017-02-03 10:31 UTC
Labels: T:Duplicate

**Comment by sonnguyenit** [comment] 2017-02-16 15:04
@kristiandupont I can't find any solution in the link you refer.
I don't understand what about:
```
task send(type: SendAnalyticsTask) {
    applicationId = getAppId()
    version = "npm.cmd --silent run get-version".execute(null, projectDir).text.trim()
}
```
