### ISSUE TITLE
Realm file decryption failed on ios 13 devices but not ios emulator or android

### ISSUE THREAD

**Issue by MatthewMHughes** [realm/realm-js#2998] opened 2020-06-23 10:06 UTC
## Goals

We are trying to implement an encryption solution across our application so that every local realm file is encrypted on the device using a secret key stored on the secure keychain/keystore on the device.

## Expected Results

We expected that the secret key could be used to encrypt and decrypt all of the local realm files across ios and android. This would ensure a high level of security across our realm solution.

## Actual Results

The solution works perfectly for android on a physical device and also on the emulator. However on ios, we have the decryption failing on the actual device but working fine on an emulator. 

This is the Stack Trace:

_ERROR: Connection[2]: Session[2]: In finalize_state_transfer, the realm /path_to_file/partially_downloaded.realm could not be opened, msg = Realm file decryption failed Path: /path_to_file/partially_downloaded.realm
Exception backtrace:
0 0x000000010194ee2c ZN5realm15InvalidDatabaseC2ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9 + 60
1 0x000000010189dacc _ZN5realm9SlabAlloc11attach_fileERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERNS0_6ConfigE + 4720
2 0x0000000101948e04 _ZN5realm11SharedGroup7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_18SharedGroupOptionsE + 3088
3 0x00000001016a1e30 _ZN5realm11SharedGroup4openERNS_11ReplicationENS_18SharedGroupOptionsE + 292
4 0x0000000101a7ca8c _ZN5realm11SharedGroupC2ERNS_11ReplicationENS_18SharedGroupOptionsE + 864
5 0x0000000101abacec _ZN5realm5_impl19ClientStateDownload19finalize_async_openEv + 496
6 0x0000000101ab97f0 _ZN5realm5_impl19ClientStateDownload13receive_stateEyxyyyNS_10BinaryDataE + 1268
7 0x0000000101a95f9c _ZN5realm5_impl14ClientImplBase7Session21receive_state_messageEyxyyyNS_10BinaryDataE + 572
8 0x0000000101a92d3c _ZN5realm5_impl14ClientProtocol22parse_message_receivedINS0_14ClientImplBase10ConnectionEEEvRT_PKcm + 3852
9 0x0000000101a8de80 _ZN5realm5_impl14ClientImplBase10Connection33websocket_binary_message_receivedEPKcm + 60
10 0x0000000101b486d4 _ZN12_GLOBAL__N_19WebSocket17frame_reader_loopEv + 1536
11 0x0000000101a9cacc ZN5realm4util7network7Service9AsyncOper29do_recycle_and_execute_helperINSt3__18functionIFvNS5_10error_codeEmEEEJS7_mEEEvbRbT_DpT0 + 168
12 0x0000000101a9c908 ZN5realm4util7network7Service9AsyncOper22do_recycle_and_executeINSt3__18functionIFvNS5_10error_codeEmEEEJRS7_RmEEEvbRT_DpOT0 + 148
13 0x0000000101a9c464 _ZN5realm4util7network7Service14BasicStreamOpsINS1_3ssl6StreamEE16BufferedReadOperINSt3__18functionIFvNS8_10error_codeEmEEEE19recycle_and_executeEv + 240
14 0x0000000101b3a8b0 _ZN5realm4util7network7Service4Impl3runEv + 400
15 0x0000000101ad1ef8 _ZN5realm4sync6Client3runEv + 36
16 0x00000001016da0a4 _ZZN5realm5_impl10SyncClientC1ENSt3__110unique_ptrINS_4util6LoggerENS2_14default_deleteIS5_EEEERKNS_16SyncClientConfigEENKUlvE0_clEv + 248
17 0x00000001016d9f60 ZNSt3__1L8__invokeIZN5realm5_impl10SyncClientC1ENS_10unique_ptrINS1_4util6LoggerENS_14default_deleteIS6_EEEERKNS1_16SyncClientConfigEEUlvE0_JEEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOSE_DpOSF + 28
18 0x00000001016d9ebc _ZNSt3__1L16__thread_executeINS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEZN5realm5_impl10SyncClientC1ENS1_INS6_4util6LoggerENS3_ISA_EEEERKNS6_16SyncClientConfigEEUlvE0_JEJEEEvRNS_5tupleIJT_T0_DpT1_EEENS_15__tuple_indicesIJXspT2_EEEE + 32
19 0x00000001016d95c0 ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN5realm5_impl10SyncClientC1ENS2_INS7_4util6LoggerENS4_ISB_EEEERKNS7_16SyncClientConfigEEUlvE0_EEEEEPvSJ + 116
20 libsystem_pthread.dylib 0x00000001831e02c0 + 128
21 libsystem_pthread.dylib 0x00000001831e0220 pthread_start + 44
22 libsystem_pthread.dylib 0x00000001831e3cdc thread_start + 4

## Steps to Reproduce

Assigning an encryption key to the realm config (after initialising the config) then opening the realm.

## Code Sample

// This code using the SInfo library to get the key from the secure keystore/keychain. If it exists then it runs the function onAuthenticated, else it generates a new key and stores it in the keystore/keychain before running the function onAuthenticated.
SInfo.getItem("realmKey", {}).then((key) => {
    if (!key) {
        generateSecureRandom(64).then((randomBytes) => {
					const buffer = randomBytes.buffer;
					key = Array.prototype.map
						.call(new Uint8Array(buffer), (x) => ("00" + x.toString(16)).slice(-2))
						.join("");
					SInfo.setItem("realmKey", key, {}).then((value) => {});
					this.onAuthenticated(user, accessToken, randomBytes);
				});
			} else {
				let encKey = Uint8Array.from(Buffer.from(key, "hex"));
				this.onAuthenticated(user, accessToken, encKey);
			}
		});

// onAuthenticated begins with creating a realm config, assigned it the encryption key, then opening the realm
onAuthenticated(user, accessToken, key) {
		const userConfig = user.createConfiguration({
			sync: { url: REALM_URL + "/~/userProfile", error: (err) => console.log(err), fullSynchronization: true },
			schema: userSchema
		});
		userConfig.encryptionKey = key;
		Realm.open(userConfig).then((realm) => {

## Version of Realm and Tooling

- Realm JS SDK Version: 5.0.3
- Node or React Native: Node 9.4.0, RN 0.62.2
- Client OS & Version: ios 13
- Which debugger for React Native: None

**Comment by bmunkholm** [comment] 2020-06-24 12:22
@MatthewMHughes Which version of realm-js are you using?
For the "Steps to reproduce", could could you please instruct how WE can reproduce it? Can you provide a minimal sample project that does that?

**Comment by MatthewMHughes** [comment] 2020-06-24 12:31
> @MatthewMHughes Which version of realm-js are you using?
> For the "Steps to reproduce", could could you please instruct how WE can reproduce it? Can you provide a minimal sample project that does that?

Oh sorry, the version is 5.0.3 - will try and put together a sample project and post it here soon

**Comment by steffenagger** [comment] 2020-07-09 09:02
@MatthewMHughes any progress?

**Comment by steffenagger** [comment] 2020-07-27 13:37
Duplicate of https://github.com/realm/realm-js/issues/2920 (closing this one).
@MatthewMHughes please see/follow https://github.com/realm/realm-js/issues/2920 for a solution.

**Closed** 2020-07-27 13:42 UTC
Labels: O-Community
