### ISSUE TITLE
Missing Realm Constructor

### ISSUE THREAD

**Issue by DevaLee** [realm/realm-js#1160] opened 2017-07-25 02:43 UTC
## Version of Realm and Tooling

- Realm JS SDK Version: "realm": "^1.8.3"
- Node or React Nattive: node: v7.10.0   "react-native": "0.44.3"
- Client OS & Version: mac OS Sierra 10.12.4(16E195)
- Which debugger for React Native: i use realm in Simulator enviorment , 
I do that According  https://realm.io/docs/react-native/latest/#missing-realm-constructor for troubleshooting  say, it do as expected ,but when I select Debug JS Remotely ,it also crash and throw Missing Realm Constructor error, help me

**Comment by thatjuan** [comment] 2017-07-25 08:14
Dupe of #1128?

**Closed** 2017-07-26 11:33 UTC
Labels: T:Duplicate
