### ISSUE TITLE
Cyrillic in file path for Windows

### ISSUE THREAD

**Issue by brightsider** [realm/realm-js#2319] opened 2019-04-04 08:02 UTC
If using cyrillic in path then can't open database.
Error text:
Unable to open a realm at path 'D:\тест\default.realm.managment': make_dir() failed: No such file or directory Path:.
Same error get through Realm Studio for Windows.

**Comment by kneth** [comment] 2019-04-05 09:41
I believe we have seen it recently, and it is unrelated to Cyrillic. See #2097. Can you confirm that you also see it if you are on Latin-1?

**Comment by nirinchev** [comment] 2019-04-05 10:18
@kneth I believe #2097 is due to exceeding the windows path length - the path posted in that issue contains 297 characters, whereas this one seems to be well within bounds.

**Comment by brightsider** [comment] 2019-04-05 15:14
@kneth I think this bug not related to #2097 because test it on short path.
How to test Latin-1? I think It happens on Windows-1251

**Comment by kneth** [comment] 2019-04-08 08:21
@brightsider Is it possible for you to share a minimal example which can reproduce the error?

By Latin-1 I mean Windows-1252 (too much of an old Linux user in me).

**Comment by brightsider** [comment] 2019-04-08 13:28
@kneth create any database on Windows, move to folder with Cyrillic in path like this - D:\тест\default.realm.managment.
And try to open in Realm Studio

**Comment by chetak-nis** [comment] 2019-04-22 10:27
@kneth 
Getting this issue in a folder having a Japanese character in windows 10.

**Comment by kneth** [comment] 2019-04-24 10:45
The proper fix is in Realm Core (see https://github.com/realm/realm-core/issues/3230).

**Comment by kneth** [comment] 2019-07-01 13:52
We have merged the bug not it is not released yet.

**Closed by kneth** 2019-07-01 13:52 UTC
Labels: Blocked, O:User, T:Bug

**Comment by ironage** [comment] 2019-07-11 13:44
Released in js version v2.29.0.
