### ISSUE TITLE
useQuery data cannot be used directly in FlatList

### ISSUE THREAD

**Issue by skam22** [realm/realm-js#5404] opened 2023-02-09 20:21 UTC
### How frequently does the bug occur?

Always

### Description

this returns an empty FlatList:

```
const {useQuery} = realmContext;

const App = () => {
  const tasklists = useQuery(Tasklist)
  return (
    <FlatList
      data={tasklists}
      keyExtractor={item => String(item._id}
      renderItem={({item, index}) => <Text>index is: {index}</Text>}
    />
  )

❌ does not work

```

memoizing the useQuery response also returns an empty FlatList:

```
const {useQuery} = realmContext;

const App = () => {
  const tasklists = useQuery(Tasklist)
  const sorted = useMemo(() => tasklists.sorted(),[tasklists])
  return (
    <FlatList
      data={sorted}
      keyExtractor={item => String(item._id}
      renderItem={({item, index}) => <Text>index is: {index}</Text>}
    />
  )

❌ does not work

```

spreading the useQuery response to a new array correctly displays the items in the list:

```
const {useQuery} = realmContext;

const App = () => {
  const tasklists = useQuery(Tasklist)
  return (
    <FlatList
      data={[...tasklists]}
      keyExtractor={item => String(item._id}
      renderItem={({item, index}) => <Text>index is: {index}</Text>}
    />

✅ this works
```

mapping through the useQuery response renders correctly as well (but without the benefit of the virtualized list).

```
const {useQuery} = realmContext;

const App = () => {
  const tasklists = useQuery(Tasklist)
  return (
    <View>
      {tasklists.map((tasklist, index) => <Text key={String(tasklist._id)}>index is: {index}</Text>)}
    </View>

✅ this works
```

the same source code works fine if pasted into the template starter (react-native.todo.flex) which installs react-native 0.70.5, @realm/react 0.4.1, realm 11.2.0

### Can you reproduce the bug?

Always

### Version

realm 11.4.0, @realm/react 0.4.3, react-native 0.71.2

### What services are you using?

Atlas Device Sync

### Are you using encryption?

Yes

### Platform OS and version(s)

IOS and Android

### Build environment

realm 11.4.0, @realm/react 0.4.3, react-native 0.71.2

**Comment by kneth** [comment] 2023-02-12 09:55
I cannot see what the type of `item._id` is.  If it is UUID or ObjectId, it can be that `String(item._id)` is not producing a unique string. Please try to use `item._id.toHexString()` instead.

Using the spread operator (`data={[...tasklists]}`) is likely to give you poor performance as you are copying the Realm objects to JavaScript objects.

**Comment by skam22** [comment] 2023-02-12 15:21
._id is a BSON ObjectId

**Comment by lufke** [comment] 2023-02-12 16:33
Same problem. The _id is Unique for every item

**Comment by skam22** [comment] 2023-02-12 16:37
I think I found the issue, the react-native FlatList component _getItemCount looks like this:

```
  _getItemCount = (data: ?Array<ItemT>): number => {
    if (Array.isArray(data)) {
      const numColumns = numColumnsOrDefault(this.props.numColumns);
      return numColumns > 1 ? Math.ceil(data.length / numColumns) : data.length;
    } else {
      return 0;
    }
  };
```

Array.isArray(tasklists) is returning false.

The object returned from useQuery fails Array.isArray()

**Comment by lufke** [comment] 2023-02-12 16:41
When i see the typo of the useQuery, ir gives me object

**Comment by skam22** [comment] 2023-02-12 16:57
That’s correct, and an array is an object.. 

But Array.isArray(useQueryResponseObject) is false. 

The object looks like an array, but it isn’t passing the isArray test. I believe isArray looks for the existence of a .toString() method on the object.

**Comment by skam22** [comment] 2023-02-12 17:03
Here is the react-native FlatList commit that breaks the useQuery hook:

https://github.com/facebook/react-native/commit/d574ea3526e713eae2c6e20c7a68fa66ff4ad7d2

**Comment by skam22** [comment] 2023-02-12 17:24
The workaround I’m currently using is patch-package to remove the Array.isArray() guard.

Moving forward, though, it seems that Realm.Results needs to be updated to pass the data guard inserted with react native 0.71.

**Comment by takameyer** [comment] 2023-02-13 08:37
Looks like this was added in [`0.71.2`](https://github.com/facebook/react-native/commit/d574ea3526e713eae2c6e20c7a68fa66ff4ad7d2).  We will need to investigate a solution.

**Comment by takameyer** [comment] 2023-02-14 13:45
Just an update.  We are currently in discussions with Meta on how to proceed with this matter.  We have two options, either they include a way that we can bypass their check, or we create a Proxy object that wraps an Array and access a Realm collection (with a possible performance regression).

**Comment by skam22** [comment] 2023-02-14 14:51
> Just an update. We are currently in discussions with Meta on how to proceed with this matter. We have two options, either they include a way that we can bypass their check, or we create a Proxy object that wraps an Array and access a Realm collection (with a possible performance regression).

Could a third option be to export a FlatList component from the @realm/react package that reverts their check? Then users could import {FlatList} from ‘@realm/react’ instead of from ‘react-native’.

**Comment by takameyer** [comment] 2023-02-15 09:31
@skam22 while possible, I would rather we obtain compatibility with React Native primitives.  In any case, we directly in contact with Meta at this time and hopefully will have a resolution soon.

**Comment by takameyer** [comment] 2023-02-17 14:35
@hadnet Nothing to report right now, we are still in discussions.  That being said, it is a priority for us to resolve this, so we will post as soon as we have an update.

**Comment by takameyer** [comment] 2023-02-21 08:16
After discussing this with Meta, they have agreed to loosen the restrictions on the `data` property to allow for "array-like" structures to be rendered.  No current timeline when this will happen, but we are hopeful it will come in a `0.71.x` release in the near future.  Will keep this open to report and track any progress.

**Comment by takameyer** [comment] 2023-02-22 08:58
The following PRs to `react-native` will fix this issue:
https://github.com/facebook/react-native/pull/36236
https://github.com/facebook/react-native/pull/36237

Once these are live, we can close the issue.  Thanks everyone for your patience.

**Comment by takameyer** [comment] 2023-02-28 15:51
Another update.  React Native [0.71.4](https://github.com/reactwg/react-native-releases/discussions/58#discussioncomment-5122765) is being put together and will fix the issue.  Hopefully will happen soon!

**Comment by mMarcos208** [comment] 2023-03-06 17:56
Same issue after upgrade to 0.71.3

```
  const filteredTasks = useRealmQuery<Task>({
    source: Task.schema.name,
  })
  
    <FlatList
          key={TypeOfCalendar.Card}
          data={filteredTasks}
          keyExtractor={(item) => String(item.id)}
          ListEmptyComponent={<NoRecordsFound />}
          renderItem={({item}) => (
            <TaskList
              onPress={() => goToDetails(item.id)}
            />
          )}
        />
        
```

**Comment by mMarcos208** [comment] 2023-03-09 12:49
New version is disponible: https://react-native-community.github.io/upgrade-helper/?from=0.71.3&to=0.71.4

Upgrade solve me.

**Comment by takameyer** [comment] 2023-03-09 16:47
React Native [0.71.4](https://github.com/facebook/react-native/releases/tag/v0.71.4) is out!  If you want `FlatList` support, then I recommend updating to this version.

**Closed by takameyer** 2023-03-09 16:47 UTC
Labels: T-Bug, O-Community, SDK-Use:Sync, Frequency:Always, Repro:Always, Encryption:On

**Comment by lufke** [comment] 2023-03-09 17:09
> React Native [0.71.4](https://github.com/facebook/react-native/releases/tag/v0.71.4) is out! If you want `FlatList` support, then I recommend updating to this version.

tested with flatlist and sectionList. Works excelent!!

**Comment by lufke** [comment] 2023-06-22 18:13
The problem is back again for FlatList, just created an react native app and must use spread operator on data for see the items on list, otherwise it shows an empty list

"@realm/react": "^0.5.0"
"react-native": "0.71.3"
"realm": "^11.10.1"

I can see the items on console.log

**Comment by skam22** [comment] 2023-06-24 17:02
React native 0.71.3 doesn’t include the changes that meta added. Upgrade to at least 0.71.4On Jun 22, 2023, at 11:13 AM, lufke ***@***.***> wrote:﻿
The problem is back again for FlatList, just created an react native app and must use spread operator on data for see the items on list, otherwise it shows an empty list
***@***.***/react": "^0.5.0"
"react-native": "0.71.3"
"realm": "^11.10.1"
I can see the items on console.log

**Comment by lufke** [comment] 2023-06-24 21:15
> React native 0.71.3 doesn’t include the changes that meta added. Upgrade to at least 0.71.4
> 
> On Jun 22, 2023, at 11:13 AM, lufke wrote:﻿
> The problem is back again for FlatList, just created an react native app and must use spread operator on data for see the items on list, otherwise it shows an empty list
> “react": "^0.5.0"
> "react-native": "0.71.3"
> "realm": "^11.10.1"
> I can see the items on console.log

I deleted the coment because when paste the dependencies i Saw tjat i was using rn 0.71.3 instead 0.71.4
