### ISSUE TITLE
Error: Realm context not found.  Did you call useRealm() within a <RealmProvider/>?

### ISSUE THREAD

**Issue by fatemehmarzoughi** [realm/realm-js#5957] opened 2023-06-29 15:43 UTC
### How frequently does the bug occur?

Always

### Description

I have used Realm for my React-Native project and I have followed the (<a href="https://www.mongodb.com/docs/realm/sdk/react-native/quick-start/">documentation</a>), these are my configs:

<b>This is my Schema (<a href="https://github.com/fatemehmarzoughi/MyPlayer/blob/develop/frontend/src/Realm/models/ItemsModel.ts">Link to the file</a>)</b>
```js
class Item extends Realm.Object<Item> {
  _id!: Realm.BSON.ObjectId;
  title!: string;

  static schema = {
    name: ISchemas.Item,
    properties: {
      _id: 'objectId',
      title: 'string',
    },
    primaryKey: '_id',
  };
}

export const realmConfig: Realm.Configuration = {
  schema: [Item],
  inMemory: true, // setting this to false/true doesn't differ
};
```
<b>This is my Realm context hook (<a href="https://github.com/fatemehmarzoughi/MyPlayer/blob/develop/frontend/src/Realm/context.ts">Link to the file</a>)</b>
```js
import {createRealmContext} from '@realm/react';
import {realmConfig} from './models';

export const useRealmContext = () => {
  return createRealmContext(realmConfig);
};
```

<b>And I have already wrapped my whole App inside a RealmProvider (<a href="https://github.com/fatemehmarzoughi/MyPlayer/blob/develop/frontend/AppProvider.tsx">Link to the file</a>)</b>
```js
const AppProvider: React.FC = React.memo(() => {
  const {RealmProvider} = useRealmContext();
  return (
    <Provider store={store}>
      <NativeBaseProvider>
        <ContextProvider>
          <RealmProvider> // here it is, Changing this Provider position to the top level doesn't differ
            <App />
          </RealmProvider>
        </ContextProvider>
      </NativeBaseProvider>
    </Provider>
  );
});
```

<b>But still I'm getting the error that there is no provider before calling `useRealm` hook inside <a href="https://github.com/fatemehmarzoughi/MyPlayer/blob/develop/frontend/src/Realm/hooks/useRealmCRUD.ts">this file</a></b>
```js
export const useRealmCRUD = ({onRealmChange}: IUseRealmCRUD) => {
  const {useRealm, useQuery, useObject} = useRealmContext();
  const realm = useRealm(); // here is the error

  .....
});
```

### Stacktrace & log output

```shell
Error: Realm context not found.  Did you call useRealm() within a <RealmProvider/>?

This error is located at:
    in Unknown (created by Connect(Component))
    in Connect(Component) (at AppRoute.tsx:253)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:124)
    in SceneView (at useDescriptors.tsx:218)
    in RCTView (at View.js:89)
    in View (at DebugContainer.native.tsx:27)
    in DebugContainer (at NativeStackView.native.tsx:82)
    in MaybeNestedStack (at NativeStackView.native.tsx:326)
    in RCTView (at View.js:89)
    in View (at NativeStackView.native.tsx:319)
    in RNSScreen (at createAnimatedComponent.js:211)
    in AnimatedComponent (at createAnimatedComponent.js:264)
    in AnimatedComponentWrapper (at src/index.native.tsx:300)
    in Suspender (at src/index.tsx:40)
    in Suspense (at src/index.tsx:39)
    in Freeze (at src/index.native.tsx:203)
    in DelayedFreeze (at src/index.native.tsx:299)
    in InnerScreen (at src/index.native.tsx:545)
    in Screen (at NativeStackView.native.tsx:244)
    in SceneView (at NativeStackView.native.tsx:385)
    in Suspender (at src/index.tsx:40)
    in Suspense (at src/index.tsx:39)
    in Freeze (at src/index.native.tsx:203)
    in DelayedFreeze (at src/index.native.tsx:217)
    in RNSScreenStack (at src/index.native.tsx:224)
    in ScreenStack (at NativeStackView.native.tsx:373)
    in NativeStackViewInner (at NativeStackView.native.tsx:446)
    in RCTView (at View.js:89)
    in View (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at NativeStackView.native.tsx:445)
    in NativeStackView (at createNativeStackNavigator.tsx:72)
    in PreventRemoveProvider (at useNavigationBuilder.tsx:718)
    in NavigationContent (at useComponent.tsx:35)
    in Unknown (at createNativeStackNavigator.tsx:71)
    in NativeStackNavigator (at AppRoute.tsx:222)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:430)
    in BaseNavigationContainer (at NavigationContainer.tsx:132)
    in ThemeProvider (at NavigationContainer.tsx:131)
    in NavigationContainerInner (at AppRoute.tsx:220)
    in ThemeProvider (at PaperProvider.tsx:113)
    in RCTView (at View.js:89)
    in View (at PortalHost.tsx:126)
    in Portal.Host (at PaperProvider.tsx:104)
    in RCTView (at View.js:89)
    in View (at SafeAreaProviderCompat.tsx:46)
    in SafeAreaProviderCompat (at PaperProvider.tsx:103)
    in PaperProvider (at AppRoute.tsx:219)
    in Unknown (at App.tsx:94)
    in Unknown (at App.tsx:92)
    in App (at AppProvider.tsx:23)
    in ContextProvider (at AppProvider.tsx:21)
    in $29383e587d62412a$export$9f8ac96af4b1b2ae (at NativeBaseProvider.tsx:97)
    in ToastProvider (at NativeBaseProvider.tsx:95)
    in PortalProvider (at NativeBaseProvider.tsx:94)
    in HybridProvider (at NativeBaseProvider.tsx:90)
    in ResponsiveQueryProvider (at NativeBaseProvider.tsx:89)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:87)
    in SafeAreaProvider (at NativeBaseProvider.tsx:84)
    in NativeBaseConfigProviderProvider (at NativeBaseProvider.tsx:77)
    in NativeBaseProvider (at AppProvider.tsx:20)
    in Provider (at AppProvider.tsx:19)
    in _c (at renderApplication.js:57)
    in RCTView (at View.js:89)
    in View (at AppContainer.js:101)
    in RCTView (at View.js:89)
    in View (at AppContainer.js:128)
    in AppContainer (at renderApplication.js:50)
    in MyPlayer(RootComponent) (at renderApplication.js:67), js engine: hermes
```

### Can you reproduce the bug?

Always

### Reproduction Steps

MyProject is open source so you can find the bug in the <b>develop branch</b> of this <a href="https://github.com/fatemehmarzoughi/MyPlayer/tree/develop">repo</a>

### Version

"react-native": "0.71.8",

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS simulator (iPhone 11 v16.4)

### Build environment

```
"react-native": "0.71.8",
"realm": "^11.9.0",
"@realm/react": "^0.5.1",
```

**Comment by takameyer** [comment] 2023-06-30 07:35
Hi @fatemehmarzoughi.  First off, thanks for trying out Realm and providing an easy way to reproduce this issue.  I have tried your code and found out where the problem lies.  It is your implementation of `useRealmContext()`.  Currently, everytime you use `useRealmContext()`, the hook will call `createRealmContext` on every rerender.  This will cause the original context you created at the AppProvider to be different than the one you use elsewhere within the app.  The quick fix for this would be to do this:
```tsx
const realmContext = createRealmContext(realmConfig);

export const useRealmContext = () => realmContext;
```

Here the context is created once and is returned from your hook.  

Alternatively, since version v0.5.0 we create an initial context for you so that you can import the realm hooks and providers directly from `@realm/react`.  So you could have your AppProvider as so:
```tsx
import { RealmProvider } from '@realm/react';
import { realmConfig } from 'src/Realm/models';

const AppProvider: React.FC = React.memo(() => {
  const {RealmProvider} = useRealmContext();
  return (
    <Provider store={store}>
      <NativeBaseProvider>
        <ContextProvider>
          <RealmProvider {...realmConfig}>
            <App />
          </RealmProvider>
        </ContextProvider>
      </NativeBaseProvider>
    </Provider>
  );
});
```

and implement as so:

```tsx
import {useRealm, useQuery, useObject} from '@realm/react';
export const useRealmCRUD = ({onRealmChange}: IUseRealmCRUD) => {
  const realm = useRealm(); // no more error

  ....
});
```

Then you will not need to call `createRealmContext` (unless you want multiple realm databases in an app, which is unlikely)

**Closed** 2023-06-30 07:35 UTC
Labels: T-Bug, O-Community, SDK-Use:Local, Encryption:Off, Frequency:Always, Repro:Always

**Comment by fatemehmarzoughi** [comment] 2023-07-01 09:59
> Hi @fatemehmarzoughi. First off, thanks for trying out Realm and providing an easy way to reproduce this issue. I have tried your code and found out where the problem lies. It is your implementation of `useRealmContext()`. Currently, everytime you use `useRealmContext()`, the hook will call `createRealmContext` on every rerender. This will cause the original context you created at the AppProvider to be different than the one you use elsewhere within the app. The quick fix for this would be to do this:
> 
> ```tsx
> const realmContext = createRealmContext(realmConfig);
> 
> export const useRealmContext = () => realmContext;
> ```
> 
> Here the context is created once and is returned from your hook. You should also not use `inMemory` realm, otherwise your data will not persist.
> 
> Alternatively, since version v0.5.0 we create an initial context for you so that you can import the realm hooks and providers directly from `@realm/react`. So you could have your AppProvider as so:
> 
> ```tsx
> import { RealmProvider } from '@realm/react';
> import { realmConfig } from 'src/Realm/models';
> 
> const AppProvider: React.FC = React.memo(() => {
>   const {RealmProvider} = useRealmContext();
>   return (
>     <Provider store={store}>
>       <NativeBaseProvider>
>         <ContextProvider>
>           <RealmProvider {...realmConfig}>
>             <App />
>           </RealmProvider>
>         </ContextProvider>
>       </NativeBaseProvider>
>     </Provider>
>   );
> });
> ```
> 
> and implement as so:
> 
> ```tsx
> import {useRealm, useQuery, useObject} from '@realm/react';
> export const useRealmCRUD = ({onRealmChange}: IUseRealmCRUD) => {
>   const realm = useRealm(); // no more error
> 
>   ....
> });
> ```
> 
> Then you will not need to call `createRealmContext` (unless you want multiple realm databases in an app, which is unlikely)

It worked, Thanks a lot for devoting your time, pray:

**Comment by joeljerushan** [comment] 2023-07-21 17:05
i would like to try Realm for my apps.. but every-time i start checking documentation i'm getting confused and ended up with this error anyone can help me on this ? 
![simulator_screenshot_1059A659-E891-4A62-BD40-481942CE142B](https://github.com/realm/realm-js/assets/10111309/b10033a5-37b3-4c38-9cd1-5f3bf47e512a)<br/><br/>
This is my index file 
![image](https://github.com/realm/realm-js/assets/10111309/b9011456-e875-4282-8c5d-a665e9e3d922)
This is App.js file 
![image](https://github.com/realm/realm-js/assets/10111309/016a8965-dd3d-4108-8ba9-0f79ec917062)
ProfileListScreen.js
![image](https://github.com/realm/realm-js/assets/10111309/8db43158-ac00-4177-babe-d4c8d590b37c)
addProfileScreen.js
![image](https://github.com/realm/realm-js/assets/10111309/eb405053-cbae-414d-82aa-a0935dbae4d6)
UpdateProfileScreen.js
![image](https://github.com/realm/realm-js/assets/10111309/3dd31d77-3a88-482a-b634-ef622ea6e181)

**Comment by konradjurk** [comment] 2023-07-21 19:29
@joeljerushan I just had the same problem following the documentation on the website. I stumbled over this example and it seems to work: https://github.com/realm/realm-js/blob/main/example/app/AppWrapperNonSync.tsx

Good luck!

**Comment by CristianFigueredo** [comment] 2023-11-29 20:03
Greetings!
I found a solution that resolved my issue, and I sincerely hope it proves beneficial for you as well.

To implement the fix, kindly replace the usage of `createRealmContext` with the imported `RealmProvider`. Something like this:

```jsx
// First, import RealmProvider
import { RealmProvider } from "@realm/react"

// Then, utilize RealmProvider with your specified schemas
<RealmProvider schema={yourSchemas}>
  <YourApp />
</RealmProvider>
```
