### ISSUE TITLE
OpenAsync returns an incorrect callback

### ISSUE THREAD

**Issue by ArsalanBashir** [realm/realm-js#1152] opened 2017-07-20 10:12 UTC
## Goals

I'm trying to load information stored in an ROS in a client device using ReactNative. I successfully created a local realm, and was able to operate it with no problem whatsoever. I wish to have some text stored in an ROS, which I will edit from time to time using the Realm Browser, and have that reflect on the client device. 

## Expected Results

Expected the callback of the OpenAsync method to include error (if any at all) and the realm object. 

## Actual Results

The realm object is undefined, but the error returns just fine (of course, only when there is an error to return)

## Steps to Reproduce

Simply create a remote realm using OpenAsync on react native. 

## Code Sample

https://gist.github.com/ArsalanBashir/b4bedbcd597e13be315129e0f7f7d6ba

## Version of Realm and Tooling

- Realm JS SDK Version: 1.10.0
- Node or React Native: React Native
- Client OS & Version: iOS 10.3
- Which debugger for React Native: None

**Comment by ArsalanBashir** [comment] 2017-07-20 10:12
I suspect this is closely related to #1140

**Comment by kneth** [comment] 2017-07-31 08:56
@ArsalanBashir Since #1140 has been resolved, can you still reproduce it?

**Comment by kneth** [comment] 2017-08-10 09:26
@ArsalanBashir With 1.10.1 released, the fixed in #1140 is out. I suggest that you upgrade and see if your issue has been solved. I close the issue but don't hesitate to reopen if the issue hasn't been solved.

**Closed by kneth** 2017-08-10 09:26 UTC
Labels: Reproduction Required, T:Bug
