### ISSUE TITLE
Crashed app when enabling Hermes on IOS (React-native 0.64)

### ISSUE THREAD

**Issue by DuCaoTien** [realm/realm-js#3657] opened 2021-03-22 09:28 UTC
## Goals

**To enable Hermes on iOS**

## Expected Results

The application works normally

## Actual Results
com.facebook.react.JavaScript (12): EXC_BAD_ACCESS (code=2, address=0x10dd53190)
![image](https://user-images.githubusercontent.com/26642281/111967990-44429180-8b2b-11eb-8f95-44c2cded9157.png)
![image](https://user-images.githubusercontent.com/26642281/111968302-9683b280-8b2b-11eb-8ee7-fcf447e7e460.png)

## Steps to Reproduce
1. Update react-native to version 0.64
2. Enabled Hermes on Podfile
Follow this link: https://reactnative.dev/blog/2021/03/12/version-0.64

## Code Sample
use_react_native!(
   :path => config[:reactNativePath],
   :hermes_enabled => true
)

## Version of Realm and Tooling

- Realm JS SDK Version: 10.2.0
- Node or React Native: 0.64.0
- Client OS & Version: macOS Catalina

**Comment by maxencehenneron** [comment] 2021-03-23 07:58
@DuCaoTien Realm-js does not support hermes, but it is their "top priority" https://github.com/realm/realm-js/issues/2455#issuecomment-799188897

**Comment by DuCaoTien** [comment] 2021-03-23 08:23
Thanks @maxencehenneron. Hope it working asap

**Comment by kneth** [comment] 2021-03-23 13:40
I close it as a duplicate of #2455.

**Closed by kneth** 2021-03-23 13:40 UTC
Labels: O-Community
