### ISSUE TITLE
[React native] Decryption failed on real ios device

### ISSUE THREAD

**Issue by thanhnd1o2** [realm/realm-js#6366] opened 2024-01-13 12:35 UTC
### How frequently does the bug occur?

Always

### Description

I got decryption failed on real ios device but it works perfectly on others like ios simulator, android, realm studio. I don't know why

### Stacktrace & log output

```shell
Error: Failed to open Realm file at path '/var/mobile/Containers/Data/Application/8D449C47-2A27-486C-A9B6-B088C9D8B126/Documents/bundle.realm': Realm file decryption failed (Decryption failed)

This error is located at:
    in Unknown (created by App)
    in ThemeProvider (created by App)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by App)
    in RecoilRoot_INTERNAL (created by RecoilRoot)
    in RecoilRoot (created by App)
    in RCTView (created by View)
    in View (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in apptest(RootComponent), js engine: hermes
```

### Can you reproduce the bug?

Always

### Version

>=12.2.1

### What services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

17.2.1

### Build environment

Which debugger for React Native: ..

### Cocoapods version

~> 1.13

**Comment by thanhnd1o2** [comment] 2024-01-14 08:10
Is there anyone to help me?

**Comment by kneth** [comment] 2024-01-18 16:04
@thanhnd1o2 

You provide very little information. Forgive me for asking, but you are certain that the encryption key is correct?

In version 12.3.0 we have a fix related to encryption but it doesn't cover your case.

Can you provide a small project which can reproduce the issue?

**Comment by nirinchev** [comment] 2024-03-20 20:02
Realm files are not portable across different operating systems, due to the different page size of those platforms. It is not clear which OS you generated `bundle.realm` on, but the name implies it was created on a platform different than the platform it's running on and thus the most likely explanation is the different page size.

Closing this, but feel free to reopen if you have more info and/or a repro case.

**Closed by nirinchev** 2024-03-20 20:02 UTC
Labels: T-Bug, O-Community, Waiting-For-Reporter, SDK-Use:Local, Repro:Always, Encryption:On
