### ISSUE TITLE
App.currentUser.profile is empty after app restarts

### ISSUE THREAD

**Issue by yourstruly22** [realm/realm-js#3647] opened 2021-03-15 10:40 UTC
`##` Goals

When logging in a user I use metadata which is added to their currentUser.profile property.
On app.login() the user object contains the profile property which contains all the needed metadata.
After the app is restarted, the user object persists and is still logged in, but the currentUser.profile property is empty.

## Expected Results

app.currentUser.profile should persist when the app is restarted.

## Actual Results

app.currentUser.profile is an empty object after app restarts.

## Code Sample
```
import Realm from 'realm';
import {getRealmApp} from './getRealmApp';

const app = getRealmApp();
const AuthContext = React.createContext(null);

const AuthProvider = ({children}) => {
  const [user, setUser] = useState(app.currentUser);

const signIn = async ({username, password}) => {
       getCustomJwt({username, password})
      .then((jwt) => {
        const credentials = Realm.Credentials.jwt(jwt);
        // Authenticate the user
        app
          .logIn(credentials)
          .then((loggedInUser) => {
            setUser(loggedInUser);
          })
          .catch((err) => console.error('Failed to log in', err));
      })
      .catch((err) => console.log(err));
  };

  return (
    <AuthContext.Provider
      value={{
        signIn,
        user,
      }}>
      {children}
    </AuthContext.Provider>
  );
};
const useAuth = () => {
  const auth = useContext(AuthContext);
  if (auth == null) {
    throw new Error('useAuth() called outside of a AuthProvider?');
  }
  return auth;
};

export {AuthProvider, useAuth};
```

## Version of Realm and Tooling

- Realm JS SDK Version: 10.2
- Node or React Native: React Native
- Client OS & Version: Android 8.0.0
- Which debugger for React Native: Chrome DevTools

**Comment by takameyer** [comment] 2021-03-16 11:18
This is a duplicate of #3561

**Closed by takameyer** 2021-03-16 11:18 UTC
Labels: O-Community
