### ISSUE TITLE
yarn add realm@11.3.1 endless loading

### ISSUE THREAD

**Issue by dimonnwc3** [realm/realm-js#5328] opened 2023-01-25 22:04 UTC
### How frequently does the bug occur?

Always

### Description

when I add realm to react native project it builds infinitely.
Expo 47, RN 0.70, realm 11.3.1

### Stacktrace & log output

```shell
❯ yarn add realm@11.3.1
yarn add v1.22.19
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning realm > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning realm > request > har-validator@5.1.5: this library is no longer supported
warning realm > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[1/1] ⠐ realm
```

### Can you reproduce the bug?

Always

### Reproduction Steps

run `yarn add realm@11.3.1`

### Version

11.3.1

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

MacOS 13.1

### Build environment

Expo 47, RN 0.70
MacBook M1
Nodejs v19.5.0

**Comment by kneth** [comment] 2023-01-26 11:06
I believe it is a duplicate of https://github.com/realm/realm-js/issues/5136. You can try to downgrade to node 18.

**Closed** 2023-01-26 11:07 UTC
Labels: T-Bug, O-Community, SDK-Use:Local, Encryption:Off, Frequency:Always, Repro:Always
