### ISSUE TITLE
Realm graphql throws error: cannot find app using Client Ap

### ISSUE THREAD

**Issue by abhishekmatta999** [realm/realm-js#4191] opened 2022-01-06 06:38 UTC
### How frequently does the bug occur?

All the time

### Description

I’m getting graphql error on the first start of my app
Error is:
“cannot find app using Client App ID”
And when I refresh the app login again it works.

Configurations:
Node js 14,
electron 12.0.0
realm 10.10.1 (Node js SDK)

Here's my code: 
```
const app = new Realm.App({ id: process.env.VUE_APP_REALM_APP_ID })
const credentials = Realm.Credentials.jwt(token);
await app.logIn(credentials);
return app.currentUser.accessToken
```

The token I'm providing is same but on the refresh it starts working.
It throws error: "couldn't find app using Client App ID '----' "
And on the realm logs error is : "token contains an invalid number of segments"

### Can you reproduce the bug?

Yes, always

### Version

10.10.1

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Macos big sur Version: 11.5.2

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment] 2022-01-06 09:31
@abhishekmatta999 Notice that [Realm GraphQL](https://www.npmjs.com/package/realm-graphql-client) is deprecated and cannot be used together with [MongoDB Realm](https://www.mongodb.com/realm). Please take a look at our [GraphQL API](https://docs.mongodb.com/realm/graphql/).

**Comment by abhishekmatta999** [comment] 2022-01-06 09:49
@kneth 
`Credential headers are useful for infrequent or test requests. However, we strongly encourage you to authenticate GraphQL requests using an Authorization Header from a client that uses a Realm SDK.`
This is mentioned in the docs to use a realm SDK and it's advisable to use an authorization header.
And if I'm creating one for the first time when I'm running my app I'm getting this error: "couldn't find the app with realm Id '--xyz--' "

Here's my code:
```
const app = new Realm.App({ id: process.env.VUE_APP_REALM_APP_ID })
const credentials = Realm.Credentials.jwt(token);
await app.logIn(credentials);
return app.currentUser.accessToken
```

Here's my jwt token information
```
{
  "session": {
    "userId": "5e4e58c31c09280007523ee6"
  },
  "aud": "xyz,
  "sub": "user",
  "exp": 1646645802,
  "user_data": {
    "name": "abhi-matta",
    "guid": "5e4e58c31c09280007523ee6"
  },
  "iat": 1641461802
}
```
Could you help me out for the same?

**Comment by kraenhansen** [comment] 2022-01-06 14:50
I would need more concrete code (not just the Realm specific part) to reproduce and locate the root cause of this.

I understand from your process environment that you might be using Vue, but have you seen the React guide on this? https://docs.mongodb.com/realm/web/graphql-apollo-react/

> It throws error: "couldn't find app using Client App ID '----' "

What exact line in your example throws this?

> And on the realm logs error is : "token contains an invalid number of segments"

Is there a filename or line number associated with this log message?

**Comment by abhishekmatta999** [comment] 2022-01-06 16:18
@kraenhansen Thanks for the reply!

1. First time when I try to log in using 
`Realm.credentials.jwt(token)`
and then tries to add the token in graphql queries in headers as 'Bearer ${token}' provided by realm using:
`app.currentUser.accessToken`
It gives this error:
![image](https://user-images.githubusercontent.com/59220090/148414148-d9b64db7-69ef-42c9-b169-d6f6a1e680f2.png)

2. Error Screenshot attached.
![image](https://user-images.githubusercontent.com/59220090/148412492-1b0c5c1d-3fb7-4a82-be8a-ac4af236fdda.png)

**Comment by kraenhansen** [comment] 2022-01-06 16:36
Thanks again for your reply, without more knowledge of the code you're putting the `accessToken` into, I can only speculate what might be going on here. I've asked my colleagues who are more familiar with the GraphQL endpoint (this is not actually a part of the Realm Web SDK, per se) to have a look at this issue.

**Comment by abhishekmatta999** [comment] 2022-01-06 16:42
Here's my code for graphql (using apollo-client for graphql queries):
```
async function getValidAccessToken () {
  try {
    const token = '--token--'
    const app = new Realm.App({ id: process.env.VUE_APP_REALM_APP_ID })
    if (token) {
      const credentials = Realm.Credentials.jwt(token);
      await app.logIn(credentials);
    }
    return app.currentUser.accessToken
  } catch (error) {
    console.error('main token error', error)
  }
}

const apolloClient = new ApolloClient({
    uri: process.env.VUE_APP_REALM_GRAPHQL_URI,
    fetch: async (uri, options) => {
      const accessToken = await getValidAccessToken()
      options.headers.Authorization = `Bearer ${accessToken}`
      return fetch(uri, options)
    }
})

const apolloProvider = new VueApollo({
    defaultClient: apolloClient
})
```

**Comment by abhishekmatta999** [comment] 2022-01-07 04:48
> Thanks again for your reply. Without more knowledge of the code you're putting the `accessToken` into, I can only speculate what might be going on here. I've asked my colleagues who are more familiar with the GraphQL endpoint (this is not actually a part of the Realm Web SDK, per se) to have a look at this issue.

I'm using Realm node js SDK as I'm using it with electron and in addition I'm using graphql API

**Comment by kneth** [comment] 2022-01-18 13:21
@abhishekmatta999 It might be that your token needs to be refreshed (the call to `refreshCustomData()` in https://docs.mongodb.com/realm/web/graphql-apollo-react/#set-up-user-authentication).

Moreover, you could check if everything is fine from the command-line: https://docs.mongodb.com/realm/graphql/cli/

**Comment by abhishekmatta999** [comment] 2022-01-18 13:26
@kneth, I believe refreshing custom data is required when the token is expired. I've logged in for the very first time at the time of installation.

**Comment by kraenhansen** [comment] 2022-01-25 16:03
I tried, but failed to reproduce the issue.
See this repository for a complete example using JWT and the GraphQL endpoint: https://github.com/kraenhansen/realm-js-issue-4191

Since I can't reproduce, I'll close this issue for now. Please adapt your code to my reproduction and reopen this issue with an extended version of the reproduction to show any errors that you're experiencing.

**Closed by kraenhansen** 2022-01-25 16:03 UTC
Labels: T-Bug, O-Community

**Comment by abhishekmatta999** [comment] 2022-01-27 06:07
@kraenhansen Are you using realm node-js SDK or realm-web?

**Comment by kraenhansen** [comment] 2022-01-27 09:06
My reproduction (linked above) is using the Realm JS (Node.js) API from an Electron renderer process.

**Comment by abhishekmatta999** [comment] 2022-01-27 09:15
@kraenhansen , When I'm trying to run the electron app using your repo I'm getting this error:
```
Uncaught Error: Cannot find module 'react'
Require stack:
- /Users/unthinkable-mac-0072/Downloads/realm-js-issue-4191-main/node_modules/@apollo/client/react/context/context.cjs
- /Users/unthinkable-mac-0072/Downloads/realm-js-issue-4191-main/node_modules/@apollo/client/react/react.cjs
- /Users/unthinkable-mac-0072/Downloads/realm-js-issue-4191-main/node_modules/@apollo/client/main.cjs
- /Users/unthinkable-mac-0072/Downloads/realm-js-issue-4191-main/index.html

```

**Comment by kraenhansen** [comment] 2022-01-27 09:23
What version of NPM are you using? If it's below v6 it might not be installing peer dependencies.
I'm running this with:
```
❯ npm -v
8.1.2
❯ node -v
v16.13.1
```

**Comment by abhishekmatta999** [comment] 2022-01-27 09:27
@kraenhansen I'm using this:
Node version: 14.7.3
Npm: 6.14.13

**Comment by kraenhansen** [comment] 2022-01-27 09:34
Try upgrading your NPM, `rm -rf node_modules` and re-install.

**Comment by abhishekmatta999** [comment] 2022-01-27 11:58
@kraenhansen  Still having the same issue after upgrading to the new node& npm versions.
