### ISSUE TITLE
Incompatible with React Native Autolinking (React Native v0.60)

### ISSUE THREAD

**Issue by s1ro6** [realm/realm-js#2460] opened 2019-07-19 06:35 UTC
## Goals

Use the Realm.js with React Native Autolinking correctly.

## Expected Results

Don't show warning information.

Let the CocoaPods don't show warning after executing `pod install`.

## Actual Results

After the `pod install`, it shows the following warning:

```
[!] use_native_modules! skipped the react-native dependency 'realm'. No podspec file was found.
    - Check to see if there is an updated version that contains the necessary podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The react-native-webview podspec is a good example of a package.json driven podspec. See
    https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
    - If necessary, you can disable autolinking for the dependency and link it manually. See
    https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library
```

## Steps to Reproduce

```bash
cd ${REACT_NATIVE_PROJECT_ROOT_PATH}
npm install --save realm
cd ios && pod install & cd ..
```

## Version of Realm and Tooling

- Realm JS SDK Version: `realm-js 2.29.1`
- Node or React Native: `React Native v0.60.3`
- Client OS & Version: `iOS 12.2`
- Which debugger for React Native: `None`

**Comment by cantonalex** [comment] 2019-07-23 05:19
What's the workaround for this?

**Comment by renalpraba** [comment] 2019-07-23 06:22
> What's the workaround for this?

run ```npx react-native link realm``` then ```npx jetify```
ignore the warning, my project is running properly with that

**Comment by m-ochyra** [comment] 2019-07-23 06:36
> > What's the workaround for this?
> 
> run `npx react-native link realm` then `npx jetify`
> ignore the warning, my project is running properly with that

Jetify is for Android.

I have different issue but I think it is connected with autolinking on iOS. After realm installation, ``pod install`` gives me following error:

```
[!] Invalid `Podfile` file: no implicit conversion of nil into String.

 #  from /Users/marcinochyra/projects/classified/ios/Podfile:37
 #  -------------------------------------------
 #  
 >    use_native_modules!
 #  end
 #  -------------------------------------------
```

**Comment by mnlbox** [comment] 2019-07-24 10:34
Related warning:
```
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - realm: https://realm.io
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
```

**Comment by CaptainQuark** [comment] 2019-07-28 20:28
To fix the pod's `use_native_modules!`-error, just add a `react-native-config.js`-file in the root of your project with the following code (exclusive example for realm, but you get the idea):

```
module.exports = {
  dependencies: {
    realm: {
      platforms: {
        ios: null // disable iOS platform, other platforms will still autolink if provided
      }
    }
  }
};
```

👉 [autolinking info](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md) for more info

Disabling autolinking means we have to use good ol' manual linking, but sadly realm doesn't provide a guide here and the standard way (as told by the react-native-team) doesn't work, either. 

I followed the [this guide](https://www.fabrizioduroni.it/2017/11/14/react-native-realm-custom-manual-linking-app-custom-directories-ios.html), but still get the `Cannot read property 'debugHosts' of undefined` error. It looks like the export of NativeModules in RealmJS is undefined, thus no destruction of `debugHosts`. 

Looking forward for this issue to being closed.

**Comment by excitedcat** [comment] 2019-07-30 05:17
**warn** The following packages use deprecated "rnpm" config that will stop working from next release:
  - realm: https://realm.io

Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

**Comment by edritech93** [comment] 2019-08-21 03:09
same for me

**Comment by conorbr** [comment] 2019-08-29 13:53
I'm getting the same problem as @excitedcat. Has anyone found a solution?

**Comment by d14na** [comment] 2019-09-04 03:21
> Currently we only support React Native (both iOS & Android)

I would beg to differ. Finally upgraded to RN 0.60 _(you know to support 64-bit on Play),_ and now I gotta go looking for an alternative local db. ugh!

**Comment by liamjones** [comment] 2019-09-04 07:25
@d14na You don't need to change DB. We've got two RN 0.60.5 apps using Realm 2.29.1 live with the Android 64-bit update.

The only issue right now is that it doesn't support autolinking, but that doesn't mean you can't use the module.

Just tell RN it doesn't support autolinking on ios (Android actually works fine since it works in a different manner) by editing your `react-native.config.js` like so:

```
module.exports = {
    dependencies: {
        'realm': {
            platforms: {
                ios: null,
            },
        },
    },
}
```

Since you're upgrading a project I assume your iOS project already has the manually linked `RealmReact.xcodeproj`? That'll be sufficient for the iOS side. On the Android side ensure the `implementation project(':realm')` isn't in the `app/build.gradle` and:
```
include ':realm'
project(':realm').projectDir = new File(rootProject.projectDir, '../node_modules/realm/android')
```
isn't in the `settings.gradle` and you should be good to go on both platforms. Android will autolink, iOS won't.

**Comment by joaodematejr** [comment] 2019-09-04 13:29
+1

**Comment by blagoev** [comment] 2019-09-04 18:40
Hey everyone. There are already plans to fix this soon.

**Comment by mattmogford** [comment] 2019-09-04 18:41
Really could do with Hermes at the moment so this is good news

**Comment by mohammadalijf** [comment] 2019-09-22 09:47
can it be marked as bug? i use custom xcode config file for Develop, Stage, Release. using both Cocoapods and manual linking cause xcode fail due to incorrect CONFIGURATION_BUILD_DIR

**Comment by empitechathu** [comment] 2019-09-30 03:26
I m using React Native 0.60.5 for my project and I am having the same issue. I tried every thing guys suggested here and nothing happened. I added realm 2.29.1 and done react-native link command and linked the library and then added the react-native-config file and added the code suggested by one guy here to ignore pod lookup for realm. Nothing happening and I am still getting an error of 'Native Module cannot be null' Error

**Comment by henriqueweiand** [comment] 2019-10-03 22:29
I have this problem too :(

**Comment by Malikkhoja** [comment] 2019-10-04 18:14
Facing same issue :(

**Comment by ertankara** [comment] 2019-10-08 00:10
I was hyped to use RealmDB for the current project but, I've been chasing errors after errors. This is an awesome project and I really hope to see it up without errors soon :/

**Comment by pengcao1** [comment] 2019-10-12 07:04
any solution or update for react-native 0.60 above??

**Comment by Yieron** [comment] 2019-10-12 12:52
> > What's the workaround for this?
> 
> run `npx react-native link realm` then `npx jetify`
> ignore the warning, my project is running properly with that

![image](https://user-images.githubusercontent.com/16173466/66701731-1e0fa400-ed32-11e9-9ac4-b28edc1fadd2.png)
not work

**Comment by kraenhansen** [comment] 2019-10-18 14:46
I'm working on this from https://github.com/realm/realm-js/tree/kh/podspec, after checkout run `pod spec lint` to attempt a compilation. Any help getting this to pass linting would be greatly appreciated.

**Comment by mindwards** [comment] 2019-10-18 19:35
> I'm getting the same error as @excitedcat. Has anyone found a solution?
I've tried the solutions posted here, and manual linking works.

1. Add a `react-native.config.js` config file in the root of the project with this content:

```module.exports = {
    dependencies: {
        'realm': {
            platforms: {
                ios: null,
            },
        },
    },
}```

That will skip autolinking for Realm for iOS.

2. Add the project `RealmReact.xcodeproj` from `node_modules` into your project as a subproject

3. Be sure to include `libRealmReact.a` in the `Link Binary With Libraries` step of your target `Build Phases`. 
**Important**: I've spent a lot of time chasing the `Cannot read property 'debugHosts' of undefined` bug because I was linking to `libRealm.a` and not `libRealmReact.a`, I'm sure that may happen to someone else.

**Comment by kmvkrish** [comment] 2019-10-31 10:07
> > I'm getting the same error as @excitedcat. Has anyone found a solution?
> 
> I've tried the solutions posted here, and manual linking works.
> 
> 1. Add a `react-native.config.js` config file in the root of the project with this content:
> 
> ```
> module.exports = {
>     dependencies: {
>         'realm': {
>             platforms: {
>                 ios: null,
>             },
>         },
>     },
> }
> ```
> 
> That will skip autolinking for Realm for iOS.
> 
> 1. Add the project `RealmReact.xcodeproj` from `node_modules` into your project as a subproject
> 2. Be sure to include `libRealmReact.a` in the `Link Binary With Libraries` step of your target `Build Phases`.
>    **Important**: I've spent a lot of time chasing the `Cannot read property 'debugHosts' of undefined` bug because I was linking to `libRealm.a` and not `libRealmReact.a`, I'm sure that may happen to someone else.

We have followed the same approach, but ended up with the error "**React/RCTBridge+Private.h file noti found**"

Can you please suggest us if we have missed specifying any PODs path in **HEADER_SEARCH_PATH** of the iOS project?

**Comment by abcpen-inc** [comment] 2019-10-31 13:49
> > > I'm getting the same error as @excitedcat. Has anyone found a solution?
> > 
> > 
> > I've tried the solutions posted here, and manual linking works.
> > 
> > 1. Add a `react-native.config.js` config file in the root of the project with this content:
> > 
> > ```
> > module.exports = {
> >     dependencies: {
> >         'realm': {
> >             platforms: {
> >                 ios: null,
> >             },
> >         },
> >     },
> > }
> > ```
> > 
> > 
> > That will skip autolinking for Realm for iOS.
> > 
> > 1. Add the project `RealmReact.xcodeproj` from `node_modules` into your project as a subproject
> > 2. Be sure to include `libRealmReact.a` in the `Link Binary With Libraries` step of your target `Build Phases`.
> >    **Important**: I've spent a lot of time chasing the `Cannot read property 'debugHosts' of undefined` bug because I was linking to `libRealm.a` and not `libRealmReact.a`, I'm sure that may happen to someone else.
> 
> We have followed the same approach, but ended up with the error "**React/RCTBridge+Private.h file noti found**"
> 
> Can you please suggest us if we have missed specifying any PODs path in **HEADER_SEARCH_PATH** of the iOS project?

Add RealmReact target to Podfile,It's work,but can't Archive.

~~~
target 'RealmReact' do
  pod 'React', :path => '../node_modules/react-native/'
  project '../node_modules/realm/react-native/ios/RealmReact.xcodeproj'
end
~~~

**Comment by kraenhansen** [comment] 2019-11-01 14:29
I have a PR ready for this https://github.com/realm/realm-js/pull/2586.
If some of you have experience writing Podspec files and especially in the context of React Native libraries, it would be really awesome if you spent a few minutes reviewing the change and adding a comment on the PR.

It would also be great if one or more of you wanted to test out the changes:
1. Clone the PRs branch: `git clone --single-branch --branch kh/podspec https://github.com/realm/realm-js.git`
2. Install dependencies: `npm install`
3. Pack Realm JS to an archive: `npm pack`
4. From your app, install Realm JS from the archive: `npm install [path to realm-js]/realm-3.3.0.tgz`
5. Build your app and confirm that it's working .. you might need to run `react-native unlink realm` first.

**Comment by kenbchung** [comment] 2019-11-01 16:27
@kraenhansen I tried cloning your branch as suggested and installing realm from the npm pack output, but i'm getting this error when trying to do pod install

cp: src/object-store/src/*.hpp: No such file or directory

**Comment by GreyGao** [comment] 2019-11-02 06:43
@2586 @kraenhansen 
if the react-native version >=0.60, we don't have public header files in /ios/Pods/Headers/Public/React-Core
![image](https://user-images.githubusercontent.com/27724175/68067236-05b60680-fd7f-11e9-866b-f56583745e0c.png)
so the build can not be compiled.

**Comment by kraenhansen** [comment] 2019-11-02 07:12
> @kraenhansen I tried cloning your branch as suggested and installing realm from the npm pack output, but i'm getting this error when trying to do pod install
> 
> cp: src/object-store/src/*.hpp: No such file or directory

I pushed an update to the branch, please pull and try again.

**Comment by GreyGao** [comment] 2019-11-02 08:13
fix my question:
if `Podfile` we used `use_frameworks!`
then it can not be found /Pods/Headers/Public/React-Core anymore
so how could I fix this problems

**Comment by prscX** [comment] 2019-11-02 16:36
Hi @kraenhansen: I have tried installing realm using your branch. Post installation, I am encountered with below error during project build, as per [issues/2271](https://github.com/realm/realm-js/issues/2271) I have tried adding `JavaScriptCore.framework` but no luck:

<img width="1070" alt="Screenshot 2019-11-02 at 10 02 36 PM" src="https://user-images.githubusercontent.com/28862892/68074056-db833980-fdbc-11e9-9d35-e827c2d79a6f.png">

Could you please guide me to solve this issue.

Thanks
</ Pranav >

**Comment by kraenhansen** [comment] 2019-11-02 22:01
I've pushed to the `kh/podspec` branch what I believe is a fix for the case where the Podfile calls `use_frameworks!`.

@GreyGao Please pull the latest update to the branch and try again.

@prscX You are you using `use_frameworks!` in your Podfile, right?
Please pull the latest update to the branch and try again.

**Comment by prscX** [comment] 2019-11-03 03:48
Thanks a lot @kraenhansen for quick support. It worked post taking pull 💯.

Yes, I am using `use_frameworks!` in Podfile for few Swift library integration.

Thanks
</ Pranav >

**Comment by GreyGao** [comment] 2019-11-04 04:00
Thanks for @kraenhansen help！😄 ❤️
It works.

**Comment by kraenhansen** [comment] 2019-11-04 07:54
Great! We'll roll-up a release with this ASAP.

**Comment by cmeiller** [comment] 2019-11-04 09:35
@kraenhansen I tried your package but I got this error to run on simulator:
```
Undefined symbols for architecture x86_64:
  "_RCTJSThread", referenced from:
      -[RealmReact setBridge:] in RealmReact.o
  "_RCTRegisterModule", referenced from:
      +[RealmReact load] in RealmReact.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

What's wrong?

**Comment by kraenhansen** [comment] 2019-11-04 09:51
@cmeiller 

> What's wrong?

I believe this is caused by the Podspec incorrectly referencing the RCTBridge headers. Would you mind sharing a bit more information about your setup?
- Did you pull the latest changes to the branch? (Git SHA `4a404b6` or `910ae34`).
- Are your project calling `use_frameworks!` in your Podfile?
- Can you paste or screenshot an image of your directory structure? Specifically, I am curious about your project's root directory: Does it contain an `ios` folder which contains the `Podfile` and `Pods` directory and does your root directory contain the `node_modules` directory as a direct descendant?

**Comment by cmeiller** [comment] 2019-11-04 12:10
@kraenhansen yes I have the latest changes and I'm calling `use_frameworks!` in my Podfile.
Here is my directory root structure (I cut the root files below):
<img width="222" alt="Capture d’écran 2019-11-04 à 13 02 26" src="https://user-images.githubusercontent.com/412839/68119620-6ec68700-ff03-11e9-95b1-a3aafed58af3.png">

Thank you for your answer :)

**Comment by kraenhansen** [comment] 2019-11-04 12:18
@cmeiller I've moved our conversation to a new issue https://github.com/realm/realm-js/issues/2590, let's continue there.

**Closed** 2019-11-11 09:28 UTC
Labels: O-Community, T-Enhancement

**Comment by esutton** [comment] 2019-12-04 20:51
@CaptainQuark could you please edit your comment?

File name must be: **react-native.config.js**

```diff
- react-native-config.js <= Wrong !!!!
+ react-native.config.js
```

**Comment by CaptainQuark** [comment] 2019-12-04 21:24
> @CaptainQuark could you please edit your comment?
> 
> File name must be: **react-native.config.js**
> 
> ```diff
> - react-native-config.js <= Wrong !!!!
> + react-native.config.js
> ```

 🤦‍♂️ Sure, fixed.
