### ISSUE TITLE
realm.object() returning array with empty object

### ISSUE THREAD

**Issue by Trosdan** [realm/realm-js#3710] opened 2021-05-04 17:45 UTC
## Goals

Read data after write

## Expected Results

That the data be returned after using the function `realm.objects ('TermoOrientacao')`

## Actual Results

A list with empty objects is being returned `[{}, {}]`

## Steps to Reproduce

Write an object in the database and after trying to read

### Schema
```javascript
import { ObjectSchema } from 'realm';

export default class TermoOrientacao {
  public static schema: ObjectSchema = {
    name: 'TermoOrientacao',
    primaryKey: 'id',
    properties: {
      id: 'string',
      agenteFiscalizacaoId: 'string',
      estabelecimentoComercialId: 'string',
      observacao: 'string',
      dataCadastro: 'date',
      dataAlteracao: 'date',
      dataHoraFiscalizacao: 'date',
      codigoFiscalizacao: 'int',
      versao: 'string',
    },
  };

  public id!: string;

  public agenteFiscalizacaoId!: string;

  public estabelecimentoComercialId!: string;

  public observacao!: string;

  public dataCadastro!: Date;

  public dataAlteracao!: Date;

  public dataHoraFiscalizacao!: Date;

  public codigoFiscalizacao!: number;

  public versao!: string;
}
```

### getRealm
```javascript
import Realm from 'realm';

import TermoOrientacao from './schemas/TermoOrientacao';

export default function getRealm(): ProgressPromise {
  return Realm.open({
    schemaVersion: 1,
    schema: [TermoOrientacao.schema],
  });
}
```

### Write Data
```javascript
  const saveTermoOrientacao = useCallback(
    async ({
      observacao,
      dataHoraFiscalizacao,
    }: Pick<TermoOrientacao, 'observacao' | 'dataHoraFiscalizacao'>) => {
      try {
        const realm = await getRealm();

        realm.write(() => {
          realm.create<TermoOrientacao>('TermoOrientacao', {
            id: uuid(),
            dataCadastro: new Date(),
            dataAlteracao: new Date(),
            agenteFiscalizacaoId: '123',
            estabelecimentoComercialId: '312',
            codigoFiscalizacao: 123,
            observacao,
            dataHoraFiscalizacao,
            versao: Constants.nativeAppVersion as string,
          });
        });

        realm.close();
      } catch (e) {
        // e
      }
    },
    [],
  );
```

### Read data
```javascript
  const listTermoOrientacao = useCallback(async () => {
    try {
      setLoading(true);
      const realm = await getRealm();

      const termoOrientacaoRealmObj = realm.objects<TermoOrientacao>(
        'TermoOrientacao',
      );

      termoOrientacaoRealmObj.forEach((item, index) => {
        console.log({
          index,
          item,
          itemId: item.id,
          itemNome: item.observacao,
        });
      });

      console.log('Start List', {
        termoOrientacaoRealmObj: termoOrientacaoRealmObj.values(),
        termoOrientacaoArray: Array.from(termoOrientacaoRealmObj),
      });
      // setTermoOrientacaoData();
    } catch (e) {
      console.log('Error List');
      console.log(e);
    } finally {
      console.log('Finish List');
      setLoading(false);
    }
  }, []);
```
### The logs after write 2 items
```
{"index": 0, "item": {}, "itemId": undefined, "itemNome": undefined}     
{"index": 1, "item": {}, "itemId": undefined, "itemNome": undefined}     

Start List {"termoOrientacaoArray": [{}, {}], "termoOrientacaoRealmObj":  {}}

Finish List
```

## Version of Realm and Tooling

- Realm JS SDK Version: 10.3.0
- Node or React Native: 0.63.4
- Client OS & Version: Emulator Android 10
- Which debugger for React Native: ?/None

**Comment by DuCaoTien** [comment] 2021-05-05 09:46
Same the issue. Please let me know if you have any solutions.
- Realm JS SDK Version: 10.4.0
- Node or React Native: 0.64.0
- Client OS & Version: Emulator Android 10
- Which debugger for React Native: ?/None

**Comment by Trosdan** [comment] 2021-05-05 11:26
No solution yet

**Comment by kneth** [comment] 2021-05-05 11:56
Closing as a duplicate of https://github.com/realm/realm-js/issues/2758

**Comment by kneth** [comment] 2021-05-05 13:15
Sorry, I was too quick. Just for be sure: you only observe it on Android, and with a debugger attached?

**Comment by Trosdan** [comment] 2021-05-05 21:04
Verifique os logs usando metro bundler e Flipper, ambos retornam o mesmo resultado. Tentei mostrar dados na tela e foi retornado indefinido

**Comment by DuCaoTien** [comment] 2021-05-07 04:30
Hi @Trosdan, @kneth . My problem was resolved by decreasing the version of react-native-reanimated (2.1.0 -> 1.13.3). I think there are conflicts between the 2 libraries on android. @Trosdan Hope this can helps you if you get the same problem.

**Comment by Trosdan** [comment] 2021-05-07 14:03
@DuCaoTien Changing the version of react-native-reanimated to 1.13.3 solved the problem, I believe that using the bare flow of the expo I needed to make some changes to the native code of android.

```
package br.com.novetech.atendvigilanciasanitaria;

// Others imports
import expo.modules.updates.UpdatesController;

import com.facebook.react.bridge.JSIModulePackage;
// import com.swmansion.reanimated.ReanimatedJSIModulePackage;  <- this

import java.lang.reflect.InvocationTargetException;
import java.util.Arrays;
import java.util.List;
import javax.annotation.Nullable;

public class MainApplication extends Application implements ReactApplication {
    // @Override
    // protected JSIModulePackage getJSIModulePackage() {   <- this
    //   return new ReanimatedJSIModulePackage();
    // }

    // Other override functions
}

**Comment by steffenagger** [comment] 2021-05-07 14:14
@DuCaoTien & @Trosdan react-native-reanimated requires Hermes: https://docs.swmansion.com/react-native-reanimated/docs/installation/#android
Realm does not yet support Hermes.

**Closed** 2021-05-10 10:13 UTC
Labels: O-Community

**Comment by ebasharin** [comment] 2021-05-12 06:50
This seems to be a valid issue.
React-native-reanimated v2.1.0 supports JSC on Android (https://github.com/software-mansion/react-native-reanimated/releases/tag/2.1.0).
Realm.object() returns a list with empty objects [{}, {}] while working together with react-native-reanimated v.2.1.0.
