### ISSUE TITLE
Can't build on iOS due supporting "n" version manager

### ISSUE THREAD

**Issue by radeno** [realm/realm-js#2099] opened 2018-11-08 13:09 UTC
## Goals

Fix issue with `shellScript`
Need to revert this PR https://github.com/realm/realm-js/pull/2078

## Expected Results

Build and Run iOS app

## Actual Results

```
RealmJS requires a node package manager (n or nvm).
Command /bin/sh failed with exit code 1
```

## Steps to Reproduce

Replace shellScript in file src/RealmJS.xcodeproj on line 863 with code before PR:
```
shellScript = "if [[ -d \"$HOME/.asdf/shims\" ]]; then\n  export PATH=$HOME/.asdf/shims:$PATH\nfi\n\n[ -z \"$NVM_DIR\" ] && export NVM_DIR=\"$HOME/.nvm\"\n\nif [[ -s \"$HOME/.nvm/nvm.sh\" ]]; then\n  . \"$HOME/.nvm/nvm.sh\"\nelif [[ -x \"$(command -v brew)\" && -s \"$(brew --prefix nvm)/nvm.sh\" ]]; then\n  . \"$(brew --prefix nvm)/nvm.sh\"\nfi\n \nif [[ \"$(command -v nvm)\" ]]; then\n nvm install 7.10.0\nfi\n \n node ../scripts/download-realm.js ios --sync";
```

It works

## Version of Realm and Tooling

- Realm JS SDK Version: 2.19
- Node or React Native: Node 10.13, ReactNative 0.57.4
- Client OS & Version: MacOS 10.13

**Comment by kneth** [comment] 2018-11-09 09:14
I have only `npm` installed, and I haven't been able to reproduce it yet. I have a little RN app with a 2.19.0 dependency. When I do `npm install && react-native run-ios` I get the following output (together with a lot more):

```
WriteAuxiliaryFile /Users/kneth/tmp/RealmTestApp/ios/build/Build/Intermediates.noindex/RealmJS.build/Debug-iphonesimulator/RealmJS.build/Script-F63FF2C51C12462600B3B8E0.sh (in target: RealmJS)
    cd /Users/kneth/tmp/RealmTestApp/node_modules/realm/src
    write-file /Users/kneth/tmp/RealmTestApp/ios/build/Build/Intermediates.noindex/RealmJS.build/Debug-iphonesimulator/RealmJS.build/Script-F63FF2C51C12462600B3B8E0.sh

PhaseScriptExecution Download\ Core /Users/kneth/tmp/RealmTestApp/ios/build/Build/Intermediates.noindex/RealmJS.build/Debug-iphonesimulator/RealmJS.build/Script-F63FF2C51C12462600B3B8E0.sh (in target: RealmJS)
    cd /Users/kneth/tmp/RealmTestApp/node_modules/realm/src

... a lot of output ...
v7.10.0 is already installed.

Now using node v7.10.0 (npm v4.2.0)

Resolved requirements: { SYNC_SERVER_FOLDER: 'sync',
  SYNC_ARCHIVE: 'realm-sync-cocoa-3.13.1.tar.gz',
  SYNC_ARCHIVE_ROOT: 'core' }

No lockfile found at the target, proceeding.

Download url: https://static.realm.io/downloads/sync/realm-sync-cocoa-3.13.1.tar.gz

Downloading realm-sync-cocoa-3.13.1.tar.gz

Extracting realm-sync-cocoa-3.13.1.tar.gz => /Users/kneth/tmp/RealmTestApp/node_modules/realm/vendor/realm-ios

Success
```

**Comment by radeno** [comment] 2018-11-09 09:17
@kneth Do you use nvm? Because i don't use any `nvm` nor `n`. My node versions are handled with `homebrew`

**Comment by radeno** [comment] 2018-11-09 09:28
There is unminified script:

```shell
if [[ -d "$HOME/.asdf/shims" ]]; then
  export PATH=$HOME/.asdf/shims:$PATH
fi

if [[ -d "$HOME/.n" ]]; then
  export N_PREFIX="$HOME/.n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"
fi

if [[ "$(command -v n)" ]]; then
 n 7.10.0
else
  [ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"

  if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
    . "$HOME/.nvm/nvm.sh"
  elif [[ -x "$(command -v brew)" && -s "$(brew --prefix nvm)/nvm.sh" ]]; then
    . "$(brew --prefix nvm)/nvm.sh"
  fi
 
  if [[ "$(command -v nvm)" ]]; then
    nvm install 7.10.0
  else
    echo "RealmJS requires a node package manager (n or nvm)."
    exit 1
  fi
fi
 
node ../scripts/download-realm.js ios --sync
```

I if understand it right then exit is always execute when `nvm` or `n` is not available

Original unminified:
```shell
if [[ -d "$HOME/.asdf/shims" ]]; then
  export PATH=$HOME/.asdf/shims:$PATH
fi

[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"

if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
  . "$HOME/.nvm/nvm.sh"
elif [[ -x "$(command -v brew)" && -s "$(brew --prefix nvm)/nvm.sh" ]]; then
  . "$(brew --prefix nvm)/nvm.sh"
fi
 
if [[ "$(command -v nvm)" ]]; then
 nvm install 7.10.0
fi
 
 node ../scripts/download-realm.js ios --sync
```

Need to remove information about requirement and exit statement. There are more than two ways how to install node.js.

**Comment by radeno** [comment] 2018-11-09 09:33
Or better way.

Check first if `node` command is available and then check version with `node -v`
After that if any node is not available or version missmatch. Then show error message. Do not force autoinstall.

**Comment by kneth** [comment] 2018-11-09 14:20
@radeno I must have misunderstood you. Yes, I use `nvm`, and so far we have required that you use a node version manager. I can see that we have never actually documented it in `README.md`. 

I will try to get some time next week to create a more robust script for Xcode.

**Comment by shubham1164** [comment] 2018-11-11 19:02
I am also getting the same error. I have created a new project with "react-native init NewRealmProject" and then added realm and "react-native link realm" but it is not working in ios with the same above error. Its working in Android without any hassle

**Comment by shubham1164** [comment] 2018-11-11 19:18
I have created this project today and facing the issue. Just 1 month back, I was using lower version of react/react-native/realm/Xcode and everything was working fine. Please help to resolve it

My latest (created on 11 Nov) project spec versions:
"react": "16.6.0-alpha.8af6728",
"react-native": "0.57.4",
"realm": "^2.19.0",
Xcode: Version 10.1 (10B61)

**Comment by kneth** [comment] 2018-11-12 08:17
@shubham1164 You can replace the line using any editor. The file is `node_modules/realm/src/RealmJS.xcodeproj/project.pbxproj`. Simply replace the line with the line suggested by @radeno.

**Comment by radeno** [comment] 2018-11-12 21:50
@shubham1164 or just rewrite line `863` with `shellScript = "node ../scripts/download-realm.js ios --sync";`

**Comment by aljs** [comment] 2018-11-13 16:10
I can't build Release version because of it. Realm switches nvm to 7.10.0 and react-packager does not support this version:

>  │  You are currently running io.js v7.10.0.                                  │ 
>  │                                                                            │ 
>  │  React Native runs on Node 8.3 or newer. There are several ways to         │ 
>  │  upgrade Node.js depending on your preference.                             │

**Comment by kneth** [comment] 2018-11-13 16:13
@aljs Thanks for reporting. I'll take time tomorrow to fix it.

**Comment by donghungx** [comment] 2018-11-14 05:45
Thanks radeno  for the fix, I got built on iOS working now, but this should not be an error :(

**Comment by kneth** [comment] 2018-11-14 10:46
@aljs @donghungx @shubham1164 @radeno I have opened a PR to support "naked" node installation and `n` and `nvm`. Please take a look at #2109.

**Comment by ramki1979** [comment] 2018-11-15 10:31
@aljs 
I am facing the same issue on Bitrise CI with node 8.12.0

**Comment by radeno** [comment] 2018-11-26 09:46
@kneth any progress of this? I know it is paused due test issues https://github.com/realm/realm-js/pull/2109 . Quick hot fix should be removing `exit` statement. It will work like before merging commit but still support of `n`

**Comment by kneth** [comment] 2018-11-26 12:31
@radeno I hope to return to it this week 🤞

**Comment by ozburo** [comment] 2018-12-09 21:15
Doesn't anyone check these PR's before they're merged? Seriously this is not cool.

To quote the original PR's commit message "Currently Realm expects to use nvm. However, n is a valid alternative. This change adds support for users using the n version manager."

That's cute but it _breaks_ the original use of nvm which I (and many others obviously) have been using till now.

So to clarify -- you now can't even build Realm from a clean initialized project -- do i need to list steps to reproduce, lol?

**Comment by radeno** [comment] 2018-12-11 16:18
@kneth until PR https://github.com/realm/realm-js/pull/2109 will be shipped, could you revert problematic commit?
I think there are lot of developers which use "naked" node so modify same file after every node_modules update is really annoying.

**Closed** 2018-12-13 14:15 UTC
Labels: O:User, T:Bug

**Comment by alihbk** [comment] 2019-01-12 11:18
i have this error
realmjs requires a node package manager (n or nvm).

**Comment by joshuapinter** [comment] 2019-04-08 01:02
I personally prefer [`nodenv`](https://github.com/nodenv/nodenv). It works the exact same way as [`rbenv`](https://github.com/rbenv/rbenv), if you're familiar with that. _But_, `realm` wants either `n` or `nvm`, which I think isn't fair. It should just want and expect _a_ version of `node`. Not any, or worse a specific, node package manager.

**Comment by kneth** [comment] 2019-04-08 08:12
@joshuapinter #2307 is an attempt to do what you ask for.
