### ISSUE TITLE
Error when App try to get realm objects : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by BravenxX** [realm/realm-js#3167] opened 2020-08-27 15:30 UTC
This errors just happens (by now) on physical device and just sometimes, on android emulator does not happen.

I have this function to get objects lists from Realm.

```
import R from 'ramda';

const fn = async ({ Realm, DatabaseOptions }, schema, filter) => {
  console.log('localStorage/fwGet');
  console.log({ schema, filter });

  const realm = await Realm.open(DatabaseOptions);

  let users = realm.objects(schema);

  if (filter) {
    users = users.filtered(...filter).snapshot();
  }

  console.log('Terminando get');

  const x = [];
  for (const i in users) {
    x.push(users[i]);
  }

  console.log('values devueltos: ');

  return x;
};

const fwGet = R.curry(fn);

export { fwGet };
```

Sometimes, just SOMETIMES, it gets me this error (via android studio logcat) and the app just closes without visual error.

![image](https://user-images.githubusercontent.com/43297929/91460297-a8cb9580-e855-11ea-88e7-f27ae1dc3c61.png)

Another

![image](https://user-images.githubusercontent.com/43297929/91466586-5a21f980-e85d-11ea-9cdf-5028159fd51b.png)

This error is throw in almost all latest Realm version. those aboves error were threw using Realm@6.1.0, though the same happens with realm 6.0.5, 6.0.3, 10.0.0-beta.10, 10.0.0-beta.7. At least those are the ones that I used to check if the error was in a particular realm version.

## Version of Realm and Tooling

- Realm: 6.1.0
- React Native: 0.62.2
- Device: Motorola g(6) plust - Android 9

**Comment by kneth** [comment] 2020-08-27 16:20
The two logs  indicate that the error is happening in

```
const x = [];
for (const i in users) {
    x.push(users[i]);
}
```
(I see `Terminando get` but not `values devueltos:`)

Is it possible to write to the log in the loop (both `i` and `users[i]`) to understand what value is causing the error? Moreover, can you provide a full stack trace from the `SIGSEGV` error?

**Comment by BravenxX** [comment] 2020-08-27 16:56
@kneth I changed it, now: 

```
import R from 'ramda';

const fn = async ({ Realm, DatabaseOptions }, schema, filter) => {
  console.log('localStorage/fwGet');
  console.log({ schema, filter });

  const realm = await Realm.open(DatabaseOptions);

  let users = realm.objects(schema);

  if (filter) {
    users = users.filtered(...filter).snapshot();
  }

  console.log('Terminand get');

  const x = [];
  for (const i in users) {
    console.log('i', i);
    console.log('users[i]', users[i]);
    x.push(users[i]);
  }

  console.log('values devueltos: ');

  return x;
};

const fwGet = R.curry(fn);

export { fwGet };
```

But anyway, even if that lines within the for are not processed (because there's no object in users (empty)) it throws me this type of error

![image](https://user-images.githubusercontent.com/43297929/91471132-a2dcb100-e863-11ea-8696-e42ce03a0bfe.png)

And when it has to pass for the for stops before the console logs (just sometimes).

![image](https://user-images.githubusercontent.com/43297929/91471778-84c38080-e864-11ea-9617-bc4c21863aa9.png)

What do you mean with the full stack trace, how can I get it?

**Comment by BravenxX** [comment] 2020-08-27 17:18
Also, in fwUpdate happens the same (SOMETIMES, even when I want to update the same obj with the same value):

![image](https://user-images.githubusercontent.com/43297929/91473953-9bb7a200-e867-11ea-95e0-e2286c1ffd5b.png)

fwUpdate.js:
 
```
import R from 'ramda';

const fn = async ({ Realm, DatabaseOptions }, schema, filter, newValues) => {
  console.log('update fw', schema, 'filter', filter, 'newValues', newValues);
  const realm = await Realm.open(DatabaseOptions);

  let data = realm.objects(schema);

  if (filter) {
    data = data.filtered(...filter).snapshot();
  }

  realm.write(() => {
    for (const i in data) {
      const item = data[i];
      for (const key in newValues) {
        item[key] = newValues[key];
      }
    }
  });
};

const fwUpdate = R.curry(fn);

export { fwUpdate };
```

**Comment by BravenxX** [comment] 2020-08-28 18:40
solved downgrading to realm@3.6.5. See [#3177](https://github.com/realm/realm-js/issues/3177#issue-688282331)

**Comment by kraenhansen** [comment] 2020-09-03 10:12
@BravenxX would it be possible for you to share the value of `DatabaseOptions` in your examples above? In particular, I'm interested in knowing if you're opening a synchronized Realm or not.

**Comment by BravenxX** [comment] 2020-09-11 16:25
@kneth  I can't repreduce the error because I already downgrade the Realm Version. 

@kraenhansen this is my DatabaseOptions: 

```
const DatabaseOptions = {
  schema: [
    ActProgSchema,
    ActRealSchema,
    ObsTecnSchema,
    UsuarioActivoSchema,
    UsuariosSchema,
    FormularioSchema,
    InstanciaComplementoSchema,
    FaenaSchema,
    UnidadSchema,
    FeriadosSchema,
    NfcChipsSchema,
    RegisterListSchema,
  ],
};

export default DatabaseOptions;
```

I'm not working with syncing. As you see it is a very simple DB.

**Comment by kneth** [comment] 2020-09-14 08:18
@BravenxX We haven't been able to reproduce the crash locally.

With JS v6.1.1 we released some important bug fixes, and we suggest that you upgrade to that version.

**Comment by kneth** [comment] 2020-10-07 13:11
We have release v6.1.3 and we suggest that you upgrade. I close the issue, and if the issue is observed again, please create a new issue.

**Closed** 2020-10-07 13:12 UTC
Labels: O-Community
