### ISSUE TITLE
property of type date does not except js Date

### ISSUE THREAD

**Issue by thomasarogers** [realm/realm-js#2832] opened 2020-04-21 18:14 UTC
## Goals

Trying to create object in realm and assign date to a property of type date

## Expected Results

Object is created in realm

## Actual Results

Causes error from realm, saying that value is of type object not date

![image](https://user-images.githubusercontent.com/42372294/79898875-de71f500-8403-11ea-825e-bba4afee2ff3.png)

## Steps to Reproduce

Create realm with an object with property of type date, assign a new moment.toDate() or new Date() to this property in a write block

## Code Sample
![image](https://user-images.githubusercontent.com/42372294/79899111-3c064180-8404-11ea-9be3-ba173a2f2417.png)
![image](https://user-images.githubusercontent.com/42372294/79899152-4fb1a800-8404-11ea-9d5b-ab73b56eafcb.png)

## Version of Realm and Tooling

- Realm JS SDK Version: 5.0.3
- Node or React Native: React Native 61.4
- Client OS & Version: macOS Catalina
- Which debugger for React Native: Console

**Comment by thomasarogers** [comment] 2020-04-22 08:45
Looks like a duplicate of#2755 apologies

**Comment by kneth** [comment] 2020-06-25 12:27
Yes, I close it as a duplicate of #2755

**Closed** 2020-06-25 12:29 UTC
Labels: O-Community
