### ISSUE TITLE
Realm flooding react native debugger

### ISSUE THREAD

**Issue by mattfysh** [realm/realm-js#3012] opened 2020-06-30 02:20 UTC
https://github.com/realm/realm-js/blob/0a305a1c994fb2f247bb600df1d408f183804cb9/lib/browser/rpc.js#L33-L43

It looks as though Realm always grabs the version of XMLHttpRequest that will appear in React Native's network debugger. This is causing a flood of requests to show up, making it difficult to debug other application-level http requests.

Do you know if there is a way for me to filter out the Realm requests in the Network tab?

![image](https://user-images.githubusercontent.com/470258/86075741-0b114f80-bacc-11ea-8e8d-d59b6799580d.png)

**Comment by kneth** [comment] 2020-06-30 10:12
Unfortunately we haven't found a good solution yet. It is related to #505 and in particular #1538. We know that some users are using Safari and its dev tools to debug RN apps.

I close the issue as a duplicate of #1538.

**Closed** 2020-06-30 10:17 UTC
Labels: O-Community
