### ISSUE TITLE
Not install previous version of realm

### ISSUE THREAD

**Issue by yasinugrl** [realm/realm-js#5892] opened 2023-06-15 16:22 UTC
### How frequently does the bug occur?

Always

### Description

My React Native version is 0.67 and I wanto install your 11.0.0-rc.0 version of package but not install this versiyon by using yarn add realm@11.0.0-rc.0. İnstalling stuck not progressing

Also try with npm and same issue

npm install realm@11.0.0-rc.1                     
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
(##################) ⠼ reify:realm: http fetch GET 200 https://registry.npmjs.org/realm/-/realm-11.0.0-rc.1.tgz 13530ms (cache miss)

stuck here cache miss.

Do you have any solition for that.

### Can you reproduce the bug?

Always

### Version

11.0.0-rc.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Mac

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment] 2023-06-16 12:47
I am not able to reproduce it. Could you run `yarn --verbose add realm@11.0.0-rc.0` to see where it is stuck?

Furthermore, we did have an issue with node 19 at some point (see https://jira.mongodb.org/browse/RJS-2306). It was fixed in v11.5.2. You could try to change node version.

**Comment by takameyer** [comment] 2023-06-30 07:55
Closing due to inactivity.  Please feel free to open if you have any more information for us.

**Closed by takameyer** 2023-06-30 07:55 UTC
Labels: T-Bug, O-Community, Waiting-For-Reporter, SDK-Use:Local, Encryption:Off, Frequency:Always, Repro:Always
