### ISSUE TITLE
Unexpected crash and required migration

### ISSUE THREAD

**Issue by AlexeyPanchenko** [realm/realm-js#1472] opened 2017-11-07 00:37 UTC
## Description

I added realm in my half Native Android - half React Native application. It works cool, but if I got a crash in Native Android part of app, then my React part of app don`t work (it crash immediately, it writes: "Migration is required due to the following errors:"). If i clear storage of app it cool again.

## Stacktrace Error

![image](https://user-images.githubusercontent.com/22294817/32471081-3ec16302-c3a7-11e7-9b0e-cf9a514d736d.png)

![image](https://user-images.githubusercontent.com/22294817/32471122-6ebff56e-c3a7-11e7-9b1b-a555072d3a33.png)

## Version of Realm and Tooling

- Realm JS SDK Version: 2.0.0
- Node or React Native: React Native
- Client OS & Version: Android 6.0.1
- Which debugger for React Native: Chrome

**Comment by kneth** [comment] 2017-11-07 08:41
To me, it looks like you are opening the Realm file with two different schemas. Do you use Realm Java in the native Android part?

**Comment by AlexeyPanchenko** [comment] 2017-11-07 08:48
No, I don`t use Realm in the native Android part.
Yes, I opening the Realm whis two different shemas: 
![Uploading image.png…]()
Because my ProductLine is a part of Document schema

**Comment by AlexeyPanchenko** [comment] 2017-11-07 08:50
No, I don`t use Realm in the native Android part.
Yes, I opening the Realm with two different shemas:

export const realm = new Realm({schema: [ProductLine.schema, Document.schema]});

Because my ProductLine is a part of Document schema

**Comment by kneth** [comment] 2017-11-07 09:30
But you open the Realm with those two always, right?

**Comment by AlexeyPanchenko** [comment] 2017-11-07 23:15
Yes. I open Ream instance once and use it with Dependency Injection (Inversify)

**Comment by kneth** [comment] 2017-11-08 09:40
I am not familiar with Inversify. Can you provide a short example which reproduces the issue?

**Comment by kneth** [comment] 2017-11-17 14:11
I close the issue for now.

@AlexeyPanchenko If you can write a small sample app to demonstrate the issue, please reopen it so we can investigate it a bit.

**Closed by kneth** 2017-11-17 14:11 UTC
Labels: O:User, Reproduction Required, T:Help
