### ISSUE TITLE
Jest: Maximum call stack size exceeded when filtering objects with inverse relationship in React Native Jest-testing( Realm 10.1.1 )

### ISSUE THREAD

**Issue by Fabio-GC** [realm/realm-js#3488] opened 2020-12-31 11:21 UTC
## Goals
Giving the following schema:

```
const Person = {
  name: "Person",
  primaryKey: "_id",
  properties: {
    _id: "objectId",
    name: "string",
    age: "int",
    company: "Company[]"
  }
};

const Company = {
  name: "Company",
  primaryKey: "_id",
  properties: {
    _id: "objectId",
    name: "string",
    boss: {
      type: 'linkingObjects',
      objectType: 'Person',
      property: 'company'
    }
  }
};
```

After adding some persons and several of them with a company, I try to filter by age and get the ones that are over 30 years with the code `realm.objects("Person").filtered("age > 30");`

## Expected Results
I expect to have a list of Persons which meets the requirement 

## Actual Results
The result of this query is the following error:

**Maximum call stack size exceeded.**

I have seen that in the release 10.0.0 this error is suppose to be fix for toJSON() function. If I try to filter the object by its id everything works fine, but once I try to get a list of some objects I get this error.

## Steps to Reproduce
Generate the schema with realm and create a test with Jest which reproduce the code to execute.

## Version of Realm and Tooling
* Realm JS SDK Version: 10.1.1 ( realm react native )
* Node or React Native: node:10.22.1 ; React-native: 0.62.2
* Jest version: 26.6.3

**Comment by kneth** [comment] 2021-01-04 11:50
I think your schema is incorrect, and it should be:

```
const Person = {
  name: "Person", // was "User"
  primaryKey: "_id",
  properties: {
    _id: "objectId",
    name: "string",
    age: "int",  // was "number"
    company: "Company[]"
  }
};

const Company = {
  name: "Company",
  primaryKey: "_id",
  properties: {
    _id: "objectId",
    name: "string",
    boss: {
      type: 'linkingObjects',
      objectType: 'Person',
      property: 'company'
    }
  }
};
```

But it doesn't explain the error message as `realm.objects("Person").filtered("age > 30")` should fail with `"Person"` being unknown.

**Comment by steffenagger** [comment] 2021-01-05 09:10
Hey @Fabio-GC, you mention Jest. Is this an issue only in the context of Jest, or also at app runtime?

**Comment by Fabio-GC** [comment] 2021-01-07 09:01
Hello @steffenagger 

It seems that the issue is only related with Jest, when running the app everything works fine.

@kneth Yes, you are right. But as you mentioned if this was related with the issue the error would be different. I´ll change it anyway :)

**Comment by steffenagger** [comment] 2021-01-22 11:23
@Fabio-GC We'll need to investigate Jest issues in general. I don't have an estimate on when this will be fixed, but a potential workaround can be found here: https://github.com/realm/realm-js/issues/2490

**Comment by takameyer** [comment] 2021-03-10 10:05
@Fabio-GC We took some time to try and reproduce this issue and failed to reproduce it.  Can you try updating Jest and Realm, to see if the issue is resolved?

**Comment by Fabio-GC** [comment] 2021-03-15 16:10
Hello @takameyer. 
Thank you for taking the time to reproduce this error. I'm still trying to get this solve without any luck. I think I can provide you a more specific test so you can try this out. 
I'v decided to slightly change the schema so is even easier to reproduce, so giving the following schema:
`const Person = {
  name: "Person",
  primaryKey: "_id",
  properties: {
    _id: "objectId",
    name: "string",
    bestFriend: Person,
    bestFriendOf: {
      type: 'linkingObjects',
      objectType: 'Person',
      property: 'bestFriend'
    }
  }
};` 

If I tried to run the following test it will give "RangeError: Maximum call stack size exceeded" : 
```
const person1 = new Person();
        person1.id = '1';
        person1.firstName = 'Jhon';
       

        const person2 = new Person();
        person2.id = '2';
        person2.firstName = 'Peter';
   

        const person3 = new Person();
        person3.id = '3';
        person3.firstName = 'Andrew';
   

          it('should filter nested objects', async () => {
            person1.bestFriend = person2;
            const personRepo = new PersonObjectRepo();
            await personRepo.saveObjects([person1, person2, person3]);
            const persistedPerson1 = await personRepo.getObjectById('1');
            expect(persistedPerson1).toEqual(person1);
        })
```

But if I run the same test but for person with id 3, which doesn't have any reverse relation applied I don't have the error. 

` it('should filter nested objects', async () => {
            person1.bestFriend = person2;
            const personRepo = new PersonObjectRepo();
            await personRepo.saveObjects([person1, person2, person3]);
            const persistedPerson3 = await personRepo.getObjectById('3');
            expect(persistedPerson3).toEqual(person3);
        })`

I guess the error is related on how jest compare equality in its test. Do you think is there any way of solving this? 
Thank you in advance.

**Comment by takameyer** [comment] 2021-03-16 09:07
@Fabio-GC I have attempted to reproduce a test that describes your issue:
```javascript
  it('can handle linkingObject circular references', async () => {
    const Person = {
      name: "Person",
      primaryKey: "_id",
      properties: {
        _id: "objectId",
        name: "string",
        bestFriend: "Person",
        bestFriendOf: {
          type: 'linkingObjects',
          objectType: 'Person',
          property: 'bestFriend'
        }
      }
    };

    const realm = await Realm.open({schema:[Person], inMemory:true})

    realm.write(() => {
      const person1 = realm.create("Person", {_id: new ObjectId(), name: "Jon"})
      const person2 = realm.create("Person", {_id: new ObjectId(), name: "Andrew"})
      const person3 = realm.create("Person", {_id: new ObjectId(), name: "Peter"})
      person1.bestFriend = person2;
      const persistedPerson1 = realm.objectForPrimaryKey("Person", person1._id);
      expect(persistedPerson1.bestFriend.name).toEqual("Andrew");
      expect(persistedPerson1.bestFriend.bestFriendOf[0].name).toEqual("Jon");
    })
    realm.close()
  })
```
This test is successful.  I believe this is not an issue with Jest, but with the internals of `personRepo`, which is unknown to me.  Can you provide an example of this crash in clear code?

**Comment by bmunkholm** [comment] 2021-11-09 12:34
@Fabio-GC Closing this as we can't get further without more information.

**Closed by bmunkholm** 2021-11-09 12:34 UTC
Labels: O-Community
