### ISSUE TITLE
Can't import realm on win32 platform

### ISSUE THREAD

**Issue by kpostekk** [realm/realm-js#4951] opened 2022-09-26 14:12 UTC
### How frequently does the bug occur?

All the time

### Description

App can't start, because loading realm throws an error.

I know for sure it's not an Electron nor Vite issue, because it works just fine on macOS.
The last working version is v10.20.0.

I think it might be related to this issue: 
https://github.com/realm/realm-js/issues/4937
and this post on mongodb forum:
[realm node is no a avalid win32 application during integration testing](https://www.mongodb.com/community/forums/t/realm-node-is-not-a-valid-win32-application-during-integration-testing/189174)

I have tested versions between `10.20.0` and `11.0.0-rc.2` and only these had that bug:
 - `10.21.0`
 - `10.21.1`
 - `11.0.0-rc.2`

### Stacktrace & log output

```shell
App threw an error during load
Error: \\?\C:\Users\kpostek\Documents\Develop\travel\player-electron\node_modules\realm\build\Release\realm.node is not a valid Win32 application.
\\?\C:\Users\kpostek\Documents\Develop\travel\player-electron\node_modules\realm\build\Release\realm.node
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1205:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1812)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (C:\Users\kpostek\Documents\Develop\travel\player-electron\node_modules\bindings\bindings.js:112:48)
    at getRealmConstructor (C:\Users\kpostek\Documents\Develop\travel\player-electron\node_modules\realm\lib\index.js:28:37)
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. Create basic electron app
2. Install electron and realm
3. Try importing realm

### Version

10.21.0, 11.0.0-rc.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Windows 11 21H2 22000.978

### Build environment

- NodeJS: 16.17.0
- Visual Studio Build Tools 2022: 17.3.4
- Electron: 20.1.4
- Vite: 3.1.3
    - `vite-plugin-electron`: 0.9.3

**Comment by kpostekk** [comment] 2022-09-26 14:24
I'm not an expert, but after checking diff between 10.20 and 10.21 I guess, there might be a bug in CMake

Diff: https://github.com/realm/realm-js/compare/v10.20.0...v10.21.0
CMake changes:
![image](https://user-images.githubusercontent.com/30326322/192301510-ff9c8976-9fa1-42dd-9230-7f7a09e27783.png)

**Comment by kneth** [comment] 2022-09-26 15:09
@kpostekk Thank you for reporting. I believe it is a duplicate of https://github.com/realm/realm-js/issues/4937. We are currently investigating what is the root cause of why we are getting non-working binaries.

If possible you can use v10.20.0.

**Closed** 2022-09-28 06:42 UTC
Labels: T-Bug, O-Community, Waiting-For-Reporter

**Comment by rossicler-hostalky** [comment] 2023-04-03 22:33
I'm using v11.7.0 and getting the same errors. For reference, it's an electron app production build. The error I'm getting is the following:
```
Uncaught Exception:
Error:
\\?\C:\Users\MyUser\AppData\Local\Programs\electron-react-boilerplace\res...\realm.node is not a valid Win32 application.
\\?\C:\Users\MyUser\AppData\Local\Programs\electron-react-boilerplace\res...\realm.node
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at c._load (node:electron/js2c/asar_bundle:5:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
   ...
```
