### ISSUE TITLE
Infinite loop of "callbacks_poll"

### ISSUE THREAD

**Issue by mschipperheyn** [realm/realm-js#1538] opened 2017-11-28 14:25 UTC
So, it's YOU! :-)

I've been seeing this endless loop of "callbacks_poll" that is killing my debugging performance and pleasure. 

<img width="1097" alt="screen shot 2017-11-24 at 17 11 55" src="https://user-images.githubusercontent.com/384959/33324241-2fbadf06-d436-11e7-844a-47abc159f8a9.png">

## Goals

Get rid of the endless loop of callbacks_poll in my networking request pane and the associated memory leak

## Expected Results

No callbacks_poll visible and no memory leak

## Actual Results

See image. Endless loop. Makes it hard to identify individual network requests and there seems to be an associated memory leak, although I can't guarantee that it is related.

## Steps to Reproduce

Not sure. This happened after I upgraded Realm but I didn't realize it at the time. Here's my Realm setup

## Code Sample
```
class User {}
User.schema = {
	name: 'User',
	primaryKey: 'id',
	properties: {
		id: { type: 'int' },
		nickName: { type: 'string' },
		displayName: { type: 'string' },
		title: { type: 'string', optional: true },
		email: { type: 'string' },
		photo: { type: 'string', optional: true },
		photoDir: { type: 'string' },
		gender: { type: 'string' },
		refId: { type: 'string', optional: true },
		sessionToken: { type: 'string', optional: true }
	}
};

export default User;

```
```
import Realm from 'realm';
import { logoutUser } from 'modules/login/actions/loginActions';
import { delToken, clearTokens } from 'modules/login/actions/oauthActions';
import * as config from 'config';
import { dbg } from 'utils';
import UserRecord from 'data/records/userRecord';
import {
	EMIT_USER,
	GET_USER,
	STORE_USER,
	DEL_USER,
	CLEAR_ALL
} from '../userActionTypes';
import User from '../schemas/userDbSchema';

const realmSettings = {
	schema: [User],
	schemaVersion: 1,
	migration: (oldRealm, newRealm) => {
		// only apply this change if upgrading to schemaVersion 1
		/* if (oldRealm.schemaVersion < 1) {
          const oldObjects = oldRealm.objects('User');
          const newObjects = newRealm.objects('User');
    
          // loop through all objects and set the name property in the new schema
          for (let i = 0; i < oldObjects.length; i++) {
            newObjects[i].sessionToken = undefined;
          }
        } */
	}
};

const realm = new Realm(realmSettings);

export function getUser() {
	return {
		type: GET_USER
	};
}

export function emitUser(user) {
	return {
		type: EMIT_USER,
		user
	};
}

export function loadUser(userId) {
	return async (dispatch, getState) => {
		dispatch(getUser());

		const sessionUser = getState().users.sessionUser;

		if (sessionUser && sessionUser.id === userId) return sessionUser;

		let user = null;

		if (userId) user = realm.objectForPrimaryKey('User', userId);
		else {
			const users = realm.objects('User');

			if (users.length > 0) user = users.values().next().value;
		}

		dbg(user ? `User ${user.id} loaded` : 'No user loaded');

		if (user) {
			dispatch(emitUser(new UserRecord(user)));

			return user;
		}

		return null;
	};
}
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.0.11
- Node or React Native: React Native 0.49.5
- Client OS & Version: Mac Os
- Which debugger for React Native: React-Native-Debugger or Chrome

**Comment by kneth** [comment] 2017-11-29 10:15
Thanks for reporting. In version 2.0.7 we fixed a bug in `Realm.open` (hanging in RN debugging). In order to see if that fix had anything to do with it, can I ask you to try with 2.0.6?

**Comment by mschipperheyn** [comment] 2017-11-29 18:30
So, the infinite loop network log doesn't occur on 2.0.6. 
I also had a go at 2.0.7, and that's where it starts occurring.

**Comment by blagoev** [comment] 2017-11-29 19:00
@mschipperheyn @kneth the callbacks_poll method reinvoke is intentional. This is used only in debugging to be able to support handling arbitrary callbacks called from the device side. This method is called only if there are no invocations of any method/get property etc for specified small amount of time from the application. 
Our current implementation is using http requests to communicate with the debugger backend, so constant pulling is needed when arbitrary callbacks need to be invoked.

We can improve this in the future by using websockets, but it's not a high priority right now. We have other issues with performance we are working on to fix (like #491)

cheers

**Comment by pkunetspy** [comment] 2017-11-30 01:56
@blagoev I think it's a high priority issue because the chrome debugger turn very slow and we almost cannot do any thing. Thanks.

**Comment by mschipperheyn** [comment] 2017-11-30 11:27
@blagoev network debugging is a nightmare with this constant polling, not the mention the network logging of the polling itself growths infinitely as well and eventually crashes the debugger or brings the computer to a halt. This can be filtered out by using a regex in the logging, but this has to be done every time you restart the debugger which is a poor experience.

Perhaps this "specified small" amount of time can be made configurable, so that we can just set it to a much larger value and take any associated consequences for granted?

**Comment by icfr** [comment] 2017-12-08 19:10
i changed this in 'lib/browser/rcp.js' at line 292 (v2.0.12)

`pollTimeoutId = setTimeout(() => sendRequest('callbacks_poll'), 60000);`

@blagoev what is arbitrary callback and when it is needed ?

**Comment by blagoev** [comment] 2017-12-12 13:28
Guys by arbitrary callback I mean callbacks that can be fired at any point of time. For example one such callback are the callbacks for change notifications. The debugger works by piggy backing on normal debugger commands but if there are no invocations from the client side the debugger invokes this poll request, so callbacks are not left pending. This poll callback should happen only when there are no method invocations/property getters/setters etc to the debugger backend. 
Now If we make the debugger use websockets then this constant polling will go away and you will not see it anymore. It's priority is measured against many other important fixes we need to go through hence we decided to split the issues when we fixed the support for arbitrary callbacks. 

If you are experiencing slow debugger there is bigger problem with it we outlined here #491

**Comment by mschipperheyn** [comment] 2017-12-12 18:15
@blagoev Yeah, websockets would seem to be the way to go. For me, staying on 2.0.6 is an acceptable workaround for now. Thanks for being open about this.

**Comment by fealebenpae** [comment] 2017-12-12 21:52
@blagoev could we perhaps create a module for ReactNative's CxxBridge and use the React Native bridge to post callbacks to the debugger because it already sets up a websocket?

**Comment by blagoev** [comment] 2017-12-13 10:12
@fealebenpae Yes we could do that. it's a matter of priorities to spend the some time on it.

**Comment by mutale** [comment] 2018-02-23 08:52
Hi, any news on that? I'm currently using 2.2.12 and these callbacks_poll requests flooding my network requests.

Thanks

**Comment by Uysim** [comment] 2018-03-20 07:30
+1

**Comment by comann** [comment] 2018-04-03 19:02
+1

**Comment by AlexisLeon** [comment] 2018-04-10 03:38
+1

**Comment by sohobloo** [comment] 2018-04-14 07:32
+1

**Comment by sbayd** [comment] 2018-04-16 11:16
+1

**Comment by iremercan** [comment] 2018-04-16 11:17
+1

**Comment by yiky84119** [comment] 2018-04-18 09:37
+1, any news on that? i find it when i use redux-saga

**Comment by mdgrech** [comment] 2018-04-25 18:03
Please fix.

**Comment by AlexisLeon** [comment] 2018-04-25 20:12
@alazier @appden

**Comment by kneth** [comment] 2018-04-26 06:31
Unfortunately we have had other priorities lately. I'll take it up with the rest of the team as a more general prioritization of debugging experience.

**Comment by guatedude2** [comment] 2018-06-02 22:34
This is what the logs come out as:
```
Connection[4]: Will emit a ping in 0 milliseconds
Connection[3]: Received: PONG(timestamp=775651006)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651007, rtt=2)
Connection[3]: Sending: PING(timestamp=775651007, rtt=1)
Connection[3]: Received: PONG(timestamp=775651007)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651008, rtt=1)
Connection[4]: Received: PONG(timestamp=775651007)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651009, rtt=2)
Connection[4]: Received: PONG(timestamp=775651009)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651010, rtt=1)
Connection[3]: Received: PONG(timestamp=775651008)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651010, rtt=2)
Connection[3]: Received: PONG(timestamp=775651010)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[4]: Received: PONG(timestamp=775651010)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651011, rtt=1)
Connection[4]: Sending: PING(timestamp=775651011, rtt=1)
Connection[4]: Received: PONG(timestamp=775651011)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651013, rtt=1)
Connection[3]: Received: PONG(timestamp=775651011)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651013, rtt=2)
Connection[3]: Received: PONG(timestamp=775651013)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651014, rtt=1)
Connection[4]: Received: PONG(timestamp=775651013)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651014, rtt=1)
Connection[3]: Received: PONG(timestamp=775651014)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651015, rtt=1)
Connection[4]: Received: PONG(timestamp=775651014)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651016, rtt=1)
Connection[3]: Received: PONG(timestamp=775651015)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651016, rtt=1)
Connection[4]: Received: PONG(timestamp=775651016)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651017, rtt=1)
Connection[3]: Received: PONG(timestamp=775651016)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651018, rtt=2)
Connection[4]: Received: PONG(timestamp=775651017)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651018, rtt=1)
Connection[3]: Received: PONG(timestamp=775651018)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[4]: Received: PONG(timestamp=775651018)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651019, rtt=1)
Connection[4]: Sending: PING(timestamp=775651020, rtt=1)
Connection[4]: Received: PONG(timestamp=775651020)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651021, rtt=0)
Connection[3]: Received: PONG(timestamp=775651019)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651021, rtt=2)
Connection[4]: Received: PONG(timestamp=775651021)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651022, rtt=1)
Connection[3]: Received: PONG(timestamp=775651021)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651022, rtt=1)
Connection[4]: Received: PONG(timestamp=775651022)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651024, rtt=1)
Connection[3]: Received: PONG(timestamp=775651022)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651024, rtt=2)
Connection[4]: Received: PONG(timestamp=775651024)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651025, rtt=1)
Connection[3]: Received: PONG(timestamp=775651024)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651026, rtt=2)
Connection[4]: Received: PONG(timestamp=775651025)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651027, rtt=2)
Connection[3]: Received: PONG(timestamp=775651026)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651027, rtt=1)
Connection[4]: Received: PONG(timestamp=775651027)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651028, rtt=1)
Connection[3]: Received: PONG(timestamp=775651027)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651029, rtt=2)
Connection[4]: Received: PONG(timestamp=775651028)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651030, rtt=2)
Connection[3]: Received: PONG(timestamp=775651029)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651031, rtt=2)
Connection[4]: Received: PONG(timestamp=775651030)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651033, rtt=3)
Connection[3]: Received: PONG(timestamp=775651031)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651033, rtt=2)
Connection[4]: Received: PONG(timestamp=775651033)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651035, rtt=2)
Connection[3]: Received: PONG(timestamp=775651033)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651036, rtt=3)
Connection[4]: Received: PONG(timestamp=775651035)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651036, rtt=1)
Connection[3]: Received: PONG(timestamp=775651036)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651037, rtt=1)
Connection[4]: Received: PONG(timestamp=775651036)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651037, rtt=1)
Connection[3]: Received: PONG(timestamp=775651037)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651038, rtt=1)
Connection[4]: Received: PONG(timestamp=775651037)
Connection[4]: Will emit a ping in 0 milliseconds
Connection[4]: Sending: PING(timestamp=775651039, rtt=2)
Connection[3]: Received: PONG(timestamp=775651038)
Connection[3]: Will emit a ping in 0 milliseconds
Connection[3]: Sending: PING(timestamp=775651040, rtt=1)
```

**Comment by hannigand** [comment] 2018-07-06 09:06
Is there a resolution for this?

I am using Realm version 2.12.0 which is continuously making a request to `http://localhost:8083/callbacks_poll`. After 1313 requests, my application crashes.

**Comment by kneth** [comment] 2018-07-06 14:52
@hannigand Unfortunately I have no updates to share.

**Comment by agsole-asapp** [comment] 2018-07-06 14:54
something tells me this is related to ROS not Realm Client. I tested with an older version of ROS and it seems fine.

**Comment by kneth** [comment] 2018-07-09 08:18
@agsole-asapp Thanks for the feedback. The PING/PONG is done to check if network or ROS is alive but it can be that it has a bad effect on the debugger.

**Comment by hannigand** [comment] 2018-07-27 10:36
@kneth - Is there a need for PING/PONG if Realm database is the only product being used? I'm not using ROS so I am just wondering what the point of having the checks are if I am only communicating with the on-device database.

**Comment by kneth** [comment] 2018-08-06 13:04
@hannigand There should be no PING/PONG if you don't have a sync configuration (since there is no server to send them to). But there seems to be an issue with the device/debugger communication which is what the issue originally was about.

**Comment by pedrosimao** [comment] 2018-08-22 15:27
@kneth I am using RealmJS v.2.14.2 on RN, just for internal DB / Persistence (no sync server) and I still have this issue on my debugger. Is that normal? Are you still working on a solution? The production build of the app will not have such weird behavior?

**Comment by pedrosimao** [comment] 2018-08-23 08:42
Ok, thanks a lot!

**Comment by pedrosimao** [comment] 2018-08-24 19:29
@kneth I have just done a build/archived to test the app in production, and actually, I could not get the database working in production mode. Actually, even when I have the app open via the Metro Bundler (on the iOs simulator) but without the "Debug JS Remotely" option, the app seems not able to modify the database. It does create db files, but afterward, it does not seem able to modify the database and ad new entries like it did when I had it running with the Debugger. It's quite odd.

**Comment by pedrosimao** [comment] 2018-08-24 20:16
That's the error I am getting: 
TypeError: Network request failed]
     line: 27971,
     column: 31,
     sourceURL: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false' }

**Comment by pedrosimao** [comment] 2018-08-24 21:41
When I build for production I still get an error at the same part of the app. this time it points to mainjs.bundle

**Comment by pedrosimao** [comment] 2018-08-25 12:08
I just deleted my comments as I found out my problem was not related to Real.
Concerning callback_poll I have decided to go with realm v2.0.6 and the messages go away.
Do you have any major concern about using this version?

**Comment by mrigo** [comment] 2018-08-27 15:18
Hi! I've the same issue!
There's no other way for now than to downgrade to v2.0.6?
The app crashes very often and after only few minutes!

Thanks!

**Comment by pedrosimao** [comment] 2018-08-27 17:53
Not that I know.
I am using v2.0.6 without any problem.
I think the problem is that Realm implements a sync feature and for that to work on debugger they check some API constantly.
They would do better using websocket, but I don't know if it is feasible on their side.
I think if you don't use functions that sync with a realm server you will be good with a lower version.

**Comment by mrigo** [comment] 2018-08-28 10:53
Thanks @pedrosimao ,
I've downgraded realm to 2.0.6 but I'm continuing to have the same problem, also with cache cleaning and a fresh npm installation of modules...

**Comment by pedrosimao** [comment] 2018-08-28 10:57
@mrigo pretty strange. The messages disappeared to me when I downgraded to 2.0.6.
Try:
rm -rf node_modules 
rm -rf ~/.rncache
also remove the .lock files then:
yarn install
then close all metro bundler screens, delete app and build again...

**Comment by pedrosimao** [comment] 2018-08-28 11:13
@mrigo are you using Expo or ExpoKit? If you are you have to get rid of it.

**Comment by hannigand** [comment] 2018-08-28 11:15
`2.0.6` is almost a year old, what are the implications of downgrading? At the time of recommendation (2nd comment), 2.0.6 was one version back.

**Comment by mrigo** [comment] 2018-08-28 11:17
@pedrosimao I've used react-native, no expo..
I've tried your advices, but nothing changed.. I'll return to the latest version..

**Comment by mrigo** [comment] 2018-08-28 14:05
@kneth in the iOS version the app continues to crash after few seconds, also doing nothing, I suppose because of this bug :(
Do you know if it will be fixed soon? I'm a little bit in hurry for a deploy in production and now I can't really work well :(

Sorry to bother you!
Thanks!

**Comment by hdsenevi** [comment] 2018-09-14 05:04
@kneth is there any other workaround that we can do to fix this issue (in the meantime)?. 

Our app has come to the point of been unusable when debugger is attached. As you can imagine that's not a great place to be in. I appreciate you guys having higher priority issues than this, but this is a deal breaker for us. We are seriously considering taking out realm from our react-native app. 

Any possible fix/workaround is highly appreciated

**Comment by Eyesonly88** [comment] 2018-09-19 23:37
This is happening for me on `react-native` "0.56" and `realm`: "^2.15.3"

This is causing the app to crash consistently when in debug mode.
This makes development very slow and unbearable.

@kneth any update on the state of this ticket? is it on the roadmap? is it in progress? any ETAs?
Thanks.

**Comment by rimallo** [comment] 2018-09-24 14:41
Unresponsiveness of the ream team makes this great idea and product a total crap :(

**Comment by bmunkholm** [comment] 2018-09-25 13:12
Is this also the same when using Safari? See [issue here](https://github.com/realm/realm-js/issues/491#issuecomment-404670910)

**Comment by cyphire** [comment] 2018-10-24 16:44
I am also in a pickle.  We cannot debug with Realm.  Realm consistently is the stopping point for moving forward in our development.  The sad part is that our application uses both Realm sync and non-synced.  For testing, development, etc. we don't institute any listeners, we don't use a synced version of realm.  I don't understand how this isn't somewhat of an important issue for the Realm team.  It makes the product unusable.

Please - can you give any insight into Realm causing debugging to become unusable, or what steps can be taken to fix it?

**Comment by nirinchev** [comment] 2018-10-24 17:45
I'm sorry you feel this way, but comments reiterating things already mentioned are hardly productive. The link in the comment just above yours points to a thread where we've outlined the reasons for the current limitations and there have been proposed workarounds when debugging on iOS. Beyond that, there's not much we can do until Facebook improves their debugger support.

**Comment by FirdousNath** [comment] 2019-02-09 08:21
facing same app crash issue on iOS. Its sad realm team isn't taking it seriorusly :(

**Comment by cyphire** [comment] 2019-02-09 13:30
I would think that at least on the realm.io website there would be a big warning right at the top of the introduction that debugging becomes problematic when using this product.

I invested so much into using realm without the knowledge that I wouldn't be able to use JavaScript debugging anymore. On the bright side the fact that realm.io kills the development experience has made me into a much, much better programmer!

I use reactotron for logging and have to write really good code!

That being said it's a shame that this issue doesn't have a big warning banner displayed on the Realm.io website.

**Comment by kneth** [comment] 2019-02-11 08:42
@FirdousNath We are taking it seriously but we are waiting for React Native to make the debugging experience easier (for us with C++ code).

@cyphire I see your point. Not that we try to hide it (https://realm.io/docs/javascript/latest/#chrome-debugging-is-slow).

**Comment by matiasbuildops** [comment] 2019-08-14 10:44
@kneth Well, to be honest, I would recommend changing the docs to 'forget about it' rather than 'it's slow' as there are a number of bugs (ranging from 3+ year old bugs #491 as mentioned by @blagoev as 'higher priority' in this very thread to ones that have a resolution but closed with no fix on your part; #1034 ) that make any sort of debugging in an app that includes realm extremely painful.

Also, what does 'higher priority' mean in this context - can we expect a fix for #491 within the *next* 3 years and perhaps this bug might be fixed within the next 6 years?

**Comment by kneth** [comment] 2019-08-14 12:27
@matiasbuildops v2.28.0 (from May 2019) improves the performance of debugging. We are very interested in learning what use cases v2.28.0 didn't improve.

**Comment by matiasbuildops** [comment] 2019-08-14 13:11
@kneth yeah, performance is okay but this problem right here persists, making it nigh impossible to debug any application with network activity (which in 2019 is pretty much any app) - debugger network tabs are full of callbacks_poll.

 Also; see #1034 (or #2441 which seems to be a similar/same bug) as I mentioned in my earlier post which also persists to this day and the resolution is *manually editing a .java file in node_modules*.

**Comment by pedrosimao** [comment] 2019-08-14 13:32
@matiasbuildops you are right. I gave up RealmJS because of those issues, after building my first app with it. The evolution of versions is quite slow, and if we are serious about our app, RealmJS is not an option. Maybe WatermelonDB would be a good fit for replacement, but I haven't really tried it yet.

**Comment by FirdousNath** [comment] 2019-08-14 15:05
Life becomes much easier when you change realm to any other persistant library. I can say realm is pretty good for natives app but worse for hybrid apps :(

**Comment by rassemdev** [comment] 2020-02-03 16:55
Still no solution of this problem!

**Comment by oojikoo** [comment] 2020-08-12 03:07
still no solution for this?!

**Comment by heytulsiprasad** [comment] 2021-04-22 09:10
Any updates (or workarounds) on this folks?

**Comment by kneth** [comment] 2021-04-22 10:32
@heytulsiprasad After the issue was created, we batched the requests to lower the load. Unfortunately, it didn't solve all cases.

If it is possible for you, you can also debug your app using Safari (MacOS + iOS only) by enabling DevTools and connect to your device's JavaScript context.

**Comment by heytulsiprasad** [comment] 2021-04-23 07:59
No I'm on windows, think I have to depend on Reactotron from now on. Thanks for being quick to respond.

**Comment by aravi365** [comment] 2021-06-21 18:50
> Any updates (or workarounds) on this folks?

got any??

**Closed** 2022-03-31 12:55 UTC
Labels: T-Bug, O-Community
