### ISSUE TITLE
Group by in Realm

### ISSUE THREAD

**Issue by MehdiRaza1998** [realm/realm-js#3015] opened 2020-06-30 13:16 UTC
## Goals

Group by in Realm - React Native
## Expected Results
Each category's expense should be shown once and with its sum.  
like 
id category Expense
1      1            400
2      2            500
3      2            600
4      1            400

so Output should be :
id category Expense
1      1            800
2      2            1100

## Actual Results

Not getting sum of expense according to category id.

**Comment by kneth** [comment] 2020-06-30 14:50
I close the issue as a duplicate of #474, and I suggest that you follow the issue instead.

**Closed** 2020-06-30 14:54 UTC
Labels: O-Community

**Comment by MehdiRaza1998** [comment] 2020-07-01 05:49
So I take it as "no feature of group by is there." In that #474 issue you mentioned, there is no any solution.
I want the solution please.

**Comment by ironage** [comment] 2020-07-08 22:19
We don't currently support a "group by" feature where you can sum a property on the collapsed objects. However, we do support "DISTINCT" so you can do a `...filtered('TRUEPREDICATE DISTINCT(category)')` but you'd have to sum the expenses manually. This is requested in https://github.com/realm/realm-core/issues/1073
